apache/gobblin

gobblin-modules/google-ingestion/src/main/java/gobblin/ingestion/google/AsyncIteratorWithDataSink.java
gobblin-modules/google-ingestion/src/main/java/gobblin/ingestion/google/webmaster/GoogleWebMasterSource.java
gobblin-modules/google-ingestion/src/main/java/gobblin/ingestion/google/webmaster/GoogleWebmasterDataFetcherImpl.java
gobblin-modules/google-ingestion/src/main/java/gobblin/ingestion/google/webmaster/GoogleWebmasterExtractor.java
gobblin-modules/google-ingestion/src/main/java/gobblin/ingestion/google/webmaster/GoogleWebmasterExtractorIterator.java
gobblin-modules/google-ingestion/src/test/java/gobblin/ingestion/google/webmaster/GoogleWebmasterDataFetcherImplTest.java
gobblin-modules/google-ingestion/src/test/java/gobblin/ingestion/google/webmaster/GoogleWebmasterExtractorTest.java

Due to the limitation of Gobblin's retry mechanism, Gobblin doesn't reset the state of extractors, or cannot create new extractor objects, when doing retries. Therefore, do this PR to keep the states in iterators and reset the extractor to restart from the very beginning if necessary. This PR also improves the error handling and logging for the GSC module. This PR also fixes a bug in AsyncIteratorWithDataSink which is causing a deadlock with LinkedBlockingDeque.

Fix the bug in multi-properties GSC job

---

gobblin-core/src/main/java/gobblin/http/ThrottledHttpClient.java
gobblin-core/src/main/java/gobblin/writer/http/AsyncHttpWriter.java
gobblin-core/src/main/java/gobblin/writer/http/AsyncHttpWriterBuilder.java
gobblin-core/src/test/java/gobblin/writer/http/AsyncHttpWriterTest.java
gobblin-modules/gobblin-http/src/main/java/gobblin/http/ApacheHttpClient.java
gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2Client.java
gobblin-modules/gobblin-http/src/main/java/gobblin/writer/AvroHttpWriterBuilder.java
gobblin-modules/gobblin-http/src/main/java/gobblin/writer/R2RestWriterBuilder.java
gobblin-utility/src/main/java/gobblin/util/http/HttpLimiterKey.java

Below configuration should be added in the job profile.
gobblin.broker.limiter.GLOBAL.class=qps
gobblin.broker.limiter.qps=1
@ibuenros @zxcware Can you please review?

Add throttling for asynchttpwriter

---

gobblin-core-base/src/main/java/gobblin/crypto/EncryptionConfigParser.java
gobblin-core-base/src/test/java/gobblin/crypto/EncryptionConfigParserTest.java
gobblin-modules/gobblin-crypto-provider/src/main/java/gobblin/converter/SerializedRecordToEncryptedSerializedRecordConverter.java
gobblin-modules/gobblin-crypto-provider/src/main/java/gobblin/converter/StringFieldEncryptorConverter.java

only looked converter.encrypt.*, but this breaks down if there are
multiple converters in a chain that are doing encryption. This change
allows you to specify config at `converter.<ConverterName>.encrypt.*`
I think this approach is a little cleaner than a positional approach (converter.0.encrypt.foo), but don't know if you have thoughts @htran1 or @ibuenros . Also definitely want to document this somewhere and/or make the config parsing a little more generic. I know Typesafe Config can handle some of the heirarchy stuff as well.

- Add a little bit of hierarchical config for converter encryption - previously converters

---

gobblin-docs/case-studies/Kafka-HDFS-Ingestion.md

DatasetUtils.getDatasetSpecificProps is now explicitely looking for the "dataset" object in the JSON so the case study no longer works.

update case study to latest version of code

---

gobblin-modules/gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java

@ibuenros can you take a look? Removed `cancelJob` call from `cancel` in `AzkabanJobLauncher` so that `cancel` wouldn't persist state store.

Remove fs operations when Azkaban shutdownHook is called

---

gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java

Add `datasetUrn` when creating workunits.
Use `isDatasetStateEnabled` to ensure backwards compatible when reading `FsStateStore` that is not `datasetAware`.
Tested on holdem.

Switch to dataset statestore for KafkaSource

---

gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java

Moved the code to add the watermark predicate in getExtractQuery to a separate function called addOptionalWatermarkPredicate because SqlQueryUtils.addPredicate does not allow for group by or order by in the inputQuery. So an extractor that extends JDBCExtractor can override addOptionalWatermarkPredicate and allow it to use a query with group by/order by.

addOptionalWatermarkPredicate function

---

gobblin-compaction/src/main/java/gobblin/compaction/audit/KafkaAuditCountHttpClient.java
gobblin-compaction/src/main/java/gobblin/compaction/audit/PinotAuditCountHttpClient.java
gobblin-core-base/src/main/java/gobblin/converter/AsyncConverter1to1.java
gobblin-core-base/src/main/java/gobblin/instrumented/converter/InstrumentedConverterDecorator.java
gobblin-core/build.gradle
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AsyncHttpJoinConverter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AvroApacheHttpJoinConverter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/HttpJoinConverter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/http/ApacheHttpAsyncClient.java
gobblin-modules/gobblin-http/src/main/java/gobblin/http/ApacheHttpClient.java
gobblin-modules/gobblin-http/src/main/java/gobblin/http/ApacheHttpResponseHandler.java
gobblin-modules/gobblin-http/src/main/java/gobblin/http/HttpClient.java
gobblin-modules/gobblin-http/src/main/java/gobblin/http/ThrottledHttpClient.java
gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2Client.java
gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2RestResponseHandler.java
gobblin-modules/gobblin-http/src/main/java/gobblin/utils/HttpUtils.java
gobblin-modules/gobblin-http/src/test/java/gobblin/writer/AsyncHttpWriterTest.java
gradle/scripts/dependencyDefinitions.gradle

1. Add ApacheHttpAsyncClient
2. Add AsyncHttpJoinConverter inheriting AsyncConverter1To1
3. Add processStream to InstrumentedConverterDecorator to workaround convertRecord unsupported operation issue.
4. Replace threadSafe annotation to a javax package version
5. Remove doOnComplete from AsyncConverter1To1 because it will duplicate shutdown logic

Add AsyncHttpJoinConverter

---

gobblin-modules/gobblin-http/src/test/java/gobblin/http/ApacheHttpRequestBuilderTest.java
gobblin-modules/gobblin-http/src/test/java/gobblin/restli/R2RestRequestBuilderTest.java

Prevent `a/part1:${part1}/a/part2:${part2}` from being prefixed with a `/`.

Fix failed http test

---

gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2RestRequestBuilder.java

Using gson to convert a json string to a `HashMap` then to `DataMap` fails because gson introduced `LinkedTreeMap` which `DataMap` doesn't like.

Fix R2 DataMap conversion from nested objects in a json string

---

gobblin-core/src/main/java/gobblin/converter/avro/FlattenNestedKeyConverter.java
gobblin-utility/src/main/java/gobblin/util/AvroUtils.java

- Use avro 1.7.4 apis in `FlattenNestedKeyConverter`
- Remove avro 1.8.1 checks in `AvroUtils`

Improve compatibility for avro version 1.7.4

---

gobblin-core-base/src/main/java/gobblin/converter/AsyncConverter1to1.java
gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedSource.java
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AvroApacheHttpJoinConverter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AvroHttpJoinConverter.java

1) Remove duplicate init() from AsyncConverter1To1
2) Change AvroHttpJoinConverter type from HttpJoinConverter to AsyncHttpJoinConverter 
3) Fix the UnsupportedOperationException issue during prevFsSnapshot addAll() because prevFsSnapshot may be an ImmutableSet type

Change AvroHttpJoinConverter type from HttpJoinConverter to AsyncHttpJoinConverter 

---

gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactionTask.java
gobblin-compaction/src/main/java/gobblin/compaction/source/CompactionFailedTask.java
gobblin-compaction/src/main/java/gobblin/compaction/source/CompactionSource.java
gobblin-compaction/src/main/java/gobblin/compaction/verify/CompactionVerifier.java
gobblin-compaction/src/test/java/gobblin/compaction/mapreduce/MRCompactionTaskTest.java
gobblin-compaction/src/test/java/gobblin/compaction/suite/TestCompactionSuiteFactories.java
gobblin-compaction/src/test/java/gobblin/compaction/suite/TestCompactionSuites.java
gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTask.java
gobblin-runtime/src/main/java/gobblin/runtime/task/FailedTask.java

1. Set failed state instead of throwing an exception from FailedTask.java
2. Add failure test case in MRCompactionTaskTest.java
3. Add an upper bound for verification upper bound. Both time (in minutes) and count limit will be checked.

Fix the failed task hanging issue in compaction flow

---

gobblin-core/src/main/java/gobblin/async/AsyncRequest.java
gobblin-core/src/main/java/gobblin/net/Request.java
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AsyncHttpJoinConverter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AvroR2JoinConverter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/HttpJoinConverter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/http/ApacheHttpResponseHandler.java
gobblin-modules/gobblin-http/src/main/java/gobblin/r2/R2Client.java
gobblin-modules/gobblin-http/src/main/java/gobblin/r2/R2ResponseStatus.java
gobblin-modules/gobblin-http/src/main/java/gobblin/r2/R2RestRequestBuilder.java
gobblin-modules/gobblin-http/src/main/java/gobblin/r2/R2RestResponseHandler.java
gobblin-modules/gobblin-http/src/main/java/gobblin/writer/AsyncHttpWriter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/writer/AsyncHttpWriterBuilder.java
gobblin-modules/gobblin-http/src/main/java/gobblin/writer/R2RestWriterBuilder.java
gobblin-modules/gobblin-http/src/test/java/gobblin/r2/R2RestRequestBuilderTest.java
gobblin-modules/gobblin-http/src/test/java/gobblin/writer/AsyncHttpWriterTest.java

A restli service can choose to throw an exception to report an error instead of replying a normal response. Most cases, the R2 client will receive a cause of type `RestException`, which internally contains a valid `RestResponse`
Previously, the `ResponseHandler` is agnostic about the request associated with the response. To support rich events emission while handling response, now it is provided with request information.
The stuff in the restli package is really about r2. `gobblin-http` module or extension now supports 3 different types of clients: `ApacheHttp`, `ApacheAsyncHttp`, and `R2Client`

Extract RestResponse from exception and make ResponseHandler aware of Request

---

gobblin-hive-registration/src/main/java/gobblin/hive/avro/HiveAvroSerDeManager.java
gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java

1. Implemented a database status map to cache the check result of hive database / tables. `hiveRegister.doubleLockPatternCheck.enabled` is the configuration key to enable this optimization.
2. Put some metric for Schema R/w during HiveSpec Computation
(May not be useful now but for future investigation reference)

Reduce lock aquisition using local map cache

---

gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
gobblin-modules/gobblin-azkaban/src/main/java/gobblin/data/management/retention/Avro2OrcStaleDatasetCleaner.java

1) Changes in AbstractAvroToOrcConverter to update the partition location (governed by the config property) to a time-stamped partition location if partition already exists, to avoid breaking inflight queries
2) Adding a new file, Avro2OrcStaleDatasetCleaner to clean the stale directories(left after writing partition to a different time stamp dir) after a grace time period

Changes to avoid breaking in-flight queries during avro2orc conversion

---

gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AsyncHttpJoinConverter.java

Some R2 request will fail due to invalid recource id (statusCode 410). Remove these bad request to prevent any retrying logic, which may lead to NPE.

 Skip bad record from asynchttpconverter

---

gobblin-api/src/main/java/gobblin/writer/FsWriterMetrics.java
gobblin-api/src/main/java/gobblin/writer/PartitionIdentifier.java
gobblin-api/src/test/java/gobblin/writer/FsWriterMetricsTest.java
gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
gobblin-core/src/test/java/gobblin/publisher/BaseDataPublisherTest.java
gobblin-core/src/test/java/gobblin/writer/AvroHdfsDataWriterTest.java
gobblin-core/src/test/resources/publisher/sample_metadata.json
gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/types/GlobalMetadata.java
gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/types/GlobalMetadataJsonMerger.java
gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/types/StaticStringMetadataMerger.java

- Each writer will emit a set of internal writer metric tuples
(writerId, partitionKey, branchId, list of [filename, numRecords in
file]) in its job state. If a PartitionedWriter is being used there may
be multiple keys emitted - it does not try to do any rollup itself
- The BaseDataPublisher will go through each set of writer metrics and
group them by (partitionKey, branchId). An aggregated set of those
metrics will be published to the metadata file in the appropriate output
paths.
- A global Num-Records/Num-Files field is also published as dataset
level metadata for each (partitionKey, branchId) generated by the job

Add support for publishing aggregated writer metrics in the metadata.json optionally produced by BaseDataPublisher.

---

.github/PULL_REQUEST_TEMPLATE.md

Standardize the Github PR template, so that new PRs are created with proper title, subject and commit messages. This should leverage learnings from existing Apache projects.

[GOBBLIN-168] Standardize Github PR template for Gobblin

---

dev/README.md
dev/gobblin-pr
dev/requirements.txt

- https://issues.apache.org/jira/browse/GOBBLIN-166
This entails deriving from existing tooling from Spark and Airflow.
The script will manage and automate PR activities including: cloning the PR locally, merging it to master, pushing to Apache remote, and closing related JIRA issues.
This is dev tooling work in progress.

[GOBBLIN-166] Add dev tooling for simplifying the Github PR workflow

---

gobblin-metastore/src/main/java/gobblin/metastore/database/DatabaseJobHistoryStoreV101.java
gobblin-metastore/src/main/java/gobblin/metastore/database/DatabaseJobHistoryStoreV102.java
gobblin-metastore/src/main/resources/db/migration/V1_0_2__LauncherType_enum_expansion.sql

Add `CLUSTER` to the launcher_type enum in the JobHistory DB
Modified DatabaseJobHistoryStoreV101 to return values of LauncherTypeEnum.CLUSTER as "YARN" and created DatabaseJobHistoryStoreV102 which keeps them as "CLUSTER".

[GOBBLIN-11] Fix for #1822 and #1823

---

gobblin-data-management/config-example/gobblin-retention-run.sh
gobblin-data-management/config-example/gobblin-retention.properties
gobblin-data-management/config-example/hdfs-gobblin-config-store/user/root/gobblin-config-management/_CONFIG_STORE/1.0/hive/db1/main.conf
gobblin-data-management/config-example/hdfs-gobblin-config-store/user/root/gobblin-config-management/_CONFIG_STORE/1.0/hive/db2/main.conf
gobblin-data-management/config-example/hdfs-gobblin-config-store/user/root/gobblin-config-management/_CONFIG_STORE/1.0/hive/db2/table1/main.conf
gobblin-data-management/config-example/hdfs-gobblin-config-store/user/root/gobblin-config-management/_CONFIG_STORE/1.0/hive/includes.conf
gobblin-data-management/config-example/hdfs-gobblin-config-store/user/root/gobblin-config-management/_CONFIG_STORE/1.0/tags/retention/hive/main.conf
gobblin-data-management/config-example/hdfs-gobblin-config-store/user/root/gobblin-config-management/_CONFIG_STORE/1.0/tags/retention/timebased/main.conf
gobblin-data-management/config-example/hdfs-gobblin-config-store/user/root/gobblin-config-management/_CONFIG_STORE/store-metadata.conf
gobblin-data-management/src/main/java/gobblin/runtime/retention/DatasetCleanerCli.java
gobblin-docs/data-management/Gobblin-Retention.md

This pull request adds a run script for the ```DatasetCleanerJob``` class which is used in the ```gobblin-data-management``` module to run retention process. There is also example configuration to complement the retention module docs.

[GOBBLIN-25] Gobblin data-management run script and example configuration

---

gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/test/java/gobblin/service/FlowConfigTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-176
Removed package org.eclipse.jetty.http.HttpStatus and added the package com.linkedin.restli.common.HttpStatus instead
gobblin-restli build now succeeds locally

[GOBBLIN-176] Fix missing dependency error

---

gobblin-core/src/main/java/org/apache/gobblin/publisher/BaseDataPublisher.java
gobblin-core/src/test/java/org/apache/gobblin/publisher/BaseDataPublisherTest.java

writer is used and a filename for metadata output has not been set.
- [x ] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
- https://issues.apache.org/jira/browse/GOBBLIN-194
- [x ] Here are some details about my PR, including screenshots (if applicable):
Push the null check up the stack so we can catch null parameters before trying to build a Path object out of them.
- [x ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Test for this specific use case
- [x ] My commits all …

[GOBBLIN-194] Fix a NullPointerException that can occur if a partitioned

---

gobblin-modules/gobblin-sql/build.gradle
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/source/extractor/extract/jdbc/PostgresqlSource.java
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/source/jdbc/PostgresqlExtractor.java
gobblin-modules/gobblin-sql/src/test/java/org/apache/gobblin/source/jdbc/PostgresqlExtractorTest.java
gradle/scripts/dependencyDefinitions.gradle

[GOBBLIN-203] Add Postgresql source and extractor

---

gobblin-api/src/main/java/org/apache/gobblin/util/RecordCountProvider.java
gobblin-compaction/src/main/java/org/apache/gobblin/compaction/mapreduce/MRCompactor.java
gobblin-compaction/src/main/java/org/apache/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
gobblin-core-base/src/main/java/org/apache/gobblin/writer/AsyncWriterManager.java
gobblin-core/build.gradle
gobblin-core/src/main/java/org/apache/gobblin/publisher/BaseDataPublisher.java
gobblin-core/src/main/java/org/apache/gobblin/publisher/TimePartitionedDataPublisher.java
gobblin-core/src/main/java/org/apache/gobblin/publisher/TimestampDataPublisher.java
gobblin-core/src/main/java/org/apache/gobblin/writer/RetryWriter.java
gobblin-core/src/main/java/org/apache/gobblin/writer/http/SalesforceRestWriter.java
gobblin-core/src/test/java/org/apache/gobblin/writer/RetryWriterTest.java
gobblin-modules/google-ingestion/src/main/java/org/apache/gobblin/source/extractor/extract/google/GoogleAnalyticsUnsampledExtractor.java
gobblin-modules/google-ingestion/src/test/java/org/apache/gobblin/source/extractor/extract/google/GoogleAnalyticsUnsampledExtractorTest.java
gobblin-utility/build.gradle
gobblin-utility/src/main/java/org/apache/gobblin/exception/NonTransientException.java
gobblin-utility/src/main/java/org/apache/gobblin/util/WriterUtils.java
gobblin-utility/src/main/java/org/apache/gobblin/util/recordcount/CompactionRecordCountProvider.java
gobblin-utility/src/main/java/org/apache/gobblin/util/retry/RetryerFactory.java

In our environment we use Gobblin for shipping logs to s3. Gobblin on it's own works pretty well but at a couple of place it assumes the underlying fs is consistent which is not true in some case like in some S3 region.
To overcome this I added a couple of retry if the created dir/file fails to exist right away after publish.
The following changes were added:
- Refactored RetryWriter to gobblin-core to be able use in WriterUtils and not having circular dependencies.
- Introducing mkdirsWithRecursivePermissionWithRetry to be able set retry if directory does not exists right after creation on eventual consistent fs.
- Adding retry to publisher (data.publisher.retry.enabled=true) like TimestampDataPublisher, TimePartitinedDataPublisher to support eventual consisteny filesystem targets
- Tmp …

[GOBBLIN-6] Support eventual consistent filesystems like S3

---

gradle/scripts/release.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-355
Disable snapshot versioning until downstream fixes. It was added during 0.12.0 release
Yes, built locally on downstream.

[GOBBLIN-355] Disable snapshot versioning until downstream fixes

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1436
After the job emits cancel event it needs to have the Flow Event field cleared, so it can have its job status marked as Resumed later. 

Clear flow event after cancel

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1448
Currently AbstractJobLauncher will default to sending a jobSucceededTimer if job state is anything other than FAILED. It probably makes more sense to send a jobFailedTimer instead in the case of CANCELLED status.
Trivial change

[GOBBLIN-1448] Send failed timer instead of success timer when job is cancelled

---

gobblin-binary-management/build.gradle
gobblin-core/build.gradle
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/CleanableMysqlDatasetStoreDatasetTest.java
gobblin-hive-registration/build.gradle
gobblin-iceberg/build.gradle
gradle/scripts/dependencyDefinitions.gradle
gradle/scripts/repositories.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-1463
Pentaho's library for aggdesigner is used in tests. https://mvnrepository.com/artifact/org.pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde However, the nexus repository frequently goes down and is unreliable.
Proposal to move to a newer version of aggdesigner hosted on maven central, similar to calcite https://issues.apache.org/jira/browse/CALCITE-1474.
6. Body explains "what" and "why", …

[GOBBLIN-1463] Remove pentaho dependency

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java

- https://issues.apache.org/jira/browse/GOBBLIN-1469
We have noticed two instances where the streaming topics were having Missing/Orphan hive partition issues. After investigating, it's because the schema.literal is missing when creating the table, and thus the following partition registration in ingestion job are all fail which cause the hourly partition missing. So create this ticket to make it able to proceed hive registration even if schema.literal is missing.
5. Body …

[GOBBLIN-1469]Fix Issue that hive registration cannot process when schema.literal is not set

---

.github/workflows/build_and_test.yaml

- https://issues.apache.org/jira/browse/GOBBLIN-1482
- 
The issue is caused by the `./gradlew assemble` step conflicting with the build step and not including all the classes needed for some of the build tasks, if it’s done before the build step.
`./gradlew assemble` is still needed to verify the dependencies, as `./gradlew build` caches the dependencies between runs as an optimization

[GOBBLIN-1482] Move verify dependencies test to after build step to fix pegasus error

---

gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/source/jdbc/JdbcExtractor.java
gobblin-modules/gobblin-sql/src/test/java/org/apache/gobblin/source/jdbc/JdbcExtractorTest.java
gobblin-modules/gobblin-sql/src/test/java/org/apache/gobblin/source/jdbc/MockTimestampResultSet.java

- https://issues.apache.org/jira/browse/GOBBLIN-1479
In MySQL Connector 8, calling ResultSet.getString(int) on a record with a zero timestamp
returns the string "0000-00-00 00:00:00", even when the connection property
`zeroDateTimeBehavior=CONVERT_TO_NULL` is set.
This change is a workaround to return null for these timestamps when the property is set.

[GOBBLIN-1479] Add support to convert zeroDateTime to null when configured

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/HiveRegistrationUnitComparator.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/orc/HiveOrcSerDeManager.java

- https://issues.apache.org/jira/browse/GOBBLIN-1485
1. enable feature to get schema from writer schema instead of listing directory to get latest schema. 
2. When determine whether there is schema change, use schema version to compare to avoid special character issue. 
Run test on parallel pipeline

[GOBBLIN-1485]Enable feature to get schema from writer schema when do hive registration

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/datanodes/fs/GridFSDataNode.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompilerTest.java
gobblin-service/src/test/resources/flow/flow6.conf
gobblin-service/src/test/resources/flowgraph/datanodes/GridFsDataNode-1.properties
gobblin-service/src/test/resources/flowgraph/flowedges/hdfs-1-to-gridfs.properties
gobblin-service/src/test/resources/template_catalog/multihop/flowEdgeTemplates/hdfsToGridFs/flow.conf
gobblin-service/src/test/resources/template_catalog/multihop/flowEdgeTemplates/hdfsToGridFs/jobs/distcp-hdfs-to-gridfs.job
gobblin-service/src/test/resources/template_catalog/multihop/jobTemplates/distcp-push-hdfs-to-gridfs.template

- https://issues.apache.org/jira/browse/GOBBLIN-1487
Adds GridFS as a recognized fs schema

[GOBBLIN-1487] Add gridfs datanode gaas

---

gobblin-utility/src/main/java/org/apache/gobblin/util/request_allocation/PriorityIterableBasedRequestAllocator.java
gobblin-utility/src/test/java/org/apache/gobblin/util/request_allocation/BruteForceAllocatorTest.java
gobblin-utility/src/test/java/org/apache/gobblin/util/request_allocation/GreedyAllocatorTest.java
gobblin-utility/src/test/java/org/apache/gobblin/util/request_allocation/PreOrderAllocatorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1481
When generating workunits, there are scenarios where the underlying file system can throw errors when attempting to collect files to allocate them into workunits. The behavior for single threaded workunit generation is to throw the error, so we should make the multithreaded configuration also throw errors and fail loudly instead of logging and marking the job as successful (although there would still be 0 workunits).
5. …

[GOBBLIN-1481] Throw failure in concurrency mode when allocating files

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/GobblinMCEProducer.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1484
Sometime we need the avro schema in place even for ORC tables, we have that information in ingestion job but not for compaction job. And it's hard to get the avro schema from orc file itself, so we want to support schema source db, so that we can fetch the schema from source db where ingestion job registers to.
unit test

[GOBBLIN-1484]Make Gobblin metadata writer be able to support schema source DB

---

gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/idl/org.apache.gobblin.service.flowconfigsV2.restspec.json
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/snapshot/org.apache.gobblin.service.flowconfigsV2.snapshot.json
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/main/java/org/apache/gobblin/service/FlowConfigV2Client.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/test/java/org/apache/gobblin/service/FlowConfigV2Test.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigV2ResourceLocalHandler.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigsV2Resource.java

- https://issues.apache.org/jira/browse/GOBBLIN-1458
Previously the way to manually trigger an execution of a scheduled flow is to send a partial update that sets the flow's `runImmediately` property to true. This PR improves the API by adding a restli action that sends the same partial update. With this, flows can be triggered through the URL: `/flowconfigsV2/(flowGroup:test1,flowName:test1)?action=trigger`
Also copied the implementation of `partialUpdateFlowConfig` to `FlowConfigV2ResourceLocalHandler` for testing convenience (normally when running the service `GobblinServiceFlowConfigResourceHandler` would be used, but for tests it is …

[GOBBLIN-1458] Add endpoint to trigger a flow in GaaS

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-core/src/main/java/org/apache/gobblin/publisher/BaseDataPublisher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1488
Allow option to change perm group at publisher dir leaf level. 
if publisherdir = /db/table then the perm group is set for path /table

[GOBBLIN-1488] Added option to set perm group at table level

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/GobblinMCEProducer.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1490
In some use case, we may run data pipeline on different clusters but those clusters share the same file system. And in those case, we will want the metadata pipeline to be able to consume all the records even they are running on different clusters. Also make the cluster name for GMCE be configurable so that we don't need to change the accepted cluster names when cluster name itself changes 
unit test …

[GOBBLIN-1490] Make metadata pipeline to support consume GMCE emitted from different cluster

---

gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/D2Announcer.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceConfiguration.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/NoopD2Announcer.java

- https://issues.apache.org/jira/browse/GOBBLIN-1491
Currently, D2 servers are started on all hosts at the time of service start. This change will allow using D2 delayed start, then marking up/down the servers when a host becomes the master/slave respectively. This means only the master will be announced to D2, so all requests will be routed to it.
The logic for markup is linkedin specific so must be implemented in internal code.
6. Body …

[GOBBLIN-1491] Add option to mark up/down D2 servers for gobblin service on leadership change

---

gobblin-utility/src/main/java/org/apache/gobblin/util/hadoop/TokenUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1495
When the application tries to fetch Hadoop tokens for a cluster with no remote namenodes, the current implementation of the getHadoopTokens method doesn't check for the property "other_namenodes" while getting remoteFSURIList. This property is not mandatory and won't be present if there are not remote namenodes. In such cases, it throws NPE.
Tested by releasing snapshot version locally, application succeeded successfully. …

[GOBBLIN-1495] Fix NPE when trying to fetch Hadoop tokens for cluster with no remote namenodes

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/dataset/CleanableIcebergDataset.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/HiveLock.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/MetadataWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/Utils/IcebergUtils.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1501
This PR mostly adds documentation, renaming and fixing typo in the `gobblin-icberg` module, with extra focus on `IcebergMetadataWriter` for: 
- Change the way that `Transaction` object is initialized as it is shared in many different places. 
- Change the way for accessing or initializing `AppendFiles` and `DeleteFiles` object. All these changes in `TableMetadata` object. 
- Adding documentation for places where commit does happen or doesn't happen for reasons. 
- Remove some of the `IOException` in the method signature wherever they are not required. 
This PR doesn't add or delete any of the …

[GOBBLIN-1501] Documentation + Code Cleaning for IcebergMetadataWriter 

---

gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/CleanableMysqlDatasetStoreDatasetTest.java

JIRA
My PR addresses the following Gobblin JIRA issues and references them in the PR title.
https://issues.apache.org/jira/browse/GOBBLIN-1506
Description
Here are some details about my PR, including screenshots (if applicable):
Corroborated and consistently failing unit tests, which are already disabled for CI, are now likewise disabled for local build.
Tests
My PR adds the following unit tests OR does not need testing for this extremely good reason:
The change is itself isolated to unit tests.
4. Subject uses the imperative …

[GOBBLIN-1506] Disable CleanableMysqlDatasetStoreDatasetTest unit tests, already dropped from Continuous Ingetration

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobSchedulerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1507
When demoted from leader, GaaS removes all flows from orchestrator. We need to ensure that fail over events are not disruptive or destructive to currently running flows, we only want the new leader node to handle scheduling responsibilities from that point forward.

[GOBBLIN-1507] Prevent orchestrator removals when unscheduling flows

---

gobblin-data-management/src/test/java/org/apache/gobblin/data/management/conversion/hive/HiveSourceTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1511
Adds additional tables to test so that tests can run without interfering with each other. Currently there is a concurrency issue when running `HiveSourceTest` locally through Intellij

[GOBBLIN-1511] Fix concurrency issue where tests conflict with each others tables

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/dataset/DatasetUtils.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/PathFilterTest.java
gobblin-utility/src/main/java/org/apache/gobblin/util/PropertiesUtils.java
gobblin-utility/src/main/java/org/apache/gobblin/util/filters/RegexPathFilter.java
gobblin-utility/src/test/java/org/apache/gobblin/util/PropertiesUtilsTest.java

@aplex  please review
- https://issues.apache.org/jira/browse/GOBBLIN-1513
Path filters are supposed to be provided by key "gobblin.dataset.path.filter.class", but `instantiatePathFilter` only calls the empty constructors for the path filter classes. Right now only HiddenFilter can be created with empty constructor.
This PR will make a constructor for RegexPathFilter so that it can be used with config "gobblin.dataset.path.filter.class"
added a unit test to test initialization and basic working of RegexPathFilter
4. Subject uses …

[GOBBLIN-1513] fixed the construction of regex filters

---

gradle/scripts/dependencyDefinitions.gradle

Previous version was blocked by security scanner due to unpatched
vulnerabilities.
https://issues.apache.org/jira/browse/GOBBLIN-1457

[GOBBLIN-1457] Bump commons-dbcp2 version

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/SingleTask.java

- https://issues.apache.org/jira/browse/GOBBLIN-1514
Currently sometimes when a task is attempted to be cancelled but is unsuccessful (due to helix being disconnected for example), the job will continue to run on the worker but the taskdriver will delete the jobState, causing an NPE here. This PR just throws a better error message, since the job is meant to be cancelled anyway.
trivial

[GOBBLIN-1514] Throw more useful error from already cancelled tasks

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixTaskStateTracker.java
gobblin-core-base/src/main/java/org/apache/gobblin/instrumented/writer/InstrumentedDataWriterBase.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/local/LocalTaskStateTracker.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRTaskStateTracker.java

https://issues.apache.org/jira/browse/GOBBLIN-1516
This PR contains two parts: 
- Rename `Optional<ScheduledThreadPoolExecutor> writerMetricsUpdater` to be `writerMetricsUpdateExecutor` which is more accurate. The original name collide with `WriterMetricsUpdater` class which is the actual Runnable to be scheduled. 
- Within `registerNewTask`, only schedule the `TaskMetricsUpdater` if `metrics.enabled` is true. The `TaskMetricsUpdater` holds a reference to `Task` object and `TaskMetricsUpdater` is only terminated/removed after commit. As a result, when there are a large number of tasks being executed, all of them will only be GC'ed after commit phase. …

[GOBBLIN-1516] Only schedule TaskMetricsUpdateder when metric-reporting is enabled by config

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/db/ServiceDatabaseManager.java

By default, Flyway will throw an exception if the database is not
empty and Flyway's own table is missing. Production Gobblin service
DBs already have state tables in them, so migration didn't work.
With this change, we ask Flyway to ignore existing tables when
initializing new db.
https://issues.apache.org/jira/browse/GOBBLIN-1457

[GOBBLIN-1457] Fix service DB initialization when DB is not empty

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixMultiManager.java

- https://issues.apache.org/jira/browse/GOBBLIN-1523
Currently, the live instances are logged at info level. This can result in a ton of uninformative logs in a production deployment, making debugging issues hard.
Existing tests. 

GOBBLIN-1523: Change logging of live instances in Gobblin cluster to debug level

---

gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java

- https://issues.apache.org/jira/browse/GOBBLIN-1524
Currently, there are no limits on the number of threads used, which can result in OOMEs with "unable to create a new native thread". This PR makes the number of threads configurable with a default of 1024.
Trivial change. Existing tests should be sufficient.

GOBBLIN-1524: Limit the number of container launch threads used by YarnService

---

gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java

- https://issues.apache.org/jira/browse/GOBBLIN-1582
Gobblin can overallocate containers when a Yarn application is started up. The main reason for the overallocation is because the AMRM client does not track which container requests have already been submitted. Container requests are sent to RM through the allocate() method inside the AMRMClient. Once a container has been allocated, the application is responsible for removing the container request from the matching request table (maintained by the AMRMClient) by calling its removeContainerRequest() method. Between successive calls to allocate() method, if one or more container requests have not been …

GOBBLIN-1528: Reduce overshoot of Yarn containers in Gobblin-on-Yarn mode

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/GobblinMetrics.java

- https://issues.apache.org/jira/browse/GOBBLIN-1534
Currently in both gaas and jobs launched by gaas, we use kafka event reporting, but not kafka metrics reporting. In #3035, there were some changes which includes splitting the kafka reporter factory. As a side effect, the two reporters (metrics/events) became all or nothing, where previously if just one was missing config it would be skipped. This causes gaas and jobs launched by gaas to always contain an error stacktrace about failing to instantiate the kafka metric reporter.
This PR adds config keys to enable/disable the reporters individually. For backwards compatibility, if …

[GOBBLIN-1534] Allow kafka metrics/events reporting to be disabled individually

---

gobblin-modules/gobblin-troubleshooter/src/main/java/org/apache/gobblin/troubleshooter/AutoTroubleshooterLogAppender.java
gobblin-modules/gobblin-troubleshooter/src/test/java/org/apache/gobblin/troubleshooter/AutoTroubleshooterLogAppenderTest.java

Issue code should depend only on exception stack trace and type,
but previously there was a bug when exception message was included
in generation of the code. Since the message can have variable
parts, like paths and dataset names, some issue got multiple
codes assigned to them.
https://issues.apache.org/jira/browse/GOBBLIN-1536

[GOBBLIN-1536] Fix issue code generation

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompiler.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompilerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1530
When copying data from a source node that does not exist/fails to be added to GaaS FlowGraph, a very cryptic error message pops up where DmasAuthorizer shows a NullPointerException.
This PR guards against source nodes that do not exist so that the error is much easier for developers and users to understand.

[GOBBLIN-1530] Add error reporting for missing source nodes that may not exist

---

gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/CleanableMysqlDatasetStoreDatasetTest.java
gobblin-metastore/src/main/java/org/apache/gobblin/metastore/MysqlJobStatusStateStore.java
gobblin-metastore/src/main/java/org/apache/gobblin/metastore/MysqlStateStore.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/idl/org.apache.gobblin.service.flowexecutions.restspec.json
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/snapshot/org.apache.gobblin.service.flowexecutions.snapshot.json
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/test/java/org/apache/gobblin/service/FlowStatusTest.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowExecutionResource.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowExecutionResourceHandler.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowExecutionResourceLocalHandler.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/MysqlDatasetStateStore.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatus.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatus.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatusRetriever.java
gobblin-runtime/src/test/java/org/apache/gobblin/service/monitoring/FlowStatusGeneratorTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/test/matchers/service/monitoring/FlowStatusMatch.java
gobblin-runtime/src/test/java/org/apache/gobblin/test/matchers/service/monitoring/JobStatusMatch.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowExecutionResourceHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/FsJobStatusRetriever.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/LocalFsJobStatusRetriever.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetriever.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/JobStatusRetrieverTest.java
gobblin-utility/src/main/java/org/apache/gobblin/util/function/CheckedExceptionFunction.java

- https://issues.apache.org/jira/browse/GOBBLIN-1527
"Extend REST `flowexecutions` endpoint with finder `latestFlowGroupExecutions`"
This adds the new endpoint while augmenting both (primary) forms of `JobStatusRetriever` (Mysql and FS) to support querying flow executions across a flow group.
It leverages the recent refactoring of https://github.com/apache/gobblin/pull/3378
Included enhancements of existing unit tests cover added code paths. …

[GOBBLIN-1527] Add finder `latestFlowGroupExecutions` to `FlowExecutions` endpoint.

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/TaskStateCollectorService.java

- https://issues.apache.org/jira/browse/GOBBLIN-1543
User encountered exception when summing work units for retention jobs that do not have size associated with it, so I am defaulting to progress reporting in terms of work units for cases that do not have size associated with it. 
Tested manually with retention job with progress reporting turned on. 

[GOBBLIN-1543] Set default for work unit size

---

gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/reporter/util/FixedSchemaVersionWriter.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/reporter/util/NoopSchemaVersionWriter.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/reporter/util/SchemaVersionWriter.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/metrics/reporter/util/SchemaRegistryVersionWriter.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaAvroJobStatusMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1546
The kafka job status monitor is currently calling `readSchemaVersioningInformation` to advance the input stream of the kafka messages it reads to the record portion, which calls the schema registry every time, but the result of it is ignored. This PR adds another API that just advances the input stream without contacting the schema registry, to remove a point of failure.
tested in local gaas deployment
5. Body wraps at …

[GOBBLIN-1546] Don't contact schema registry for every record read by job status monitor

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/hive/HiveDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/profile/ManagedCleanableDatasetFinder.java

- https://issues.apache.org/jira/browse/GOBBLIN-1550
Knowing dataset.root of a dataset is a nice-to-have property which can be used by different constructs. 

[GOBBLIN-1550] add dataset.root in ConfigurableCleanableDataset

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/conversion/hive/utils/AvroHiveTypeUtils.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java

https://issues.apache.org/jira/browse/GOBBLIN-1551
The conversion of Avro schema object `Schema` to Hive Schema is a neat utility that is currently only used for Avro2ORC conversion module. It is private static now, while it could actually be useful for other use cases especially when it comes to crafting Hive DDL to create Hive views for example. 
This PR is to increase the visibility of the method `generateAvroToHiveColumnMapping` by copying it into a utility class, and add some basic unit tests for this method. There's no change to the `generateAvroToHiveColumnMapping` itself except making sure the newly created utility class is conforming to Gobblin …

[GOBBLIN-1551] Refactoring of Avro-hive type conversion utils

---

gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/idl/org.apache.gobblin.service.flowexecutions.restspec.json
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/snapshot/org.apache.gobblin.service.flowexecutions.snapshot.json
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/test/java/org/apache/gobblin/service/FlowStatusTest.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowExecutionResource.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowExecutionResourceHandler.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowExecutionResourceLocalHandler.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowStatusResource.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatus.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatusRetriever.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowExecutionResourceHandler.java

Previously, we loaded issues from the db on batch execution requests.
This can result in long response times when large number of flows
are queried.
Now the users can specify if they want to retrieve them, or omit
and speed up the query.
https://issues.apache.org/jira/browse/GOBBLIN-1457

[GOBBLIN-1457] Lazy-load issues to improve performance

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1553
- this is one hotfix
There is one update in upstream that support get iceberg schema for non-optinal union type, but get metrics will throw exception. So we need to catch this kind of exception when get metrics as well

[GOBBLIN-1553] Catch exception when iceberg does not support get metrics for non-optional union type

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/job_catalog/ImmutableFSJobCatalog.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/job_catalog/MysqlJobCatalog.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_serde/GenericGsonSpecSerDe.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_serde/GsonFlowSpecSerDe.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_serde/GsonJobSpecSerDe.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_serde/JobSpecDeserializer.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_serde/JobSpecSerializer.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/job_catalog/TestMysqlJobCatalog.java

- https://issues.apache.org/jira/browse/GOBBLIN-1569
Add RDBMS-backed `MysqlJobCatalog`, as alternative to file system storage
Present storage bindings for `JobCatalog` are in-memory or file system.  While the latter is durable, it requires an NFS-like capability for cross-instance sharing.
Support alternative multi-instance backing through MySQL, precluding the need for NFS.
New unit tests

[GOBBLIN-1569] Add RDBMS-backed `MysqlJobCatalog`, as alternative to file system storage

---

gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanJobLauncher.java
gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/service/modules/orchestration/AzkabanMultiCallables.java

- https://issues.apache.org/jira/browse/GOBBLIN-1571
From Azkaban, depending on the setup some URLs are not accessible for users.
In gobblin-as-a-service, it is possible to declare the property `azkaban.link.jobexec.proxyUrl` using the additional configs key tied to the executor. This passes the property to the JobLauncher that is unique per executor

[GOBBLIN-1571] Tag metrics with proxy url if available

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/MetadataWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMetadataException.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/MetadataFlushException.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

…e will not affect other topics in the same container
- https://issues.apache.org/jira/browse/GOBBLIN-1565
GMIP should be fault tolerant, so that one topic failure should not affect other topics in the same container. One potential solution is that we can catch the error and document the error dataset, if we have more than one datasets have issue, that normally something wrong happening on the whole job, we should fail the task, but if there is only one problematic topic, we can handle the exception and let the pipeline move on and process other topics.
Left some todo for emitting GTE so that we can rely on those event to detect failure and do backfill …

[GOBBLIN-1565]Make GMCEWriter fault tolerant so that one topic failure will not affect other topics in the same container

---

gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/test/java/org/apache/gobblin/service/FlowStatusTest.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowExecutionResourceLocalHandler.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatus.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatusRetriever.java
gobblin-runtime/src/test/java/org/apache/gobblin/service/monitoring/FlowStatusGeneratorTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/test/matchers/service/monitoring/FlowStatusMatch.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceConfiguration.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/FsJobStatusRetriever.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/LocalFsJobStatusRetriever.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetriever.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerFlowTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/FsJobStatusRetrieverTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/FsJobStatusRetrieverTestWithoutDagManager.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/JobStatusRetrieverTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetrieverTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetrieverTestWithoutDagManager.java

- https://issues.apache.org/jira/browse/GOBBLIN-1552
flow status is determined by looking at the flow level events. but flow level events are not emitted outside of dag manager. so currently flow status is not being determined correctly when dag manager is disabled.
this pr adds a field `flowStatus` to FlowStatus class, which is determined by JobStatus'es when DagManager is not enabled. in a way it used to be done prior to https://github.com/apache/gobblin/commit/59f3beeea1e62dcc1f3901f082e46bc3d237f9fb#diff-141f30f7aa658e9e18316e3e5ecea3b92865dcc88a4c0809b6d5c0ef1598e410 
a couple of new unit tests are added. existing test cases are updated
1. Subject …

[GOBBLIN-1552] determine flow status correctly when dag manager is disabled

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1580
Make change to so that cacheDbTableExistence make more sense will not affect alter table even this flag is enabled.
Check table existence before we try to create the table
unit test

[GOBBLIN-1580] Check table exists instead of call create table directly to make sure table exists

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixDistributeJobExecutionLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobTask.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixManagerFactory.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixMultiManager.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinReferenceCountingZkHelixManager.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinTaskRunner.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinZkHelixManager.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixRetriggeringJobCallable.java

- https://issues.apache.org/jira/browse/GOBBLIN-1575
GobblinTaskRunner creates a HelixManager and passes it to HelixJobTask. When the GobblinTaskRunner is stopped, it disconnects to HelixManager, but because the HelixJobTask is also using the same HelixManager object, it cannot use it do its own shutdown operation. This PR will make a copy of HelixManager to be used by HelixJobTask 's.
Same argument with GobblinClusterManager passing the same HelixManager object to HelixRetriggeringJobCallable …

[GOBBLIN-1575] use reference count in helix manager, so that connect/disconnect are called once and at the right time

---

gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/writer/commands/MySqlWriterCommands.java

* after sql-connector was bumped, exception results from ResultSet.first() being called because it iterates in backward direction of set
- https://issues.apache.org/jira/browse/GOBBLIN-1581 
after sql-connector was bumped, exception results from ResultSet.first() being called because it iterates in backward direction of set
can also be addressed by changing the prepare statement of every sql cmd that is executed
_PreparedStatement pstmt = this.conn.prepareStatement(sql) ->
PreparedStatement pstmt = this.conn.prepareStatement(sql, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE)_
Tested manually with snapshot and ingestion job
1. Subject is …

[GOBBLIN-1581] Iterate over Sql ResultSet in Only the Forward Direction

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/writer/commands/BaseJdbcBufferedInserter.java
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/writer/commands/JdbcWriterCommandsFactory.java
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/writer/commands/MySqlBufferedInserter.java
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/writer/commands/MySqlWriterCommands.java
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/writer/commands/PostgresWriterCommands.java
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/writer/commands/TeradataWriterCommands.java
gobblin-modules/gobblin-sql/src/test/java/org/apache/gobblin/writer/JdbcWriterCommandsTest.java
gobblin-modules/gobblin-sql/src/test/java/org/apache/gobblin/writer/MySqlBufferedInserterTest.java
gobblin-modules/gobblin-sql/src/test/java/org/apache/gobblin/writer/PostgresWriterCommandsTest.java

* Allows user to configure a mysql ingestion job to allow replacement of the record's value for an existing record in the table.
* Also replaces a backward iteration of ResultSet() with forward iteration in MySqlWriterCommands
- https://issues.apache.org/jira/browse/GOBBLIN-1584 
We only support insertion of new values into tables, not update/upsert. If you run an ingestion job with a record containing a record with the same primary key the whole job will fail because of the duplicate entry. We don't expect ingestion jobs to always contain only new records, so we should handle duplicate entries, ingestion of data already in the table or updates to old …

[GOBBLIN-1584] Add replace record logic for Mysql writer

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/ClusterEventMetadataGenerator.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/TimingEvent.java
gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatus.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatusRetriever.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/TimingEventUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/JobStatusRetrieverTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1585
The issue is that for the same flow execution, we don't receive the event in order. if the job fail and we retry, we may receive running event first, and then the Orchestrate event which update the current attempts and should retry value will be ignored and cause to job to continually try to retrying util the running job finished.
Add low/high water info in cluster event metadata generator since jobStateEvent will not been processed for job status
Unit test …

[GOBBLIN-1585]GaaS (DagManager) keep retrying a failed job beyond max attempt number

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_serde/JobSpecSerializer.java

(fix issue blocking rollout of:)
- https://issues.apache.org/jira/browse/GOBBLIN-1569
Correct small error from mixing up two `Optional`s contained by the same class.
Previously added unit test passes; see: https://github.com/apache/gobblin/pull/3421

Fix bug in `JobSpecSerializer` of inadequately preventing access errors (within `MysqlJobCatalog`)

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMCEMetadataKeys.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1588
Sent failure events in both cases where a watermark could be advanced
1. After a flush due to operation change, if a previous write failed
2. After a periodic flush where GMCE watermark will be advanced
Updated unit test to check that events are sent

[GOBBLIN-1588] Send failure events for write failures when watermark is advanced in MCE writer

---

gobblin-aws/build.gradle
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java

- https://issues.apache.org/jira/browse/GOBBLIN-1595
In hive registration, we get one client and call ensureHiveTableExistenceBeforeAlternation to check table existence, and inside the method, we call tableExist method which again will try to get one client and cause dead lock. 
unit tests

[GOBBLIn-1595]Fix the dead lock during hive registration

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/hive/UnpartitionedTableFileSet.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/hive/UnpartitionedTableFileSetTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1579
When path of the existing hive table in target does not match with the desired path of the target table to be copied, HiveTableLocationNotMatchException is logged, empty list is returned and job state is set to committed. Propagating the HiveTableLocationNotMatchException so that job state can be set as failed.
UnpartitionedTableFileSetTest.java

GOBBLIN-1579 Fail job on hive existing target table location mismatch

---

gobblin-metrics-libs/gobblin-metrics-base/src/test/java/org/apache/gobblin/metrics/metric/filter/MetricNameRegexFilterTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/TestServiceMetrics.java

- https://issues.apache.org/jira/browse/GOBBLIN-1598
2021/06/12 07:11:32.067 ERROR [DagManager] [pool-19-thread-3] [gobblin-service-war] [] Exception encountered in org.apache.gobblin.service.modules.orchestration.DagManager$DagManagerThread
java.lang.IllegalArgumentException: A metric named GobblinService.testFlow.RunningStatus already exists
at org.apache.gobblin.metrics.InnerMetricContext.register(InnerMetricContext.java:266) 
Likely root cause:
If we activate/deactivate DagManager several times, DagManagerThreads alongside with their flowGauges maps will be recreated, but RootMetricContext will still stay the same. So the newly created threads will …

[GOBBLIN-1598]Fix metrics already exist issue in dag manager

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopySource.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopyableFile.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/RecursiveCopyableDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
gobblin-data-management/src/main/java/org/apache/gobblin/util/commit/SetPermissionCommitStep.java
gobblin-data-management/src/test/java/org/apache/gobblin/util/commit/SetPermissionCommitStepTest.java

add a configuration to match permission of ancestor directories permissions in source and destination
@Will-Lo @ZihanLi58 please review
- https://issues.apache.org/jira/browse/GOBBLIN-1601
Provide a configuration to replicate permissions of ancestor directories of the directory to be copied on the destination side directories. We save the permissions of ancestor directories in a PostPublishStep which is executed after the publish.
created SetPermissionCommitStepTest to test SetPermissionCommitStep
4. Subject uses the imperative …

[GOBBLIN-1601] implement ChangePermissionCommitStep

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/CopyableFileUtils.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/converter/UnGzipConverterTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/writer/TarArchiveInputStreamDataWriterTest.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/InnerMetricContext.java

@jack-moseley  @ZihanLi58  please review
- https://issues.apache.org/jira/browse/GOBBLIN-1606
a) change default value of gobblin_copy_check_filesize to true because it makes more sense to abort the copy if the copied file size does not match the source file size
b) remove the old metric which counts how many bytes are copied, because in case of retries, this can give incorrect value
updated existing unit tests
6. Body explains "what" and …

[GOBBLIN-1606] change DEFAULT_GOBBLIN_COPY_CHECK_FILESIZE value

---

gobblin-core/src/main/java/org/apache/gobblin/writer/RetryWriter.java
gobblin-core/src/test/java/org/apache/gobblin/writer/RetryWriterTest.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1607
Rollback pr3464 because it resulted in job failures. there seems to be a possibility that input and output file sizes are not calculated correctly.
from logs
java.io.IOException: Incomplete write: expected 283839, wrote 283935 bytes.
These exceptions sky rocketed after PR 3464 
not required because rolling back to previous state

[GOBBLIN-1607] Rollback pr3464

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1608
When `max.error.dateset` is reached and the container is failed, gobblin will cause close() on the writer, which will call flush(). This causes a couple issues with events due to assumptions on where flush() is called.
- Move `tableOperationTypeMap.remove(tableString)` to before the container is failed, otherwise an extra flush() will be called on the table. This flush() shouldn't actually do anything since writer.reset has been called for the dataset already.
- Don't send error GTEs for all tables if flush() is called from close(). This event emission is here because GMCE watermark is advanced when …

[GOBBLIN-1608] Fix case where error GTE is incorrectly sent from MCE writer

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1609
Reduce number of commits by not flushing when change_property operation comes in.
e.g. `add_file, add_file, change_property, add_file` will flush 0 times instead of 2
Tested in e2e pipeline

[GOBBLIN-1609] Don't flush on change_property operation

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiExtractor.java
gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceConnector.java
gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceExtractor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1616
In RestApiConnector, we only consume the HttpEntity but not close the response, which potentially leave the socket as CLOSE_WAIT status and eat up the resources. 
local build

[GOBBLIN-1616] Make RestApiConnector be able to close the connection finally

---

gobblin-core/src/main/java/org/apache/gobblin/writer/FsDataWriter.java
gobblin-utility/src/main/java/org/apache/gobblin/util/HadoopUtils.java

@ZihanLi58  please review
In this PR, I am adding an option to pass configuration to some HadoopUtils APIs. This will provide more control to the user.

[GOBBLIN-1617] pass configurations to some HadoopUtils APIs

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java

- https://issues.apache.org/jira/browse/GOBBLIN-1623
Now when we try to call httpClient.getClientManager, it's possible that the implementation of httpClient will throw an NPE in this case. To make it more safer, we close the client when it's a CloseableHttpClient and other than that, we rely on the implementation of httpClient to handle the open connection

[GOBBLIN-1623] Fix NPE when try to close RestApiConnector

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/hive/HiveUtils.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/hive/HiveCopyEntityHelperTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1625
There are edge cases where hive tables are rejected due to the mismatch check not being robust enough. For example:
1. If the user specified path and the existing hive table path are exact matches, we should always return that they are equivalent
2. If the existing hive table path does not exist on the filesystem, we need to recursively check the parents to see if the fs.uri and folder directories are equivalent
Added test cases for each observed scenario …

[GOBBLIN-1625] Add coverage for edge cases when table paths do not exist, check parents

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/BaseFlowGraph.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/pathfinder/AbstractPathFinder.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/pathfinder/BFSPathFinder.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/flowgraph/pathfinder/AbstractPathFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1627
data node names may need some conversion, e.g. we may only have one node Node1, but it may be referred by multiple names Node1-dev, Node1-prod, so I am providing a config to supply a map for all this conversation.
added a unit test

[GOBBLIN-1627] provide option to convert datanodes names

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMCEMetadataKeys.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1628
Add a few fields similar to the format of fields in `IcebergMetadataCommitEvent`
- Add `clusterIdentifier`
- Split topic name/partition to separate fields
- Add exception message as a field (`exception.getCause().getMessage()` because otherwise the message will just be non-descriptive wrapper message like "failed to flush table").
Ran in test pipeline and observed failure events
6. Body …

[GOBBLIN-1628] Add/fix some fields of MetadataWriterFailureEvent

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1629
Now, GobblinMCEWriter can only catch exception, but we notice that if there is one issue in schema, i.e. recursive schema, it will throw StackOverflowError, and cannot handled by the pipeline and thus block other topics
unit test and deployed the change in prod env and verify it works as expected

[GOBBLIN-1629] Make GobblinMCEWriter be able to catch error when calculating hive specs

---

gobblin-iceberg/build.gradle
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisherTest.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriterTest.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java
gobblin-iceberg/src/test/resources/publisherTest/data.json
gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GobblinMetadataChangeEvent.avsc

- https://issues.apache.org/jira/browse/GOBBLIN-1613
Add optional field to GMCE schema for specifying metadata writers that should write. I've added corresponding code to filter base on this metadata writer field the GobblinMCEWriter
Unit tests added and tested on holdem using iceberg metadata repair job

[GOBBLIN-1613] Add metadata writers field to GMCE schema

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/UserQuotaManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanDagFactoryTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1630
Gobblin-as-a-Service emits flow level events for users to keep track of their flow compilation status, job status, number of workunits etc. However, users rarely if ever track adhoc-flows, where they are generally used in a fire-and-forget manner. Furthermore, keeping track of metrics continuously adds strains to the metric libraries which leads to wasted resources.
We should only be emitting flow level events for flows that are scheduled and saved.
This PR adds a flag for adhoc flows such that downstream executions can also differentiate scheduled and adhoc flows, so that downstream workloads can also …

[GOBBLIN-1630] Remove flow level metrics for adhoc flows

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/pathfinder/AbstractPathFinder.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/FlowConfigUtils.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/flowgraph/pathfinder/AbstractPathFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1632
use data node aliases to figure out data node names before using DMAS 
some minor refactoring, moved `getDataNodes` from AbstractPathFinder to FlowConfigsUtils

[GOBBLIN-1632] use data node aliases to figure out data node names before using DMAS

---

gobblin-utility/src/main/java/org/apache/gobblin/util/WriterUtils.java
gobblin-utility/src/test/java/org/apache/gobblin/util/WriterUtilsTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1619
- Race condition for creating parent directories, causing FileNotFound exception even when the file exists on file system
- HDFS fs.mkdirs atomically creates missing parent directories. Thus, the recursive approach is making unnecessary calls.
In HDFS, which the current [FileSystem](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/fs/FileSystem.html) interface is built upon, guarantees the parents will be created. So, all FileSystem class implementations should also follow this behavior. 
See the [FileSystem](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/fs/FileSystem.html) …

[GOBBLIN-1619] WriterUtils.mkdirsWithRecursivePermission contains race condition and puts unnecessary load on filesystem

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-data-management/src/main/java/org/apache/gobblin/runtime/retention/DatasetCleanerCli.java
gobblin-data-management/src/main/java/org/apache/gobblin/runtime/retention/DatasetCleanerTask.java
gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/data/management/retention/DatasetCleanerJob.java

- https://issues.apache.org/jira/browse/GOBBLIN-1636
DatasetCleaner internally launches the clean tasks for each version of the dataset in an ExecutorService and then waits for the tasks to get completed in the close() method but since DatasetCleanerTask never invokes close() soWe observed that the Gobblin tasks and Job finish early and don’t wait for all the dataset versions to get deleted successfully. 
6. Body explains "what" and "why", …

[GOBBLIN-1636] Close DatasetCleaner after clean task

---

gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/TimingEvent.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaAvroJobStatusMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1634
On Gobblin as a Service flows can fail SLAs if they do not receive a Kafka event in some designated amount of time.
Since GaaS supports retrys on failures, these failures due to SLAs should also be retryable.
However, if the flow is cancelled from a user specified event through the API we do not want to retry.
Additionally, we also do not want to retry if a flow is skipped due to concurrent jobs running at the same time, as it is unlikely without a more sophisticated waiting algorithm that the job will be finished by the time the job is retried again, wasting resources.
1. Subject is separated from …

[GOBBLIN-1634] Add retries on flow sla kills

---

gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/service/modules/orchestration/AzkabanClient.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/UserQuotaManager.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/UserQuotaManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1638
Sending a client request to Azkaban can sometimes lead to a TimeoutException. This TimeoutException handled by the guava retrying library wraps it in a different exception for some reason unlike other exceptions, so needs special handling. https://github.com/rholder/guava-retrying/issues/29
Upon further inspection on Azkaban even if the request times out the job can still be running on the executor, so it's unsafe to force the request to retry; there needs to be special handling/checking around timeouts before retrying to not duplicate jobs and overload Azkaban.
The timeout can lead to the thread …

[GOBBLIN-1638] Fix unbalanced running count metrics due to Azkaban failures

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriterWithPartitionInfoException.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMetadataException.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMCEMetadataKeys.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1637
- Add info of which metadata writer failed in the failure events
- Add which operation type failed. To do this, split up the events so that there's a separate event if opType changes, otherwise the event offset ranges could contain multiple different offsets
- Add which partition values were intended to be added/dropped as part of these GMCE. To do this added a `HiveMetadataWriterWithPartitionInfoException.java` only thrown from hive writer in order to pass partition info back to MCE Writer
- Fix bug in hive metadata writer where failure in flush would throw RuntimeException, but catch block only …

[GOBBLIN-1637] Add writer, operation, and partition info to failed metadata writer events

---

gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTest.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTestWithExpiration.java

update unit test
update requestedContainerCountMap
- https://issues.apache.org/jira/browse/GOBBLIN-1643
There's a bug in "requestTargetNumberOfContainers" method in YarnService when shrinking the container size: it incorrectly updates the requestedContainerCountMap which cause the container count result in wrong number.
Passed unit tests and also tested in cluster.

Fix bug when shrinking the container in Yarn service

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterManager.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixAssignedParticipantCheck.java

- https://issues.apache.org/jira/browse/GOBBLIN-1644
Added log line for the current instance name and the assigned participant if the participant check fails
```
2022-05-10 18:42:23 PDT INFO  [pool-35-thread-1] org.apache.gobblin.cluster.HelixAssignedParticipantCheck 145 - The current helix instance is not the assigned participant. helixInstanceName=WorkerInstance_0, assignedParticipant=WorkerInstance_0
```
Ignore how the names are the same. I added some temp code to trigger the log line in the UT
Doesn't need tests. its just a log line
3. Subject does not end with a …

[GOBBLIN-1644] Log assigned participant when helix participant check fails

---

gobblin-compaction/src/main/java/org/apache/gobblin/compaction/action/CompactionCompleteFileOperationAction.java
gobblin-compaction/src/main/java/org/apache/gobblin/compaction/mapreduce/MRCompactionTask.java
gobblin-compaction/src/main/java/org/apache/gobblin/compaction/verify/CompactionTimeRangeVerifier.java
gobblin-compaction/src/test/java/org/apache/gobblin/compaction/verify/CompactionTimeVerifierTest.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1633
- The issue is that when [CompactionCompleteFileOperationAction.java](https://github.com/apache/gobblin/pull/3494/files#diff-1cff14b642342f6005b830c658cae9c6030148c9c79cf3a914d9acac57f3c644) succeeds , it persists the init time using the key `CompactionSlaEventHelper.LAST_RUN_START_TIME`. However, if the job fails after this point but before metadata registration, then the files will not be registered until the next re-compaction cycle determined by `compaction.timebased.min.recompaction.duration`. 
- Note: This value for the `CompactionSlaEventHelper.LAST_RUN_START_TIME` is used by the …

[GOBBLIN-1633] Fix compaction actions on job failure not retried if compaction succeeds

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/DefaultGobblinJobMetricReporter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/GobblinJobMetricReporter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/ServiceGobblinJobMetricReporter.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/LocalJobLauncherTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/metrics/GobblinJobMetricReporterTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanDagFactoryTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1639
For Adhoc flows in GaaS, metrics are still being emitted on the Gobblin pipeline. This will use the adhoc configuration to determine whether or not to emit these metrics.
For non-GaaS initiated pipelines (will be controlled by a configuration key) there will be no naming changes
For GaaS pipelines they will use the naming convention `GobblinService.<FlowGroup>.<FlowName>.<EdgeId>.<MetricName>` so that they can be grouped together with the flow compilation status and the running status of these flows
3. Subject does …

[GOBBLIN-1639] Prevent metrics reporting if configured, clean up workunit count metric

---

gobblin-compaction/src/main/java/org/apache/gobblin/compaction/action/CompactionCompleteFileOperationAction.java
gobblin-compaction/src/main/java/org/apache/gobblin/compaction/mapreduce/MRCompactionTask.java

- https://issues.apache.org/jira/browse/GOBBLIN-1649
The change made in [GOBBLIN-1633 ](https://github.com/apache/gobblin/pull/3494)may cause resourcing issues that affect other jobs because recompaction is expensive. The original change was made so that hive registration would be reattempted if there was a failure during the oncompleteactions. Ideally hive registration needs to happen another way or recompaction portion is skipped
Tested on parallel pipeline (and verified that the "bug" is back) and that compaction works
4. …

[GOBBLIN-1649] Revert gobblin-1633

---

gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/kafka/client/AbstractBaseKafkaConsumerClient.java

I think we should provide an API to fetch only one kafka topic's partitions. Right now, there is only getTopics() API which fetches all the topics metadata which is very unnecessary.
- https://issues.apache.org/jira/browse/GOBBLIN-1640
trivial change

[GOBBLIN-1640] add an API in AbstractBaseKafkaConsumerClient to list selected topics

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/HiveRegister.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1651
Currently hiveRegister.close() waits for futures with no timeout, which could cause long delays in GMIP failing/restarting if there is hive slowness. Adding an option to configure this timeout, and by default in GMIP setting it to the same timeout as hive calls during normal operation.

[GOBBLIN-1651] Add config to set close timeout in HiveRegister

---

gobblin-metastore/src/main/java/org/apache/gobblin/metastore/MysqlStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/db/ServiceDatabaseProviderImpl.java
gobblin-utility/src/main/java/org/apache/gobblin/util/jdbc/DataSourceProvider.java
gobblin-utility/src/main/java/org/apache/gobblin/util/jdbc/MysqlDataSourceUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1648
To avoid Gobblin Cluster Manager downtime, observed during DB failover (when the currently connected instance which was active becomes a follower), detect once the connection on hand becomes read-only.  Enforce verification when this happens, so we know to create new, replacement connections (to a read-write host).
This addresses the one code path where this wasn't happening.  in addition, it adds logging to trace when the validation query was successfully initialized, just in case the code we believe to be executing is not in fact.
2. Subject is …

[GOBBLIN-1648] Complete use of JDBC `DataSource` 'read-only' validation query by incorporating where previously omitted

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/UserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/UserQuotaManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1650
Certain GaaS flows can have a large number of flows that can cause instability on dependent services. We want to be able to control the throughput of flows from a flowgroup granularity on top of a user granularity. We keep the quota configuration separate as there can be many users submitting flows to the same flowgroup.

[GOBBLIN-1650] Implement flowGroup quotas for the DagManager

---

gobblin-completeness/src/main/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifier.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1657
- There are quiet topics where data can be generated quiet infrequently causing the completion watermark to lag. Also, a commit operation could miss completion watermark update if there is a lag in kafka audit.
To fix above issues:
- Added logic to check audit count on change_property operation type for the next window of current watermark 
If counts match or an empty map is returned then consider audit count as complete and update the watermark.
- Added a config in KafkaAuditVerifier to return complete if found an empty map (with no counts from audit system) 
Added unit test to update completion …

[GOBBLIN-1657] Update completion watermark on change_property in IcebergMetadataWriter

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterConfigurationKeys.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinTaskRunner.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnAutoScalingManager.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnContainerRequestBundle.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnHelixUtils.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/event/NewContainerRequest.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/GobblinYarnTestUtils.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnAutoScalingManagerTest.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTest.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTestWithExpiration.java
gobblin-yarn/src/test/resources/YarnServiceTest.conf

- https://issues.apache.org/jira/browse/GOBBLIN-1661
This change enable Helix instances use the specific tag defined(if exists) in their Job/Workflow. This makes the Helix cluster management easier and more strait forward, as each job's instances can carry unique Helix tag. 
In this case, for each Gobblin job run, helix tasks within this job will
be assigned to containers with desired helix tag and resource. This can make within one Gobblin job run, multiple resource config can be set for different topics, instead of the need of creating new Helix cluster for different Gobblin job run setting.
Passed all updated unit tests, tested in the cluster.
1. …

Make Yarn container and helix instance allocation group by tag

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetrieverTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1652
Now in some conner case, we fail to process one kafka message, and it's super hard to get the reason for why it fails. To get more info there we want to add more log when processing message. Along with this, we need to add null check in 
modifyStateIfRetryRequired to avoid NPE as well.
Add unit test

[GOBBLIN-1652]Add more log in the KafkaJobStatusMonitor in case it fails to process one GobblinTrackingEvent

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1664
Currently if a table fails to write, we reset the writer that failed, and also remove it from the `tableOperationTypeMap` to avoid a no-op flush. However, if the writer that failed is not the first writer, there may still be other succeeding writers that we do want to flush. Removing this line so that we will still flush even if there was a failure of a writer for this situation.
Trivial
6. …

[GOBBLIN-1664] Allow table to flush after write failure

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1662
When flows are retried automatically, GaaS Dagmanager would perform submitJob() function again.
Add a guard against currentAttempts() to ensure that each flow is only incremented a single time

[GOBBLIN-1662] Fix running counts for retried flows

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/predicates/ExistingPartitionSkipPredicate.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/predicates/ExistingPartitionSkipPredicateTest.java
gobblin-docs/case-studies/Hive-Distcp.md

Currently the hive.dataset.existing.entity.policy.ABORT will not
abort if there is an existing partition. One option to resolve this
is to support the ABORT configuration but that might be backwards
incompatible, so introducing a new skip predicate called
ExistingPartitionSkipPredicate that will skip any partition that
already exists in the target table
- https://issues.apache.org/jira/browse/GOBBLIN-1667
My PR introduces a new simple skip predicate called ExistingPartitionSkipPredicate which will skip the partition if it exists in the target table.
My PR adds a unit test for the new predicate
2. Subject …

[GOBBLIN-1667] Create new predicate - ExistingPartitionSkipPredicate

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/GobblinMCEProducer.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisherTest.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GobblinMetadataChangeEvent.avsc

- https://issues.apache.org/jira/browse/GOBBLIN-1668
Pass audit count maps from streaming through a new field in GMCE, then publish those counts to a new tier after iceberg registration is done.
- Add a new field in GMCE to contain a serialized audit map string
- Populate this in MCE publisher using key `SERIALIZED_AUDIT_MAP_KEY` (will be set internally)
- After iceberg commit, call sendAuditCounts using the map from the GMCE (will be implemented internally)
- Also use a new WhitelistBlacklist for sending these audit counts, because we may want to count only for specific dbs.
Tested in parallel pipeline …

[GOBBLIN-1668] Add audit counts for iceberg registration

---

bin/gobblin.sh

- https://issues.apache.org/jira/browse/GOBBLIN-1671
When using `mapreduce` mode in gobblin.sh, the additional jars passed to
gobblin.sh through --jars are comma separated. They are incorrectly
added to HADOOP_CLASSPATH that takes colon (:) separated jars. The fix is to convert the external jars to use colon instead of comma as delimiter when adding to the GOBBLIN_CLASSPATH, which in turn is used to set HADOOP_CLASSPATH
Tested locally. The error was reproducible locally, which caused ClassNotFoundException.
The PR fixes the issue and jobs are able to get the dependent jars correctly.
Otherwise, this PR does not seem to need tests as it's a script change …

[GOBBLIN-1671] : Fix gobblin.sh script to add external jars as colon separated to HADOOP_CLASSPATH

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/TimeAwareRecursiveCopyableDataset.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/TimeAwareRecursiveCopyableDatasetTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1677
Fix bug where TimeAwareRecursiveCopyableDataset could not read user configured timezones due to not reading the key correctly.
Line 72 : DateTimeZone.forID(DATE_PATTERN_TIMEZONE_KEY))  ===> should be DateTimeZone.forID(properties.get(DATE_PATTERN_TIMEZONE_KEY)))

[GOBBLIN-1677] Fix timezone property to read from key correctly

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1686
Currently we catch `RuntimeException` in `IcebergMetadataWriter.flush()` and rethrow another `RuntimeException`. We should throw `IOException` in all cases so that MCE writer will catch and be able to skip it in the case of a single dataset issue.
Trivial

[GOBBLIN-1686] Allow all iceberg exceptions to be fault tolerant

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/MetadataWriterKeys.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1694
- Explicitly add the GMCE topic as a field in hive commit events. This was in the events before from gobblin framework, but in some situations (not sure why) the event submitter got reset and stopped including it in the events, so explicitly adding it now. For backwards compatibility keeping the name `kafkaTopic` for the key.
- Also updated an iceberg writer log line to avoid blowing up the logs when gmip is going through older offsets (before it printed the entire GMCE which was extremely large).
Tested in gmip test pipeline
2. Subject is limited to 50 …

[GOBBLIN-1694] Add GMCE topic explicitly to hive commit event

---

gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigV2ResourceLocalHandler.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/FlowSpec.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_catalog/FlowCatalog.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/util/InjectionNames.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceConfiguration.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/BaseFlowToJobSpecCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowConfigResourceHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowConfigV2ResourceHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowExecutionResourceHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobSchedulerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1689
Now, when add/update flow spec, we rely on scheduler to compile the flow and return status, but in warm standby mode, where every host can accept and process request but not running the flow, we should be able to compile flow without scheduler. 
Unit test

[GOBBLIN-1689] Decouple compiler from scheduler in warm standby mode

---

gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
gobblin-metastore/src/test/java/org/apache/gobblin/metastore/testing/TestMetastoreDatabaseServer.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/AbstractUserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/InMemoryUserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/UserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/InMemoryUserQuotaManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobSchedulerTest.java

@umustafi @ZihanLi58
- https://issues.apache.org/jira/browse/GOBBLIN-1691
Current UserQuotaManager stores quota usage in memory and thus cannot share it with other instances of the Gobblin Service.
A mysql based manager can share the quota usage with other instances.
Added unit tests in MysqlUserQuotaManagerTest

[GOBBLIN-1691] add MysqlUserQuotaManager

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixUtils.java
gobblin-cluster/src/test/java/org/apache/gobblin/cluster/GobblinHelixJobLauncherTest.java
gobblin-cluster/src/test/java/org/apache/gobblin/cluster/GobblinHelixJobSchedulerTest.java
gobblin-cluster/src/test/resources/GobblinHelixJobSchedulerTest.conf

- https://issues.apache.org/jira/browse/GOBBLIN-1702
Currently the HelixUtils.waitJobCompletion() has a bug when hob in STOPPING state, it immediately try to delete it, instead of waiting the job itself to transit to STOPPED state, due to the stoppingStateEndTime is not set correctly.
This fix the place where stoppingStateEndTime is set.
Added test cases

[GOBBLIN-1702] fix helix job wait completion bug when job goes to STOPPING state

---

gradle/scripts/buildscript.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-1711
gradle build works. CI should catch the rest of the issues since this is just a repo change. I am cleaning up a missed reference to jcentral.
- Related to  https://github.com/apache/gobblin/pull/3554
None because we are just changing the repo from jcenter to maven central

[GOBBLIN-1711] Replace Jcenter with maven central

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/TimeAwareRecursiveCopyableDataset.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/TimeAwareRecursiveCopyableDatasetTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1708

[GOBBLIN-1708] Improve TimeAwareRecursiveCopyableDataset to lookback only into datefolders that match range

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixMultiManager.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/GobblinEventBuilder.java
gobblin-yarn/build.gradle
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinApplicationMaster.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/HelixInstancePurgerWithMetrics.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/GobblinYarnAppLauncherTest.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/HelixInstancePurgerWithMetricsTest.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTest.java

To avoid accumulation of helix instances, we should clean up over time. But we can only perform the clean up at startup because it's unsafe to call the API while instances are being created / removed.
- https://issues.apache.org/jira/browse/GOBBLIN-1704
Gobblin streaming does not currently clean up helix instances.This means that after spikes in the number of gobblin task runners, causes accumulation in the `INSTANCES` znode, which will exceed the 1MB limit. This will cause zookeeper to either have delays or drop requests completely. 
This change cleans up these offline instances on startup. We cannot periodically clean up these instances because it is …

[GOBBLIN-1704] Purge offline helix instances during startup

---

gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_store/MysqlBaseSpecStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/BaseFlowToJobSpecCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/AbstractUserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/InMemoryUserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/UserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/InMemoryUserQuotaManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1703
When a gaas flow request comes, resource handler checks the quota right there.
However, if the flow has runImmediately=true, the quota will be checked again when the first job starts. This should be avoided.

[GOBBLIN-1703] avoid double quota increase for adhoc flows

---

gobblin-utility/src/main/java/org/apache/gobblin/util/HadoopUtils.java
gobblin-utility/src/test/java/org/apache/gobblin/util/HadoopUtilsTest.java

org.apache.gobblin.util.HadoopUtilsTest.testMoveToTrash
```
Gradle suite > Gradle test > org.apache.gobblin.util.HadoopUtilsTest > testMoveToTrash STARTED
Gradle suite > Gradle test > org.apache.gobblin.util.HadoopUtilsTest > testMoveToTrash PASSED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 2s
7 actionable tasks: 2 executed, 5 up-to-date
3:31:11 PM: Execution finished ':gobblin-utility:test --tests …
```

[GOBBLIN-1719] Replace moveToTrash with moveToAppropriateTrash for hadoop trash 

---

gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinBaseOrcWriter.java
gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/RowBatchPool.java
gobblin-modules/gobblin-orc/src/test/java/org/apache/gobblin/writer/RowBatchPoolTest.java

As mentioned in the ticket the existing array resizing is buggy for ORC's vectorized row batch.  In almost all the cases we should fall back on the 'enlargeFactor' option. In some cases where throughput may be a big concern. We should enable the proposed approach below.  We've seen some benefits of using the current approach. 
1. Major GC pauses have reduced
BEFORE ![Before](https://user-images.githubusercontent.com/129474/193365599-87151649-9edc-4849-9d20-227613715aba.png)
AFTER ![After](https://user-images.githubusercontent.com/129474/193365616-82bad31f-b3b8-421e-94a2-043bf37a7082.png)
3. Memory is …

GOBBLIN-1715: Support for Vectorized row batch pooling

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1712
Transient errors during shutdown like "Filesystem closed" can cause GMCEs to get skipped when they would have succeeded on the restart. Adding a list of exceptions like this that will fail the container to avoid data loss in these cases.
Also use `Throwables.getRootCause` to get a more meaningful exception message for the failure events since sometimes the events just have a generic "Flush failed" message right now.
Added unit test
4. Subject uses the imperative mood ("add", …

[GOBBLIN-1712 ] Fail GMIP container for known transient exceptions to avoid data loss

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1723
Sometimes hive writer hits AlreadyExistsException when adding a partition because of metastore slowness/timeout when checking existence of the partition. Since the partition has already been added, there's no need to throw an exception/fail in this case, so skipping in the case of this exception.
Trivial

[GOBBLIN-1723] Ignore AlreadyExistsException in hive writer

---

gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/BaseFlowGraphHelper.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/SharedFlowGraphHelper.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/FsFlowGraphMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/FsFlowGraphMonitorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1724
Support a flowgraph format where nodes can be shared between subgraphs. This allows for less repetition and cleaner hierarchies within the flowgraph.
It will follow the following structure
```
/flowgraph
../nodeA
..../nodeB
......edgeAB.properties
../nodeB
....nodeB.properties
/nodes
..nodeA.properties
..nodeB.properties
```
Where nodeA will use the shared properties, and nodeB will use the union of the properties in nodeB from /flowgraph and the shared properties.
4. Subject …

[GOBBLIN-1724] Support a shared flowgraph layout in GaaS

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1729
For consistency, use the root cause of the exception to match against the list of transient exceptions. Also use toString() instead of getMessage(), so that the exception class itself can be matched as well.
Updated unit test

[GOBBLIN-1729] Use root cause for checking if exception is transient

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisherTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1732
Before, when sending change_property events, the GMCE publisher searches in the top level dataset directory for an example file. This could find files with other schemas/paths if there are different directories in the dataset directory. This PR changes it to search under the `TimeBasedWriterPartitioner.WRITER_PARTITION_PREFIX` folder if that config exists to avoid this.
Also, there was no reason why there was a list/for loop here before, because `ConfigurationKeys.DATA_PUBLISHER_DATASET_DIR` is a single path, so the for loop has been removed.
Updated unit test
1. Subject is separated from body by a …

[GOBBLIN-1732] Search for dummy file in writer directory

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/BaseFlowGraphHelper.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/SharedFlowGraphHelper.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/FsFlowGraphMonitorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1722
Gobblin flowgraph supports both .conf and .properties files
SharedFlowgraph explciitly only looks for .properties files, which misses nodes that are defined in .conf files (HOCON format). 
We should support both these types.
Also fix a bug where exception outputs are not properly formatted when adding flowgraphs

[GOBBLIN-1733] Support multiple node types in shared flowgraph, fix logs

---

gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnAutoScalingManager.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnHelixUtils.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTest.java

Due to race condition and incorrect API call, the yarn service both allocates too many containers and in rare cases has a discrepancy between the number of containers state due to race conditions.
- https://issues.apache.org/jira/browse/GOBBLIN-1728
Due to an inaccurate API call, Yarn service can endlessly request thousand of containers in edge case scenarios. This is wasteful and puts a large load on Yarn RM. We saw over 50k containers requested in edge case scenarios. After this fix, the number of containers is only ~6k-9k
- This patch contains 2 main fixes:
- fix yarn service allocating too many containers
- non descriptive logs in yarn service that …

[GOBBLIN-1728] Fix YarnService incorrect container allocation behavior

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterConfigurationKeys.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixDistributeJobExecutionLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobScheduler.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1721
Currently when we receive a job restart(handleUpdateJobConfigArrival), GobblinHelixJobLauncher will firstly call  helixTaskDriver.waitToStop to stop the workflow, then initiate the new one. We observe the behavior of Helix taking exceptionally long to stop the workflow, making the job state staying in STOPPING status. This will make waitToStop timeout and throw exception all the time, making the new flow never be able to launch.
We can utilize Delete API in this case since our job is stateless for Helix, to avoid job hanging.
Tested in the cluster.
2. …

[GOBBLIN-1721] Give option to cancel helix workflow through Delete API

---

gobblin-core/src/main/java/org/apache/gobblin/destination/DestinationDatasetHandler.java
gobblin-core/src/main/java/org/apache/gobblin/destination/DestinationDatasetHandlerService.java
gobblin-core/src/test/java/org/apache/gobblin/destination/TestDestinationDatasetHandler.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1734
Rich now DestinationDatasetHandler does not support streaming sources, this PR will provide an interface to include streaming sources as well.

[GOBBLIN-1734] make DestinationDatasetHandler work on streaming sources

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-modules/gobblin-service-kafka/src/main/java/org/apache/gobblin/service/SimpleKafkaSpecProducer.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java

- https://issues.apache.org/jira/browse/GOBBLIN-1730
Include flow execution id when try to cancel/submit job using SimpleKafkaSpecProducer
Unit test;
Test on local service and verify that we job spec uri contains the flow execution id

[GOBBLIN-1730] Include flow execution id when try to cancel/submit job using SimpleKafkaSpecProducer

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1738
staging directory cleanup code runs before the current position of dataset handler code execution. dataset handler code execution should happen before the cleanup so that the cleanup code gets the right configs. actually it was moved to the wrong location in this pr https://github.com/apache/gobblin/pull/3592 to put together all the code of processing and transforming workunitsStream at the same place.
5. …

[GOBBLIN-1738] move dataset handler code before cleaning up staging data

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/BaseFlowToJobSpecCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManager.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1737
Change the way we get config to to consistent with other mysql store
Only check quota in compiler when the flow compile successful and explain flag is not set
Change the way we initialize the quota Manager.
Deploy locally and verify the mysql quota manager works as expected

[GOBBLIN-1737] Fix bug when using mysql user quota manager

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDataset.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java
gobblin-utility/src/main/java/org/apache/gobblin/util/PathUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1720
- Update `IcebergDataset` to add the ancestor ownership and permissions using `CopyableFile.resolveReplicatedOwnerAndPermissionsRecursively` and preserve them between src and dest
- Augment `IcebergDatasetTest` unit test to exercise Fs ownership and permissions are preserved

[GOBBLIN-1720]Add ancestors owner permissions preservations for iceberg distcp

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1742
when DestinationDatasetHandlerService is created using try with resources, it immediately calls the close method on the handlers that does the cleanup. But we should wait till the job completes so that cleanup happen in the end.
trivial changes, kind of rollback of https://github.com/apache/gobblin/commit/4d991a9bd872a98bc52dda2ec366ad7d77847f9a#diff-873102512dd53692aefa05b778655ebe076b5afc268439b7ad906dc740bf9b24
5. …

[GOBBLIN-1742] do not close DestinationDatasetHandlerService prematurely

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinTaskRunner.java

- https://issues.apache.org/jira/browse/GOBBLIN-1743 
this PR https://github.com/apache/gobblin/pull/3519/files has a call to Helix cluster contained outside of a conditional that was previously never encountered for use cases without yarn. I moved the call back inside the conditional to ensure we don't attempt to retrieve an instanceConfig that is not registered with Helix as we don't have Yarn mode enabled. 
6. Body explains "what" and …

[GOBBLIN-1743] Ensure GobblinTaskRunner works without Yarn use

---

gobblin-compaction/src/main/java/org/apache/gobblin/compaction/source/CompactionSource.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSource.java

- https://issues.apache.org/jira/browse/GOBBLIN-1747
adding job.name and job.id to workunits created by kafka and compaction source. these configs can be used by dataset handlers or other part of code flow
trivial changes. tested manually

[GOBBLIN-1747] add job.name and job.id to kafka and compaction workunits

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopyableFile.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDatasetFinder.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/ManifestBasedDatasetFinderTest.java
gobblin-data-management/src/test/resources/manifestBasedDistcpTest/sampleManifest.json
gobblin-utility/src/main/java/org/apache/gobblin/util/PathUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1741
Create manifest based dataset finder
unit test, test on azkaban to see it can copy data

[GOBBLIN-1741] Create manifest based dataset finder

---

gobblin-data-management/src/test/java/org/apache/gobblin/data/management/conversion/hive/materializer/HiveMaterializerTest.java

HiveMaterializerTest is blocking CI/CD on Github, but works locally
From a lengthy investigation it seems to have some issue with creating the database on the Github runner, I cannot pinpoint what is happening exactly but the issue is that the HiveDbcpConnector and the HiveMetastore client java class are not reading/writing to the same locations, this is causing issues that is very difficult to debug.
This PR disables this test on CI/CD until more investigation can be done
4. …

[GOBBLIN-1758] Disable flaky HiveMaterializerTest on CI/CD

---

README.md

Updates the slack invite link
Updates the slack link. It should never expire this time.

[GOBBLIN-1761] Update Gobblin OSS Slack channel link to a never-expire link

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixUnexpectedStateException.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixAssignedParticipantCheck.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixUtils.java
gobblin-cluster/src/test/java/org/apache/gobblin/cluster/HelixUtilsTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1744
I made 2 helix null checks in 2 separate spots
----------
In production, we've seen that the helix assigned participant check failed due but due to helix issues not due to a split brain. When helix returns null, this actually means that the data does not exist. This is an unexpected case and we can assume that Helix itself is having issues (i.e. not a Gobblin side issue).
I am adding this log because if the Helix assigned participant check fails, this is most likely a Helix issue but it's not immediately obvious what the exact issue is. I've added 2 likely scenarios we've seen internally as common …

[GOBBLIN-1744] Improve handling of null value edge cases when querying Helix

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopyConfiguration.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopyableFile.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/OwnerAndPermission.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/publisher/CopyDataPublisher.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1765
We want to add support so that when user specify a dir in manifest file, we will blindly sync the metadata for that dir regardless the modification time.
This change include:
1. add config to support whether we want preserve mod time for dir and by default it's true
2. Change the FileAwareInpuSTreamWriter so that during commit, when we see the output path already exist and CopyableFile is one directory, we won't rename/overwrite the target dir incase we overwrite the file that already been copied in the same job.   We still want to add this dir as copyableFile because only in this case, we can make …

[GOBBLIN-1765] Add support to sync metadata for dir in manifest based copy

---

gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GaaSObservabilityEventExperimental.avsc
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSObservabilityEventProducer.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/GaaSObservabilityProducerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1770
When looking into the IssueRepository before the creation of GaaSObservabilityEvents, many issues do not populate their fields for details and summary. This is because the Issue details are composed of a stack trace, but since Issues can be composed of warn/error logs and stack traces, it is not guaranteed that every issue has a corresponding stack trace.
However, from investigation it looks like the automated troubleshooter will always populate the issue severity, code, and summary.
This PR accounts for this when creating a GaaSObservabilityEvent by modifying the schema to allow both null and …

[GOBBLIN-1770] Allow null values for fields in GaaSObservabilityEvent.Issue fields which are optional

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/SafeDatasetCommit.java
gobblin-utility/src/main/java/org/apache/gobblin/util/JobLauncherUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1771
Large datasets (multiple terabytes), depending on their jobs, can send a large number of repetitive logs for failing dataset states and cleaning up the dataset state.
For failed dataset states, this PR will only print the unique exceptions for each taskState, and not log repeated errors for each workunit on the errors in the taskstate.
When cleaning up the writer directories, we also can just log when we are deleting the parent directories, not necessarily each subdirectory which can be a large number. 
3. Subject …

[GOBBLIN-1771] Clean up logs for dataset commit and file cleanup

---

gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1777
Unlike other metrics gauges need to be registered. Quick fix to this.

[GOBBLIN-1777] Register gauge metrics for change monitors

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/InnerMetricContext.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerMetrics.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerFlowTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1778
Now dag managers have the assumption that it is the only process that can update mysql table and the in-memory state is always in sync with mysql. But we do notice that during the leader transforms period, it's possible that two dag manager can run concurrently and update the mysql db at the same time. 
To address that, we need either add a lock to make sure only one dag manager is working at one time, or we need to have a housekeeping thread to periodically sync the in-memory state with the mysql table. After discussion, we choose to go with the later approach and we do have the assumption that GaaS …

[GOBBLIN-1778] Add house keeping thread in DagManager to periodically sync in memory state with mysql table

---

gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceIT.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTestWithExpiration.java
gobblin-yarn/src/test/resources/YarnServiceIT.conf

This renaming is done as YarnServiceTest currently is disabled on CI testing. We would like to add unit tests in this file that are run during CI, but this requires removing some components. This rename is so we don't override YarnServiceTest Git history, simply a rename to YarnServiceIT. After renaming the tests to YarnServiceIT, there will be another PR that has a new file of the original name (YarnServiceTest.java) will be created, new unit tests will be created there, and those new tests will run in CI testing.
- https://issues.apache.org/jira/browse/GOBBLIN-1780 …

[GOBBLIN-1780] Refactor/rename YarnServiceIT to YarnServiceTest

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1782

[GOBBLIN-1782] Fix Merge State for Flow Pending Resume statuses

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-metastore/src/main/java/org/apache/gobblin/metastore/MysqlStateStore.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/dag_action_store/MysqlDagActionStore.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_catalog/FlowCatalogTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/BaseFlowToJobSpecCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobSchedulerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1773
We used to check the quota when we accept flow for ad-hoc flow and run immediately flow. But we only use the same execution id for ad-hoc flow. So for a run immediately flow, we will check quota once with a random execution id, and then really run the job with a different execution id and forget the first one. This will cause us to double-check the quota for a run immediately flow and never release one of them. 
In this PR:
1. We change the behavior to only check the quota upon accepting the request when it's an adhoc job, and for run-immediate flow, we won't check the quota. If quota exceeds, we will …

[GOBBLIN-1773] Fix bugs in quota manager

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/metastore/HiveMetaStoreUtils.java
gobblin-hive-registration/src/test/java/org/apache/gobblin/hive/metastore/HiveMetaStoreUtilsTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1774
Problem Statement:
>     Non-optional union: A union type with more than one non-null option type
>     e.g. [“int”, “string”] or [“null”, “int”, “string”]
>     Alternate phrasing:
>     A schema where there 's a union type of >= 2 branches which are non null.
>     [int, null] - no
>     [int, string] - yes
>     [int, string, null] yes
- Iceberg, unlike Hive, does not support non optional `uniontypes` (i.e. [uniontypes](https://cwiki.apache.org/confluence/display/hive/languagemanual+types#LanguageManualTypes-UnionTypesunionUnionTypes) that can be null). These are supported as struct types instead.
- …

[GOBBLIN-1774] Util for detecting non optional uniontype columns based on Hive Table metadata

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1775
**Problem Statement:**
The way GMIP handles Hive has 2 issues:
1. `drop_file` GMCE creates a table even if it does not already currently exist. 
2. Schema issues when creating tables throws an exception and the running container fails. Upon restart, the container will resume from the same watermark and the container will again face an exception. (i.e. when there are schema issues they should be skipped over instead of aborted). These GMCE's are not possible to process, causing indefinite starvation
Other changes:
- The `HiveMetadataWriter#write` method is a bit hard to read and [mixes layers of …

[GOBBLIN-1775] GMIP Hive metadatawriter should gracefully fail

---

gobblin-docs/user-guide/Configuration-Properties-Glossary.md

- https://issues.apache.org/jira/browse/GOBBLIN-1611
The description about  the writer.codec.type property in the document has a little mistake. This PR corrects it.
No additional test, since it's just a documentation fix.
I ran `mkdocs serve` locally and confirmed the document was modified as expected.

[GOBBLIN-1611] Fix a wrong value for writer.codec.type in the document

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/Dag.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerMetrics.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerFlowTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1784
Currently, the DagManager will poll a dag until it receives that the *job* has been completed/failed/cancelled, and then emit the flow event and clean up the dag. However, on service restart or crash, it is possible that the flow event never gets emitted. Since the dag is already cleaned up, this job status becomes stuck, and will never progress.
To address this scenario, this PR only cleans up dags when the cleanup function polls that the *flow status* is completed. If it does not receive the flow status that the job is completed within 3 minutes of the dag finishing all of its jobs, then it will …

[GOBBLIN-1784] Only clean dags from the dag manager if a flow event is received

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java

- The GobblinMCEWriter is defined as a public class, we should make its constructor `GobblinMCEWriter()` public too to allow usages outside of the package. For example, my current use case is allowing unit tests in other modules to construct a `GobblinMCEWriter` to set up a test infra, without the constructor being public, I have no other way to construct a object of it.
`gradle :gobblin-iceberg:test`

Make GobblinMCEWriter constructor public

---

gobblin-metastore/src/main/java/org/apache/gobblin/metastore/StateStore.java
gobblin-metastore/src/main/java/org/apache/gobblin/runtime/StateStoreBasedWatermarkStorage.java
gobblin-modules/gobblin-helix/src/main/java/org/apache/gobblin/metastore/ZkStateStore.java
gobblin-modules/gobblin-helix/src/test/java/org/apache/gobblin/runtime/ZkDatasetStateStoreTest.java

Let's improve the interface for state stores that Gobblin uses to storing watermarks and various other pieces of state. State stores like zookeeper have native methods for batch deletes that we cannot take advantage of with the current implementation.
This is useful for cleaning up no longer used watermarks in a state store. The size of a state store has physical limitations depending on the underlying implementation (e.g. ZK supports roughly ~10k tables per state store). And even migrating to a new state store requires a lot of operational burden / doesn't clean up the old state store.
Design:
- Add a default method to the interface for backward …

[GOBBLIN-1787] Ability to delete multiple watermarks in a state store

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/datanodes/iceberg/IcebergDataNode.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/flowgraph/datanodes/iceberg/IcebergOnHiveDataNodeTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1789
As part of supporting multiple Iceberg Catalogs, I am defining generic `IcebergDataNode` that will represent an Iceberg node in the Flow Graph for any type of Iceberg Catalog and not just Hive. Below are the changes added as part of this PR:

[GOBBLIN-1789] Create Generic Iceberg Data Node to Support Different Types of Catalogs

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GaaSObservabilityEventExperimental.avsc
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/TimingEvent.java
gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanJobLauncher.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/TimingEventUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSObservabilityEventProducer.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaAvroJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanDagFactoryTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/GaaSObservabilityProducerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1790
In GaaS, the observability events are still missing a few fields:
1. Job Orchestration time
2. Flowgraph edge ID
3. Spec executor ID
4. Azkaban user (if eligable)
Additionally, the job start time field is inaccurate as it is set from multiple GTE events. We should be tracking it from a consistent point in the Gobblin Job, otherwise it will not be accurate when measuring the job runtime.
6. …

[GOBBLIN-1790] Add and change appropriate job status fields for observability events

---

gobblin-api/src/main/java/org/apache/gobblin/dataset/DatasetConstants.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/BaseIcebergCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergCatalogFactory.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetFinder.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergHiveCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTableTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1786
Currently, we provide support for Iceberg based Distcp for Hive Catalogs. However, we now want to extend this functionality to any generic type of Iceberg Catalog and be able to perform Distcp operation from source to destination. As part of this initiative below are changes:

[GOBBLIN-1786] Support Other Catalog Types for Iceberg Distcp

---

gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GaaSObservabilityEventExperimental.avsc

- https://issues.apache.org/jira/browse/GOBBLIN-1794
Fields `jobPlanningStartTime` and `jobPlanningEndTime` both are newly added fields to the avro schema for GaaSObservabilityEventExperimental. These 2 newly added fields should have defaults in order to support schema compatbility

[GOBBLIN-1794] Add defaults to newly added fields in observability events

---

gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceIT.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1796
In the event that container launch fails, Gobblin logs unhelpful information about the failure  and there is no observability with what went wrong. This code change will at least tell us what the command was for starting up the container. We will only print this if exit code `1`. See https://komodor.com/learn/how-to-fix-container-terminated-with-exit-code-1/ for a high level description of what this code tends to mean (ignore that it is for K8s, the same principle applies).
> 
> Exit Code 1 indicates that a container shut down, either because of an application failure or because the image pointed to an …

[GOBBLIN-1796] Log startup command when container fails to startup

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/dataset/DatasetUtils.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/dataset/DatasetsFinderFilteringDecorator.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/DatasetsFinderFilteringDecoratorTest.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/predicates/DatasetHiveSchemaContainsNonOptionalUnion.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/predicates/DatasetHiveSchemaContainsNonOptionalUnionTest.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java
gobblin-utility/src/main/java/org/apache/gobblin/util/function/CheckedExceptionPredicate.java

- https://issues.apache.org/jira/browse/GOBBLIN-1779
Problem Statement:
Goal is to make it easy for users to filter out datasets with non optional unions. Avro and ORC flexible schema supports non optional unions. But Iceberg does not support these schemas. This can cause mismatched schemas when writing with different writers. e.g. writing with iceberg will write a struct but writing native orc writer will write as a uniontype 
- https://github.com/apache/gobblin/pull/3632
Future users may want to implement similar complex filtering on the results of their dataset finders. And this filtering may be very complex. The goal is to make it easy for users to …

[GOBBLIN-1779] Ability to filter datasets that contain non optional unions

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1801
Match exceptions against a known list of non-transient/dataset-specific exceptions, and avoid counting those towards the max failed datasets in a container since they are not indicating any wider issue.
Tested in parallel GMIP pipeline by manually throwing an exception with dataset failure limit of 0

Add matching of non-transient exceptions that will avoid failing the container in GMIP

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/BaseIcebergCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetFinder.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergHiveCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergRegisterStep.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTableTest.java
gradle/scripts/dependencyDefinitions.gradle

Implementing the capability to register iceberg tables based on table metadata updates after the data has been published. Below are the changes as part of this PR:

[GOBBLIN-1802]Register iceberg table metadata update with destination side catalog

---

defaultEnvironment.gradle
gobblin-admin/build.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-1807
Context: https://groups.google.com/g/cascading-user/c/qAQvajapawI
The repo conjars.org is not reliably available and has issues with not being able to build due to dependency failure. Gobblin OSS relies on an older version of Apache Calcite that does not exist on mvnrepository. So we must continue to use conjars as our repo.
The repo https://conjars.wensel.net/ is more reliable and does not cause our github actions to fail
Dependency on hive 1.0.1 which has a dependency on calcite-core 0.9.2 means we have no choice in using this repo
```
project :gobblin-hive-registration > …
```

[GOBBLIN-1807] Replaces conjars.org with conjars.wensel.net

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/DatasetCleaner.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/version/finder/LookbackDateTimeDatasetVersionFinder.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/version/finder/LookbackDateTimeDatasetVersionFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1809
Add new version finder which does not actually list filepaths, and just constructs all unique path names/versions for a given lookback time with a given path partition pattern. This is useful for example with the iceberg cleanable datasets, which if decoupled from data files, should not depend on existence of the file path.
Also fixed a bug in `DatasetCleaner` which sometimes causes the job to fail during shutdown and not print the actual issue with the job.
Added unit test and tested in retention job
3. Subject …

[GOBBLIN-1809] Add new lookback version finder for use with iceberg retention

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GaaSObservabilityEventExperimental.avsc
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/TimingEvent.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/test/MetricsAssert.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/DatasetTaskSummary.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/JobLauncherTestHelper.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/TestWorkUnitStreamSource.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSObservabilityEventProducer.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaAvroJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/GaaSObservabilityProducerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1806
This PR adds a `JobSummaryTimer` which is emitted right before the `JobCommitTimer`, after the datasets are written and published to the destination.
Collection of the records/bytes is dependent on the DataWriter implementing `bytesWritten()` and `recordsWritten()`, which is implemented by most writers and those that extend from the `InstrumentedDataWriter`. 
Gobblin-as-a-Service ingests these JobSummaryTimer events and serializes them into the GaaSObservabilityEvent
Added unit tests to test that every job with writers emits a JobSummaryTimer and the serializer/deserialization in the …

[GOBBLIN-1806] Submit dataset summary event post commit and integrate them into GaaSObservabilityEvent

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterConfigurationKeys.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixDistributeJobExecutionLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixRetriggeringJobCallable.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixUtils.java
gobblin-cluster/src/test/java/org/apache/gobblin/cluster/GobblinHelixJobLauncherTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1813
When Helix is under tremendous load, Helix workflows can easily exceed the 5 minute timeout. When the timeout is exceeded, our jobs clean up the Gobblin job state. Gobblin considers these workflows effectively dead. 
If Helix were to schedule these workflows, the workflows will spin up and the tasks assigned will immediately have a `FileNotFoundException`, causing an immediate termination of the container. This ironically puts a greater load on ZK / Helix and can further increase the delays in future workflow submissions.
The workflow timeouts need to be not hardcoded so that users can adjust the …

[GOBBLIN-1813] Helix workflows submission timeouts are configurable

---

gobblin-core/src/main/java/org/apache/gobblin/converter/serde/HiveSerDeConverter.java
gobblin-core/src/main/java/org/apache/gobblin/writer/HiveWritableHdfsDataWriterBuilder.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/HiveSerDeWrapper.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/HelixInstancePurgerWithMetrics.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java

- https://issues.apache.org/jira/browse/GOBBLIN-1817
change some deprecated hive classes so that downstream projects can upgrade to higher version of hive.
In Hive 1.x which is used in Gobblin, Every kind of serde extends to `AbstractSerDe`, EXCEPT `OrcSerDe` which extends to `VectorizedSerDe`. Also all kind of serdes implements `SerDe`, so in Gobblin we type casted every type of serde to `SerDe` interface.
However in Hive 2.x `SerDe` interface is removed and all type of serdes now extend to `AbstractSerDe` including `OrcSerDe`.
So I have made changes in this PR to handle the special case of `OrcSerDe` in such a way that if hive 2.x is on the classpath, …

[GOBBLIN-1817] change some deprecated code and fix minor codestyle

---

gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanGobblinYarnAppLauncher.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/GobblinYarnAppLauncherTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1818
Moved the logic of creating yarn clients out of the constructors, because child class variables are not initialized until super class is created and hence it cannot use it's own initialized variables in modifying logic in overriden methods.
This is in the continuation of https://github.com/apache/gobblin/pull/3671 work

[GOBBLIN-1818] initilaize yarn clients in yarn app launcher so that a child class can override the yarn client creation logic

---

gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GaaSObservabilityEventExperimental.avsc
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSObservabilityEventProducer.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/GaaSObservabilityProducerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1816
GaaSObservabilityEvents can add the following fields to increase its effectiveness:
1. Job properties, serialized in JSON. This enables the querying of specific job properties, which used to only be possible through MySQL on scheduled flows. Now it is possible to query for properties to solve questions such as `"How much memory are GaaS pipelines requesting from Azkaban on average?"`
2. GaaS Instance ID, to differentiate between different clusters of GaaS which write to the same observability topic.
3. Subject does …

[GOBBLIN-1816] Add job properties and GaaS instance ID to observability event

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixUtils.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnAutoScalingManager.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java

- https://issues.apache.org/jira/browse/GOBBLIN-1819
Logging during helix workflow submission are currently pretty unhelpful. I Here are some examples of what has changed.
```
Before:
Waiting for work flow initialization.
After:
Waiting for workflow initialization. workflowName=job_GobblinHelixJobLauncherTest1_1504201348470, jobName=job_GobblinHelixJobLauncherTest1_1504201348470, timeSubmittedEpoch=1681873657577, timeoutSeconds=300
```
```
Before:
Work flow job_KafkaHdfsStreamingTrackingOrcMedVol0_1680885392649 initialized
After:
Workflow job_GobblinHelixJobLauncherTest1_1504201348470 initialized. timeToInitMs=2003
```
```
ContainerInfo{ …
```

[GOBBLIN-1819] Log helix workflow information and timeout information during submission wait / polling

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-core/src/main/java/org/apache/gobblin/writer/PartitionedDataWriter.java
gobblin-core/src/test/java/org/apache/gobblin/writer/PartitionedWriterTest.java
gobblin-core/src/test/java/org/apache/gobblin/writer/test/TestPartitionAwareWriterBuilder.java

- https://issues.apache.org/jira/browse/GOBBLIN-1828
When HDFS slowness happens, we can get stuck in creating writer phase and never proceed further. So we want to add a timeout guarantee there to make sure to fail earlier and retry in this case. 
Add new unit test and run job to make sure timeout can cause the task to retry

[GOBBLIN-1828] Implement Timeout for Creating Writer Functionality

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixJobsMapping.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/service/StreamingKafkaSpecExecutorTest.java
gobblin-modules/gobblin-service-kafka/src/main/java/org/apache/gobblin/service/SimpleKafkaSpecProducer.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/job_monitor/KafkaJobMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1831
This PR handles the scenario where concurrent jobs can run on Gobblin cluster from GaaS and handles the cancellation logic properly.
When executing jobs from GaaS to Gobblin cluster, there can be a mismatch of flowexecution ids to jobs running on Gobblin cluster. The old behavior was that the current job will be deleted regardless of the execution ID, but this could mean that a state mismatch could lead to current jobs being deleted when they should still continue to run.
To address this, we tried adding the FlowExecutionId to the jobSpec, but that meant that jobs could run concurrently on Gobblin …

[GOBBLIN-1831] Use flowexecutionid in kafka monitor and jobnames

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnAutoScalingManager.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java

- https://issues.apache.org/jira/browse/GOBBLIN-1823
**Problem**: When Yarn allocates "ghost containers" without calling the onContainerAllocated() method and when the container is eventually released, onContainersCompleted() is called, container numbers mismatches can occur. 
In the onContainerAllocated() method, we add the container to the containerMap using the container ID as the key, and increase the count for the specific tag.
In the onContainersCompleted() method, we remove the container from the containerMap and decrease the count. However, in some cases, we find that the containerMap does not contain the ID, and we ignore this while still …

[GOBBLIN-1823] Improving Container Calculation and Allocation Methodology

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/version/HiveDatasetVersionCleaner.java

- https://issues.apache.org/jira/browse/GOBBLIN-1825
Hive retention would perform two tasks: drop the partition first and then delete the underlying files. Now, if for some reason the partition was dropped, but we couldn't delete the underlying files, the job would still succeed. Thus, if we try to re-run the job, it wouldn't fine any work and the hdfs files would never be discovered.
In order to avoid running into this situation, I have made the below changes:
- Delete the underlying files first and then try dropping the hive partition
- throw the exceptions and fail the job rather than marking the job status as successful
1. Subject is separated from …

[GOBBLIN-1825]Hive retention job should fail if deleting underlying files fail

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1805
Currently, Audit check is done for [currentWatermark, currentWatermark +1hour] window for quiet topics. However when the audit check for this window fails (due to an upstream bug in audit), the watermark never progress as the currentWatermark is never updated. To avoid this we keep progressing the watermark by checking the window [currentHour -1, currentHour] window
Updated unit test to reflect this change
5. Body wraps …

[GOBBLIN-1805] Check watermark for the most recent hour for quiet topics

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixTask.java
gobblin-cluster/src/test/java/org/apache/gobblin/cluster/GobblinHelixTaskTest.java
gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1836
In our system, when a helix disconnection occurs, we take the necessary step to cancel the ongoing job. Furthermore, when we opt for a graceful exit, we ensure that no exception is thew and we mark the task as complete. However, it is important to note that due to this graceful exit, the task cannot be retried accurately. 
So we need to introduce a cancel flag to make sure we return the correct task status
Also, a small fix to add schema.literal when creating a new iceberg table. (Ideally, iceberg should work without schema.literal property, but some downstream query engine need the original avro …

[GOBBLIN-1836] Ensuring Task Reliability: Handling Job Cancellation and Graceful Exits for Error-Free Completion

---

gobblin-data-management/build.gradle
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-iceberg/build.gradle
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/Utils/IcebergUtils.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java
gradle/scripts/defaultBuildProperties.gradle
gradle/scripts/dependencyDefinitions.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-1835
I want to upgrade our iceberg version to 1.2.0 to leverage performance improvements such as optimized metadata caching, reduced memory consumption, and faster metadata commits, enhanced APIs, schema evolution. Most importantly it natively provides support for Apache Spark 3.x, allowing seamless integration and improved performance when using Iceberg with Spark. As part of this upgrade, below are the major changes:
- Update method signatures for `CatalogUtil.loadCatalog()` and `Snapshots.allManifests`
- Initialize and load `HiveCatalog` via `CatalogUtil` inside `IcebergMetadataWriter` 
- Updated unit …

[GOBBLIN-1835]Upgrade Iceberg Version from 0.11.1 to 1.2.0

---

gobblin-compaction/src/main/java/org/apache/gobblin/compaction/hive/HiveTable.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/dataset/DatasetsFinderFilteringDecorator.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/metastore/HiveMetaStoreUtils.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/predicates/DatasetHiveSchemaContainsNonOptionalUnion.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/predicates/DatasetHiveSchemaContainsNonOptionalUnionTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1843
Datasets with URN that have a `-` will be represented in Hive with an `_`.  Failing to do so will mean the code will fail to pull up the correct hive table
This code will replace all '-' with '_' before querying hive. We do not need to consider lower / uppercase because hive is case insensitive

[GOBBLIN-1843] Utility for detecting non optional unions should convert dataset urn to hive compatible format

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-runtime/src/main/java/org/apache/gobblin/scheduler/JobScheduler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java

* Adds logging at 3 critical points to ensure no scheduled events are missed
- when jobs are first rescheduled (or updated)
- each trigger of a new job
- when jobs are unscheduled
- https://issues.apache.org/jira/browse/GOBBLIN-1846
Follow up to previous PR [GOBBLIN-1837](https://github.com/apache/gobblin/pull/3700) to add validation via logging statements that we will query to ensure no scheduled trigger events are missed during host downtime. Also moves `Flow` specific logic from `JobScheduler` to `GobblinServiceJobScheduler`. 
N/A to be added in the future but will be validated using these statements and local deploy
1. Subject is separated from body …

[GOBBLIN-1846] Validate Multi-active Scheduler with Logs

---

gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnAutoScalingManager.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnAutoScalingManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1844
When the `GobblinClusterManager` starts, it will do an asynchronous deletion of workflows (all workflow deletions are technically async). And we do not want the yarn service to acknowledge these workflows while the controller processes the request asynchronously. 
When there is heavy load on the zookeeper cluster, the deletes will be slow and there will be significant overlap of having 2 of the same workflows 
Modified existing unit to cover edge case of workflows that marked for deletion. Also refactored the testing code to improve the readability since there is a ton of copy paste involved for …

[GOBBLIN-1844] Ignore workflows marked for deletion when calculating container count

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1842
Add timers for:
- hivespec computation
- write for each metadata writer
- flush for each metadata writer
These timers are set up with a 1 hour sliding window, so the statistics will be for the last hour of execution. The timers are registered with metric context so they will send metrics through gobblin's metric framework. Also, added logging during every flush interval (every 1 min) which logs the current mean/99th percentile of every timer, so it is easier to see where time is being spent.
Ran test pipeline. Example timer logs:
```
2023-06-13 11:16:58 PDT INFO  [StreamModelTaskRunner] …
```

[GOBBLIN-1842] Add timers to GobblinMCEWriter

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterConfigurationKeys.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-cluster/src/test/java/org/apache/gobblin/cluster/GobblinHelixJobLauncherTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1847
If the JobLauncher encounters any errors, Gobblin code cleans up the working directory that contains Gobblin state. But we do not clean up the helix workflows. This can cause us to spin up helix workflows that do not have valid Gobblin State on HDFS / S3. 
When this occurs, it causes rapid container recycling, which puts tremendous load on Zookeeper due to Helix API calls, causing a peak in ZK callbacks
The cancellation logic is obnoxious, so here is the high level of what happens.
1. Calling `AbstractJobLauncher#cancelJob(JobListener)` sets `AbstractJobLauncher#cancellationRequested` to `true`
2. This …

[GOBBLIN-1847] Exceptions in the JobLauncher should try to delete the existing workflow if it is launched

---

gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/MetricTagNames.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerMetrics.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1848
DagManager metrics due to being sent as a gauge in some backend system needs differentiation despite using the same ContextAwareMeter class.
This PR is to add tags (which are extensible) for metric emitting classes to check these tags to process before sending the metrics to their corresponding backend system
Needed to modify DagManagerTests to handle concurrency scenarios where multiple DagManager threads in tests would affect other tests
4. Subject uses the imperative mood …

[GOBBLIN-1848] Add tags to dagmanager metrics for extensibility

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java

The HiveMetadataWriter and IcebergMetadataWriter make schema changes and need to make calls to Hive / HDFS per GMCE. This is an unnecessary hotspot because we can reference the schema cache beforehand and determine whether we actually need to make network call. 
Also, there are cases where the HiveMetadataWriter can update the latest schema to be a null schema. We want to fail earlier, and fail the code when updating the latest schema map instead of failing later with a NPE. I've also changed the if statement from `containsKey` to checking if the value is null so that if this somehow happens in the …

[GOBBLIN-1853] Reduce # of Hive calls during schema related updates in metadata registration

---

gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinBaseOrcWriter.java
gobblin-modules/gobblin-orc/src/test/java/org/apache/gobblin/writer/GobblinOrcWriterTest.java

pull request to start a conversation on whether to remove unused code from Orc Writer
Ticket https://issues.apache.org/jira/browse/GOBBLIN-1854

[GOBBLIN-1854] Remove unused ORC writer code

---

gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/predicates/DatasetHiveSchemaContainsNonOptionalUnionTest.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java

HiveMetaStoreTest from Iceberg had some minor changes to the class that affect the order of metastore creation. This did not break our CI because iceberg tests run as a group in ABC order, so one of the tests was properly starting the metastore. But going forward, we should call the method and have an empty catch in case another test already init the hive metastore. 
This would cause a NPE when the tests were run in isolation.  …

[GOBBLIN-1855] Metadata writer tests do not work in isolation after upgrading to Iceberg 1.2.0

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1856
As part of this PR, I want to add metrics for `FlowTriggerHandler` to help understand if we were able to obtain, handle and transition the different lease acquiring statuses when we switch to multi-active scheduler mode where each scheduler would attempt to lease a flow event and process it further based on the status of the attempt. 
- Builds Successfully
6. Body explains "what" and "why", …

[GOBBLIN- 1856] Add flow trigger handler leasing metrics

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/listeners/EmailNotificationJobListener.java

- https://issues.apache.org/jira/browse/GOBBLIN-1860
When job fails during workunit creation, it sets the job state as FAILED, but does not set JOB_FAILURES_KEY.
It also does not have datasets created if it fails at such an early stage and the current code relies on dataset state's properties to find the failure count.
This PR will set the config JOB_FAILURES_KEY when the job fails.
trivial change

Correct num of failures

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1861
The total completion watermark whitelist was not respected when a change_property GMCE was sent. These should be treated the same as add_files GMCEs.
Tested with a whitelisted and non-whitelisted topic in test pipeline.

[GOBBLIN-1861] Fix bug with total count watermark whitelist

---

gobblin-completeness/src/main/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifier.java
gobblin-completeness/src/test/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifierTest.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/CompletenessWatermarkUpdater.java

- https://issues.apache.org/jira/browse/GOBBLIN-1864
If one type of watermark calculation fails (e.g. due to missing tier, or count being 0) it causes all watermarks not to get updated. This PR allows watermarks to get updated individually to avoid blocking other ones if they are working correctly.
Added unit test which reproduces the issue

[GOBBLIN-1864] Catch exceptions if specific watermark calculation fails

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/DagActionStore.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerFlowTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1863
Bugs
- `DagManager` check leader status before `addDag` bc calling this method from non-leader hosts throws a `NPE` which may caused failed dag event to be emitted. Then those job executions are skipped since they are marked as failed. 
- also handle `LAUNCH` type events upon leader change and setting a new participant `DagManager` to be active. Failing to handle these events may be causing missed flow launches on any leader change or restart. 
Refactoring Done 
- Create a static function in Orchestrator to emit a flow failed event if spec compilation fails. This function is shared by the between the …

[GOBBLIN-1863] Multi-Active Launch Job Related Issues

---

gobblin-completeness/src/main/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifier.java
gobblin-completeness/src/test/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifierTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1862
Due to possible issues upstream reporting incorrect reference counts for number of records, there could be times when the reference count reported to be 0.
In the current case, if reference tier counter is reported to be 0 but there are counts in other PCM tiers, an exception is thrown, however is silently swallowed, thus, causing the watermark to not move forward in this case.
This PR fixes said issue, allowing reference count to be 0 but no less. For completeness percentage calculations in such cases, the completeness will be reported as positive infinity as any number divided by double 0 is positive …

[GOBBLIN-1862] Allow reference count to be 0 but no less

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixJobsMapping.java
gobblin-cluster/src/test/java/org/apache/gobblin/cluster/GobblinHelixJobMappingTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1865
With "gobblin.cluster.job.useGeneratedJobIds" configuration, jobs with that prefix should be using the system timestamp of Gobblin cluster instead of a provided flow execution ID.
Instead of this, it is more consistent to append flowExecutionId to a jobName then append a timestamp on top of that, so that all earlystop jobs relating to a flow execution can be tracked.
Now jobNames should have the following structure:
job_ActualJob<jobName><flowExecutionId><timestamp>
The timestamp is needed so that Helix can run concurrent jobs given a job ID.
2. Subject …

[GOBBLIN-1865] Fix for job id tracking where configuration is unnecessary

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterTest.java

Gobblin distcp copies the file permissions but not the sticky bit. As the expectation is that the destination files have preserved permissions from the source, we want to maintain the sticky bit across copies.
-- Unit test to compare the input and output FsPermission with and without sticky bits with different permission modes
-- A workflow on HDFS where a  directory is copied from one location to another.
☑︎ My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit …

[GOBBLIN-1866] Preserve sticky bit across distcp copies

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/orc/HiveOrcSerDeManager.java
gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-1871
hiveMetadataWriter might update Avro.schema.literal without making the corresponding change in hive schema columns
Also change the HiveOrcSerDeManager to only talk with hdfs when necessary to reduce the num of call to hdfs.
unit tested

[GOBBLIN-1871] Fix bug that hiveMetadataWriter may make the hive schema columns inconsistent with the Avro.schema.literal

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1859 
In multi-active mode, multiple participants will be reading/writing to MySQL table. We want to make sure each participant acts on the table in a manner that takes into account that the state may have changed while the MultiActiveLeaseArbiter is processing the result of a READ. This PR adds unit tests that validate SQL Insertion statements are conditional upon the state of the particular row corresponding to the flow action event being unchanged from the read made by this participant. 
The PR adds 3 unit tests to test each of the cases of acquiring a lease to ensure the following insertions do not …

[GOBBLIN-1859] Multi-active Unit Test for Multi-Participant state 

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/kafka/HighLevelConsumer.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1872
Add, clean up, and move some log statements that would help debug issues with multi-active scheduler. 

[GOBBLIN-1872] Modify logs to improve multi-active debugging

---

gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GenericRecordToOrcValueWriter.java
gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinBaseOrcWriter.java
gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinOrcWriterBuilder.java
gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/InstrumentedGobblinOrcWriter.java

Currently the metrics for streaming mainly relate to the Kafka consumption side. We want to also capture metrics through events from the ORCWriter to capture the memory usage and internal performance of the writer.
This PR captures the following information:
1. Schema name
2. Bytes written
3. Records written
4. Rowbatch size (buffer size)
5. Resize count
Logs of the fields looks like the below:
```
2023-08-03 18:23:46 PDT INFO  [StreamModelTaskRunner] org.apache.gobblin.writer.InstrumentedGobblinOrcWriter  - Emitting ORC event metrics
2023-08-03 18:23:46 PDT INFO  [StreamModelTaskRunner] …
```

[GOBBLIN-1869] Create instrumented orc writer

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/main/java/org/apache/gobblin/scheduler/JobScheduler.java
gobblin-runtime/src/test/java/org/apache/gobblin/scheduler/JobSchedulerTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1875
We are seeing the following errors when trying to schedule reminders for Multi-active scheduler after losing lease acquisition:
`Unable to store Trigger with name: '...' and group: '...' because one already exists with this identification`
The Quartz scheduler allows multiple unique triggers mapping to one job in a N:1 relation, but this requires the trigger having a unique identifier associated with it. When we create triggers, we were previously using only the job name and group to identify the trigger so we're unable to add additional triggers for the same job. The trigger key is only used …

[GOBBLIN-1875] Create Unique Trigger Keys 

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDatasetFinder.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/ManifestBasedDatasetFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1877
Manifest-based copy (FS distcp) shouldn't presume the manifest files to be on the same FileSystem used as the I/O source to copy from.  Instead allow optional config to provide an alternative solely for reading manifest files (enumerating filepaths).
Proposed config: `gobblin.copy.manifestBased.read.fs.uri` (after `gobblin.copy.manifestBased.manifest.location`, and `source.filebased.fs.uri`)
Improved `ManifestBasedDatasetFinderTest`
4. Subject uses the imperative mood ("add", …

Enhance `ManifestBasedDatasetFinder` with config for specifying an alt. FS solely for reading manifests

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/KafkaCommonUtil.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/KafkaCommonUtilTest.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaExtractorTest.java

Gobblin has the ability to process records from multiple kafka brokers, across multiple *.conf files and *.job files. But the tracking metadata / observability does a poor job of specifying which broker the events correspond to.
This is because Gobblin was written with the assumption that it would consume from a single aggregate kafka broker (e.g. brooklin). But going forward, we want to add support for multiple *.conf files each with their own kafka broker. This change adds a utility for mapping the different Kafka broker URI's to a simple human readable name that can be used within …

[GOBBLIN-1876] Kafka source / extractor utility to get a simple name for kafka brokers

---

gobblin-utility/src/main/java/org/apache/gobblin/util/ProxiedFileSystemCache.java
gobblin-utility/src/main/java/org/apache/gobblin/util/ProxiedFileSystemUtils.java
gobblin-utility/src/main/java/org/apache/gobblin/util/WriterUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1883
While creating a proxied file system, sometimes we need multiple tokens. e.g. when there exists multiple namenodes 
trivial change

[GOBBLIN-1883] Multiple tokens in ProxiedFileSystem

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/RuntimeMetrics.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandlerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1881 
The following error is thrown when attempting to schedule reminder events. 
```
{{The job ... referenced by the trigger does not exist.","stackTrace":[
{"index":0,"call":"storeTrigger","columnNumber":null,"fileName":"RAMJobStore.java","lineNumber":422,"nativeMethod":"0","source":"org.quartz.simpl.RAMJobStore"}
,
{"index":1,"call":"scheduleJob","columnNumber":null,"fileName":"QuartzScheduler.java","lineNumber":932,"nativeMethod":"0","source":"org.quartz.core.QuartzScheduler"}
,
{"index":2,"call":"scheduleJob","columnNumber":null,"fileName":"StdScheduler.java","lineNumber":258,"nativeMethod":"0","source" …
```

replace job props upon setting reminder scheduler event

---

FlowTriggerHandlerTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1884
There is a bug in which launch actions get accumulated and "stuck" in the dag action store, so every time a leader is changed or the service is re-deployed we will keep redoing old launch actions again and again. 
*Also includes a few refactoring improvements to the `FlowTriggerHandler` to make it more readable and ensure the right `JobKey` when adding trigger reminders to the `Scheduler`. …

[GOBBLIN-1884] Delete Dag Action After Loading from Store Upon Startup

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1885
Ensure all logs are in UTC for ease of comparison between other logging done.

[GOBBLIN-1885] Ensure All Logged Timestamps are in UTC

---

gradle/scripts/dependencyDefinitions.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-1886
Who knows what changed between these versions. 1.0.3 release notes don't exist but here are the [1.0.4 ones ](https://helix.apache.org/1.0.4-docs/releasenotes/release-1.0.4.html)🤣 
The main thing that seems important is ZK client version bumped from 3.4.9 to 3.6.3, which means the default ZK client version will have a client side jute max buffer decreased from 4MB to 1MB. Within LinkedIn, we addressed this by overriding with the following java arg. This client buffer will be exceeded if a znode exceeds ~8k children. This will occur within Gobblin if your Gobblin jobs are particularly large and you are …

[GOBBLIN-1886] Upgrade to Helix 1.1.0

---

gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceExtractor.java
gobblin-salesforce/src/test/java/org/apache/gobblin/salesforce/SalesforceExtractorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1888
- The current query for fetching high watermark metadata does a sort and then picks the top row, which times out for very large datasets.
- MAX based query should perform better
- Added tests for the get high watermark metadata method, where the changes are done.

[GOBBLIN-1888] Optimizing high watermark metadata query for SFDC

---

gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/HiveMetadataWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1890
It's possible for GMIP to support processing GMCEs that correspond to records from different kafka brokers. This can be done by passing in extra information as a prefix to the offset range map. However, we must also update the algorithm for fetching the topic name to allow for a prefix.
For example, the following offset range keys should be valid and all parse to the `topicname`
- `topicname-0`
- `kafkaBroker1.topicname-0`
- `colocation-kafkabroker1.topicname-0`
4. Subject uses …

[GOBBLIN-1890] Offset ranges allow multiple formats GMIP

---

gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSource.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaTopic.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSourceTest.java

Kafka source is commonly used to ETL from Kafka to HDFS as part of Fast Ingest. This data is later exposed via Hive / Iceberg to be queried via Spark / Trino. Hive does not support `.` to be part of the table name. This means that in order to keep consistency between Hive and Kafka names, it requires some conversion. 
This is a high toil and low reward process. It would be great to have a flag to just outright ignore these topics altogether. Especially if the Gobblin operator does not control who creates Kafka topics. 
2. Subject is limited to 50 …

[GOBBLIN-1894] Add ability to filter topics with a period in kafka source

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopyableFile.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterTest.java
gobblin-utility/src/main/java/org/apache/gobblin/util/filesystem/FileSystemDecorator.java

- https://issues.apache.org/jira/browse/GOBBLIN-1892
- We run into issues when we try to update acl entries for existing paths. Previously, used `setAcl`API provided by `hadoop.fs`, but it requires all 3 Acl entry types: `user, group and others` to be always present, which might not be case when fetching acl entries. Thus, `modifyEntries` should be used since it will either update existing Acls or set Acls if missing.
- modified unit tests
6. …

[GOBBLIN-1892] replace setAcl with modifyEntries while preserving acls during distcp

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
ligradle/findbugs/findbugsExclude.xml

- https://issues.apache.org/jira/browse/GOBBLIN-1897
Fix the findBugsMain complaining redundant null check after adding annotation of EqualsAndHashCode. More details can be found in  https://github.com/projectlombok/lombok/issues/891
Original error:
Code | Warning
RCN | Redundant nullcheck of this$partitions, which is known to be non-null in org.apache.gobblin.source.extractor.extract.kafka.KafkaTopic.equals(Object)
RCN | Redundant nullcheck of $partitions, which is known to be non-null in org.apache.gobblin.source.extractor.extract.kafka.KafkaTopic.hashCode()
local build pass the check
2. Subject is …

[GOBBLIN-1897] Fix the findBugsMain complaining redundant null check after adding annotation of EqualsAndHashCode

---

gobblin-completeness/src/main/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifier.java
gobblin-completeness/src/test/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifierTest.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/CompletenessWatermarkUpdater.java

- https://issues.apache.org/jira/browse/GOBBLIN-1896
Problem:
There is a scenario where an audit map returned from Kafka Audit URL is not empty, as when there are counts in at least one of the Kafka tiers. However, it is possible that all or some of the source tiers and all or some of the reference tiers have 0 count. If there is a comparison of two counts where the source tier is 0 and the reference tier is also 0, it will result in a 0/0 calculation when calculating the percentage completeness and this evaluates to NaN (not a number). In this scenario as the determined percentage is NaN, the completeness check for that type of completeness will be …

[GOBBLIN-1896] Fix completion percentage calculation when non-empty map and srcTier is 0 and refTier is 0

---

gobblin-utility/src/test/java/org/apache/gobblin/util/ClustersNamesTest.java
gobblin-utility/src/test/resources/GobblinClustersNames.properties

- https://issues.apache.org/jira/browse/GOBBLIN-1899
Nothing crazy here. I had concerns about the current behavior of the clusters names properties that is used to add the `clusterIdentifier` for GMCE and GTE. 
Internally we use non scheme in the properties with a port and it wasn't clear whether or not this code was working as expected. I've added these unit tests to both check this behavior and maintain this behavior going forward.
6. Body …

[GOBBLIN-1899] More unit tests for ClustersNames

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1900
MapReduce is an aging legacy technology, so it's worth exploring additional execution frameworks.  To simplify experimentation and evaluation, add the ability to "borrow" MR's WorkUnit preparation, so such forays may at first jump ahead to investigate WU execution.
The option `mr.persist.workunits.then.cancel` works as advertised.
successful manual testing
6. Body explains "what" and "why", …

Add `MRJobLauncher` option to persist WorkUnits, then cancel before running the job

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiterTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1907
When other participants complete a lease (not just acquire it) in the time that the current participant has attempted the lease, we will see a NULL `lease_acquisition_timestamp` and should appropriately handle the resulting value. This case was missed and we were only expecting another participant to have acquired the lease. 
We also add warning logs for `JobExceptions` that can be hiding the stack trace of errors encountered in runtime. 
Tested behavior without change to see NPE and after updates the tests pass without any exceptions 
2. Subject is …

[GOBBLIN-1907] Handle Lease Completion From Other Multi-active Participants

---

gobblin-modules/gobblin-helix/src/test/java/org/apache/gobblin/runtime/StateStoreWatermarkStorageTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1909
Github Actions CI fails consistently with this error:
```
Gradle suite > Gradle test > org.apache.gobblin.runtime.StateStoreWatermarkStorageTest > testPersistWatermarkStateToZk FAILED
java.lang.RuntimeException: Failed to create ZkStateStore with factory
at org.apache.gobblin.metastore.ZkStateStoreFactory.createStateStore(ZkStateStoreFactory.java:39)
at org.apache.gobblin.runtime.StateStoreBasedWatermarkStorage.<init>(StateStoreBasedWatermarkStorage.java:107)
at org.apache.gobblin.runtime.StateStoreWatermarkStorageTest.testPersistWatermarkStateToZk(StateStoreWatermarkStorageTest.java:65)
Caused by: …
```

[GOBBLIN-1909] Disable zk state store test as it tends to timeout on github runners

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1908
We had previously assumed the `Date` object returned from a `Trigger` uses the system default timezone, but taking a look at the javadoc and runtime values have shown it is already in UTC so we update our conversion function. To prevent further confusion about timezones, we also log the conversion that assumes the `Date` object is in system default timezone to make it easier to debug. 
6. …

[GOBBLIN-1908] Fix Date to Milliseconds Conversion to Use UTC 

---

gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceExtractor.java
gobblin-salesforce/src/test/java/org/apache/gobblin/salesforce/SalesforceExtractorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1911
- We updated the Salesforce high watermark query to use MAX aggregate function instead of order by with limit 1 as part of https://github.com/apache/gobblin/pull/3750.
- When there are no modified records, this query returns an empty row, compared to no rows with the previous query.
- This is resulting in NPE while trying to parse the high watermark value.
- Adding checks on the objects to prevent the NPE as part of this change.
- Added UTs to cover for the potential cases where empty response is returned for the high watermark query
2. Subject is …

[GOBBLIN-1911] Fixing NPE in Salesforce high watermark fetch

---

gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceExtractor.java
gobblin-salesforce/src/test/java/org/apache/gobblin/salesforce/SalesforceExtractorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1912
- We updated the Salesforce high watermark query to use MAX aggregate function instead of order by with limit 1, as part of #3750 
- The response for the aggregate query is a bit different from the previous version.
- Updating the parsing logic accordingly as part of this PR.
The new response looks as follows when there is no valid result of the MAX query:
```json
{
"totalSize": 1,
"done": true,
"records": [
{
"attributes": {
"type": "AggregateResult"
},
"expr0": null
}
]
}
```
When there is a valid value, it looks as follows:
```json
{
"totalSize": 1,
"done": true,
"records": [
{
"attributes": { …
```

[GOBBLIN-1912] Highwtm query record parsing fix

---

gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinBaseOrcWriter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncher.java
gobblin-utility/src/main/java/org/apache/gobblin/util/JobConfigurationUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1906
A customer reported seeing:
```
Error: java.io.IOException: Task failed: java.lang.IllegalArgumentException: The value of property <<redacted>> must not be null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
at org.apache.hadoop.conf.Configuration.set(Configuration.java:1260)
at org.apache.hadoop.conf.Configuration.set(Configuration.java:1241)
at org.apache.gobblin.util.JobConfigurationUtils.putStateIntoConfiguration(JobConfigurationUtils.java:95)
...
```
the appears to arise from concurrent modification to the `State`'s underlying `Properties` (i.e. between the time the …

[GOBBLIN-1906] Add null-check to `JobConfigurationUtils.putStateIntoConfiguration` to avoid `IllegalArgumentException`

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1913
We've determined the correct timezone for timestamp conversions in the scheduler trigger tracing logs. Remove unnecessary information to make log easier to read. 

[GOBBLIN-1913] Remove extra information from scheduler trigger tracing logs

---

gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/GobblinYarnAppLauncherTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1914
The current design of the GobblinApplicationMaster has a heavy dependency on Helix task framework. Going forward, we'd like to explore Gobblin on Temporal as an alternative to Helix TF. I am requesting the ability to add specify a custom Application Master class from the Azkaban yarn app launcher to allow experimentation with different GobblinAM implementations that do not rely on Helix.
Existing unit tests / internal testing …

[GOBBLIN-1914] Configurable Gobblin Application Master class for Yarn

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandlerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1920
When setting the reminder event we use the trigger time local to each host. Instead we want to use the timestamp from database to see consistency between hosts in case their clock drift is significant. 

[GOBBLIN-1920] Use db laundered timestamp for reminder event

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MultiActiveLeaseArbiter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiterTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1921
Reminder flow trigger events were being improperly handled and interpreted as new events because they are triggered linger time after the original trigger where epsilon < linger and we use epsilon to determine event distinctness. With reminder events being considered distinct events, we were launching excess concurrent flows that were then being cancelled. Now we handle reminder events differently from normal event triggers to ensure they're properly evaluated. Because of db laundering, reminder events are easy to handle - if they're older than the currently worked upon event in the database they can …

[GOBBLIN-1921] Properly handle reminder events

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandlerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1924
Reminder event flag is mistakenly always set to false, it is needed for reminder events to handle them differently than original events. 
Add this check to existing unit tests

[GOBBLIN-1924] Reminder event flag true

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/dag_action_store/MysqlDagActionStore.java

- https://issues.apache.org/jira/browse/GOBBLIN-1923
Add retention to lease arbiter table so it does not grow unbounded. The table can be as large as O(number of flows) which may grow so large that reading/writing from this table becomes time consuming and slows down our throughput of obtaining and evaluating leases for launching flows. 
- Remove default values from lease arbiter table (left off on previous PR)
- Increase default for scheduler max backoff to include more jitter between participants holding a reminder. 
4. Subject …

[GOBBLIN-1923] Add retention for lease arbiter table

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1926
For a large number of reminder events, we are still seeing the event be considered distinct and launching a separate execution. Analysis of the reminder events being considered unique shows that `reminder eventTimestamps` that are well in the past are handled properly by this [case](https://github.com/apache/gobblin/blob/e4cae2e3c559691f8b8873f81ab805c8a6482fd2/gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java#L296). However, a large number of reminder events fall into the case of being exactly equal to the timestamp in the database. Those are handled …

[GOBBLIN-1926] Fix Reminder Event Epsilon Comparison

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/DagActionStore.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MultiActiveLeaseArbiter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/RuntimeMetrics.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiterTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerMetrics.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandlerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1930
Improve logging and metrics around multi-active launch flow event handling to identify any missing events between the `MysqlMultiActiveLeaseArbiter` committing the launch event to the `dagActionStore` and the `DagActionMonitor` receiving events for processing. We want to be able to distinguish between the following cases of 
- events that are never received by the `DagActionMonitor`
- events incorrectly filtered out by the `DagActionMonitor`
- any failed submissions of dags to the `DagManager` either upon leader change or from the `DagActionChangeMonitor`
1. Subject is separated from body by a blank …

[GOBBLIN-1930] Improve Multi-active related logs and metrics

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/RecursiveCopyableDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java

This PR adds dataset path in IcebergDataset and RecursiveCopyableDataset , which is one of the most commonly used dataset type in distcp jobs. dataset path is needed by datasethandler to find the shard path.
- https://issues.apache.org/jira/browse/GOBBLIN-1929
This PR completes the work of https://github.com/apache/gobblin/pull/3799/files 
trivial changes, tested manually

[GOBBLIN-1929] add dataset root in some common type of datasets

---

gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSource.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/validator/TopicNameValidator.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/validator/TopicValidatorBase.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/validator/TopicValidators.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSourceTest.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/source/extractor/extract/kafka/validator/TopicValidatorsTest.java
gobblin-utility/src/main/java/org/apache/gobblin/util/ExecutorsUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1927
* Topic validation is used for validating topic and skipping the bad ones during work unite creation. This PR introduces a generic validation layer to support plugging in topic validator, to validate topic names, bad schema evolution, etc.
* More details in this PR:
* Add the topic validation support in `KafkaSource`
* Add the first validator `TopicNameValidator` into the validator chain, as a refactor of existing codes.
- Added `TopicValidatorsTest`
- Enhanced `KafkaSourceTest`
3. Subject does not end with a …

[GOBBLIN-1927] Add topic validation support in KafkaSource, and add TopicNameValidator

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/DagActionStore.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/kafka/HighLevelConsumer.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/RuntimeMetrics.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiterTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/ChangeMonitorUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1931
- Small refactor to improve coding style of `updateFlowExecutionId` method of `DagAction`. Add an additional clarifying comment to ensure the right `DagActions` are used. 
- Log when we filter out duplicates to ensure events are not wrongfully skipped

[GOBBLIN-1931] Refactor dag action updating method & add clarifying comment

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/kafka/HighLevelConsumer.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/RuntimeMetrics.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1934
We suspect that the HighLevelConsumer class may be dropping Kafka messages if the thread for a particular consumption queue is interrupted or stalled. Before changing how these queues are handled, we want to verify that blocked or dropped queues is the reason for missed messages by emitting metrics about each queue's size. 
Metrics added to be verified by monitoring 
6. Body explains "what" …

[GOBBLIN-1934] Monitor High Level Consumer queue size

---

gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/kafka/client/AbstractBaseKafkaConsumerClient.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/kafka/client/GobblinKafkaConsumerClient.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSource.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSourceTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1922
Add a new feature in Kafka source to create workUnit for selected topics partitions. This feature can provide functionality for:
1. Recompute and split tasks(workUnit) during runtime for selected topics partitions, instead of recompute for all Kafka topics
2. Make topic level replan feasible
3. One step closer to dynamic work unit allocation 
Need to have a followup to make work unit packer able to pack the recomputed workunits into a desired number of containers 
4. Subject …

[GOBBLIN-1922]Add function in Kafka Source to recompute workUnits for filtered partitions

---

gobblin-core/src/main/java/org/apache/gobblin/writer/partitioner/TimeBasedAvroWriterPartitioner.java

- https://issues.apache.org/jira/browse/GOBBLIN-1940
This PR expose functions in TimeBasedAvroWriterPartitioner in order to allow extended classes to be able to operate independently based on the writerPartitionColumnValue and calculate the timestamp of the record separately with different defaults.

[GOBBLIN-1940] Expose functions to fetch record partitionColumn value and customize default record timestamp

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-api/src/main/java/org/apache/gobblin/source/workunit/MultiWorkUnit.java
gobblin-api/src/main/java/org/apache/gobblin/source/workunit/WorkUnit.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/SingleTask.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopyableFile.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/JobContext.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/JobState.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/TaskState.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/GobblinOutputCommitter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncher.java
gobblin-utility/src/main/java/org/apache/gobblin/util/JobLauncherUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1919
Modest changes before (re-)using it, to simplify impl and add JSON pretty-printing.
continues use of existing tests

[GOBBLIN-1919] Simplify a few elements of MR-related job exec before reusing code in Temporal-based execution

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/RuntimeMetrics.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/ChangeMonitorUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1937
Measure the amount of work that would have been missed by a participant otherwise completed by the reminder event concept. This can be done by checking the number of reminder events that actually obtain a lease to re-trigger a flow launch. Reminder events that see another lease is in progress are not included to avoid double counting the participant actually doing the work on reminder case. 
Additionally, address a bug to filter out heartbeat events before attempting to extract the FlowActionType from DagActionStoreChangeEvents because heartbeat events have null FlowActionTypes, causing the heartbeats …

[GOBBLIN-1937] Quantify Missed Work Completed by Reminders

---

gobblin-completeness/src/main/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifier.java
gobblin-completeness/src/test/java/org/apache/gobblin/completeness/verifier/KafkaAuditCountVerifierTest.java
gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaIngestionHealthCheck.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaTopicGroupingWorkUnitPacker.java

- https://issues.apache.org/jira/browse/GOBBLIN-1933
1. Change the logic in completeness verifier to support multi reference tier and use the lowest completeness percentage as the result. In other words, we will wait until src tier catches up to all reference tiers (upto 99.9%) to mark that hour as completed.
2. Change the default topic partition number to be configurable as 10 is fair small and can cause us to allocate resources aggressively
3.  Add log for consumption rate to help debugging
Unit test
4. Subject is limited to 50 characters
5. Subject does not end with a period
6. Subject uses the …

GOBBLIN-1933]Change the logic in completeness verifier to support multi reference tier

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/GobblinTemporalConfigurationKeys.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/cluster/AbstractTemporalWorker.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/cluster/GobblinTemporalTaskRunner.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/cluster/TemporalWorker.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/cluster/WorkerConfig.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/joblauncher/GobblinTemporalJobScheduler.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/util/nesting/work/SeqBackedWorkSpan.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/util/nesting/work/SeqSliceBackedWorkSpan.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/util/nesting/work/WFAddr.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/util/nesting/work/WorkflowAddr.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/util/nesting/work/Workload.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/util/nesting/workflow/AbstractNestingExecWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/util/nesting/workflow/NestingExecWorkflow.java

- https://issues.apache.org/jira/browse/GOBBLIN-1941
"Create abstractions for developing on Temporal"
Refine Temporal abstractions, including:
* `Workload` for workflows of unbounded size through sub-workflow nesting
* `WorkerConfig`, for tunneling the `TemporalWorker`'s configuration to the workflows and activities it hosts
manual execution

[GOBBLIN-1941] Develop Temporal abstractions, including `Workload` for workflows of unbounded size through sub-workflow nesting

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/loadgen/activity/IllustrationItemActivity.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/loadgen/activity/impl/IllustrationItemActivityImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/loadgen/launcher/GenArbitraryLoadJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/loadgen/work/IllustrationItem.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/loadgen/work/SimpleGeneratedWorkload.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/loadgen/worker/ArbitraryLoadWorker.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/loadgen/workflow/impl/NestingExecOfIllustrationItemActivityWorkflowImpl.java
gobblin-utility/src/main/java/org/apache/gobblin/util/PropertiesUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1944
"Create Gobblin-Temporal load-generator to de-risk Temporal's scaling"
To de-risk Temporal as an effective platform for executing Gobblin jobs, we wish to validate that temporal workflows can scale-up to a Big Data number of activities.  To accomplish such load testing, we provide a simple load-generator for creating nesting workflows that ultimately subsume whatever desired number of activities.
manual execution already north of 1M activities/workflow …

[GOBBLIN-1944] Add gobblin-temporal load generator for a single subsuming super-workflow with a configurable number of activities nested beneath

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/State.java
gobblin-temporal/build.gradle
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/ProcessWorkUnit.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/ProcessWorkUnitImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/launcher/ProcessWorkUnitsJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/util/JobStateUtils.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/AbstractEagerFsDirBackedWorkload.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/EagerFsDirBackedWorkUnitClaimCheckWorkload.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WUProcessingSpec.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WorkUnitClaimCheck.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/assistance/Help.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/styles/FileSystemApt.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/styles/FileSystemJobStateful.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/styles/JobStateful.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/worker/WorkFulfillmentWorker.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/ProcessWorkUnitsWorkflow.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/NestingExecOfProcessWorkUnitWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ProcessWorkUnitsWorkflowImpl.java
gobblin-utility/src/main/java/org/apache/gobblin/util/HadoopUtils.java
gobblin-utility/src/main/java/org/apache/gobblin/util/JobLauncherUtils.java
gobblin-utility/src/main/java/org/apache/gobblin/util/PropertiesUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1945
"Implement Gobblin-on-Temporal WorkUnit Evaluation"
evaluate/execute Gobblin `Workunit`s atop Temporal.io.  to begin we may 'borrow' WUs created  by other platforms, such as the `MRJobLauncher`.  eventually we'll likely add the ability for Gobblin-on-Temporal to generate `WorkUnit`s of its own.
multiple manual executions

[GOBBLIN-1945] Implement Distributed Data Movement (DDM) Gobblin-on-Temporal `WorkUnit` evaluation

---

gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinBaseOrcWriter.java
gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinOrcWriterConfigs.java

- https://issues.apache.org/jira/browse/GOBBLIN-1949
Added an option to validate of ORC file to detect malformation. If enabled, will throw exception and delete malformed ORC file during commit

[Hotfix][GOBBLIN-1949] add option to detect malformed orc during commit

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/FlowSpec.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/FlowSpecTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1948
A consistent `flowExecutionId` is used during lease arbitration between hosts and that id is available to the `DagActionStoreChangeMonitor` but not used when passing `launch` events to the `Orchestrator` for recompilation and eventual execution. The unintended consequence of this is that a different `flowExecutionId` will be used across each participant when the flow is recompiled before passing to the `DagManager`. This messes up the job status of the most recent flow execution of each flow as it appears there are `N flow execution Ids`, 1 for each of the `N` hosts. Only one will be executed but the …

[GOBBLIN-1948] Use same flowExecutionId across participants

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java

- https://issues.apache.org/jira/browse/GOBBLIN-1950
This PR enables the extension of GobblinMCEPublisher in order to customize the fileList that the file metrics are calculated for. This allows for customization of the file metrics that is calculated and can be sent to different GobblinMCEs.

[GOBBLIN-1950] Allow extension of functions in GobblinMCEPublisher and customization of fileList file metrics are calculated for

---

gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinBaseOrcWriter.java
gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/InstrumentedGobblinOrcWriter.java
gobblin-modules/gobblin-orc/src/test/java/org/apache/gobblin/writer/GobblinBaseOrcWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1951
This commit modifies ORC file validation during the commit phase and deletes corrupted files to also emit a GTE. It also includes a test for ORC file validation.

[GOBBLIN-1951] Emit GTE when deleting corrupted ORC files

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagActionStoreChangeMonitorTest.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/FlowSpec.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/FlowSpecTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1946
Add basic unit testing framework for `DagActionStoreChangeMonitor.processMessage()` function which is used for processing `launch`, `kill`, and `resume` flow action events. This is a crucial piece of functionality used to launch events, so it needs to be resilient to malformed message types and handle them without interrupting the thread processing the queue. 
Tests calling process message on HEARTBEAT, INSERT, UPDATE, DELETE operation types. The main functionality we seek to test is to ensure heartbeat type messages or messages with null dag action types are handled without throwing a …

Add framework and unit tests for DagActionStoreChangeMonitor

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanDagFactoryTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1952
Gobblin-as-a-Service creates jobnames using flowgroups flownames, edges, and jobnames from the template. However, this tends to create a very long string which then causes issues in Gobblin job when creating files that use the jobname to create working directories or state stores. 
Although there has been previous code that shortens job name lengths, we want to further increase this by being more aggressive with the maximum length of the jobname to reduce the odds of exceeding 255 chars (max length of HDFS component)
The PR reduces the max job name length to 128 characters (1/2 of previous max) as well …

[GOBBLIN-1952] Make jobname shortening in GaaS more aggressive

---

gobblin-api/src/main/java/org/apache/gobblin/source/workunit/MultiWorkUnit.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaTopicGroupingWorkUnitPacker.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaTopicGroupingWorkUnitPackerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1936
Make KafkaTopicGroupingWorkUnitPacker pick up the variable numContainers so that be able to pack with desired num of container. 
Added test cases.

Make KafkaTopicGroupingWorkUnitPacker pack with desired num of container

---

gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinBaseOrcWriter.java
gobblin-modules/gobblin-orc/src/test/java/org/apache/gobblin/writer/GobblinBaseOrcWriterTest.java

The current metrics are not descriptive in what sorts of exceptions are occurring. The current try catch block is catching all exceptions, which could include errors other than malformed ORC file exceptions. 
I am adding this feature as a stop-gap for better insight while I am in parallel working on a change for removing orphan files on startup at the publisher level.
6. Body explains "what" …

[GOBBLIN-1953] Add an exception message to orc writer validation GTE

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java

- https://issues.apache.org/jira/browse/GOBBLIN-1955
Emit metric to count the number of lease owners that fail to persist their lease. If there are a large number of them then we may want to increase our default linger values to be larger as the lease may be expiring before an owner persists their lease. 
This PR also reduces the number of info logs as they're no longer as necessary. 

Emit metric to tune LeaseArbiter Linger metric 

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/JobContext.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/SafeDatasetCommit.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/JobLauncherTestHelper.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/LocalJobLauncherTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1959
Currently, the partial success semantics in Gobblin where it follows a commit on task success policy will return a successful job running status even though some tasks fail. This is because in most Gobblin jobs, there would be movement of the watermark after the tasks succeed so we want to follow that semantic to not lead to duplicate ingestion.
However, there are some Gobblin jobs (distcp) which do not follow the watermark semantic, thus a partial success should return a failed status so that the job callers can understand that not every task has succeeded, thus invoke a retry with amended amounts of …

[GOBBLIN-1959] Add semantics for failure on partial success

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowExecutionResourceHandlerWithWarmStandby.java

- https://issues.apache.org/jira/browse/GOBBLIN-1958
The current /flowexecutions implementation treats the presence of a pending action differently between RESUME and KILL: for the former it gives HTTP 409 Conflict and the latter gives HTTP 400 Bad Request.
1. fix so it is 409 in both cases
2. in all error handling, forward any message to include in the `RestLiServiceException` (it had been dropped when 400)
3. combine the impls between RESUME and KILL to ensure consistency
existing unit tests
4. Subject is limited to 50 characters
5. Subject does not end with a period
6. Subject uses the imperative mood …

[GOBBLIN-1958] Consistently handle /flowexecutions errors for KILL and RESUME actions

---

gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinBaseOrcWriter.java
gobblin-modules/gobblin-orc/src/main/java/org/apache/gobblin/writer/GobblinOrcWriterConfigs.java
gobblin-modules/gobblin-orc/src/test/java/org/apache/gobblin/writer/GobblinOrcWriterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1957
GobblinORCWriter self tune uses a number of metrics to determine how large their buffers should be for both its own internal buffer used for conversion and the native ORC writer buffer. However when there are very large record sizes (100s of kb) the buffers default max size (e.g. 1000) can still hold a very large amount of data. Observed performance would be hundreds of megabytes to even a gigabyte depending on the configured batch size maximums.
We want a configuration to impose a maximum buffer max size so that large records in the buffer do not exceed the size of a stripe, so when it is added to the …

[GOBBLIN-1957] GobblinOrcwriter improvements for large records

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/lineage/LineageEventBuilder.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/lineage/LineageInfo.java
gobblin-metrics-libs/gobblin-metrics-base/src/test/java/org/apache/gobblin/metrics/event/lineage/LineageEventTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1961
"Qualify `IcebergTable` `DatasetDescriptor`s (used by Iceberg-Distcp)"
`IcebergTable.getDatasetDescriptor` currently uses only the table name, although it should be qualified by the DB (aka. namespace), source or destination, respectively
added unit test case

[GOBBLIN-1961] Use DB-qualified table ID as `IcebergTable` dataset descriptor

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetFinder.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergRegisterStep.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1961
"Qualify IcebergTable DatasetDescriptors (used by Iceberg-Distcp)"
The same DB name and table name are currently used in common for both the source-side table and the dest-side table.  Instead, these should be allowed to be different, so facilitate separately specifying source names and dest names.  Nonetheless, continue, for the sake of backwards compatibility, to support the legacy properties that specify the current combo props (shared by both source AND destination).
enhanced existing tests
3. Subject does not …

[GOBBLIN-1961] Allow `IcebergDatasetFinder` to use separate names for source vs. destination-side DB and table

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java

Flow compilation failures currently result in an NPE:
```
java.lang.NullPointerException: null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
at com.google.common.base.Optional.of(Optional.java:105) ~[guava-21.0.jar:?]
at org.apache.gobblin.service.modules.utils.FlowCompilationValidationHelper.validateAndHandleConcurrentExecution(FlowCompilationValidationHelper.java:114) ~[gobblin-service-0.18.0-dev-483.jar:?]
at org.apache.gobblin.service.modules.orchestration.Orchestrator.orchestrate(Orchestrator.java:240) ~[gobblin-service-0.18.0-dev-483.jar:?]
... …
```

Prevent NPE in `FlowCompilationValidationHelper.validateAndHandleConcurrentExecution`

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java

[GOBBLIN-1960] Emit audit count after commit in IcebergMetadataWriter

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/BaseIcebergCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1971
For some dataset lineage schemes, metadata tracing must take into account not only the Iceberg `TableIdentifier`, but also the catalog where that table resides.  Allow therefore `IcebergCatalog`s to adjust the name of the tables they create, for metadata reporting purposes.
Updated existing test

[GOBBLIN-1971] Allow `IcebergCatalog` to specify the `DatasetDescriptor` name for the `IcebergTable`s it creates

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanDagFactoryTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1975
When migrating Gobblin jobs over to GaaS, users want to maintain their jobname that they originally use in their configurations as jobnames are used to store watermarks, which is integral to the data pipeline behavior. It is difficult to consolidate watermarks between different tables so instead use a config feature flag to maintain the jobname instead of using a GaaS generated name.
This also prevents the need of overshortening jobnames if they are generated too long as users can now just specify a shorter name instead of having GaaS potentially change current watermarks.
Reverts …

[GOBBLIN-1975] Keep job.name configuration immutable if specified on GaaS

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobSchedulerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1974
Adhoc flow executions delete the flow spec from the `FlowCatalog` after adding the spec to the scheduler for the single active scheduler. This makes sense in prior context since the single active scheduler has the information and the spec is no longer needed. However, in the multi-active case we run into a `No spec found error` here https://github.com/apache/gobblin/blob/00c60ca6492644652c66905eb384ab145e348bbf/gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java#L263. This PR updates the code to delete the spec after persisting it in the adhoc execution …

[GOBBLIN-1974] Ensure Adhoc Flows can be Executed in Multi-active Scheduler state

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/ManifestBasedDatasetFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1973
When Manifest distcp fails to set permissions for any reason, we would expect a retry of the copy to allow the datasets to reach eventual consistency. However, the current logic of checking if a file is eligible for copy is to check if the source file is newer, if so copy, and if the source file is exactly the same modification time as the destination file, also copy if the permissions are different. However, in most cases the destination will have a newer modification time once it is written and set permissions, so the source file will generally be older but we still want the permissions to match. …

[GOBBLIN-1973] Change Manifest distcp logic to compare permissions of source and dest files even when source is older

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/BaseIcebergCatalog.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1976
For some dataset lineage schemes, metadata tracing would use a catalog-specific platform name.  Therefore allow IcebergCatalogs to choose the platform name for all tables they create.
enhanced existing tests

[GOBBLIN-1976] Allow an `IcebergCatalog` to override the `DatasetDescriptor` platform name for the `IcebergTable`s it creates

---

gobblin-api/src/main/java/org/apache/gobblin/password/PasswordManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java

- https://issues.apache.org/jira/browse/GOBBLIN-1977
The `PasswordManager` silently continues on when the configured master password key path does not exist in the FS.  this makes debugging exceptionally difficult.  Instead, it should log such a warning, upon finding that situation.
existing tests, as this change concerns logging only

[GOBBLIN-1977] Log when `PasswordManager` fails to load any master password

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/kafka/HighLevelConsumer.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-1978
We encounter a `NullPointerException` when initializing the `DagActionStoreMonitor` after moving the loading of `DagActions` on startup from the `DagManager` to the `DagActionStoreMonitor`. Metrics for the `DagActionStoreMonitor` were initialized by its parent class the `HighLevelConsumer` only before starting to consume Kafka messages, however with the refactor these metrics are needed beforehand. In this PR I separate the creation of these metrics into a separate function and call it before loading dagActions.  …

[GOBBLIN-1978] Initialize dag action store monitor metrics

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/TaskStateCollectorService.java
gobblin-utility/src/main/java/org/apache/gobblin/exception/RuntimeExceptionWithoutStackTrace.java

- https://issues.apache.org/jira/browse/GOBBLIN-1979
Logging Task state collector failure at the granularity of every task is impractical, when tasks number in the 100k's.  Moreover the stacktrace from retrieval failure provides no meaningful info--even more so when faced w/ thousands of repetitive logs like (pre-change):
```
2023/12/20 22:08:17.894 +0000 WARN [ParallelRunner] [Azkaban] Task failed: Deserialize state for task_name_of_job_task_goes_here_0_1703105111101_51.tst
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at …
```

[GOBBLIN-1979] Pare down `TaskStateCollectorService` failure logging, to avoid flooding logs during widespread failure, e.g. O(1k)+

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobScheduler.java
gobblin-cluster/src/test/java/org/apache/gobblin/cluster/HelixRetriggeringJobCallableTest.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSource.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaTopicGroupingWorkUnitPacker.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/JobContext.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/SourceDecorator.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnAutoScalingManager.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnAutoScalingManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1947
When YarnAutoScalingManager detect helix task consistently fail, give an option to send WorkUnitChangeEvent to let GobblinHelixJobLauncher handle the event and split the work unit during runtime. This can help resolving consistent failing containers issue(like OOM) during runtime instead of relying on replaner to restart the whole pipeline
Updated test cases and tested in cluster
6. Body …

[GOBBLIN-1947] Send workUnitChange event when helix task consistently fail

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MultiActiveLeaseArbiter.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiterTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java

- https://issues.apache.org/jira/browse/GOBBLIN-1982
The problem statement addressed in this issue is to determine a unique ID per execution that is agreed upon by all hosts, computed before returning any information back to user (about compilation or execution).
Upon receiving the request for an `adhoc flow`, the recipient host creates a `flowExecutionId` when initializing `FlowSpec` from `config` for non-scheduled flows (see [code](https://jarvis.corp.linkedin.com/codesearch/result/?name=FlowConfigResourceLocalHandler.java&path=gobblin-elr%2Fgobblin-restli%2Fgobblin-flow-config-service%2Fgobblin-flow-config-service-server%2Fsrc%2Fmain%2Fjava%2Forg%2Fapa …

[GOBBLIN-1982] Show a consistent flowExecutionId btwn Compilation & Execution 

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/replication/SourceHadoopFsEndPoint.java
gobblin-utility/src/main/java/org/apache/gobblin/util/FileListUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-1985
`SourceHadoopFsEndPoint.getWatermark` currently misses certain changes to the contents of the dirs it covers because it doesn't use the mod time of those enclosing dirs when calculating the watermark.  despite those dirs not being among the files to copy, they must still participate in the watermark calculation because some compute engines, like spark, first write files to a temp subdir beneath the ultimate dest dir.  (since those temp subdirs are not valid paths, they'll anyway be skipped.)  once all executors have written their file, spark moves each from that temp subdir up to the enclosing ultimate …

[GOBBLIN-1985] Incorporate the mod time of enclosing dirs into the `SourceHadoopFsEndPoint.getWatermark`

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1987
Run-immediate flows are missing an event trigger timestamp and being skipped in multi-active mode orchestration step. Code https://github.com/apache/gobblin/blob/913d580fe19e7a6adc60d3294bac44e5a32d7bba/gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java#L241
`Skipping execution of spec: .... because missing trigger timestamp in job properties` …

[GOBBLIN-1987] Allow run-immediately flows to execute in multi-active scheduler mode

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopyConfiguration.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/RecursiveCopyableDataset.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/RecursiveCopyableDatasetTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1991
RecursiveCopyableDataset.getDatasetPath() is returning the source dataset's path. But the use of this method is to calculate the shard path by destination dataset handlers. This method should return the target dataset's path.
This bug will fail the jobs where source path and target paths are different and source path cannot be created on target filesystem.
added a unit test, which fails without the code change in this PR …

[GOBBLIN-1991] set (target) dataset path correctly in RecursiveCopyableDataset

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetFinder.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergRegisterStep.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergSnapshotInfo.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1994
Iceberg-distcp replication currently risks introducing inconsistency to the destination/replication-target table, because the current snapshot version of the tables may change between the planning phase (of creating WorkUnits) and the final post-copy commit to the destination table.
To inoculate against any concurrent commits, ensure correctness by committing:
1. the same source-side metadata observed while first listing the source table during the Planning Phase and
2. the same dest-side metadata observed just prior to that first listing of the source table.
This guarantees that:
1. any later-modified …

[GOBBLIN-1994] Ensure iceberg-distcp consistency by using same `TableMetadata` for both WU planning and final commit

---

gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
gobblin-runtime/src/test/java/org/apache/gobblin/service/monitoring/FlowStatusGeneratorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2000
In GaaS, it is difficult to debug scenarios where fetching flow status to check if another concurrent execution is safe to kick off. We want to add logging around this area.
Additionally clean up the code and tests

[GOBBLIN-2000] Add logging for concurrent flow status check

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergRegisterStep.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergRegisterStepTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-1994
The recent change to "ensure iceberg-distcp consistency...", https://github.com/apache/gobblin/pull/3870 , unwisely relied on the dest-side catalog to enforce matching `TableMetadata`.  Alas, the client-side `BaseMetastoreTableOperations.commit` evidently compares using `==`, rather than `.equals` (for value comparison).  Since the `TableMetadata` from WU planning will always have already been serialized and deserialized, this invariably leads to:
```
org.apache.iceberg.exceptions.CommitFailedException: Cannot commit: stale table metadata
```
Our fix is to essentially implement our own (ID-only) value …

[GOBBLIN-1994] Fix iceberg-distcp dest-side `TableMetadata` consistency check to accurately detect "stale table metadata"

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/Task.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/TaskConfigurationKeys.java

- https://issues.apache.org/jira/browse/GOBBLIN-2001
Currently in the Gobblin framework all failed tasks will emit events when they fail and include some stacktrace to provide context on the failure. This is problematic when there are Gobblin jobs with hundreds of thousands of tasks (e.g. iceberg distcp) and causes Kafka partitions to lag under the larger events. 
We want to enable a config to disable this, and potentially extend this solution to disable all task level events as they can get quite noisy and logs generally provide better context.
This PR disables emitting failed events if `gobblin.task.disable.failed.events` is set to true (defaults to …

[GOBBLIN-2001] Add configuration to disable task failed event from emitting

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/JobState.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncher.java
gobblin-utility/src/main/java/org/apache/gobblin/util/JobLauncherUtils.java
gobblin-utility/src/main/java/org/apache/gobblin/util/ParallelRunner.java

- https://issues.apache.org/jira/browse/GOBBLIN-1919
Continue reworking MR code to enable reuse; continuation of https://github.com/apache/gobblin/pull/3784
existing unit tests

[GOBBLIN-1919] Rework a few more elements of MR-related job exec for reuse in Temporal-based execution

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/GobblinTemporalConfigurationKeys.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/cluster/AbstractTemporalWorker.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/cluster/GobblinTemporalTaskRunner.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/GenerateWorkUnits.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/launcher/GenerateWorkUnitsJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/launcher/ProcessWorkUnitsJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/util/JobStateUtils.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/assistance/Help.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/worker/WorkFulfillmentWorker.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/GenerateWorkUnitsWorkflow.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/GenerateWorkUnitsWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ProcessWorkUnitsWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/joblauncher/GobblinJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/joblauncher/GobblinTemporalJobLauncher.java
gobblin-utility/src/main/java/org/apache/gobblin/util/JobLauncherUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-2007
Adds the `GenerateWorkUnits` Activity to generate `WorkUnit`s, bin pack them, and write in serialized form to the FileSystem.   The activity creates the specified `Source` and `.getWorkUnits()` on it, as directed by `JobState` config.
Hereafter it is no longer necessary to use another platform, such as the `MRJobLauncher` to generate the WUs that Temporal would execute.
Included is a demonstration-only `GenerateWorkUnitsWorkflow` that exercises solely the new activity and then exits.  A full end-to-end Temporal workflow is forthcoming in a future PR.
so-far: successful manual execution on `CopySource` …

[GOBBLIN-2007] Implement Distributed Data Movement (DDM) Gobblin-on-Temporal `WorkUnit` generation (for arbitrary `Source`)

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/PriorJobStateWUProcessingSpec.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WUProcessingSpec.java

- https://issues.apache.org/jira/browse/GOBBLIN-2012
Adds `@JsonIgnore` to the public method for Jackson serialization to work properly in Temporal

[GOBBLIN-2012] Fix bug where wuprocessingspec causes issues with jackson in temporal

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/util/InjectionNames.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceConfiguration.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitorFactory.java
gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobSchedulerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2013
creating instances of new new class created in PR #3858
updated tests

[GOBBLIN-2013] update guice initialization for 'DagProcEngine enabled' and related classes 

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/policy/NewestKSelectionPolicy.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/dataset/MultiVersionCleanableDatasetBase.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/version/finder/GlobModTimeDatasetVersionFinder.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/version/finder/AbstractDatasetVersionFinder.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/version/finder/GlobModTimeDatasetVersionFinder.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/version/finder/VersionFinder.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/policy/NewestKSelectionPolicyTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/CleanableDatasetBaseTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/integration/RetentionIntegrationTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/version/finder/AbstractDatasetVersionFinderTest.java
gobblin-data-management/src/test/resources/retentionIntegrationTest/testTimeBasedRetentionWithVersionIterator/retention.conf
gobblin-data-management/src/test/resources/retentionIntegrationTest/testTimeBasedRetentionWithVersionIterator/selection.conf
gobblin-data-management/src/test/resources/retentionIntegrationTest/testTimeBasedRetentionWithVersionIterator/setup_validate.conf

- Add a new method findDatasetVersion in DatasetVersion Interface that returns an iterator
- Implementing an iterator that returns a dataset version that matches the glob pattern passed
- Calling the iterator in the retention job (MultiVersionCleanableDatasetBase.java), made it batch based of 100.  
- Added a new config `gobblin.retention.version.should.iterate` to use iterator for finding versions, default will be false
- Version finder iterator can't be used with NewestKSelectionPolicy.  
4. Subject uses the imperative mood …

[GOBBLIN-2006] Adding an iterator for fetching dataset versions 

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/predicates/AlwaysFalse.java

- https://issues.apache.org/jira/browse/GOBBLIN-2025
For some use cases of predicates, we want an `alwaysFalse` semantic. Normally this is easy to import from Guava via `Predicate.alwaysFalse()` but due to Gobblin relying on classloading this is not feasible.
Trivial class added that can only be enabled via configuration

[GOBBLIN-2025] Add always false predicate

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2028
JobStatus (status of a dag node) is also a part of dag, so adding functionality of providing job status in DagManagementStateStore. Note that job status is still written in the store by JobStatusMonitor.
updated the existing unit tests.

[GOBBLIN-2028] make DagManagementStateStore return job status

---

gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java

- https://issues.apache.org/jira/browse/GOBBLIN-2024
Rollback partial change of GOBBLIN-2024 as we might see exception when calculating orc file metrics when there is complex union in the orc schema. So we want to catch then to prevent starvation on ingestion side.

[HOTFIX] catch exception when fail to compute the iceberg file metrics

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java

- https://issues.apache.org/jira/browse/GOBBLIN-2036
The old value of `flow.allowConcurrentExecution` is set as a string value in the flow configuration jsons, but in the code we parse it as boolean. Instead we want to parse as string then convert to boolean to make this backwards compatible with existing flow configs.

[GOBBLIN-2036] Fix type error where string config is forced into boolean type

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/DatasetCleaner.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/dataset/MultiVersionCleanableDatasetBase.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/CleanableDatasetBaseTest.java

- Currently in the cleaner job, if OOM error or any exception occurs in the cleaner job, the flow is terminated successfully. Why? 
- This is due to a race condition in Data cleaner job, where the `close()` waits for the countDownLatch to be 0, and when the cleaner job onFailure Method counts it down to 0. There is a race condition, where the close() method checks for the `throwables` which is empty, as the failure() method has not added the throwable in this list. Thus, the exception which was supposed to be thrown is never thrown. Resulting in the process to be completed successfully. 
- Due to the changes done in …

[GOBBLIN-2026] Fail the dataset cleaner flow during any Exception

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitorFactory.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitorFactory.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-2037
The `DagActionStoreChangeMonitor` cannot be started before the `Flowgraph, DagManager, and SpecCompiler` are up and running. When the monitor is initialized by Guice, it was previously also starting to load dagActions from the store immediately to compile and process. There is a race condition created where the actions can be loaded too quickly from the store and passed to the `specCompiler` before it's ready. The `SpecCompiler` hangs waiting for the `flowGraph` to load, causing startup to fail. A similar dependency exists between the `SpecStoreChangeMonitor` and `SpecCompiler` + `Scheduler`. 
The …

[GOBBLIN-2037] Start DagActionMonitor functionality after its dependencies

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/yarn/GobblinTemporalApplicationMaster.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-2032
In Gobblin cluster, there is a configuration to set the log sink in order to create a log copier service which copies logs to HDFS from Yarn cluster.
This PR makes the configuration for log dir sinks optional so that the application does not need to set up a log copying service. Additionally it makes the file name suffix configurable in case the user wants a non-stdout file.
Ran E2E, confirms it works without log dir sinks set up. …

[GOBBLIN-2032] Make log sink config optional

---

gobblin-core-base/src/main/java/org/apache/gobblin/source/extractor/extract/FlushingExtractor.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaStreamingExtractorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2033
This PR allows appending taskAttemptId + timestamp to writer output directory to make writer output directory unique for each task.
Context for this change is there is a chance that some corrupted files could be created when previous tasks were interrupted. To avoid moving orphan files from previous run, each task should have a unique writer output and corrupted files will not be picked up.
Unit test added:
KafkaStreamingExtractorTest.testWriteOutputDirUpdate
- verified if config.WRITER_OUTPUT_DIR_UPDATE_ENABLED is set to false, there is no change to taskOutput dir
- verified if …

GOBBLIN-2033 set unique writer output dir by appending taskAttemptId to writer output path

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagActionStoreChangeMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlDagActionStoreTest.java

DagActionChangeStoreMonitor will try to load all the dag actions in the mysql db on startup and submit them to the dagmanager.
Sometimes there are issues during this startup process that can cause errors, we want to handle these issues gracefully and not block the dag action change monitor from initialization, otherwise it will block any dags from being processed.
Unit tests
6. Body explains …

[GOBBLIN-2039] Handle failure scenarios multileader compilation startup

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopySource.java

- https://issues.apache.org/jira/browse/GOBBLIN-2041
Access to the property `gobblin.copy.copy.entity.class`, which is NOT mandatory in a `WorkUnit` can cause `CopySource::getCopyEntityClass` to throw NPE:
```
java.lang.NullPointerException:
at java.lang.Class.forName0(Native Method:0)
at java.lang.Class.forName(Class.java:264)
at org.apache.gobblin.data.management.copy.CopySource.getCopyEntityClass(CopySource.java:558)
at org.apache.gobblin.temporal.ddm.activity.impl.ProcessWorkUnitImpl.getOptCopyEntityClass(ProcessWorkUnitImpl.java:204)
at org.apache.gobblin.temporal.ddm.activity.impl.ProcessWorkUnitImpl.getOptCopyableFile(ProcessWorkUnitImpl.java:184) …
```

[GOBBLIN-2041] Fix NPE in `CopySource::getCopyEntityClass`

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/troubleshooter/AutomaticTroubleshooter.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/ProcessWorkUnitImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/assistance/Help.java

- https://issues.apache.org/jira/browse/GOBBLIN-2045
the `AutomaticTroubleshooter`'s only integration with gobblin-on-temporal is for "Work Processing", within `ProcessWorkUnitImpl`.  any issues arising during "Work Discovery" fall outside of that, and go unseen.  to include those, integrate the `AutomaticTroubleshooter` with `GenerateWorkUnitsImpl`
manual execution, then verified both "issues" GTEs seen by gaas plus issues summary logging
6. …

[GOBBLIN-2045] Integrate `AutomaticTroubleshooter` with gobblin-on-temporal `GenerateWorkUnitsImpl`

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/util/commit/SetPermissionCommitStep.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/ManifestBasedDatasetFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2043
Optimizes manifest distcp commit step action to only apply to new folders, and do not continuously calculate ancestor parent folder permissions if the path has already been calculated by another file which should greatly improve read efficiency.
Unit tests

[GOBBLIN-2043] Set execute bit only for new folders in manifest distcp

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/ProcessWorkUnitImpl.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-2046
there are many kinds of `WorkUnit`, beyond the `CopyEntity` produced by `CopySource`.
as it remains helpful, continue to log `CopyEntity`-specific info, but do so w/o suggesting something is missing when the WU is not a `CopyEntity`
in addition, add logging to `GobblinYarnAppLauncher::addAppMasterLocalResources` for a rough indication of where this lengthy phase of pre-launch init is spending so much time
manually executed `CopyEntity`-workload and non-`CopyEntity`-workload and verified intended logging
3. Subject …

[GOBBLIN-2046] Generalize gobblin-on-temporal `ProcessWorkUnitImpl` logging not to presume `CopyEntity`

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/publisher/CopyDataPublisher.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java

- https://issues.apache.org/jira/browse/GOBBLIN-2049
Gobblin `safeSetPathPermission` does not throw an exception when setting permissions fail on a path. We want to change this behavior especially for use cases like manifest distcp where hundreds of thousands of files are involved in a distcp job and permission settings are important to replicate correctly as they cannot be updated or verified by hand. 
This PR adds a new configuration to fail writing or publishing tasks when the job is configured to report success when permissions are not replicated properly. The default behavior remains the same as before to allow the job to succeed without this for …

[GOBBLIN-2049] Configure Gobblin Distcp Writer to fail if setPermission fails

---

gobblin-api/src/main/java/org/apache/gobblin/source/extractor/ComparableWatermark.java
gobblin-core-base/src/main/java/org/apache/gobblin/source/extractor/extract/LongWatermark.java
gobblin-core-base/src/test/java/org/apache/gobblin/writer/FineGrainedWatermarkTrackerTest.java
gobblin-core-base/src/test/java/org/apache/gobblin/writer/WatermarkTrackerTest.java
gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/watermark/StringWatermark.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/conversion/hive/watermarker/PartitionLevelWatermarkerTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/source/LoopingDatasetFinderSourceTest.java
gobblin-modules/gobblin-helix/src/test/java/org/apache/gobblin/runtime/StateStoreWatermarkStorageTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2040
This PR is to abstract comparable watermark so that it support different type of offset value.  
Unit test and test in Azkaban to make sure this is a backward compatible change

[GOBBLIN-2040] Abstract comparable watermark

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterConfigurationKeys.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSObservabilityEventProducer.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnContainerSecurityManager.java

- https://issues.apache.org/jira/browse/GOBBLIN-2050
Gobblin Yarn Application Launcher has some issues where directories used for the job can persist after the job ends. It also creates a number of temporary files which can grow out of control.
This PR creates a new instance of a file system for cleaning up as the previous filesystem instance gets closed by the Yarn application and the cache becomes problematic with mount table FS.
It also allows a user to define `gobblin.cluster.absolute.workDir` for the exact path their cluster temp files and jars are stored, and `gobblin.yarn.token.file.path` to determine where to store their yarn security token. …

[GOBBLIN-2050] Add settings to allow for full cleanup in GobblinYarnAppLauncher

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/JobContext.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/JobState.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/CommitActivityImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/ProcessWorkUnitImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java

- https://issues.apache.org/jira/browse/GOBBLIN-2054
thus far, gobblin-on-temporal has only worked for iceberg-distcp (`CopySource`), not other job types that gobblin-on-MR succeeds with.  Commit fails with:
```
java.lang.IllegalArgumentException: Missing required property writer.output.dir
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
at org.apache.gobblin.util.WriterUtils.getWriterOutputDir(WriterUtils.java:121)
at org.apache.gobblin.publisher.BaseDataPublisher.publishData(BaseDataPublisher.java:390)
...
```
that prop was already used just prior to commit, while processing the `WorkUnit`, so something is clearly off... …

[GOBBLIN-2054] Fix `CommitActivityImpl` to succeed for `TaskState`s that did not originate with `CopySource`

---

gobblin-api/src/main/java/org/apache/gobblin/source/extractor/ComparableWatermark.java
gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java

Remove the assumption that value of ComparableWatermark has to be comparable
- https://issues.apache.org/jira/browse/GOBBLIN-2040
Remove the assumption that value of ComparableWatermark has to be comparable, as we just need to make sure the watermark itself is comparable, and the value of it can be / not be comparable, since for some special class, we can use value combine with other field to do compare
local test
6. Body explains "what" and …

[GOBBLIN-2040] Remove the assumption that value of ComparableWatermark has to be comparable

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/OpenTelemetryMetrics.java

- https://issues.apache.org/jira/browse/GOBBLIN-2055
Since GaaS Opentelemetry is still in the early stages and hasn't been rolled out service-wide, it should not be configuring the opentelemetry instance as global otherwise it can run into the following errors when combined with existing servlet infrastructure that uses Opentelemetry as well:
```
Caused by: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to …
```

[GOBBLIN-2055] Only sets opentelemetry to be built locally rather than global

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/OpenTelemetryMetrics.java

- https://issues.apache.org/jira/browse/GOBBLIN-2059
Opentelemetry sends empty attributes even though no custom configurations are being specified. We want to just send the empty resource for consistency.

[GOBBLIN-2059] Send empty resource if no custom configs are specified

---

gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSObservabilityEventProducer.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/GaaSObservabilityProducerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2060
jobStatus was an ambiguous metric name for counting job successes and detecting failure, so changing the metric name to better reflect it.
Also move logs to be debug logs as they are emitted very frequently (every minute)
Unit tests

[GOBBLIN-2060] Change jobStatus opentelemetry metric to flowSucceeded to better reflect metric values

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSJobObservabilityEventProducer.java

…son builder
- https://issues.apache.org/jira/browse/GOBBLIN-2064
The GaaSObservabilityProducer uses    
```
.setJobProperties(GsonUtils.GSON_WITH_DATE_HANDLING.newBuilder().create().toJson(jobProperties))
```
but this actually uses a newer version of GSON than the one defined in Gobblin and used in some client systems that rely on an earlier version of Gson. Since this fix is simple, we want to avoid version ambiguity when possible and use the API of the version that we define in Gobblin.
```
.setJobProperties(GsonUtils.GSON_WITH_DATE_HANDLING.toJson(jobProperties))
```
Also cleanup some classnames to use the imported class rather than the fully …

[GOBBLIN-2064] Use proper GSON builder class for GaaSObservabilityProducer and cleanup fully qualified classnames in tests

---

gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/CleanableMysqlDatasetStoreDatasetTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/MysqlDatasetStateStoreTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/cli/JobStateStoreCliTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/job_catalog/TestMysqlJobCatalog.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_store/MysqlBaseSpecStoreTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_store/MysqlSpecStoreTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_store/MysqlSpecStoreWithUpdateTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/core/GobblinServiceHATest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/core/GobblinServiceRedirectTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerFlowTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlDagStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2065
It gives `java.sql.SQLNonTransientConnectionException: Too many connections` if we do not close test dbs created. At one point all the open connections will cross the limit and we get this error. In this PR, I am closing all such connections.
NA

[GOBBLIN-2065] close ITestMetastoreDatabase in all tests

---

gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/CleanableMysqlDatasetStoreDatasetTest.java
gobblin-metastore/src/test/java/org/apache/gobblin/metastore/testing/TestMetastoreDatabaseServer.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagActionStoreChangeMonitorTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/MysqlDatasetStateStoreTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/cli/JobStateStoreCliTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/job_catalog/TestMysqlJobCatalog.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_store/MysqlBaseSpecStoreTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_store/MysqlSpecStoreTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_store/MysqlSpecStoreWithUpdateTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/core/GobblinServiceHATest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/core/GobblinServiceRedirectTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerFlowTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlDagActionStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlDagStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiterTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetrieverTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2065
We continue to face the "Too many connections" error while running `gobblin-service` tests; see, e.g. GH actions workflow failures for https://github.com/apache/gobblin/pull/3944
this shows up as
```
java.io.IOException: Failure creation table TestDagStateStore
...
Caused by: java.sql.SQLNonTransientConnectionException: Too many connections
...
```
Adjusting the server variable `max_connections` (in [TestMetastoreDatabaseServer.java](https://github.com/apache/gobblin/compare/master...phet:gobblin:fix_gobblin-service_tests_too_many_connections?expand=1#diff-3a1f64166bc336495b2d153fe1f8bc0fdc9dd28450cb8de …

[GOBBLIN-2065] Increase `TestMetastoreDatabaseServer` concurrent cnxns; plus make closing `ITestMetastoreDatabase` `alwaysRun = true` and doc reason

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java

- https://issues.apache.org/jira/browse/GOBBLIN-2071
Currently, Gobblin-on-MR executions correctly forward their execution start time back to GaaS via the JobPrepareTimer.
The Temporal Gobblin job executions do not emit this event, thus the execution start time is 0 (epoch start). We need to forward this timer and submit it via Temporal.
Tested E2E on a Temporal pipeline and queried job status via GaaS API
```
{
"id": {
"flowGroup": "gaas-CLI",
"flowExecutionId": 1716593541158,
"flowName": "hxdMecLKPWrm"
},
"message": "",
"executionStatistics": {
"executionEndTime": 1716595914707,
"executionStartTime": 1716593541158
},
```
1. Subject is separated from …

[GOBBLIN-2071] Adds execution start timer to temporal

---

gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixConstants.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnEventConstants.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnAutoScalingManager.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/event/ContainerReleaseRequest.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnAutoScalingManagerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2052

[GOBBLIN-2052] release those containers which are running helix task that are stuck in any of the given state

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngine.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProc.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2077
create flow finish deadline dag action after the launch of first job, because otherwise the dag action, which is created by the first job will not be available to find flow sla and flow start time in while ingesting flow_finish_deadline_enforcement dag action in DagManagementTaskStreamImpl
trivial change, tested manually

[GOBBLIN-2077] create flow finish deadline dag action after the launch of first job

---

gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java

made TableMetadata constructor public

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtilsTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/GaaSJobObservabilityProducerTest.java

…odes rather than the other service config keys
- https://issues.apache.org/jira/browse/GOBBLIN-2075
Job properties, and subsequently source and destination nodes are not found in the GaaSJobObservabilityEvent. More digging identified that the root cause is that `DagManagerUtils.getJobSpec` contained a bug where it would create a new Properties() object with
```
Properties clonedProperties = new Properties(oldProperties);
```
However this is not accurate as the constructor https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html sets the input properties as the default, meaning that the keys would not exist when collecting the object, only …

[GOBBLIN-2075] Fix JobSpec fetching from DagManagerUtils so that properties are properly reflecting job configs

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java

- https://issues.apache.org/jira/browse/GOBBLIN-2080
create guice binding for DagManagementStateStore always because it is needed in KafkaJobStatusMonitor and many other places

[GOBBLIN-2080] add guice binding for DagManagementStateStore always

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/RecursiveCopyableDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/util/commit/CreateAndSetDirectoryPermissionCommitStep.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/ManifestBasedDatasetFinderTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/util/commit/CreateAndSetDirectoryPermissionCommitStepTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2071
Manifest distcp often creates large file directory structures when copying files from one location to another. There is a risk when concurrently publishing files from a directory structure where the folders may not exist before renaming files, described by the javadoc:
```
* Renames a src {@link Path} on fs {@link FileSystem} to a dst {@link Path}. If fs is a {@link LocalFileSystem} and
* src is a directory then {@link File#renameTo} is called directly to avoid a directory rename race condition where
* {@link org.apache.hadoop.fs.RawLocalFileSystem#rename} copies the conflicting src directory into dst …
```

[GOBBLIN-2082] Change setpermissioncommitstep to pre-create folders before commit

---

.github/workflows/build_and_test.yaml
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/conversion/hive/materializer/HiveMaterializerTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/retention/sql/SqlBasedRetentionPoc.java
gobblin-data-management/src/test/java/org/apache/gobblin/runtime/embedded/EmbeddedGobblinDistcpTest.java
gobblin-metastore/src/test/java/org/apache/gobblin/metastore/testing/TestMetastoreDatabaseFactory.java
gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/data/management/conversion/hive/validation/ValidationJob.java
gobblin-modules/gobblin-compliance/src/main/java/org/apache/gobblin/compliance/HiveProxyQueryExecutor.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobSchedulerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/FsFlowGraphMonitorTest.java
gobblin-tunnel/src/test/java/org/apache/gobblin/tunnel/TestTunnelWithArbitraryTCPTraffic.java

- https://issues.apache.org/jira/browse/GOBBLIN-2083
increase max_connection to 2000 to mysql from docker image to overcome SQLException too many connections
close some jdbc connections, result set and prepared connections as a good practice.

[GOBBLIN-2083] set max connections to 2000 in mysql started through the docker image to avoid "too many connections" error

---

gobblin-restli/server.gradle
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/LeaseAttemptStatus.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java
gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
gobblin-utility/src/main/java/org/apache/gobblin/util/PathUtils.java
gobblin-utility/src/main/java/org/apache/gobblin/util/PropertiesUtils.java

- https://issues.apache.org/jira/browse/GOBBLIN-2062
the Orchestrator + DagManager MUST remove adhoc flows from the FlowCatalog that fail compilation or violate concurrent execs. otherwise gaas will continue to return '409 Conflict' to each subsequent attempt to subsequently create an adhoc flow with the same flowGroup+flowName.  this is despite the fact that the flow (still remaining in the FlowCatalog, when it shouldn't be) already has the status of FAILED, which is a "final status".
added test cases (herein)
4. Subject uses …

[GOBBLIN-2062] Ensure the `Orchestrator` always has `DagManager` remove `FlowSpec` - even when orchestration has failed

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/worker/WorkFulfillmentWorker.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/CommitStepWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/NestingExecOfProcessWorkUnitWorkflowImpl.java

- https://issues.apache.org/jira/browse/GOBBLIN-2085
the currently hard-coded `startToCloseTimeout` values are too short.  upon gaining operational experience, these requirements have come into focus:
* `ProcessWorkUnits` must support extractors utilizing little parallelism (such as those reading from a DB) that take a very long time, even upwards of hours
* `CommitActivity` runs may have to handle O(10k) or more task state files, which may take a long time to open and read, esp. when the `FileSystem` is under heavy load
* `GenerateWorkUnits` must work with sources that may be quite vast, yet w/ limited recourse to parallelism, such as a massive source …

[GOBBLIN-2085] Increase hard-coded `startToCloseTimeout` for `ExecuteGobblinWorkflow` activities and `WorkFulfillmentWorker` exec concurrency

---

gobblin-metastore/src/main/java/org/apache/gobblin/metastore/MysqlStateStore.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagActionStoreChangeMonitorTest.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagManagementDagActionStoreChangeMonitorTest.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_executorInstance/MockedSpecExecutor.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/ChangeMonitorUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitorFactory.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlDagStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/EnforceDeadlineDagProcsTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2090
i) It changes DagManagementDagActionStoreChangeMonitor and delete triggers whenever deadline enforcement dag actions are deleted.
ii) Removed EnforceJobStartDeadlineDagAction when a job/dag is cancelled, so that the job that never started (and hence able to clear EnforceJobStartDeadlineDagAction), can clean it now.
iii) removed unused enums CANCEL and RETRY in DagActionStore
iv) also fixes several unit tests and did refactoring
v) fixed codestyle changes suggested by intelliJ whatever came across during the work
DagManagementDagActionStoreChangeMonitorTest
1. Subject is separated from body by a blank …

[GOBBLIN-2090] delete deadline triggers in all hosts

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderScheduler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagement.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/InstrumentedLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/LeaseAttemptStatus.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MultiActiveLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderSchedulerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandlerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2073
An event timestamp and reminder flag are used in conjunction with `DagActions` for lease arbitration and for reminder `dagActions`. It makes sense to create a new object `LeaseObject` with these fields and the `DagAction` object to easily transfer the information from one location to another. In particular for reminder events used to check back in on incomplete `dagAction` leases, these two fields are utilized and it's easiest to keep track of them when it's maintained within the `consensusDagAction` returned in a `LeaseAttemptStatus`
Besides the refactoring the key piece in doing the bug fix is the …

[GOBBLIN-2073] Use previous eventTime for lease arbitration of reminder dagActions

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowExecutionResourceHandlerWithWarmStandby.java

…ution doesn't exist
- https://issues.apache.org/jira/browse/GOBBLIN-2089
The current implementation doesn't check for FlowExecution existence before accepting a KILL or RESUME.
Updated the functions to call GET api first to get the FlowExecution. This GET api throws a 404 if a FlowExecution doesn't exist.
- Tested kill and resumse commands in dev fabric by adding the changed line to `GobblinServiceFlowExecutionResourceHandler` class resume and kill functions. Tested with flow executions which were present and did not exist in the `shared_gaas_job_status` table.
- Resume test screenshot:
- Kill test screenshot:
1. Subject is separated from body by a …

[GOBBLIN-2089] Fix /flowexecutions KILL and RESUME action to return HTTP 404 when flow execution doesn't exist

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcFactory.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlDagActionStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DeadlineEnforcementDagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/EnforceFlowFinishDeadlineDagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/EnforceJobStartDeadlineDagProc.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlDagActionStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/EnforceDeadlineDagProcsTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2094
deadline dag procs may have been pulled out of dagActionQueue for processing right before the corresponding dag actions are deleted by job status monitor (singnaling flow start) or reevaluate dag proc (signaling flow finish).
deadline dag procs should stop if these things happened by checking the dag action one more time.
also did some code refactoring to avoid duplicate code
added a unit test in EnforceDeadlineDagProcsTest …

[GOBBLIN-2094] verify dag action exist in deadline dag procs

---

gobblin-data-management/src/main/java/org/apache/gobblin/util/commit/CreateAndSetDirectoryPermissionCommitStep.java
gobblin-data-management/src/test/java/org/apache/gobblin/util/commit/CreateAndSetDirectoryPermissionCommitStepTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2095
When a job is run by a headless account that is not the dataset owner, the `CreateAndSetPermissionCommitStep` needs to set the file owners and group appropriately to match the original dataset owner, otherwise it will lead to a mismatch for the source data.
The reason why the commit step creates folders manually instead of fully copying them via rename is to avoid the race condition where multiple files may be publishing with the same file root at the same time, in which case `fs.mkdirs` in the scenario where the folder does not exist on destination may append an extra directory level.
1. Subject is …

[GOBBLIN-2095] Set owner and group when pre-creating directories

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiter.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiterTest.java

- [X ] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
- https://issues.apache.org/jira/browse/GOBBLIN-2096
We're seeing a `MySQLTransactionRollbackException`: Deadlock found when trying to get lock when calling `MysqlMultiActiveLeaseArbiter. attemptLeaseIfNewRow() `in the rare case when two hosts check the lease arbiter table at the same time, see there's no entry matching the current primary key and try to insert it at the exact same time (both wait for lock on the same row). Normally, there's slight discrepancy that …

[GOBBLIN-2096] Retry Transient SQL Exception for MALA 

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiter.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandlerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2097
We notice that after deploying the service all subsequent scheduler triggers after the very first one are incorrectly marked as reminders even when they are for "original" events. This is a result of re-using the same `JobDetail`, `JobDataMap` and `Properties` object between the `original` and `reminder` Jobs for the `Scheduler` (all shallow copies). The following changes create deep copies of the aforementioned objects to use for the reminders so adding a reminder flag in one will not affect the other. 
- adds new test to validate deep copy
- updates previous test to validate they referred to the same …

[GOBBLIN-2097] Use unique JobDataMaps and Properties to use for reminder events

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagManagementDagActionStoreChangeMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/FlowGraphPath.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderScheduler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompilerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderSchedulerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2099
i) Set the group of quartz trigger for retry triggers and deadline triggers. This helps in debugging and help in understanding which kind of trigger was it.
ii) Fixed the equals and hashcode method for JobExecutionPlan. Because of the this, dagToJobs map was holding duplicate dag nodes when we call `addDagNodeState` on DMSS. because of duplicates, even after calling `deleteDagNodeState`, one DagNode will still remain there and  ReevaluateDagProc would think that the dag is still running and will not clean up the dag and FlowFinishDeadline dag action.
updated tests
1. Subject is separated from body by a …

[GOBBLIN-2099] differentiate retry remidners from deadline reminders

---

gobblin-runtime/src/test/java/org/apache/gobblin/util/SchedulerUtilsTest.java
gobblin-utility/src/main/java/org/apache/gobblin/util/filesystem/FileStatusEntry.java

- https://issues.apache.org/jira/browse/GOBBLIN-2103
Added a new field changeTime which reads from ctime of filesystem. This gets correctly saved when a file is modified and can also be seen using the stat command.
- Updates `testPathAlterationObserver` test

[GOBBLIN-2103] GaaS does not update flowgraph or templates if file lengths remain the same

---

gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/test/java/org/apache/gobblin/service/FlowStatusTest.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatusRetriever.java
gobblin-runtime/src/test/java/org/apache/gobblin/service/monitoring/FlowStatusGeneratorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/FsJobStatusRetriever.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/LocalFsJobStatusRetriever.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetriever.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/JobStatusRetrieverTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2102
There's a bug that causes GaaS multileader to kick off unintended concurrent flows which happens in the order described below:
Host A checks the latest flow execution status to ensure the prior flow is not running, sees that the prior execution is still running.
Host A fails the flow pending execution as it cannot run concurrent flow, this emits a FAILED event to GaaS which is ingested by the JobStatusMonitor.
Host B checks the latest flow execution status, sees the current flow execution ID which is FAILED (considered a finished flow).
Host B kicks off the pending flow execution when it shouldn't be …

[GOBBLIN-2102]Concurrent flow status check fix

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagManagementDagActionStoreChangeMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderScheduler.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderSchedulerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2106
Handles the issue of identical KILL DagActions caused by multiple kill endpoint calls for the same FG+FN+flowExecId.
Adds `eventTime` to the key of the `dagActionReminderScheduler` to ensure unique keys for multiple instances of the same action on the same flow execution that originate more than 'epsilon' apart. `MultiActiveLeaseArbiter` uses the `eventTime` to distinguish these distinct occurrences of the same action. This is necessary to prevent insertion failures due to previous reminders.
Applicable only for KILL and RESUME actions; duplication for other actions is an error.
- updates existing …

[GOBBLIN-2016] Add eventTime to DagAction reminder key

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java

* if job compilation fails then ensure quota is released and flow compilation event sent in all cases
* fix bug where adhoc flows are not deleted in multi-active scheduler case by re-adding deletion to DagManager.addDag()
- https://issues.apache.org/jira/browse/GOBBLIN-2107
Delete adhoc `flowSpecs` from `flowCatalog` to avoid build up of adhoc flowSpecs in catalog even when job compilation fails by adding the deletion in a finally block in non-MA scheduler case. 
1. Previous PR: https://github.com/apache/gobblin/pull/3944/files causes a bug where adhoc flows are not deleted when multi-active scheduler is enabled. This PR re-adds deletion of `flowSpec` to …

[GOBBLIN-2107] Delete adhoc flowSpecs from flowCatalog bug fix

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergRegisterStep.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergRegisterStepTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2088 
- Added retry with maximum number of attempts as 3 for OH replication final catalog commit
- Added testRegisterIcebergTableWithRetryer() and testRegisterIcebergTableWithRetryerThrowsRuntimeException() 
- In testRegisterIcebergTableWithRetryer(), I have mocked IcebergTable:registerIcebergTable() to throw runtime exception for intital two calls and then do nothing for third call so that retryer will finish after third call.
- In testRegisterIcebergTableWithRetryerThrowsRuntimeException(), IcebergTable:registerIcebergTable() will always throw RuntimeException, so after retrying for defailt …

[GOBBLIN-2088] Add retry to OH replication final catalog commit

---

gobblin-compaction/src/main/java/org/apache/gobblin/compaction/action/CompactionCompleteFileOperationAction.java
gobblin-compaction/src/test/java/org/apache/gobblin/compaction/action/CompactionCompleteFileOperationActionTest.java

As part of Gobblin compaction (deduplication), compacted files are moved from staging to their final location at the end of the process. This movement is handled by the org.apache.gobblin.compaction.action.CompactionCompleteFileOperationAction#onCompactionJobComplete method, which determines the appropriate destination path and moves the compacted files accordingly.
- If the flag compaction.rename.source.dir.enabled is set to false (not in append mode) and recompaction.write.to.new.folder is set to true, a new directory is determined based on the execution count derived from the state file.
- The state file, however, is generated after the move to the …

[GOBBLIN-2105] Ensure the destination path does not exist before renaming during Gobblin compaction

---

build.gradle
gradle/scripts/buildscript.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-2112
update version for gradle-nexus-plugin and build-info-extractor-gradle to resolve errors
Could not find org.gradle.api.plugins:gradle-nexus-plugin:0.7.1
NA

[GOBBLIN-2112] update version for gradle-nexus-plugin and build-info-extractor-gradle

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagActionStoreChangeMonitorTest.java
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/DagManagementDagActionStoreChangeMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java

- https://issues.apache.org/jira/browse/GOBBLIN-2113
After changing `flowExecutionId` from a Str to a long in a previous PR, we encounter `NumberFormatException` in the `DagActionStoreChangeMonitor` when processing HB events. This ends up killing the `HighLevelConsumer` queues for the hosts that receive the HB events in their partition. 
```
{{Encountered exception while processing record so stopping queue processing. Record: LiKafka10ConsumerRecord(consumerRecord=ConsumerRecord(topic = ds_mysql_makto-db-152_prod_SHARED_GOBBLIN_DAG_ACTION_STORE_20221208211255, partition = 0, leaderEpoch = null, offset = 905733, NoTimestampType = -1, serialized key size = …
```

[GOBBLIN-2113] Process Heartbeat DagAction CDC messages with empty FlowExecutionId str

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
gobblin-data-management/src/main/java/org/apache/gobblin/util/commit/CreateDirectoryWithPermissionsCommitStep.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/ManifestBasedDatasetFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2109
This PR adds some minor fixes to ensure that permissions setting in Manifest distcp correctly resets folder permissions after adding execute bit along with tests, and ensures that the ownerAndPermission list is reset in between the writers and the commit step by using list iterator
Unit tests

[GOBBLIN-2109] Fix minor permission issues with setPermissionCommitStep in Manifest distcp

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-utility/src/main/java/org/apache/gobblin/util/retry/RetryerFactory.java
gobblin-utility/src/test/java/org/apache/gobblin/util/retry/RetryerFactoryTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2110
RetryerFactory does not give option to set retry_exception_predicate.Made it configurable

[GOBBLIN-2110]Made retry_exception_predicate configurable in RetryerFactory

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlDagActionStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/DagProcessingEngineMetrics.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineMetricsTest.java

* adds unit test to verify initialization
- https://issues.apache.org/jira/browse/GOBBLIN-2117
` No meter exists for dagActionType ENFORCE_JOB_START_DEADLINE in metricsMap {}`
Initialize metrics map for each `dagActionType` in default constructor of `DagProcessingEngineMetrics`
Adds two unit tests that use this default constructor and tries to mark every dagAction for the two metrics, dagActionsStored and dagActionsObserved (the other tests are trivial). 
5. Body wraps at …

[GOBBLIN-2117] Initialize metrics map for DagProcEngineMetrics

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2119
If the service restarts before we call conclude on the lease, the deadline dag actions may get entered into the dag action store. The launch dag task (that creates deadline dag actions) will be retried on service start. It is not ideal to launch a job twice. When the job is launched again, it tries to store the deadline dag actions again and fails due to Primary Key constraint. We should ignore this exception otherwise the job submission will keep on being retried.
3. Subject does not end with a …

[GOBBLIN-2119] ignore adding deadline dag actions if they are already present

---

gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GaaSFlowObservabilityEvent.avsc
gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSJobObservabilityEventProducer.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/NoopGaaSJobObservabilityEventProducer.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/GaaSJobObservabilityProducerTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/MockGaaSJobObservabilityEventProducer.java

- https://issues.apache.org/jira/browse/GOBBLIN-2079
`GaaSJobObservabilityEvents` currently encapsulate both jobs and flows in GaaS.
This is fine for single hop flows, but flows with multiple jobs encapsulated in them now have a mix of job level events with the majority of metadata, and flow level events which provide a better view to users when their flow fails at any given point.
Since the data in both events differs vastly with most metadata only having contextual sense in the job level event, we should separate job and flow level events to their own respective event types.
This PR creates a new type of event, called `GaaSFlowObservabilityEvent`, …

[GOBBLIN-2079] Separate GaaSJobObservabilityEvents to both flow and job level events

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_executorInstance/InMemorySpecExecutor.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanListDeserializer.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanListSerializer.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/SerializationConstants.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlDagStateStoreWithDagNodesTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2122
serialize/deserialize currentAttemptNumber and currentGenerationNumber in JEP
added tests in MysqlDagStateStoreWithDagNodesTest

[GOBBLIN-2122] serialize/deserialize currentAttemps and currentGeneration in dag node

---

gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/kafka/client/GobblinKafkaConsumerClient.java
gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSource.java
gobblin-modules/gobblin-kafka-common/src/test/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaSourceTest.java

[GOBBLIN-2118]Reduce no of network calls while fetching kafka offsets during startup

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/ManifestBasedDatasetFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2125
Although the logic was removed in https://github.com/apache/gobblin/pull/3988/files, it is still needed to ensure proper permission setting from src and dest.
The issue arises where a manifest describes a file to copy, but as the dataset is locked, the ancestor permission check will re-write the folder in destination to have the locked permissions. We only want to apply the `SetPermissionCommitStep` to newly created folders as those folders on destination may have an extra execution bit.
3. Subject does not end …

Remove setpermission step for pre-existing folders

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/JobStatusRetrieverTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2127
When a job fails, it is marked as PENDING_RETRY when its currentAttempt is less than maxAttempts.
For such status, creating GaaSObservabilityEvent was producing NPE.
The approach in this PR is to not update job status to PENDING_RETRY before calculating `updatedJobStatus = recalcJobStatus()`
and then emit GaaSObservabilityEvent only if a retry is not required.
updated the current tests
6. …

[GOBBLIN-2127] do not emit GaaSObservabilityEvent for a failed job that is going to be retried

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2127
missed doing it in https://github.com/apache/gobblin/pull/4018 
a reevaluate dag proc should accept pending_retry status if it is a retry
corrected the unit test that should have caught this

reevaluate dag proc should accept pending_retry status if it is a retry

---

gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_executorInstance/MockedSpecExecutor.java
gobblin-service/build.gradle
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java
gradle/scripts/dependencyDefinitions.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-2133
https://github.com/apache/gobblin/pull/4021/files had introduced a bug where i was calling SpecProducer::cancelJob without filling in the job future required to cancel the job
difficult to test ordering of events

[GOBBLIN-2133] provide job future before calling SpecProducer::cancelJob

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/trash/Trash.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/trash/TrashFactory.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/trash/TrashTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2141
Simulation mode in retention relies on the usage of MockTrash, which doesn't always reflect the details of moving trash to certain spaces that the actual Trash class implements, and some of the details of which folders it creates.
The mock trash class also makes it difficult to simulate behaviors on any classes that extend a part of Trash class since they would have to create a corresponding mock class, which makes the purpose of the simulate mode moot since it's not actually simulating the live behavior.
We want to have an opt-in configuration (to not break existing simulation jobs of retention) to …

[GOBBLIN-2141] Simulate directly on trash class

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MySqlDagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtilsTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2142
There is an apparent bug in DMSS::hasRunningJobs()
If in a dag with two sequential jobs, first failed, this method returns true, while it should return false because the second job just cannot run. Because of this bug, ReevaluateDagProc fails to remove dag (or mark it as failed)
added tests in DagManagerUtilTest

[GOBBLIN-2142] fix bug in determining if a dag is finished or not

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java

- https://issues.apache.org/jira/browse/GOBBLIN-2144
Whereas the `AbstractJobLauncher`, used by Gobblin-on-MR, runs the entire job end-to-end, the Gobblin-on-Temporal `GenerateWorkUnitsImpl` activity solely generates WUs w/o actually processing them.  Thus it's far too early to clean anything up in the temp/staging dirs (e.g. task-staging and task-output, used by writers and the commit step). 
Even worse, depending upon config, doing cleanup nonetheless could destabilize other job executions, when those share this same temp/staging area.  Such cross-job "action-at-a-distance" is unpredictable and especially challenging even to diagnose.
`./gradlew build` …

[GOBBLIN-2144] Prevent `GenerateWorkUnitsImpl` from inadvertently cleaning up temp/staging dirs

---

gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
gobblin-runtime/src/test/java/org/apache/gobblin/service/monitoring/FlowStatusGeneratorTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2145
method `getAllFlowStatusesForFlowExecutionsOrdered` expects flowGroup, flowName in this order, while it was being passed the parameters in opposite order.
updated tests

[GOBBLIN-2145] fix bug in getting flow status

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagStateStoreWithDagNodes.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MySqlDagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlDagStateStoreWithDagNodes.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MySqlDagManagementStateStoreTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProcTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2143
When a dag is cancelled and multiple ReevaluateDagProcs are being processed for kill dag nodes, all of them will try to delete the dag and insert the dag node state too. this "insert" and "delete" may create inconsistency in the dag state store.
To safe guard against this, let only ReevaluateDagProc update the status of a dag node; and it should only UPDATE the status, NOT try to INSERT the dag node.
updated tests
5. …

[GOBBLIN-2143] handle concurrent ReevaluateDagProc for cancelled dag nodes correctly

---

gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtilsTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2150
If a dag has multiple jobs; and a job failed, the Dag's status should be FAILED. Imagine, another job that was running in parallel passed. This passing job should not emit a FLOW_SUCCEEDED event. Right now, we decide it based on Dag's `flowEvent` field which is not persisted in state store and is also set by the **last finished job** and is also deprecated. In this PR, I am calculating the flow status based on **all the job statuses** of the dag. Individual job statuses are persisted.
updated tests
3. Subject does …

[GOBBLIN-2150] calculate flow status correctly

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/Dag.java

- https://issues.apache.org/jira/browse/GOBBLIN-2154
In https://github.com/apache/gobblin/commit/45ad13e07ebe212002b279132e1fa4d121a9294f while moving DagId from DagManager to Dag class, we changed toString method to lombok's generated method. This has in impact, and in DMSS, where it stores this id, it cannot find the old entries.
verified the change through existing test cases

[GOBBLIN-2154] bring back the old toString method for DagId

---

gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/service/modules/orchestration/AzkabanClient.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/Dag.java

- https://issues.apache.org/jira/browse/GOBBLIN-2156
add logging when azkaban client retries any command

[GOBBLIN-2156] add debug message in AzkabanClient

---

gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/yarn/YarnService.java
gobblin-utility/src/main/java/org/apache/gobblin/util/filesystem/HdfsJarUploadUtils.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnHelixUtils.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnHelixUtilsTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2135
Gobblin YARN Application Launcher lacks some functionality used in MRJobLauncher. One of the biggest gaps in feature parity is the absence of jar caching, where MRJobLauncher creates a monthly cache that is automatically cleaned up by subsequent executions performed 2 months in advance.
YARN/MR requires uploading jars to HDFS, this step can be quite slow (~15 mins for a sizeable job to get all the jars), and given that many jobs do share the same jars, it makes sense to cache them together and only provide YARN the shared path. 
We also want to ensure that SNAPSHOT jars are other files are not uploaded …

[GOBBLIN-2135] Cache Gobblin YARN application jars

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTableTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2157
The existing iceberg registration step has the following snippet:
```
if (dstMetadata != null) {
// use current destination metadata as 'base metadata' and source as 'updated metadata' while committing
this.tableOps.commit(dstMetadata, srcMetadata.replaceProperties(dstMetadata.properties())); <<<<<------- BUG
}
```
Since Iceberg's `replaceProperties` https://github.com/apache/iceberg/blob/e449d3405cfdb304c94835845bd8f34a73b4a517/core/src/main/java/org/apache/iceberg/TableMetadata.java#L583 just replaces the full set of properties, not just any existing properties, the result is that all of the …

[GOBBLIN-2157] Copy table properties in iceberg distcp

---

gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/OpenTelemetryMetrics.java

- https://issues.apache.org/jira/browse/GOBBLIN-2161
- This is a follow-up change from https://github.com/apache/gobblin/pull/4061, the change missed reading logExporter classname from the config property `metrics.reporting.opentelemetry.logexporter.className`'s value and was instead reading from config property's key. Fixed it to initialize LogExporter classname from the value in the config.

[GOBBLIN-2161] Read logExporter classname from config property

---

gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSJobObservabilityEventProducer.java

- https://issues.apache.org/jira/browse/GOBBLIN-2164
- As per the Metric Data Model (MDM) documentation, it is essential to define pre-aggregation rules for metrics to allow for effective slicing and dicing based on dimensions. When emitting metrics, if any dimension within a pre-aggregation does not have a value (i.e., it is an empty string ""), the metric will be dropped as it is treated as having no value, which prevents accurate metric reporting and analysis. 
- Added default value to ensure that all dimensions for pre-aggregated metrics are populated with either their actual values or a default placeholder value `-` if they are empty.
1. Subject is …

[GOBBLIN-2164] Add default value for OpenTelemetry attribute

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/publisher/CopyDataPublisher.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/SafeDatasetCommit.java

- https://issues.apache.org/jira/browse/GOBBLIN-2165
When Gobblin is using partial commit semantics, it is possible for files to be missing on the destination after the job is completed (in line with the semantic where any number of files may be missing, as long as one file is successfully published it can still be considered successful).
Currently, Gobblin will raise a FileNotFoundException when this file is being published if its performs a metadata sync, which prevents the job from running through its postpublish steps. We still want the postpublish steps to go through as they may contain important steps for the job to be considered at least partially …

[GOBBLIN-2165] Support partial commit semantic from CopyDataPublisher

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/yarn/YarnService.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnHelixUtils.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnHelixUtilsTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2162
When Gobblin launches a YARN app, if the cache is enabled it will load all the jars stored in the cache into the classpath.
This can be problematic as jars that persisted from older versions of jars or other executions may clobber the classpath, adding jars that are not needed or jars that interfere with the current jars.
This PR ensures that only the jars that were intended to be uploaded by the GobblinYarnAppLauncher are the only jars that are loaded into the classpath from the shared cache.
3. Subject does not …

[GOBBLIN-2162] Only load added jars in the cache

---

gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-2166
GoT doesn't send applicationTags while submitting yarn app from the launcher GobblinYarnAppLauncher. This PR adds the applicationTags to appSubmissionContext during yarn app submission.
Tested the change in a local azkaban project
The below query shows azkaban properties populated in RMAppSummaryEvent
```
select * from service.rmappsummaryevent
where appid in ('application_1729067421867_143934')
and datepartition between '2024-10-15' and '2024-10-18'
limit 1;
```
4. Subject …

[GOBBLIN-2166] Add azkaban fields in RMAppSummaryEvent for GoT jobs

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/hive/HiveDatasetFinder.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/hive/HiveDatasetFinderTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2167
Hive tables can be located in different folders in HDFS even if they belong to the same database.
This becomes tricky to manage within a single Gobblin job especially when there are different permissions and handling based on underlying files for viewFS.
This PR adds a configuration to have a regex to filter tables based on their table location:
```
hive.dataset.tableFolderAllowlistFilter=<regex>
```
where tables with paths matching this filter will be selected, otherwise ignore
Unit tests
3. Subject does not end …

[GOBBLIN-2167] Allow filtering of Hive datasets by underlying HDFS folder location

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java

- [✔️ ] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
- https://issues.apache.org/jira/browse/GOBBLIN-2169
- [✔️ ] Here are some details about my PR, including screenshots (if applicable):
While overwrite we log the snapshot id of last snapshot present before commit but in case of table with no snapshot (possible freshly created table) currentSnapshot will be null hence will give NPE if used to fetch SnapshotId
This PR fixes that with proper logging.
- [✔️ ] My PR adds the following unit tests __OR__ does not need testing …

[GOBBLIN-2169] Fix NPE while overwrite if table has no previous snapshot

---

gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigLoggedException.java
gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigsV2Resource.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/FlowUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderScheduler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngine.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/InstrumentedLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/LeaseAttemptStatus.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MultiActiveLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MySqlDagManagementStateStore.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiter.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProc.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitor.java
gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiterTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2171
Some logs from GaaS flow/DAG processing, e.g. by the `MysqlMultiActiveLeaseArbiter`, the `FlowLaunchHandler`, the `DagProcessingEngine`, etc., are challenging to skim, especially when only the first characters on the line are shown (as the remaining content of long lines flows beyond view).
Improve consistency, brevity, and the placement of the most-vital info.  Also contextualize when it's not otherwise clear where in the processing a message originates (e.g. which `MultiActiveLeaseArbiter` instance).
existing tests still pass
2. Subject is limited to …

[GOBBLIN-2171] Streamline log messages for easier debugging of GaaS multi-active DAG processing

---

gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanGobblinYarnAppLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/yarn/YarnService.java
gobblin-utility/src/main/java/org/apache/gobblin/util/AzkabanLauncherUtils.java
gobblin-utility/src/test/java/org/apache/gobblin/AzkabanLauncherUtilsTest.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/GobblinYarnAppLauncherTest.java
gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnServiceTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2172
It allows proxy jvm args to be sent to Yarn AM and Containers which are retrieved from a new property.
Added custom handling for emptyStringPlaceholder since that's the value of config getting passed when the string is actually emtpy.
Tested locally using test Azkaban project
Added relevant unit tests

Add support for sending proxy jvm args to Yarn AM and Containers

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/cluster/GobblinTemporalTaskRunner.java

- https://issues.apache.org/jira/browse/GOBBLIN-2176
Set default authenticator in Yarn containers if the property is set.
The default authenticator is set in MR world through [TaskRunner of MRJobLauncher](https://github.com/apache/gobblin/blob/e5d897edaee391d05a55e6ac8a420e3416fef6d9/gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncher.java#L833).
It gets set in Temporal AM through GobblinTemporalJobLauncher which extends GobblinJobLauncher which extends AbstractJobLauncher. AbstractJobLauncher's [constructor](https://github.com/apache/gobblin/blob/e5d897edaee391d05a55e6ac8a420e3416fef6d9/gobblin-runtime/src/main/java/org/apach …

[GOBBLIN-2176] Set default authenticator in Yarn Temporal containers

---

gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/HighLevelConsumerTest.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/kafka/HighLevelConsumer.java

- https://issues.apache.org/jira/browse/GOBBLIN-2177
For `enable.auto.commit` as `true`:
The `QueueProcessor` has an infinite while loop which gets stopped upon encountering any Exception. This effectively drops the messages being consumed post such Exception.
The implemented fix ensures that for any non-Interrupted Exception, we log the occurrence and keep trying to process further messages.
For InterruptedException, we interrupt the current thread and stop the queue processor.
The infinite while loop is also updated to stop based on shutdown flag.
For `enable.auto.commit` as `false`:
Messages are not committed if an exception occurs. In this case we …

[GOBBLIN-2177] Avoid shutting down QueueProcessor on non-InterruptedException

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetFinder.java
gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/TimingEvent.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/FsSpecConsumer.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/BaseFlowToJobSpecCompiler.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/template/StaticFlowTemplate.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WorkUnitsSizeSummary.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/CommitStepWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ProcessWorkUnitsWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/helloworld/GreetingWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/metrics/EventTimer.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/metrics/TemporalEventTimer.java

- https://issues.apache.org/jira/browse/GOBBLIN-2186
`GaaSJobObservabilityEvent`s for Gobblin-on-Temporal jobs presently have no values set for the fields `jobPlanningStartTimestamp` and `jobPlanningEndTimestamp`.  This is because, in contrast with Gobblin-on-MR, `GenerateWorkUnitsImpl` emits no `TimingEvent.LauncherTimings.WORK_UNITS_CREATION` GTE to record such values.
The historical impediment was that Temporal does not permit Activities to launch other Activities (only Workflows may do that).  `TemporalEventTimer`, however, emitted its GTE on a separate Activity for reliability.  This change reworks `TemporalEventTimer.Factory` to be useable within …

[GOBBLIN-2186] Emit GoT GTEs to time `WorkUnit` prep and to record volume of Work Discovery

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WorkUnitsSizeSummary.java
gobblin-temporal/src/test/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImplTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2187
when `workunit` is empty then while serializing wusizesummary GSON throws below exception `NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method`
this is coming due to not handling when values are zeros which generates NaN while generating wusizesummary
added `testDigestWorkUnitsSizeWithEmptyWorkUnits` …

[GOBBLIN-2187] Fix NaN issue while generating size summary

---

gobblin-api/build.gradle
gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-api/src/main/java/org/apache/gobblin/initializer/Initializer.java
gobblin-core/src/main/java/org/apache/gobblin/converter/initializer/MultiConverterInitializer.java
gobblin-core/src/main/java/org/apache/gobblin/initializer/MultiInitializer.java
gobblin-core/src/main/java/org/apache/gobblin/writer/initializer/MultiWriterInitializer.java
gobblin-core/src/test/java/org/apache/gobblin/initializer/MultiInitializerTest.java
gobblin-metastore/build.gradle
gobblin-modules/gobblin-sql/src/main/java/org/apache/gobblin/writer/initializer/JdbcWriterInitializer.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/CommitActivityImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/util/nesting/work/Workload.java

- https://issues.apache.org/jira/browse/GOBBLIN-2188
Stateful writer/converter `Initializer`s, such as `JdbcWriterInitializer`, work fine with Gobblin-on-MR, but get disrupted by GoT. While GoMR does also launch an MR application, the remainder of the `MRJobLauncher` execution is within the same process.  An `Initializer` must execute at the end of WorkDiscovery, before `WorkUnit` processing may begin, but is `.close()`d only after Job Commit completes.  Crucially, with GoMR, the same `Initializer` instance remains in memory all throughout.  With GoT, in contrast, Work Discovery and Commit execute completely independently - creating new …

[GOBBLIN-2188] Define `Initializer.AfterInitializeMemento` for GoT to tunnel state from `GenerateWorkUnits` to `CommitActivity`

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/joblauncher/GobblinJobLauncher.java
gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java

- https://issues.apache.org/jira/browse/GOBBLIN-2191
Temporal Application Master is not shutting down due to a non-daemon thread being alive. This thread is coming from the unclosed ExecutorService created in GobblinJobLauncher.
The ExecutorService is now being closed leading to a graceful shutdown of Temporal Application Master.
Also add a log statement to print Temporal Workflow Tracking URL
Verified in a test project which prints below log message in Application Master container.
`ApplicationLauncher has already stopped` gets printed when the shutdown hook gets called from [ServiceBasedAppLauncher](https://github.com/apache/gobblin/blob/d58bbc0a12689e8 …

[GOBBLIN-2191] Shutdown GobblinJobLauncher executor

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/cluster/GobblinTemporalTaskRunner.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/joblauncher/GobblinJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/joblauncher/GobblinTemporalJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/joblauncher/GobblinTemporalJobScheduler.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/client/TemporalWorkflowClientFactory.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/service/ManagedWorkflowServiceStubs.java
gobblin-temporal/src/test/java/org/apache/gobblin/temporal/joblauncher/GobblinTemporalJobLauncherTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2194
As part of https://github.com/apache/gobblin/pull/4095, a bug was introduced where the Metrics Scope object was not being closed, resulting in a non-daemon thread being alive. This resulted in AM container not getting shut down on application completion.
This PR implements the fix to close metrics scope wherever it is initialized. 
It also covers calling close on JobLauncher upon its completion, which now results in cleanly closing the resources launched by JobLauncher.
Instead of calling `executeCancellation()` directly we now call `cancelJob()` in `GobblinJobLauncher.close()` since the latter cancels …

[GOBBLIN-2194] Close temporal metrics scope on job completion

---

gradle/scripts/dependencyDefinitions.gradle

- https://issues.apache.org/jira/browse/GOBBLIN-2196
`hadoop-azure-datalake` brings in a bad dependency of `hadoop-project` https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-project/3.0.0-alpha2/hadoop-project-3.0.0-alpha2.pom
As part of this PR we upgrade `hadoop-azure-datalake` to `3.2.3` where the issue no longer exists
https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-project/3.2.3/hadoop-project-3.2.3.pom
Tested in local project …

[GOBBLIN-2196] Upgrade hadoop-azure-datalake dependency

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/yarn/AbstractDynamicScalingYarnServiceManager.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/yarn/DynamicScalingYarnService.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/yarn/YarnService.java
gobblin-temporal/src/test/java/org/apache/gobblin/temporal/dynamic/DummyScalingDirectiveSource.java
gobblin-temporal/src/test/java/org/apache/gobblin/temporal/yarn/DynamicScalingYarnServiceManagerTest.java
gobblin-temporal/src/test/java/org/apache/gobblin/temporal/yarn/DynamicScalingYarnServiceTest.java
gobblin-temporal/src/test/java/org/apache/gobblin/temporal/yarn/YarnServiceTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2189
Implemented handleContainerCompletion(...) which launches replacement container based on exit status
Handled Scaling down of containers based on negative delta
Refactored YarnService to remove use of helix related tags and names
Updated one existing test
Manually triggered DummyDynamicScalingYarnServiceManager to check if scale down is happening or not, the stripped logs from that are 
```
2025-01-21 09:09:59 PST [,,] INFO  [DynamicScalingYarnService STARTING] org.apache.gobblin.temporal.yarn.YarnService  - Requesting initial containers
2025-01-21 09:09:59 PST [,,] INFO  [DynamicScalingYarnService …
```

[GOBBLIN-2189] Implement ContainerCompletion callback in DynamicScalingYarnService

---

.github/workflows/build_and_test.yaml
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/LaunchDagTask.java

- https://issues.apache.org/jira/browse/GOBBLIN-2198
- DagProcessingEngine process dagTasks, and calls its conclude method in the end, however, in specific case(where flowSpec doesn't exist for Launch DagAction) it throws RuntimeException due to which the thread is terminated and Dag processing stops completely. Updated the code to not throw runtimeException and just log the error so that other Dag action can be processed. 
6. Body explains …

Prevent dagProcessingEngine thread termination by handling exceptions gracefully

---

.github/workflows/build_and_test.yaml
gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-core/src/main/java/org/apache/gobblin/source/DatePartitionedNestedRetriever.java
gobblin-core/src/main/java/org/apache/gobblin/source/PartitionAwareFileRetrieverUtils.java
gobblin-core/src/main/java/org/apache/gobblin/source/PartitionedFileSourceBase.java
gobblin-core/src/test/java/org/apache/gobblin/source/PartitionAwareFileRetrieverUtilsTest.java

- [✅] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
- https://issues.apache.org/jira/browse/GOBBLIN-2147 
- [✅] Here are some details about my PR, including screenshots (if applicable):
- In partitioned file source based copy even if copy.lookbackTime property was passed in config it wasn't used and files from lowest watermark (if passed, otherwise default value was used) were being processed  which can lead to too much processing of files in case granularity isn't configured properly.
- With this change user can pass …

[GOBBLIN-2147] Added lookback time fetch in partitioned filesource

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/GobblinTemporalConfigurationKeys.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/ProcessWorkUnitImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/RecommendScalingForWorkUnitsLinearHeuristicImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/worker/WorkFulfillmentWorker.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java
gobblin-temporal/src/test/java/org/apache/gobblin/temporal/ddm/activity/impl/RecommendScalingForWorkUnitsLinearHeuristicImplTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2199
- Moves activity parallelism in container at worker level only and using 1 worker per container as default.
- Set dynamic scaling as disabled by default. Added a config to enable/disable dynamic scaling (which can be changed at job/template level).
- Added configs to set container throughput and max WUs for a container, which is used for computing container count.
- This change introduces a major refactoring of the calcDerivationSetPoint method in the RecommendScalingForWorkUnitsLinearHeuristicImpl class. The changes improve the calculation of the recommended number of containers for dynamic scaling by …

[GOBBLIN-2199] Support dynamic container scaling based on target completion time & WU count

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTableTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2203
When Manifest file is a DELETE Manifest `ManifestFiles.readPaths(manifest, io)` throws exception 
`Caused by: java.lang.IllegalArgumentException: Cannot read a delete manifest with a ManifestReader: GenericManifestFile{content=DELETES, ...` to fix this issue I have changed to read Delete Manifest separately and fetch all delete file paths from them (there doesn't exists any direct iceberg API which can give this)
Added `testGetSnapshotInfosForDataFilesOnlyTable` to test each functionality for table containing only data files and updated other test to validate data & delete files both
1. Subject is …

[GOBBLIN-2203] Add Support for Delete Manifests in Iceberg Full Table Replication

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/ManifestBasedDataset.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/dataset/ManifestBasedDatasetFinderTest.java
gobblin-data-management/src/test/resources/manifestBasedDistcpTest/sampleManifestWithOnlyDirectory.json
gobblin-utility/src/main/java/org/apache/gobblin/util/filesystem/OwnerAndPermission.java
gobblin-utility/src/test/java/org/apache/gobblin/util/filesystem/OwnerAndPermissionTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2206
In Manifest Distcp we need permissions to be exactly similar to source but due to `FileAwareInputStreamDataWriter::setOwnerExecuteBitIfDirectory` extra execute bit gets set to owner permission even if owner doesn't have execute permission. The fix is to add extra permission in setPermissionStep to override this behaviour
`testSetPermissionWhenCopyingDirectoryWithOwnerExecutePermissionSetUnset` …

[GOBBLIN-2206] Revert extra exevute bit getting set in ManifestDistcp

---

gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixUtils.java
gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanJobLauncher.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagUtils.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/assistance/Help.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/metrics/EventSubmitterContext.java

- https://issues.apache.org/jira/browse/GOBBLIN-2207
Make temporal unique classifier GaaS attempt aware.
Currently temporal unique classifier is a combination of flowExecId, and jobUniqueId , since during retries , flowExecId and JobUniqueId is same, we need to account for attemptId in temporal unique classifier

[GOBBLIN-2207]Make temporal unique classifier GaaS attempt aware

---

gobblin-compaction/src/main/java/org/apache/gobblin/compaction/mapreduce/test/TestCompactionTaskUtils.java

[GOBBLIN-2212] Fix AvroCompactionTaskTest & OrcCompactionTaskTest

---

gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/launcher/ProcessWorkUnitsJobLauncher.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/EagerFsDirBackedWorkUnitClaimCheckWorkload.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/PriorJobStateWUProcessingSpec.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WUProcessingSpec.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WorkUnitClaimCheck.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java
gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ProcessWorkUnitsWorkflowImpl.java
gobblin-temporal/src/test/java/org/apache/gobblin/temporal/ddm/work/EagerFsDirBackedWorkUnitClaimCheckWorkloadTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2213

[GOBBLIN-2213] Propagate file system job properties to Work unit metadata

---

gobblin-api/src/main/java/org/apache/gobblin/qualitychecker/task/TaskLevelPolicy.java
gobblin-core/src/main/java/org/apache/gobblin/policies/size/FileSizePolicy.java
gobblin-core/src/test/java/org/apache/gobblin/policies/size/FileSizePolicyTest.java
gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
gobblin-runtime/src/main/java/org/apache/gobblin/quality/DataQualityEvaluator.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/Task.java
gobblin-runtime/src/main/java/org/apache/gobblin/runtime/fork/Fork.java

https://issues.apache.org/jira/browse/GOBBLIN-2219
- Changes handles scenarios where a task may not be doing any data copy, earlier such scenarios were reported as data quality failed
- Post analyzing DQ results we identified genuine scenarios where tasks are not doing any effective data copy, these cases are
- Hive based copy here copy entities are created for pre and post publish step, which translates to tasks doing no data copy
- Iceberg based copy, similarly has just post publish step
- Azure copy, where copy of empty directory is enabled, and no data is copied in empty directory copy
- In all such …

DQ handling for no bytes read scenarios and metrics for bytes read/written

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergOverwritePartitionsStep.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergPartitionDataset.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergOverwritePartitionsStepTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2221

[GOBBLIN-2221] Change iceberg data files from byte[] to list of base64 encoded string

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopySource.java

- https://issues.apache.org/jira/browse/GOBBLIN-2222

[GOBBLIN-2222] Remove unnecessary CopyEntity deserialisation

---

gobblin-api/src/main/java/org/apache/gobblin/compat/hadoop/TextSerializer.java
gobblin-api/src/test/java/org/apache/gobblin/compat/TextSerializerTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2223

[GOBBLIN-2223] Optimise writing of serialised Work Unit to File system

---

gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergOverwritePartitionsStep.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergPartitionCopyableFile.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergPartitionDataset.java
gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/publisher/CopyDataPublisher.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetTest.java
gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/iceberg/IcebergOverwritePartitionsStepTest.java

- https://issues.apache.org/jira/browse/GOBBLIN-2226

[GOBBLIN-2226] Construct iceberg data files during commit step

---

gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitorFactory.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/JobStatusMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitorFactory.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitor.java
gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitorFactory.java

- https://issues.apache.org/jira/browse/GOBBLIN-2227
Made the DagActionChangeMonitor, SpecStoreChangeMonitor config driven initialization 
Also changed DagActionChangeMonitor, SpecStoreChangeMonitor and JobStatusMonitor to bind using interface in place of Abstract class
NA

[GOBBLIN-2227] Make dag action and spec store monitor initialization config driven
