apache/gobblin

- gobblin-api/src/main/java/gobblin/configuration/State.java
Fixing a bunch of Findbugs warnings like:
File: State.java, Line: 158, Type: DM_BOXED_PRIMITIVE_FOR_PARSING, Priority: High, Category: CORRECTNESS
Boxing/unboxing to parse a primitive gobblin.configuration.State.getPropAsInt(String)
All unit tests pass.
> Fix FindBugs warnings in State.java

- gobblin-distribution/build.gradle
Change log4jextras to runtime as log4j internally depends on additional features provided by the library. 
BTW, gradle runtime dependency extends compile dependency. That's why it was working before.
> add log4jextras runtime dependency

- gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java
Currently FsStateStore throws an IOException if a given state store already exists while treating to create the store directory. The right behavior should be to do an no-op and return if the store directory already exists. This commit fixes it.
> Do not throw and IOException when a given state store already exists

- gobblin-distribution/build.gradle
- gobblin-scheduler/build.gradle
Repos dependent on gobblin and the gobblin stand alone scripts are failing because log4jextras is needed as a runtime dependency, but is only expressed as a runtime dependency in gobblin-distribution, which most downstream repos are not dependent on. I add the dependency to scheduler, which is where is belongs.
> Moving log4j-extras dependency to scheduler

- gobblin-metrics/src/main/java/gobblin/metrics/JobMetrics.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskExecutor.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- gobblin-utility/src/main/java/gobblin/util/ForkOperatorUtils.java
Currently, built-in task-level metrics are shared among the forked branches of each task. This is causing metric mismatch issues. This commit fixes the issues by making each forked branch of a task have its own copies of built-in task-level metrics that have the branch index in the metric name.
> Make each forked branch have its own built-in task-level metrics

- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
The method is called in AbstractJobLauncher when each new task gets created. Removed this duplicate call in Task.java.
> Removed a duplicate call to TaskStateTracker.registerNewTask()

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTaskStateTracker.java
Since Hadoop imposes a system-level limit (default to 120) on the number of counters, a Gobblin MR job may easily go beyond that limit if the job has a large number of tasks and each task has a few counters. This commit makes it optional to report task-level counters as Hadoop counters. 
> Make reporting task-level counters as Hadoop counters optional

- gobblin-utility/src/test/java/gobblin/util/SchedulerUtilsTest.java
It turns out the cause for the SchedulerUtilsTest failure is that the order of the loaded job configuration properties on Hudson is different from that one on my machine, I guess due to the way the job configuration files are ordered when they are listed. This commit fixed it by eliminating the dependency on a certain order.
> Fixed the Hudson build

- bin/statestore-checker.sh
- gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobStateToJsonConverter.java
There's a need to use JobStateToJsonConverter from time to time, and it has been nontrivial to use it. This commit simplifies it and also adds a script to run it.
> Made JobStateToJsonConverter simpler to use and added a script to use it

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/GobblinOutputFormat.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/GobblinOutputFormatTest.java
Here is the first version. I still need to do some cleanup, add some comments, and write a test. Making this pull request to see what everyone thinks of the approach.
Azkaban only lets the cancel method run for 5 ms, before doing a hard kill on the process. This isn't enough time to cleanup staging data, but should be enough time to kill the Hadoop job (at least based on historical behavior). The OutputCommitter allows the user to hook into the lifecycle of the task and the jobs, so when killJob is called by the client, the AM will call OutputCommitter.abortJob() method. I have over--ridden this method, and added logic to clean up the staging data. Since the AM is in a different process than the client (running on Azkaban), the code de-serializes the WorkUnit files written to HDFS in …
> Adding support for cleaning up staging data when Gobblin is cancelled via the Azkaban UI

- bin/gobblin-mapreduce.sh
- bin/gobblin-standalone.sh
- build.gradle
- conf/gobblin-env.sh
- conf/gobblin-mapreduce.properties
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/CliMRJobLauncher.java
I've incorporated the requirements discussed in #36. Handling of the command line parameters has been changed accordingly:
$GOBBLIN_HOME/build.gradle:
- bump avro version to 1.7.6 to conform with the version of avro-mapred
- force guava version 15.0: otherwise during the build gradle may pick up guava 17.0 and will include it in  
the /lib directory
instead of the defined version 15.0. (This may lead to issues like
IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class 
org.apache.hadoop.mapreduce.lib.input.FileInputFormat)
$GOBBLIN_HOME/conf/gobblin-env.sh:
- A script to initialize environment variables called by gobblin-standalone.sh and gobblin-mapreduce.sh
$GOBBLIN_HOME/bin/gobblin-mapreduce.sh:
- Job configuration as command line parameter
- …
> Fix Mapreduce startup (based on pull request #36)

- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobManager.java
- gobblin-scheduler/src/main/java/gobblin/scheduler/JobScheduler.java
- gobblin-scheduler/src/test/java/gobblin/scheduler/JobConfigFileMonitorTest.java
- gobblin-utility/build.gradle
- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
- gobblin-utility/src/test/java/gobblin/util/SchedulerUtilsTest.java
This commit contains the following fixes:
1. When a new job configuration file is added or an existing file is changed, the file is reloaded with properties included from .properties file in the same directory and .properties files in ancestor directories. Then the job is scheduled/rescheduled.
2. When an existing .properties file is changed, all job configuration files affected will be reloaded and rescheduled, again with properties included from the .properties file and .properties files in ancestor directories. The affected job configuration files include those in the same directory and the ones under the subdirectories (recursively). 
3. Code refactoring.
> Fixed the job configuration file monitor

- gobblin-core/src/main/java/gobblin/source/extractor/partition/Partitioner.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/Utils.java
When the low watermark is calculated, CURRENTDAY or CURRENTHOUR is determined by using the default timezone (America/Los_Angeles). I assume, that the correct behavior would be to check for the source.timezone and if it is not set, fall back to the default one.
> Calculation of low watermark should honor source.timezone

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
Necessary for Gobblin to run with Azkaban hadoopJava jobtype: http://azkaban.github.io/azkaban/docs/2.5/#hadoopjava-type
> Adding compatibility for hadoopJava jobtype

- gobblin-core/src/main/java/gobblin/source/workunit/MultiWorkUnitWeightedQueue.java
FindBugs Warnings:
1:
gobblin.source.workunit.MultiWorkUnitWeightedQueue$WeightedMultiWorkUnit defines compareTo(MultiWorkUnitWeightedQueue$WeightedMultiWorkUnit) and uses Object.equals()
This class defines a compareTo(...) method but inherits its equals() method from java.lang.Object. Generally, the value of compareTo should return zero if and only if equals returns true. If this is violated, weird and unpredictable failures will occur in classes such as PriorityQueue. In Java 5 the PriorityQueue.remove method uses the compareTo method, while in Java 6 it uses the equals method.
From the JavaDoc for the compareTo method in the Comparable interface:
It is strongly recommended, but not strictly required that (x.compareTo(y)==0) == (x.equals(y)). Generally speaking, any class that …
> Fixing FindBugs warnings

- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
Gobblin currently serializes both the job state and task states of each job run to the state store. Since the job state of a job run contains the task states, there's really no need to serialize the task states.
> Deprecated serializing task states to the state store

- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
In pull request #65, a new Constructor is added to SourceState that takes a previous SourceState and calls SourceState.getPreviousWorkUnitStates() to populate the SourceState.previousTaskStates. However, it turns out previousTaskStates is always empty and therefore the empty list gets passed into the current SourceState. This is the root cause for the issue with gobblin-stand-alone.
> Fixed a bug that caused an empty list of previous WorkUnitStates to pass into SourceState

- build.gradle
Disabling FindBugs plugin because FindBugs 2.x is not compatible with Java8
> Disabling FindBugs plugin

- build.gradle
- gobblin-runtime/build.gradle
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- gobblin-test/resource/job-conf/GobblinTest1.pull
- gobblin-test/resource/job-conf/GobblinTest2.pull
- gobblin-test/resource/job-conf/GobblinTest3.pull
- gobblin-test/resource/mr-job-conf/GobblinMRTest.pull
Adding support for writing byteman tests in testng, and running the tests during ./gradlew clean build. The first byteman test is to ensure that even if MRJobLauncher.collectOuput() throws an exception, that the staging data still is cleaned-up.
I also had a do a little refactoring of the JobLauncherTestBase class and made it a helper class instead. The reason is that any testng class that uses byteman must extend the byteman class BMNGRunner
> Adding byteman test support and example

- bin/gobblin-mapreduce.sh
- gobblin-example/src/main/resources/simplejson.pull
- gobblin-example/src/main/resources/wikipedia.pull
Also deleted configuration property `writer.fs.uri` from the example job config files as it is already defined in `conf/gobblin-standalone.properties` and `conf/gobblin-mapreduce.properties` and the value set there should be taken.
> Fixed gobblin-mapreduce.sh to use the new version of metrics-core

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/qualitychecker/row/RowLevelErrFileWriter.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/InputStreamCSVReader.java
- gobblin-example/src/main/java/gobblin/example/simplejson/SimpleJsonExtractor.java
- gobblin-example/src/main/java/gobblin/example/wikipedia/WikipediaExtractor.java
- gobblin-metastore/src/test/java/gobblin/metastore/DatabaseJobHistoryStoreTest.java
- gobblin-metrics/src/main/java/gobblin/metrics/OutputStreamReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaReporter.java
- gobblin-rest-service/gobblin-rest-server/src/test/java/gobblin/rest/JobExecutionInfoServerTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobMetrics.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobManager.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
- gobblin-salesforce/src/main/java/gobblin/salesforce/SalesforceExtractor.java
- gobblin-utility/src/main/java/gobblin/util/HeapDumpForTaskUtils.java
- gobblin-utility/src/test/java/gobblin/util/SchedulerUtilsTest.java
> Use Guava's Charsets.UTF_8 to replace the string representation of the encoding charset

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
- Implemented Kafka multiworkunit using bin packing algorithms. The goal is to evenly assign all workunits (each corresponding to a kafka partition) to the multiWorkUnits, while preferring to assign partitions of the same topic to the same multiWorkUnit (to avoid generating many small files).
*Note that currently it is not possible to avoid generating small files. Even if we assign multiple partitions of the same topic to the same multiWorkUnit, it will still create one file for each partition, rather than one file for the whole topic. It is currently neither possible to let multiple tasks share a writer (since tasks may run in parallel) nor possible to let each workUnit process multiple partitions (since each workUnit can only have one highwatermark). However, in the future if we change …
> Multiworkunit (bin packing) for kafka source

- gobblin-core/src/main/java/gobblin/converter/filter/AvroProjectionConverter.java
- gobblin-core/src/main/java/gobblin/converter/filter/AvroSchemaFieldRemover.java
- gobblin-core/src/main/java/gobblin/policies/avro/AvroHeaderGuidPolicy.java
- gobblin-core/src/main/java/gobblin/policies/avro/AvroHeaderTimestampPolicy.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
- Implemented AvroProjectionConverter for removing certain fields from an Avro schema or an Avro record.
- Added two row-level policies for Kafka avro records: one for timestamp and one for GUID.
> Kafka converter and row level policies

- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/MysqlExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/SqlServerExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/Utils.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/SimpleWatermark.java
When ```source.querybased.watermark.type=simple``` and ```extract.delta.fields``` contains a comma separated list of fields (e.g: id, type), one of the initial MySQL query looks like this during the job initialization:
```SELECT max(COALESCE(id,type)) FROM test  where  (id,type >= 477 and id,type <= 544);```
The query syntax seems to be invalid which leads to the following error:
```java.sql.SQLException: Operand should contain 1 column(s)```
After checking the generated queries of other watermark types, I suspect that here the fields in the where clause should be coalesced too (e.g: COALESCE(id,type) >=477...etc)
If this is the case (and the where clause is not intended to be a row subquery for instance) then the patch would address this issue.
>  Fix query for multiple delta fields in case of simple watermark (cont. of #58) 

- gobblin-metrics/src/main/java/gobblin/metrics/graphite/GraphiteReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/influxdb/InfluxDBReporter.java
- gobblin-metrics/src/test/java/gobblin/metrics/influxdb/InfluxDBReporterTest.java
As suggested in http://influxdb.com/docs/v0.8/advanced_topics/schema_design.html, the best way to structure things is to have many series and a single column named value or something consistent across all series. This is the way InfluxDB handles metrics reported through the Graphite protocol. This commit changed the way metrics are reported in the InfluxDBReporter to use the suggest schema model.
> Report each metric as an individual series in InfluxDBReporter

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
Turned out to be a really small change, but just wanted to get this in since it might be useful to anyone else writing different KafkaExtractors.
> Parameterize KafkaSource to make it polymorphic with regards to S, D

- gobblin-compaction/src/main/java/gobblin/compaction/AvroExternalTable.java
- gobblin-compaction/src/main/java/gobblin/compaction/HdfsIO.java
- gobblin-compaction/src/main/java/gobblin/compaction/HiveTable.java
- gobblin-compaction/src/main/java/gobblin/compaction/SerialCompactor.java
- gobblin-compaction/src/main/java/gobblin/hive/util/HiveJdbcConnector.java
This patch addresses the following issues:
1.
Fix conf files loading:
The Configuration object is populated from the Hadoop conf xmls defined in the ```hadoop.configfile.*``` properties. However, ```HdfsIO#addHadoopConfigPropertiesToConf``` calls
```Configuration#addResource(String)```. This method only examines the classpath for the given file name. Thus if the file is not on the classpath, the Configuration object will remain empty
2.
Ensure the correct order of the HDFS_URI resolution:
If ```fs.defaultFS``` is set to the default value before the conf files are loaded, then it won't get overridden by either the value in ```core-site.xml``` or in ```hdfs.uri```. The resolved ```hdfs.uri``` should not only be set to the Configuration object, but to the ```CompactionRunner.properties```, …
> Fix Hadoop conf files loading/processing in the Compaction tool

- bin/gobblin-standalone.sh
I'm having a bug when try to run gobblin-standalone.sh without any parameters.
```
./bin/gobblin-standalone.sh: line 56: [: ==: unary operator expected
```
> Fix bug in gobblin-standalone.sh

- build.gradle
- gobblin-core/build.gradle
- gobblin-example/build.gradle
- gobblin-runtime/build.gradle
Otherwise will run into problems like "Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected" with Hadoop 2.
> Use avro-mapred:hadoop2 for Hadoop 2

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/test/java/gobblin/writer/AvroHdfsDataWriterTest.java
- gobblin-core/src/test/java/gobblin/writer/AvroHdfsTimePartitionedWriterTest.java
- gobblin-core/src/test/java/gobblin/writer/TestConstants.java
- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
When first looking at `writer.file.name`, one would assume it allows you to control the name of the file that gets written for a specific `WorkUnit`. However, Gobblin actually takes the value specified by `writer.file.name` and sets the file name to `value.writerId.avro`. This PR changes the usage of `writer.file.name` to give the user full control of what the output file name will be.
> Changing semantics of writer.file.name

- gobblin-core/src/main/java/gobblin/writer/AvroDataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/test/java/gobblin/writer/AvroHdfsDataWriterTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskExecutor.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- gobblin-test/resource/gobblin.mr-test.properties
- gobblin-test/resource/gobblin.test.properties
- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
A recent change on writer file naming allows user to fully control the writer file name including its extension through the configuration property `writer.file.name`. This property used to be used as the prefix for writer file names that will also include the task IDs, which guarantees that each task writes to a different file. However, the test job configurations explicitly set `writer.file.name=gobblin-test`, which means every tasks of a job will write to the same file. This issue shows up in `LocalJobLauncherTest` and `MRJobLauncherTest` in the form of `WARN` messages that complained that a writer of a task is trying to write to an existing file named `gobblin-test`. This commit fixed the tests by removing `writer.file.name` from the test job configurations.
Signed-off-by: Yinan Li …
> Fixed unit tests around JobLauncher classes after recent changes on writer file naming

- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
The unit test has been failing on Hudson because an expected exception has not been injected properly through Byteman.
> Temporarily disabled unit test MRJobLauncherTest.testJobCleanupOnError

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/GobblinOutputCommitter.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
Recently, as part of pul request #120, the method `commitJob(JobContext jobContext)` in `OutputCommitter` was overriden in  `GobblinOutputCommitter`, which called `cleanUpWorkingDirectory` 
to delete the working directory of the MR job upon completion and committing of the MR job. However, there are two versions of the method `commitJob(JobContext jobContext)`, one using `org.apache.hadoop.mapred.JobContext`, and the other using `org.apache.hadoop.mapreduce.JobContext`. The one that was overriden is the latter, and this is the one called in Hadoop 2. The issue is that the Gobblin job needs to read the task states stored under the working directory after the Hadoop job finishes, at which point the working directory has already been deleted if run on Hadoop 2. The issue didn't show up in …
> Fixed a bug that caused the Hudson build failures

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
Gobblin now preserves the owner, group, permissions and replication factor for files. The state object now supports the following configuration keys which may be used to capture these attributes and pass them on to the output file.
- HDFS_FILE_OWNER
- HDFS_FILE_GROUP
- HDFS_FILE_REPLICATION_FACTOR
- HDFS_FILE_PERMISSIONS
> Support for having file attributes in the State object

- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-api/src/main/java/gobblin/source/extractor/Watermark.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
- gobblin-api/src/test/java/gobblin/source/extractor/TestWatermark.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaPartition.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaUtils.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaWrapper.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/MultiLongWatermark.java
- gobblin-utility/src/main/java/gobblin/util/KafkaUtils.java
- Refactored `KafkaSource` and `KafkaExtractor` for the complex watermark:
Now each WorkUnit in a MultiWorkUnit returned by `KafkaSource.getWorkUnits()` is
responsible for pulling multiple Kafka partitions of the same topic, so that
these partitions can share output files rather than creating its own output files.
To this end, a method `KafkaSource.squeezeMultiWorkUnits()` is added to combine all WorkUnits in a MultiWorkUnit into a single WorkUnit.
`KafkaExtractor.readRecord()` is rewritten to pull from multiple partitions.
- Small modification to complex watermark:
- Changed the implementation of `WorkUnit.getLowWatermark` and
`WorkUnit.getExpectedHighWatermark`. The original implementation doesn't work and
throws "Not a JsonObject" exceptions. 
- Changed return type of …
> Refactor Kafka adapter for complex watermark

- gobblin-metastore/src/main/java/gobblin/metastore/DatabaseJobHistoryStore.java
- gobblin-metastore/src/main/resources/gobblin_job_history_store.sql
- gobblin-metastore/src/test/resources/gobblin_job_history_store.sql
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
I was testing the job execution history store and I found this bug. Basically if start or end time is not set in `JobState` or `TaskState`, the default zero will be used when constructing a `JobExecutionInfo` or `TaskExecutionInfo`. However, when `DataaseJobHistoryStore.put(JobExecutionInfo)` is called, a zero start/end time maps to an invalid TIMESTAMP and will be rejected by the database.
@ydailinkedin can you help review this?
> Fixed a bug with the generation of JobExecutionInfo regarding start and end dates

- gobblin-api/src/main/java/gobblin/source/extractor/WatermarkSerializerHelper.java
- gobblin-api/src/test/java/gobblin/source/extractor/WatermarkTest.java
Generifying convertJsonToWatermark method in WatermarkSerializerHelper class to return objects typed with the parameter provided
> Generifying convertJsonToWatermark method in WatermarkSerializerHelper class

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroSchemaRegistry.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/SchemaNotFoundException.java
Fixed the following bugs:
- `KafkaExtractor.shouldLogError()`, original logic was wrong. Also, originally it didn't increment the error count, which it should do.
- `KafkaExtractor.readRecordImpl()`: the `if (currentPartitionFinished())` block should be inside `while`. Otherwise, if `allPartitionsFinished()=true`, `currentPartitionFinished()` will fail because there's no current partition.
- `KafkaExtractor.readRecordImpl()`: LOG should print out stack trace.
- `KafkaExtractor.moveToNextPartition()`: added a `if` block around `switchMetricContextToCurrentPartition`, since if all partitions are finished, then there's no current partition.
- `KafkaAvroSchemaRegistry.getSchemaByID()`: throw `SchemaNotFoundException` instead of `RuntimeException`.
> Kafka Adapter Bug Fix

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-core/src/main/java/gobblin/metrics/GobblinMetrics.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-metrics/build.gradle
- gobblin-metrics/src/main/java/gobblin/metrics/SerializedMetricReportReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaAvroReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaAvroSchemaRegistry.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/SchemaNotFoundException.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
Summary of changes:
* Added getProperties method to State.
* File metrics reporting can add a suffix to the filename. This is useful in MR jobs where, before, all mappers would attempt to write to the same file.
* Added schema registry functionality to Kafka metrics reporting. Since this needed KafkaAvroSchemaRegistry, refactored this class from gobblin-core to gobblin-metrics.
> Various fixes to metrics emitted to Kafka in MR mode.

- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/TimePartitionedDataPublisher.java
Changed `if (this.fss.get(branchId).exists(writerOutputDir))` from line 135 to line 111. Originally `addWriterOutputToExistingDir` (line 124) may throw FileNotFoundException if the workunit produced no data.
> Change the place that checks whether writer output dir exists

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
This pull request has the following changes:
1. `JobMetrics` is now wrapped in an `Optional`, just like in `JobContext`.
2. The setup happens and `JobMetrics.startMetricReporting` is called in the `setup` method.
3. `HobMetrics.stopMetricReporting` is called in the `cleanup` method.
> Refactored the code around JobMetrics in MRJobLauncher

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
`countersToMetrics` throws a NPE if `job.getCounters()` returns `null`. This PR fixes the NPE.
> Fixing NPE in countersToMetrics

- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
This pull request is motivated by a case from the Kafka adapter that doesn't want to have job state persisted if the job failed (so to be consistent with the Camus behavior). This pull request has the following changes (UPDATED):
1. `AbstractJobLauncher` will no longer persist job state of a job if its output data has not been committed successfully.
2. Added a check in `MRJobLauncher` on the number of `TaskState`s collected from the mapper output. If this number is less than the expected number (the number of tasks launched), the job state is set to `FAILED`.
3. Code refactoring.
> Do not persist state of a job if its output data has not been committed

- bin/gobblin-standalone.sh
- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroSource.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
- Added an option to specify the log dir in gobblin-standalone.sh, which is needed for the Kafka adapter test harness.
- In KafkaAvroExtractor, if the topic schema of the workunit is not found, give it a default schema. Because currently even if a workunit extracts 0 record, a data writer is still created, and we need an Avro schema in order to create an Avro data writer.
- In `AvroUtils.getFieldSchemaHelper`, added a `if` block to avoid NPE.
> Fix bug in AvroUtils, add default schema to KafkaAvroExtractor, add logdir option to gobblin-standalone.sh

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-azkaban/build.gradle
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanIntegrationTestLauncher.java
- gobblin-test-harness/src/main/java/gobblin/test/setup/config/TestHarnessLauncher.java
Added a class to enable running the test harness on Azkaban. The class reads a properties file hardcoded to testharness.gobblin.azkaban.properties in the working directory. This file may be used to run different configurations of tests using the Test Harness.
> Support for running test harness on Azkaban

- build.gradle
- gobblin-core/build.gradle
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/jdbc/JdbcExtractorTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/jdbc/MockJdbcColumn.java
1. Replaced conversion logic from resultSet to JsonObject
Previously -- ResultSet -> List -> Map -> Json - > gson -> JsonObject
Now -- ResultSet -> JsonObject 
2. Added unit tests
3. Verified in standalone mode for sample MySql table running locally
> Remove multi-level data conversion in JdbcExtractor

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
Before: if a partition is skipped (e.g., unable to get offsets from Kafka or other reasons), no workunit will be created. But this means the previous pulled offset will be lost.
Now: create an empty workunit, so that the previous offset can be persisted in the state store and is available for the next run.
> Create empty workunit when skipping a Kafka partition

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
- (Improvement) Before: the compactor checks whether the outputdir exists. If exists, it checks the property `compaction.force.reprocess`. If true, it will reprocess inputdir. If false, will skip inputdir.
This is problematic if inputdir and outputdir are the same. Then the fact that outputdir exists doesn't indicate whether it has been compacted or not.
Now: after compaction is done, a file named `_COMPACTION_COMPLETE` will be created in outputdir. Property `compaction.force.reprocess` is no longer used. Now if outputdir exists and has `_COMPACTION_COMPLETE`, will skip inputdir. Otherwise, will process inputdir.
- (Bug) Before: the outputdir is deleted immediately when it decides to process inputdir.
Again, this doesn't work if inputdir and outputdir are the same. Now: delete outputdir …
> Improvement and bug fix for MR-based compaction

- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobLauncherFactory.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/CliMRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobStateStoreTest.java
- gobblin-utility/src/main/java/gobblin/util/JobConfigurationUtils.java
1. Refactored the code on how system and job config properties are handled and passed around. With the changes, `AbstractJobLauncher` nows takes only a single `Properties` object that includes both system and job config properties. 
2. Added a `JobConfigurationUtils` and used it.
3. Added `WriterUtils.setFileAttributesFromState(properties, fs, outputFile);` back to `AvroHdfsDataWriter` that was deleted by accident in #123.
> Refactored the code on how sys and job config properties are handled

- gobblin-utility/src/main/java/gobblin/util/DatasetFilterUtils.java
Before: is whitelist is non-empty, a topic is selected if it matches the whitelist, regardless of blacklist.
Now: topics that match blacklist will be filtered, even if they match whitelist.
This makes it easier to select a set of topics.
> change blacklist and whitelist logic

- gobblin-core/src/main/java/gobblin/converter/avro/AvroFieldRetrieverConverter.java
- gobblin-core/src/main/java/gobblin/converter/filter/AvroFilterConverter.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWriter.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
Before: `AvroHdfsTimePartitionedWriter` requires a partition field name (e.g., `header.time`), and the Avro schema must contain this field.
Now: if field name is not provided, or if Avro schema doesn't have this field, use current system time. This is consistent with Camus. There are some tracking topics whose schemas don't have a timestamp field.
> Use current system time if record timestamp is not present

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/test/java/gobblin/password/PasswordManagerTest.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
This PR fixes the specification of file level attributes in AvroHdfsDataWriter. One can now specify the codec type, permissions, block size, replication factor, etc. of the avro files.
> Fixing specification of file level attributes in AvroHdfsDataWriter

- gobblin-runtime/src/main/java/gobblin/runtime/TaskExecutor.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalTaskStateTracker2.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTaskStateTracker.java
- gobblin-runtime/src/test/resources/log4j.xml
This bug is affecting stand-alone jobs using `LocalJobLauncher` that may hang if any of its tasks fails to `getExtractor`. In this case, the `finally` part of the `Task.run` method will be executed, and `this.taskStateTracker.onTaskCompletion(this)` is called. In the implementation class `LocalTaskStateTracker2`, `this.taskExecutor.retry(task)` is called, which will throw an exception on `task.getTaskState().getPropAsInt(ConfigurationKeys.FORK_BRANCHES_KEY)` since the key `FORK_BRANCHES_KEY` is not set because the task failed before the number of branches is known and that key is set. This runtime exception is thrown in the `finally` clause and is not caught, causing the task to hang.
> Fixed a bug that may cause a job to hang if its tasks fail to getExtractor

- gobblin-api/src/main/java/gobblin/publisher/DataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/TimePartitionedDataPublisher.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
- gobblin-utility/src/test/java/gobblin/util/ParallelRunnerTest.java
Parallelize the following: (1) moving file from task output dir to final output dir; (2) cleaning task output dir and task staging dir.
1. Renamed `ParallelStateSerDeRunner` to `ParallelRunner`, and add two methods: `deletePath()` and `renamePath()`.
2. Moved `ParallelRunner` from `gobblin-runtime` to `gobblin-utility`, since `gobblin.util.JobLauncherUtils` depends on it, but `gobblin-utility` cannot depend on `gobblin-runtime`.
3. `ParallelRunnerTest` has to stay in `gobblin-runtime`, since it depends on `gobblin.runtime.TaskState`.
> Add more parallelization during job finialization

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyMapper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
1. Added code to add dependency jars to distributed cache.
2. In Mapper class, created method `populateRecord` to replace `AvroUtils.convertRecordSchema`, which is more efficient, since `AvroUtils.convertRecordSchema` needs to serialize the record to byte array and then deserialize it.
3. For Avro key schema, created method `removeUncomparableFields` to replace `getAllFieldsExceptMap`, since we not only need to remove MAP fields, but also need to remove ARRAY and ENUM fields, as well as UNIONS that contain one of those types. Also, `getAllFieldsExceptMap` was not recursive, which is now fixed.
The reason to remove those fields in Avro key schema is that a schema that contains these fields cannot be used as the dedup key.
> several fixes and optimizations for compaction

- build.gradle
- gobblin-core/build.gradle
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopFileInputExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopFileInputSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopTextInputSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/OldApiHadoopFileInputExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/OldApiHadoopFileInputSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/OldApiHadoopTextInputSource.java
- gobblin-core/src/test/java/gobblin/source/extractor/hadoop/HadoopFileInputSourceTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/hadoop/OldApiHadoopFileInputSourceTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/test/java/gobblin/util/ParallelRunnerTest.java
1. `HadoopFileInputSource` and `HadoopFileInputExtractor` for new Hadoop APIs. Also added a `HadoopTextInputSource` mostly for example and testing.
2. `OldApiHadoopFileInputSource` and `OldApiHadoopFileInputExtractor` for old Hadoop APIs. Also added a `OldApiHadoopTextInputSource` mostly for example and testing.
3. Fixed a concurrency bug in `ParallelRunnerTest`.
> Added HadoopFileInputSource and HadoopFileInputExtractor

- gobblin-runtime/src/main/java/gobblin/runtime/TaskExecutor.java
Task retry executor core thread pool size can be zero.
> Fixed some preconditions check in TaskExecutor

- gobblin-core/src/main/java/gobblin/source/extractor/DummyExtractor.java
Adding a `DummyExtractor` which always returns 0 records. The use is for IDPC where we are trying to implement on exponential backoff for the retrying of `WorkUnit`s. There will be some executions where we want a `WorkUnit` to be serialized to the state-store, but we don't want the `WorkUnit` to actually do anything, in which case the `DummyExtractor` becomes useful.
> Adding a DummyExtractor

- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
`WorkUnit.getLowWatermark()` assumes that the key `watermark.interval.value` is set, which seems only happening in the Kafka adapter. If this key is not set, `getLowWatermark` will throw an NPE if it is called, which is called in `WorkUnitState.backoffActualHighWatermark`.
> Fixed a potential NPE in WorkUnit.getLowWatermark()

- gobblin-api/src/main/java/gobblin/configuration/ImmutableWorkUnitState.java
- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-api/src/main/java/gobblin/source/workunit/ImmutableExtract.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/AbstractSource.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/AbstractSourceTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
Currently only the previous `WorkUnitState`s are available in the current job run through `SourceState.getPreviousWorkUnitStates`. The list of previous `WorkUnitStates` are from the previous `SourceState` (`JobState` more precisely). The previous `SourceState` itself, however, is not available for the `Source` to use. This PR fixed this so the previous `SourceState` is also available through `SourceState.getPreviousSourceState`.
> Made the previous SourceState available in the current run

- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
Hey @liyinan926 I noticed that the `getExtract()` method in `WorkUnitState` adds all the props for the current `WorkUnitState` to its `Extract` before returning it. Is this behavior necessary / expected?
It's causing some issues on the IDPC side because now each `Extract` is no longer unique. Properties such as `qualitychecker.rows.written` are showing up in each `Extract` which is a little weird. This only became an issue recently because the `equals()` method of `Extract` has recently been changed so that is does a comparison for all the `Extract`s props.
> Fixing bug in WorkUnitState.getExtract()

- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-api/src/main/java/gobblin/source/workunit/Extract.java
- gobblin-api/src/main/java/gobblin/source/workunit/ImmutableExtract.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
Currently, `addAll` is called to add all properties from one `State` object to another. This will cause a `UnsupportedOperationException` if the source `State` object is immutable because the `addAll` of the immutable `State` class will be called. Changed all such occurrences to `super.addAll`.
> Fixed the way addAll(State) is used in some State classes

- bin/gobblin-mapreduce.sh
- gobblin-example/src/main/java/gobblin/example/wikipedia/WikipediaExtractor.java
1. Fixed version numbers of some dependent jars in `bin/gobblin-mapreduce.sh`.
2. Added support for using proxy in `WikipediaExtractor`.
> Fixed gobblin-mapreduce.sh and allowed use of proxy in WikipediaExtractor

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/main/java/gobblin/source/workunit/Extract.java
- gobblin-api/src/main/java/gobblin/source/workunit/ExtractFactory.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
- gobblin-api/src/test/java/gobblin/source/workunit/ExtractFactoryTest.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/AbstractSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/AbstractSourceTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
Summary:
- Deprecated all constructors of `WorkUnit`, and added some factory methods, which do not add job states to workunits. 
The reason to use factory methods is to avoid having too many constructors for `WorkUnit`, some deprecated and some not deprecated.
- Deprecated the constructor of `Extract` that takes `SourceState`, added a new constructor without `SourceState`.
- In `MRJobLauncher.prepareHadoopJob()`, serialize `jobState` into a file. Then in `TaskRunner.setup()`, read `jobState` from the file and add it to each `workUnit`.
- In `LocalJobLauncher.runWorkUnits()`, add `jobState` to each `workUnit`.
- In `MRJobLauncher.runWorkUnits()`, combine `jobState` with each `workUnit` into a `fatWorkUnit`, since properties from both `jobState` and `workUnit` are needed in order to invoke …
> Separate SourceState/JobState from workUnits

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
Modification to `AvroHdfsDataWriter` that allows a config to specify the group for a file written to HDFS.
> Support for specifying the group for a file

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaWrapper.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWriter.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaAvroSchemaRegistry.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
- gobblin-utility/src/main/java/gobblin/util/SerializationUtils.java
- Break `BaseDataPublisher.publishData()` and `AvroHdfsTimePartitionedWriter.write()` into smaller methods, so that they can be reused by subclasses.
- Added a class `SerializationUtils` which serializes and deserializes an object to/from Strings using charset ISO_8859_1. This is used to transfer Kafka audit count objects from Writers to Publishers as a config property.
- Added a method in `AvroUtils` for converting `GenericRecord` into byte array.
- Some other small changes.
> Refactor Writer and Publisher, and add a Util class for publishing Kafka audit counts

- gobblin-data-management/build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/retention/DatasetCleaner.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/DeleteAllRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/PredicateRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/RetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/TimeBasedRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ConfigurableGlobDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/DatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/DateTimeDatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/SingleVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/util/PathUtils.java
- gobblin-utility/build.gradle
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemCache.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemUtils.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemWrapper.java
- gobblin-utility/src/main/java/gobblin/util/PublisherUtils.java
Changes:
* Creating a few new data-management policies
* Creating new classes `ProxiedFileSystemUtils` and `ProxiedFileSystemCache` in order to replace `ProxiedFileSystemWrapper`. The main reason I did this was the clean up some of the code and to make a cache around all proxied filesystem objects created
* Creating a new class called `PublisherUtils` to store utilities for the `DataPublisher`s
> Adding new data-management policies, updating proxying code, creating PublisherUtils

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWriter.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobLauncherFactory.java
- `AvroHdfsTimePartitionedWriter` now writes recordsWritten and bytesWritten to task state, so that the job launcher can aggregate them into job-level metrics.
- Added a noop method in `AbstractJobLauncher` so that subclasses can override it.
- `JobLauncherFactory` now supports creating job launcher based on class name, so I'll be able to write a job launcher class for Kafka.
> make some changes for kafka adapter job-level metrics

- gobblin-data-management/src/main/java/gobblin/data/management/retention/DatasetCleaner.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ProxyableDatasetProfile.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/DatasetVersion.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/StringDatasetVersion.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/TimestampedDatasetVersion.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/FileLevelTimestampVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/util/PathUtils.java
- gobblin-utility/src/main/java/gobblin/util/FileListUtils.java
- gobblin-utility/src/test/java/gobblin/util/FileListUtilsTest.java
1. Added ProxyableFileLevelDatasetProfile for finding file level datasets with proxy enabled.
2. Added SingleTimestampVersionFinder, which uses TimestampedDatasetVersion to find single versions.
3. Added FileListUtils, which is moved from internal idpc repo.
> ETL-2989: Add file level retention for fork operator

- gobblin-runtime/src/main/java/gobblin/runtime/util/ClustersNames.java
- gobblin-runtime/src/test/java/gobblin/runtime/util/ClustersNamesTest.java
- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
* Add proper closing of input streams to ClustersNames constructor to fix a FindBugs warning
* Rename TestClustersNames to ClustersNamesTest to be consistent with other tests.
* Fix a FindBugs warning in Scheduler utils which complains that "input" parameter might be null.
@pcadabam can you please review?
> Fix a couple of FindBugs warnings

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
Added counters for:
- Failed to get current available offset from Kafka
- persisted offset too early
- persisted offset too late
> Add Kafka offset-related metrics

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
Enable compaction to be able to handle the case where new data appears in a previously compacted directory. Configurable to either copy new files over to a subdirectory of the compaction output directory or redo compaction.
> Enable compaction to handle late data arrivals

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyCompactorOutputCommitter.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyCompactorOutputFormat.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyDedupReducer.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
Added logic to MRCompactorAvroKeyDedupJobRunner to rename the outputted files to include a timestamp and record count.
> Add record count and timestamp to Avro compaction output files

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
@ibuenros can you review this?
This will make sure tags get populated from mapper tasks.
> Use jobState to get JobMetrics in TaskRunner

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
Added a config to have the ability to do compaction which is non-deduplicating, just copying files to the destination rather than going through all records and deduping.
Tested on Azkaban.
> Added config for non-deduping compaction

- build.gradle
- gobblin-core/build.gradle
- gobblin-core/src/test/java/gobblin/source/extractor/hadoop/AvroFsHelperTest.java
- gobblin-utility/src/main/java/gobblin/util/ExecutorsUtils.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
Due to the issue reported in HADOOP-10961, Hadoop 2.6.0 does not work with Guava version 16.0 or after because the deprecation of a constructor of Stopwatch. To make sure Gobblin supports Hadoop 2.6.0, we need to downgrade Guava to version 15.0.
> Downgrade Guava to version 15.0 to work with Hadoop 2.6.0

- build.gradle
Seems the earliest version of hadoop-aws is 2.6.0, so it's not possible to use hadoopVersion for it.
> Use a specific version of hadoop-aws

- gobblin-utility/build.gradle
- gobblin-utility/src/main/java/gobblin/util/PublisherUtils.java
@sahilTakiar can you take a look at this?
Currently in the DataPurgerPublisher we filter out failed extracts. We want to also know the failed extracts to emit events
> Return filtered and non filtered results from PublisherUtils

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/TimePartitionedDataPublisher.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
1. In `FsDataWriter`, when getting the writer output file permission from the state, `Short.parseShort` should be based on radix 8, not 10.
1. Originally `FsDataWriter` calls `this.fs.mkdirs`, which does not use `this.permission`, but uses default permission. Although there's another version of `FileSystem.mkdirs()` that takes a `FsPermission` object, it does not set permissions recursively. So I added a util method `mkdirsWithRecursivePermission()`.
1. In `BaseDataPublisher` add a `List<FsPermission>` field to correctly set publisher output file/folder permissions.
> Make some change regarding file permission

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
- gobblin-compaction/test/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunnerTest.java
- gobblin-test/resource/dedup-schema/dedup-schema-with-pkey.avsc
- gobblin-test/resource/dedup-schema/dedup-schema-without-pkey.avsc
- gobblin-test/resource/dedup-schema/dedup-schema.avsc
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
Previously there were two options for deduping: (1) set `compaction.use.all.attributes=true` and use all fields in the topic schema; (2) specify a custom dedup schema via `avro.key.schema.loc`.
Now adding a 3rd option suggested by @shirshanka : use all fields in the topic schema annotated by "primarykey". If there's no such fields, all fields will be used.
> Add compaction avro dedup key option

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/instrumented/Instrumented.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
@ibuenros is this the correct approach?
Also, I see that `METRIC_CONTEXT_NAME_KEY` is set for `JobMetrics` on line 692 of `MRJobLauncher`, but I don't see an equivalent setting for `TaskMetrics`. Is this expected?
> Adding Fork name tags to each Fork branch

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
The parallel runner will use the same filesystem for the ones that have same fs uri. But in proxy filesystem, besides comparing fs uri, the user of that proxy file system should also be compared.
Add fs.getHomeDirectory() to getParallelRunner. 
Tested on Nertz.
@sahilTakiar Can you review it?
> ETL-3428: Fix for cleaning staging data using proxy file system

- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
also deprecated redundant methods `getProperty` in `State` and `WorkUnitState`.
> use lowWm in KafkaSource if actualHighWm doesn't exist

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWriter.java
Before: `AvroHdfsTimePartitionedWriter` can only take a single partition column
Now: it can take multiple partition columns, which will be tried one by one.
> Allow AvroHdfsTimePartitionedWriter to take multiple partition columns

- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
Reason: https://github.com/linkedin/gobblin/issues/313
An alternative approach is to modify `AbstractJobLauncher` to avoid submitting the same directory for cleaning more than once. I'd prefer the lock approach since it is cleaner and makes it easier for future classes that use `ParallelRunner`.
> Add locks to ParallelRunner

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyCompactorOutputCommitter.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyMapper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
Previously if `deduplicate=false`, it uses the Azkaban job to copy the data from hourly folder to daily folder, which is too slow for large number of topics and data volumes.
Now using a map-only job similar as camus-sweeper.
Also add a counter in `AvroKepMapper` to get row count for map-only jobs.
> Use MR jobs for non-deduping compaction

- gobblin-runtime/src/main/java/gobblin/runtime/util/JobStateToJsonConverter.java
The JobStateToJsonConverter tool is fixed by @sahilTakiar and checked in branch "statestore-checker". I tested it and added one more option to output to a file.
@sahilTakiar Can you review?
> ETL-3544: Jobstate to json tool

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractTaskStateTracker.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskExecutor.java
- gobblin-runtime/src/main/java/gobblin/runtime/WorkUnitManager.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalTaskStateTracker.java
- gobblin-utility/src/main/java/gobblin/util/ExecutorsUtils.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
@liyinan926 can you take a look.
We're adding this because there was a recent Gobblin map task that hung for over 40 hours. ETL-3550 has more info, but long story short, the theory is that not all threads got shut down properly, causing the JVM to hang.
This PR should better help us debug this issue if it occurs again.
> Adding additional logging in case an ExecutorService cannot shutdown all its threads

- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedSource.java
In certain edge case combinations of number of files and partitions, you can run into an issue where the `fileOffset` will exceed the number of `filesToPull` and still attempt to create partitions even though there are no files to add to the partitions. Switched the for loop to loop by `fileOffset` rather than the number of partitions.
Example issue state: 100 partitions, 180 files
> Fix overflow bug in FileBased partitioning

- gobblin-metrics/src/main/java/gobblin/metrics/event/TimingEvent.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
Modified `TimingEvent` and added a new method `stop(Map<String, String> additionalMetadata)` which specifies extra metadata that can be submitted along with the `TimingEvent`. The advantage being that a user may want to emit additional metadata specific to that timing event. I decided to add `additionalMetadata` to the `stop()` method instead of the constructor, because the metadata may not be known until the timing event has completed.
Updated `MRJobLauncher` to record the hadoop job id when it submits a timing event for the length of the MR job.
@ibuenros and @liyinan926 could you review?
> Adding option to submit additional metadata when stopping a timer event

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTaskStateTracker.java
```MRTaskStateTracker``` exposes metrics as Hadoop counters if **mr.report.metrics.as.counters** is set. However, all the counters are associated to the JOB group (pull #169) which results in an emtpy taskCounterGroup in ```MRJobLauncher#countersToMetrics```. As a result, the TASK level counters will be shown in the JOB Counter group on the JobHistory UI.
The patch tries to differentiate between the MetricGroup type  by applying a filter on the counters returned by ```JobMetrics.get(null, task.getJobId()).getMetricContext().getCounters()```
in ```MRTaskStateTracker```
> Filter Hadoop counter groups in MRTaskStateTracker

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/main/java/gobblin/publisher/DataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWithRecordCountsWriter.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/test/java/gobblin/writer/SimpleDataWriterTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/test/java/gobblin/test/TestDataPublisher.java
Summary:
- Data are published by tasks if `job.commit.policy=partial` and `publish.data.in.tasks=true`.
- Added method `DataPublisher.publish(WorkUnitState)` to publish data for a single task.
- Added a flag in `BaseDataPublisher.publishData()` to control whether to publish the data for a single task. When publishing for a single task, it checks the files against `writer.final.output.path` in the `WorkUnitState` to make sure it doesn't publish data written by other tasks.
- In `AvroHdfsTimePartitionedWriter.close()`, it adds all files created by this writer to `writer.final.output.path`.
- `AvroHdfsTimePartitionedWithRecordCountsWriter.close()` will rewrite `writer.final.output.path` upon renaming output file names to include row counts. It also gets the file names from `FsDataWriter` …
> Enable tasks to publish data

- gobblin-rest-service/gobblin-rest-server/src/test/java/gobblin/rest/JobExecutionInfoServerTest.java
The local rest server is set up on port 8080 in JobExecutionInfoServerTest.
With a random port selection one can reduce the possibility of getting a BindException (Address already in use).
> Choose a random rest server port in JobExecutionInfoServerTest

- gobblin-metastore/src/main/java/gobblin/metastore/DatabaseJobHistoryStore.java
When a job execution info is inserted into the jobhistory store, first a default timestamp is inserted into the end_time column of the tables. As the job finishes this timestamp is updated to the actual one.
However, the default timestamp is defined as **1970-01-01 00:00:00** which results in the following exception:
```
Failed to write job execution information to the job history store: java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'end_time' at row 1
java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00' for column 'end_time' at row 1
at gobblin.metastore.DatabaseJobHistoryStore.put(DatabaseJobHistoryStore.java:245)
```
According to …
> Fix default timestamp insertion to JobHistoryStore

- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWriter.java
Using Branches (fork.branches > 1) in combination with AvroHdfsTimePartitionedWriter ignores the number of branches property and therefore leads to error messages about missing properties like 'Missing required property writer.staging.dir' or thows Exceptions ...
> BUGFIX: number of branches ignored when using AvroHdfsTimePartitionedWriter

- ligradle/findbugs/findbugsExclude.xml
Ignoring FindBugs warning NM_SAME_SIMPLE_NAME_AS_SUPERCLASS given for deprecated limiter classes
> Ignoring FindBugs warning NM_SAME_SIMPLE_NAME_AS_SUPERCLASS

- ligradle/findbugs/findbugsExclude.xml
The previous commit inadvertently disabled another FindBugs exclude rule.
@ydailinkedin  can you review?
> Fix incorrect FindBugs exclude rule

- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedExtractor.java
- gobblin-core/src/test/java/gobblin/source/extractor/filebased/FileBasedExtractorTest.java
@ydailinkedin can you review?
Small fix so that `hasNext()` does not get called multiple times before `next()` is invoked. This should fix the `EOFException`s we are seeing when reading specific Avro files.
> Fix EOFException with Avro DataFileReader

- ligradle/findbugs/findbugsExclude.xml
@ydailinkedin  There is one more warning to ignore (for interfaces)
> One more FindBugs warning to ignore

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-compaction/build.gradle
- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionSlaEventHelper.java
- gobblin-compaction/src/main/java/gobblin/compaction/event/DedupeStatus.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
- gobblin-metrics/build.gradle
- gobblin-metrics/src/main/java/gobblin/metrics/event/sla/SlaEventKeys.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/sla/SlaEventSubmitter.java
@ibuenros @chavdar  can you take a look at this?
Overview
- The change defines metadata required in an SLA event. An SLA event must have datasetUrn, partition, originTs and upstreamTs
- An SLA event can also have additional optional metadata like completenessPercentage, recordCount etc. See SlaEventKeys.java. Optional metadata is not applicable to all ETL flows.
- Any ETL flow can extend the abstract class SlaEvent and implement the getters for datasetUrn, partition, originTs, upstreamTs. The SlaEvent class does not expose the key names for any metadata. This promises a fixed schema for an SlaEvent.
- Next, we want to define and Arvo schema for the sla event. This change will still emit a GobblinTrackingEvent.
Compaction changes
- Enabled metrics/events for MRCompactor job
- emit an SLA …
> Defining Sla Event metadata

- build.gradle
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
- gobblin-core/build.gradle
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaUtils.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaAvgRecordSizeBasedWorkUnitSizeEstimator.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaAvgRecordTimeBasedWorkUnitSizeEstimator.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaBiLevelWorkUnitPacker.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaSingleLevelWorkUnitPacker.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaWorkUnitPacker.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaWorkUnitSizeEstimator.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractTaskStateTracker.java
- Now using the avg time to pull a record for mapper load balancing, instead of avg record size. This is more accurate since the time spent on a record is not necessarily proportional to its size. This is done in the following way:
- Each partition pulled in the previous run has an avg time per record in the workunitstate.
- In the next run, the estimated avg time per record for each topic is the geometric mean of the avg time per record of all partitions. For example if a topic has two partitions whose avg time per record in the previous run are 2 and 8, the next run will use 4 as the estimated avg time per record. The reason to choose **geometric mean** over algebraic mean is because large numbers are likely outliers, e.g., a topic may have 5 partitions, and the avg time per record …
> Kafka Adapter Performance Enhancement

- gobblin-core/src/main/java/gobblin/metrics/GobblinMetrics.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaEventReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/EventReporter.java
- Report all the events before closing the reporter
- Removed call to close all reporters in GobblinMetrics as the reporters are already registered with closer.
@ibuenros can you take a look at this?
> Report events before closing EventReporter

- gobblin-core/src/main/java/gobblin/metrics/GobblinMetrics.java
- gobblin-core/src/main/java/gobblin/metrics/GobblinMetricsRegistry.java
- gobblin-metrics/src/main/java/gobblin/metrics/MetricContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobMetrics.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/TaskMetrics.java
The deadlock may happen because:
1. One thread calls `JobMetrics.remove`, which tries to remove itself as well as the `TaskMetrics` of all the tasks from the `GobblinMetricsRegistry` while holding a lock on `JobMetrics.class` since `JobMetrics.remove` is `synchronized`. When it tries to remove a `TaskMetrics` it also needs to acquire the lock on `TaskMetrics.class` since `TaskMetrics.remove` is `synchronized`.
2. Another thread instantiates a `TaskContext`, which calls `TaskMetrics.get` and needs to acquire the lock on `TaskMetrics.class`. In the constructor of `TaskMetrics`, however, the method `parentContextForTask` will call `JobMetrics.get`, which will need to acquire the lock on `JobMetrics.class`.
3. So the first thread needs to acquire both locks in the order of …
> Fixed a bug that may cause a deadlock reported in issue #340

- bin/gobblin-mapreduce.sh
It seems to me that the Guava version was not adjusted in ```gobblin-mapreduce.sh``` when [Pull#280](https://github.com/linkedin/gobblin/pull/280) downgraded the version from 18 to 15.
> Set Guava to version 15.0 in gobblin-mapreduce.sh

- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/test/java/gobblin/runtime/FsDatasetStateStoreTest.java
When a new ```DatasetState``` is created from a ```JobState``` object in ```JobState#newDatasetState```, the start time, end time and duration properties are not copied.
This will result 0 values in the job level properties in the state store files.
> Missing properties in DatasetState

- gobblin-metrics/src/main/java/gobblin/metrics/reporter/EventReporter.java
queue.add() throws exception even for blocking queues, queue.offer() just blocks.
> Fix issue with queueing events in EventReporter.

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-metrics/src/main/java/gobblin/metrics/MetricContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinApplicationMaster.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobScheduler.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixTask.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinWorkUnitRunner.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnContainerSecurityManager.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnService.java
1. Moved code that registers with a `EventBus` instance outside the constructors so to prevent objects to be registered from being exposed too early before exiting the constructors.
2. Use `TaskExecutor.execute` instead of `submit` whenever possible as `ExecutorService.submit` will not trigger uncaught exception handler if a task throws an unchecked exception.
3. Other minor code refactoring.
> A couple of enhancement to Gobblin on Yarn

- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/main/java/gobblin/configuration/StateUtils.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/kafka/KafkaSourceTest.java
Adding a feature that allows users to specify configuration key, value pairs on a per topic basis. The approach is to use a config key called `kafka.topic.specific.state` that takes in a JSON array. More information is in the Java Docs.
Still working on finding a way to test the code.
> Kafka Adapter: Adding support for topic specific configs

- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionSlaEventHelper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
@zliu41 can you review this?
As discussed I have set the upstreamTime to midnight of partition date. This will used as date of arrival of data for compaction to compute SLA.
> Set partition folder time as upstreamTime for time based compaction

- build.gradle
- conf/application.conf
- gobblin-scheduler/src/main/java/gobblin/scheduler/JobScheduler.java
- gobblin-utility/src/main/java/gobblin/util/logs/LogCopier.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinApplicationMaster.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobScheduler.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinWorkUnitRunner.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnConfigurationKeys.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnLogSource.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnAppSecurityManager.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnContainerSecurityManager.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnHelixUtils.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnService.java
This PR adds log aggregation to Gobblin on Yarn. Implementation notes as follows:
1. There's a utility class `LogCopier` that is an `AbstractScheduledService` that periodically scans for new log files in a given source log directory and schedules a new copy task for each new source log file. Each source log file is copied to a destination directory on the destination file system.
2. The `LogCopier` remembers the current position in the input file stream of each log file and will seek to that position whenever the task starts to copy.
3. Both `GobblinApplicationMaster` and `GobblinWorkUnitRunner` now extend `GobblinYarnLogSource`, which handles to details of building a `LogCopier` to copy the container logs to HDFS.
4. `GobblinYarnAppLauncher` is a sink for logs that copies log files from …
> Added log aggregation to Gobblin on Yarn

- gobblin-utility/src/main/java/gobblin/util/ExecutorsUtils.java
- gobblin-utility/src/test/java/gobblin/util/ExecutorsUtilsTest.java
We find loop parallelizing logic in several parts of the code base hence trying to make a standard way of doing it.
Added a utility method to parallelize loops. Applies a {@link Function} to every element in a {@link List} in parallel by spawning threads. A list containing the result obtained by applying the function is returned. The method is a blocking call and will wait for all the elements in the list to be processed or timeoutInSecs which ever is earlier.
@chavdar can you review?
> Add loop parallelization utility to ExecutorsUtils

- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskContext.java
Currently in `TaskContext.getConverters(int index)`, a local copy of the `taskState` is created and used to initialize the converters. Because of this, any user-set properties in the converters are not available in the original task-level `TaskState` and therefore are lost. This PR fixed this. 
> Make sure properties set in a pre-fork converter is not lost

- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionSlaEventHelper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
Fixed record count being 0 for a few topics. The compaction jobs for these topics were mapper only. The code previously only looked at reducer counters.
@zliu41 can you take a look at this?
> Fix record count in compaction sla event

- gobblin-api/src/main/java/gobblin/util/RecordCountProvider.java
- gobblin-compaction/src/main/java/gobblin/compaction/Dataset.java
- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionSlaEventHelper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyCompactorOutputCommitter.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyRecursiveCombineFileInputFormat.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
- gobblin-compaction/src/test/java/gobblin/compaction/mapreduce/MRCompactorJobRunnerFilenameRecordCountProviderTest.java
- gobblin-core/src/main/java/gobblin/publisher/TimePartitionedDataPublisher.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWithRecordCountsWriter.java
- gobblin-utility/src/main/java/gobblin/util/DatasetFilterUtils.java
- gobblin-utility/src/main/java/gobblin/util/FileListUtils.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/main/java/gobblin/util/recordcount/CompactionRecordCountProvider.java
- gobblin-utility/src/main/java/gobblin/util/recordcount/IngestionRecordCountProvider.java
- gobblin-utility/src/main/java/gobblin/util/recordcount/LateFileRecordCountProvider.java
- gobblin-utility/src/test/java/gobblin/util/recordcount/CompactionRecordCountProviderTest.java
- gobblin-utility/src/test/java/gobblin/util/recordcount/IngestionRecordCountProviderTest.java
Main changes:
- Moved all folders (e.g., `inputPath`, `inputLatePath`, etc.) as fields of `Dataset` to avoid passing all of them around in method signatures.
- Moved the logic for finding late data files from `MRCompactorTimeBasedJobPropCreator` to `MRCompactorJobPropCreator` since they are also applicable to non time-based compaction.
- Added support for handling input late paths (since hourly compaction may create `hourly_late`, which will be the input late path for daily compaction) for both dedup and non-dedup cases. If input late dir has data and the dataset has not been compacted before, the dataset will always be deduped.
- For hourly compaction, the output file format in `hourly` folder is compaction format (start with `part-r`), while the file format in `hourly_late` folder is …
> Late data handling for compaction

- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionSlaEventHelper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
There are two types of non-deduping compaction: (1) the data doesn't need to be deduplicated, e.g., /data/service; (2) the data do need to be deduplicated, but the input data is already compacted, e.g., daily compaction for /data/tracking.
These two types need to be treated different when there's late data. For type (1), we simply copy late data to output folder; for type (2), we need to copy late data to _late folder. Also, for type (2), when we compact a folder for the first time, if the input folder contains late data (e.g., in `hourly_late`), then it will run a deduping compaction instead of non-deduping compaction.
Separated property `compaction.deduplicate` into `compaction.input.deduplicated` and `compaction.output.deduplicated`. In case (1), both are false. In case (2), both are …
> Separate two types of non-deduping compaction

- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
If a mapper publishes data for some tasks and then failed, and a new mapper is launched for the same tasks, the new mapper will still fail because it will fail to publish data for those tasks since they already exist in the dest folder.
> Do not throw Exception in ParallelRunner.rename if dst exists

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
Some metrics, e.g., `FAIL_TO_GET_OFFSET_COUNT`, are obtained in `Source` and added to `SourceState`, so they will be in `JobState` instead of `TaskState`.
> Replace postProcessTaskStates() with postProcessJobState()

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
- gobblin-utility/src/main/java/gobblin/util/SerializationUtils.java
- gobblin-utility/src/test/java/gobblin/util/ParallelRunnerTest.java
- gobblin-utility/src/test/java/gobblin/util/SerializationUtilsTest.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixTask.java
Currently in the MR mode, there's an optimization that avoids adding the JobState to the WorkUnits too early to reduce the memory footprint on the client side as well as reduce the cost of serializing the WorkUnits. The JobState is added to the WorkUnits, though, in the mappers after the WorkUnits are deserialized. Currently the Yarn mode is not doing this optimization so this PR fixes it.
> Do not add JobState to WorkUnits until when the tasks start

- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionSlaEventHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/kafka/KafkaSourceTest.java
The reason to change `topicSpecificStateMap` from `Map<KafkaTopic, State>` to  `Map<String, State>` is that some methods were calling `get` and passes a `String`. And `KafkaTopic` doesn't even implement `equals` and `hashCode`.
> Fix 2 findbugs correctness warnings

- gobblin-core/src/main/java/gobblin/source/extractor/JobCommitPolicy.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskExecutor.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/test/TestExtractor.java
1. Introduced a new `JobCommitPolicy.COMMIT_SUCCESSFUL_TASKS` that will only commit successful tasks. This is recommended to be used with jobs with task-level data publishing so tasks can control independently if their output data should be published.
2. Updated `KafkaExtractor` to skip updating the actual high watermark if the `WorkUnit` fails.
3. Used a `ExecutorCompletionService` to run `Fork`s of a `Task` and for waiting for the `Fork`s to finish, instead of a `CountDownLatch`.
4. Other code factoring.
> Fixed an issue that may cause Kafka adapter to miss data if the Fork fails

- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-api/src/main/java/gobblin/source/workunit/MultiWorkUnit.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
- gobblin-core/src/test/java/gobblin/configuration/workunit/MultiWorkUnitTest.java
- gobblin-core/src/test/java/gobblin/source/workunit/MultiWorkUnitWeightedQueueTest.java
- gobblin-example/src/main/java/gobblin/example/simplejson/SimpleJsonSource.java
- gobblin-example/src/main/java/gobblin/example/wikipedia/WikipediaSource.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/TaskContextTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/GobblinOutputCommitterTest.java
- gobblin-utility/src/test/java/gobblin/util/JobLauncherUtilsTest.java
- gobblin-utility/src/test/java/gobblin/util/WriterUtilsTest.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixTask.java
Currently, the `GobblinHelixJobLauncher` flattens `MultiWorkUnit`s and hope for Helix to do a balanced assignments of tasks to containers. However, both Gobblin Kafka and IDPC HDFS Purger already have their own logic of grouping `WorkUnit`s into `MultiWorkUnit`s. It's good to keep their logic and not to override it.
> Do not override `MultiWorkUnit` grouping in Gobblin Yarn

- build.gradle
- gobblin-api/src/main/java/gobblin/writer/WriterOutputFormat.java
- gobblin-core/build.gradle
- gobblin-core/src/main/java/gobblin/converter/serde/HiveSerDeConverter.java
- gobblin-core/src/main/java/gobblin/serde/HiveSerDeWrapper.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/OldApiWritableFileExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/OldApiWritableFileSource.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/HiveWritableHdfsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/HiveWritableHdfsDataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriter.java
1. Added a `Source`, an `Extractor`, a `Converter` and a `DataWriter` for supporting Hive SerDes.
2. Moved `stagingFileOutputStream` out of `FsDataWriter`, since Hive SerDes use `RecordWriter` to write data to staging files, which may fail if there is already an open `stagingFileOutputStream`.
Tested with Avro serde in and Orc serde out.
> Hive SerDe support

- gobblin-core/src/main/java/gobblin/source/extractor/JobCommitPolicy.java
The code that realizes `COMMIT_SUCCESSFUL_EXTRACTS` will come later in a different PR.
> Deprecated COMMIT_ON_PARTIAL_SUCCESS and added a new policy for successful Extracts

- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
It was added in 7598696 since there was a warning in eclipse that writer is never closed. But the created writer is registered again in line 70 which causes the writer to be closed twice (which will fail).
> Remove duplicate closer registration

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaUtils.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaWorkUnitPacker.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixTask.java
Originally Gobblin on Yarn was written with the assumption that we would rely on Helix to group/pack `WorkUnit`s into groups and assign them properly to the available containers. So the code originally flattened the `MultiWorkUnit`s. Later it was realized this would not be too practical since Helix does not have the knowledge of loads of individual `WorkUnit`s. In addition, the Gobblin Kafka adapter is already doing bin packing so we decided to not override that logic and changed the code to not flatten `MultiWorkUnit`s. However, the parts that actually run the job/tasks are not updated accordingly to work with `MultiWorkUnit`s. This PR fixed it. 
> Fixed Gobblin Yarn to be able to run MultiWorkUnits

- gobblin-compaction/src/main/java/gobblin/compaction/Dataset.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
Previously if the MR compaction job for a topic fails it won't affect other topics, but if it fails when creating job properties for a topic or submitting the topic to the job executor, the whole job will fail immediately and no other topic will be processed.
This PR fixes it -- in the above cases the topic will be skipped without affecting other topics.
> Improve topic isolation in MRCompactor

- gobblin-compaction/build.gradle
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
Add an option to use a prime number of reducers for compaction, which is less subject to hashcode skew.
Also changed the default data size a reducers processes from 256M to 512M, which brings the number of reducers a job uses more in-line with Camus.
> Add option to use prime number of reducers in compaction

- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpFsHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpLightWeightFileSystem.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CloseableFsCopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/extractor/CloseableFsFileAwareInputStreamExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/extractor/FileAwareInputStreamExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyDataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterBuilder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/TarArchiveInputStreamDataWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/TarArchiveInputStreamDataWriterBuilder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ConfigurableGlobDatasetFinder.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-test-harness/resource/dataManagement/copy/job-props/copy.pull
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
The pr has some bug fixes to sftp copy. 
Tested on both MR mode and local mode
**Bugs/improvements**
1. SftpFsHelper - Added support to read private key file from HDFS for password-less sftp connection
2.  SftpLightWeightFileSystem.java - 
* Removed scheme and authority from paths since jsch expects raw path strings. 
* Create a new sftp filesystem each time instead of cached copy. (Note that new instance is created only for sftp file system. Other fs still use cached copy). In the continuous execution model, multiple jobs can run in the same container/jvm. If a cached copy is used per jvm, an authenticated session created by one job will be used by another job.
3. CopySource.java - CopyableDataset was incorrectly serialized in SourceState instead of …
> Bug fixes to sftp copy

- gobblin-data-management/src/main/java/gobblin/data/management/copy/SerializableCopyableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/SerializableCopyableDatasetTest.java
Fixes -
1. Ancestor permissions were set on final destination path instead of staging path
2. Always grant execute permissions to directories created in staging directory to be able to publish them.
@sahilTakiar can you review this?
> Permission fixes for distcp-ng

- gobblin-runtime/build.gradle
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
Seems `commons-lang3` was added just for one use in `gobblin-runtime`: to use the method `ExceptionUtils.getStackTrace()`. Replaced this usage with `Throwables.getStackTraceAsString()` so the dependency on `commons-lang3` can be removed.
> Removed dependency on commons-lang3

- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriter.java
Due to some recent changes to `FsDataWriter` and its subclasses, `FsDataWriter` will throw an `FileNotFoundException` if a group is specified and it tries to set the group on the staging output file, which won't be created until later in the constructor of `AvroHdfsDataWriter` and `SimpleDataWriter`. Attempt to set group on a file that does not exist will throw an `FileNotFoundException`. 
> Set group after the staging output file gets created

- bin/gobblin-mapreduce.sh
- gobblin-api/src/main/java/gobblin/writer/WriterOutputFormat.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriterBuilder.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskContext.java
- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
If `ConfigurationKeys.WRITER_OUTPUT_FORMAT_KEY` doesn't match any `WriterOutputFormat` type, its value will be used as extension.
> Support custom output file extensions

- gobblin-runtime/build.gradle
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/CloseableJobListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobExecutionEventSubmitter.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobExecutionEventSubmitterListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobListeners.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobExecutionEventSubmitterTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobListenersTest.java
* Created a new class called `JobExecutionEventSubmitter` that submits metadata for a given `JobState`, the events are submitted using a `EventSubmitter`
* `JobExecutionEventSubmitter` is wrapped in a `JobListener` as is invoked as any other `JobListener`
* Added a new util class called `JobListeners` that provides a way of combining multiple `JobListener`s into one `JobListener` and running them in parallel
* The config key `ConfigurationKeys.TASK_FAILURE_EXCEPTION_KEY` is updated not just for Task failures, but also for task publishing failures
@liyinan926 can you review?
> Submitting event metadata for each successful job, including task exceptions

- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-yarn/build.gradle
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobLauncher.java
Setting the `job.launcher.type` key to `LauncherTypeEnum.YARN` for YARN jobs. This allows us to differentiate between jobs that run on YARN vs. MR vs. Local when consuming events produced by `JobExecutionEventSubmitter`.
> Setting job.launcher.type for YARN jobs

- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyDataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/DeletingCopyDataPublisher.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/CopyableFileUtils.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/TestCopyableDataset.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/publisher/CopyDataPublisherTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/publisher/DeletingCopyDataPublisherTest.java
@liyinan926 can you review?
Changes -
1. If a dataset publish fails, the job should not fail. It should publish other datasets
2. Add a publisher that deletes data on source after successful publish
3. Add unit tests for CopyDataPublisher and DeletingCopyDataPublisher
> Add support to delete data on source after copy

- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
@ibuenros can you review this? This is the fix for failing build on hudson. Hadoop2 freaks out if you call liststatus on a path that does not exist.
> Check path existance before calling fileSystem.listStatus

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroExtractor.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaAvroSchemaRegistry.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaSchemaRegistry.java
1. Added schema registry to `KafkaAvroExtractor`, since people are using Confluent's schema registry. It is not mandatory, and if one doesn't want to use schema registry, she needs to override `getExtractorSchema()` and get the schema in her own way.
2. Changed `KafkaSchemaRegistry` from interface to abstract class, and moved some code over from `KafkaAvroSchemaRegistry` (mainly the loading cache part), which can be reused by other implementations of schema registry.
> Add schema registry to KafkaAvroExtractor

- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
The recent change to `JobState` is breaking Kafka adapter since Kafka adapter uses a subclass of `MRJobLauncher` that is not in github. (`com.linkedin.gobblinjobmetrics.KafkaMRJobLauncher`)
This PR fixes it by having `getLauncherType()` return `LOCAL` if the job launcher name is not found in `JobLauncherType`.
> Make JobState use local job launcher by default

- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
Currently fork's row checker final states are added, but task's row checker's are not. This PR fixes it.
> Add row checker final state to task state

- gobblin-metrics/src/main/java/gobblin/metrics/event/EventSubmitter.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobExecutionEventSubmitter.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobMetrics.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinApplicationMaster.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJob.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobScheduler.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnEventNames.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnService.java
* Added feature so that the YARN application name and application id are submitted in YARN job life cycle events (job failed, task failed, etc.). This was done by modifying the constructor of `AbstractJobLauncher` so that it can take in additional metadata that is specific to any of its sub-classes
* A few other code formatting / cleanup changes.
* Tested on Nertz
@liyinan926 can you review?
> Adding yarn name and app id to job life cycle events

- gobblin-core/src/main/java/gobblin/qualitychecker/row/RowLevelErrFileWriter.java
- gobblin-core/src/main/java/gobblin/qualitychecker/row/RowLevelPolicyChecker.java
- gobblin-core/src/main/java/gobblin/qualitychecker/row/RowLevelPolicyCheckerBuilder.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/test/java/gobblin/util/HadoopUtilsTest.java
This PR fixes two issues:
1. Originally `RowLevelErrFileWriter` can only write to local FS.
2. Originally multiple tasks write the error records into the same err file. Now task id is added to the err file name to avoid this.
> Make it possible for RowLevelErrFileWriter to write to HDFS

- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
There is a race condition between `FsDataWriter.addRecordCountToFileName()` and `AvroHdfsDataWriter.bytesWritten()`. Between `if (!this.fs.exists(this.outputFile))` and `return this.fs.getFileStatus(this.outputFile).getLen()`, the output file could be renamed (adding row count to file name). Adding synchronization to resolve this. 
Also, reset `this.outputFile` to new path after renaming.
> Resolve race condition between writer and metric updater

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroCombineFileSplit.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyCombineFileRecordReader.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyMapper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyRecursiveCombineFileInputFormat.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
A proposal for a solution to https://github.com/linkedin/gobblin/issues/486.
I implemented new class AvroCombineFileSplit which stores the avro schema for each split, determined by the corresponding input file.
I added property "avro.single.input.schema" to keep old behaviour.
What do you think?
> MRCompactorAvroKeyDedupJobRunner and schema changes #486

- build.gradle
- gobblin-compaction/build.gradle
- gobblin-utility/build.gradle
- maven-sonatype.sh
Rework of the Maven Publishing code:
* Switch to using the legacy "maven" plugin instead of the new "maven-publish" due to issues with signing artifacts
* Add support for signing the artifacts
* Use group com.linkedin.gobblin instead of gobblin as per Sonatype requirements
* Add POM metadata as per Sonatype requirements
* Rename gobblin-utility.tar.gz and gobblin-compaction.tar.gz to gobblin-utility.tgz and gobblin-compaction.tgz since the Gradle signing plugin does not work correctly if a file has two extensions
* Add a helper script maven-sonatype.sh with instructions on how to publish the artifacts
@liyinan926 @ibuenros Can you review?
> Adding instrumentation to publish to Maven Central

- gobblin-api/src/main/java/gobblin/writer/DataWriter.java
- gobblin-core/src/main/java/gobblin/instrumented/writer/InstrumentedDataWriterBase.java
- gobblin-core/src/main/java/gobblin/instrumented/writer/InstrumentedDataWriterDecorator.java
- gobblin-core/src/main/java/gobblin/metrics/MetricNames.java
- gobblin-core/src/test/java/gobblin/instrumented/writer/InstrumentedDataWriterTest.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractTaskStateTracker.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
* Fixing reporting for byte level metrics in `TaskState`.
* Fix applies to `BYTES` and `BYTES_PER_SECOND` metrics. 
* Changed the method `TaskState.updateByteMetrics` to follow the same logic as `TaskState.updateRecordMetrics`.
@liyinan926 and @ibuenros can you review
> Fixing task reporting of bytes written

- gobblin-utility/src/main/java/gobblin/util/io/StreamUtils.java
- gobblin-utility/src/main/java/gobblin/util/logs/LogCopier.java
* Fix for `StreamUtils.tar` there were some problems with un-tarring the resulting object on the GNU tar distribution vs. the BSD tar distribution
* Fix for `LogCopier.Stopwatch`
@liyinan926 can you review?
> Fix for StreamUtils.tar and Yarn LogCopier

- gobblin-core/src/main/java/gobblin/fork/IdentityForkOperator.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnAppSecurityManager.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnContainerSecurityManager.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinApplicationMasterTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinHelixJobLauncherTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinHelixTaskTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinWorkUnitRunnerTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/TestHelper.java
- gobblin-yarn/src/test/java/gobblin/yarn/YarnSecurityManagerTest.java
- gobblin-yarn/src/test/resources/YarnSecurityManagerTest.conf
This is the part II of unit tests for Gobblin Yarn. Part II additionally covers `YarnAppSecurityManager` and `YarnContainerSecurityManager`. Currently the only Yarn-dependent class that has no coverage is `YarnService`. Since `YarnService` runs in the `GobblinApplicationMaster` that is supposed to be launched by Yarn without user interference, I'm still trying to figure out a way of running it manually. This PR also addresses the left-over review comments from PR #501.  
> Unit tests for Gobblin Yarn part II

- .gitignore
- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/TimePartitionedDataPublisher.java
- gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/FsDatasetStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-utility/src/main/java/gobblin/util/ExecutorsUtils.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemUtils.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemWrapper.java
- gobblin-utility/src/test/java/gobblin/util/ParallelRunnerTest.java
Support for publishing data to a different filesystem from where data is written.  The use case of this is writing the files to HDFS, but publishing them to S3.
> Separate publisher filesystem from writer filesystem

- gobblin-core/src/main/java/gobblin/metrics/GobblinMetrics.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableFile.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/FileAwareInputStream.java
- gobblin-metrics/src/main/java/gobblin/metrics/Tagged.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobMetrics.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/TaskMetrics.java
- gobblin-yarn/src/main/java/gobblin/yarn/ContainerMetrics.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixTask.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixTaskFactory.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinWorkUnitRunner.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnHelixUtils.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinHelixTaskTest.java
* YARN containers were not reporting any Task Level Metrics (e.g. records extracted, records written, bytes written, etc.) because Metrics Reporting was not enabled in the containers
* Added `ContainerMetrics.java` to handle metrics reporting for each YARN container
* The metrics hierarchy is as follows `ContainerMetrics` -> `JobMetrics` -> `TaskMetrics`
* A `JobMetrics` instance is obtained in each `GobblinHelixTask`
* Unlike `MRJobLauncher` where the `JobMetrics` instance is manually removed from the `GobblinMetricsRegistry`, `GobblinHelixTask` does not remove the `JobMetrics` instance at the end of each task because there may be more tasks in the container that need the `JobMetrics` instance
* Reporting is done on the `ContainerMetrics` instance
* Testing is still in progress …
> Adding Container Metrics for gobblin-yarn

- build.gradle
- gobblin-api/build.gradle
- gobblin-api/src/main/java/gobblin/testing/AssertWithBackoff.java
- gobblin-api/src/test/java/gobblin/testing/AssertWithBackoffTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/FileBasedJobLockTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- gobblin-scheduler/src/test/java/gobblin/scheduler/JobConfigFileMonitorTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinApplicationMasterTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinWorkUnitRunnerTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/TestHelper.java
- gobblin-yarn/src/test/java/gobblin/yarn/YarnSecurityManagerTest.java
* Wait to connect to ZK in gobblin.yarn.GobblinYarnAppLauncherTest.setUp()
* Add AssertWithBackoff to retry an assert multiple times
* Refactor tests gobblin-yarn/src/test/java/gobblin/yarn/GobblinApplicationMasterTest.java and gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java to use AssertWithBackoff
This is a squashed version of https://github.com/linkedin/gobblin/pull/523
> Changes to decrease reliance on timing in unit tests:

- build.gradle
Error is :
* Where:
Build file '/export/home/tester/hudson/data/workspace/etl-infra-gobblin-proxy-code-quality/gobblin-proxy_trunk/gobblin-github/build.gradle' line: 246
* What went wrong:
A problem occurred evaluating root project 'gobblin-github'.
> No signature of method: com.linkedin.ligradle.product.SimpleVersion.indexOf() is applicable for argument types: (java.lang.String) values: [-]
Possible solutions: findIndexOf(groovy.lang.Closure)
> Address gradle error in determining javadoc version

- build.gradle
- gobblin-core/src/main/java/gobblin/instrumented/Instrumented.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/QueryBasedExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/QueryBasedSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/MysqlExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/SqlServerExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaWrapper.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpLightWeightFileSystem.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/Utils.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/WatermarkPredicate.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriter.java
The original jar is a fat jar that contains dependencies such as commons-lang and Guava, which shadow the intended versions.
This also means that gobblin-core no longer has commons-lang, so changing to commons-lang3.
> Change hive-exec dependency to core.jar

- gobblin-core/src/main/java/gobblin/instrumented/Instrumented.java
- gobblin-core/src/main/java/gobblin/metrics/GobblinMetrics.java
- gobblin-core/src/main/java/gobblin/metrics/GobblinMetricsRegistry.java
- gobblin-metrics/src/main/java/gobblin/metrics/MetricContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobMetrics.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/TaskMetrics.java
- gobblin-yarn/src/main/java/gobblin/yarn/ContainerMetrics.java
While doing some testing for ETL-3891 I found that a bunch of duplicate `MetricContext`s were being created. The duplicate `MetricContext`s had name conflicts and thus had a `UUID` appended at the end of the name. The reason the duplicates were being created is due to the behavior of the `GobblinMetricsRegistry.getOrDefault()` method as well as the `get()` methods in `GobblinMetrics`, `JobMetrics`, `ContainerMetrics`, and `TaskMetrics`.
The `getOrDefault` behavior would construct the default value regardless of if the `id` already existed in the `GobblinMetricsRegistry` Cache. So basically, each invocation of `GobblinMetrics.get()` caused a new `GobblinMetrics` instance to be created, which in turn created a new `MetricContext`. These duplicate `MetricContext`s have no references so they …
> Fixing bug with GobblinMetricsRegistry.getOrDefault

- gobblin-core/src/main/java/gobblin/instrumented/fork/InstrumentedForkOperatorBase.java
- gobblin-core/src/main/java/gobblin/instrumented/fork/InstrumentedForkOperatorDecorator.java
- gobblin-scheduler/src/test/java/gobblin/scheduler/JobConfigFileMonitorTest.java
The class `InstrumentedForkOperatorBase` would create a new `MetricContext` in its default constructor, but it would make it with no parent (the correct parent should get the `Task` level `MetricContext`). Then during the `init()` method it would create a new `MetricContext` (this time with the correct parent). The first `MetricContext` would be GC'ed quite quickly as it has no references, but it causes some duplicate reporting so it's best to remove it.
@ibuenros can you review
> Fixing dangling MetricContext creation in ForkOperator

- gobblin-data-management/build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyConfiguration.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyContext.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableDatasetMetadata.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableFile.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/PreserveAttributes.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/RecursiveCopyableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/SinglePartitionCopyableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyDataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyEventSubmitterHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/TarArchiveInputStreamDataWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/dataset/DummyDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/partition/Partition.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ConfigurableGlobDatasetFinder.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/CopyableFileTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/CopyableFileUtils.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/PreserveAttributesTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/RecursiveCopyableDatasetTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/TestCopyableDataset.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/TestCopyablePartitionableDataset.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/extractor/InputStreamExtractorTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/publisher/CopyDataPublisherTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/writer/TarArchiveInputStreamDataWriterTest.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
This PR creates a CopyableFile builder to reuse logic in different CopyableDatasets and fixes some bugs with copy operations.
> Moved logic in RecursiveCopyableDataset to a CopyableDataset builder.

- gobblin-core/src/main/java/gobblin/source/extractor/filebased/SizeAwareFileBasedHelperDecorator.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/AvroFsHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopFsHelper.java
Added a fix for a hadoop issue (https://issues.apache.org/jira/browse/HADOOP-12169) which affects the s3a filesystem and results in duplicate files appearing in the results of ListStatus.  In the process, extracted a base class for all FsHelper classes based on the hadoop filesystem.
> Fix for HADOOP-12169

- build.gradle
- gobblin-rest-service/gobblin-rest-api/build.gradle
Generate artifacts (classes, javadoc, sources) for Pegasus-gerated gobblin-rest-api-data-template and gobblin-rest-api-rest-client.
> Adding build instrumentation for generation of rest-api-* artifacts

- gobblin-metastore/build.gradle
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
Found the missing dependency when testing `JobExecutionInfoServer`. 
@liyinan926 Can you review?
> Add mySql to gobblin-metastore runtime dependency

- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedSource.java
Fixed FileBasedSource so that it will include previously failed WorkUnits even if there are no new files in the source
> Retry failed workunits in FileBasedSource

- gobblin-core/build.gradle
Remove xerces dependencies in gobblin-core:test due to failures in Gradle 2.10
@liyinan926  can you review
Tests pass with this change:
:gobblin-core:testClasses
:gobblin-core:test
BUILD SUCCESSFUL
> Remove xerces dependencies in gobblin-core:test

- build.gradle
- gobblin-yarn/build.gradle
Hive 1.2.1 shadows some of the Hadoop 2.3.0 jars. Change to 0.14.0.
> Change hive version to 0.14.0

- gobblin-metrics/src/main/java/gobblin/metrics/reporter/MetricReportReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/OutputStreamReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ScheduledReporter.java
- gobblin-metrics/src/test/java/gobblin/metrics/reporter/ContextStoreReporter.java
* Adding a tag named `finalMetricReport` that will be set to true on the final metric report reported, this tag will not be present for all other metric reports
* The tag is enabled when a `ScheduledReporter` is stopped or a `MetricContext` is removed
* Implementation is done by introducing a few new methods in `ScheduledReporter`
* Looking at `ScheduledReporter` is the best place to start for this PR
> Adding final tag to the last metric report reported

- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
Bug fix in `WriterUtils.mkdirsWithRecursivePermission` for publishing to file systems where the root directory does not already exist.
> Bug fix for publishing to S3

- gobblin-azkaban/build.gradle
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanCompactionJobLauncher.java
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanTags.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-core/src/main/java/gobblin/metrics/GobblinMetrics.java
- gobblin-metrics/src/main/java/gobblin/metrics/Tag.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/EventSubmitter.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/ClusterNameTags.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinApplicationMaster.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJob.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobScheduler.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinWorkUnitRunner.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinHelixJobLauncherTest.java
* Add Hadoop cluster tag to metrics emitted by gobblin-yarn
* Originally Hadoop cluster tags were only added in `AzkabanJobLauncher` so only jobs launched via `AzkabanJobLauncher` had these tags.
* Moved addition of Hadoop cluster tags to `AbstractJobLauncher`
* Separated out Azkaban and Hadoop specific tags
> Adding Hadoop cluster Tags to gobblin-yarn metrics

- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java
Made the `YarnClient` inside `GobblinYarnAppLauncher` visible to testing so `GobblinYarnAppLauncher` can explicitly start and stop the `YarnClient` inside `GobblinYarnAppLauncher`. 
> Some refactoring around GobblinYarnAppLauncherTest

- gobblin-metrics/build.gradle
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaAvroReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/OutputStreamReporter.java
- gobblin-metrics/src/test/java/gobblin/metrics/reporter/ScheduledReporterTest.java
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
- gobblin-utility/src/test/java/gobblin/util/ConfigUtilsTest.java
@ibuenros and @sahilTakiar can you please review?
The change limits the conversion of properties to typesafe config only for keys that start with metrics.
> Limit typesafe config conversion to metrics keys

- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ScheduledReporter.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/CliLocalJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/ExecutorsUtils.java
* Created a new method `ExecutorUtils.newDaemonThreadFactory` that produces daemon threads
* Fixed bug in `CliLocalJobLauncher` where `LocalJobLauncher` wasn't being closed, causing a few other thread pools to not be shut down
* Fix to `ScheduledReporter.stopImpl` so that when the shutdown hook is invoked, the thread pool is first shutdown, and then one last invocation of `report()` is done
* Test locally, `RootMetricContext`'s `shutdownHook` is invoked, and the process terminates gracefully
@ibuenros and @pcadabam can you review?
> Making ScheduledReporter ThreadPool daemon threads, fixed bugs in CliLocalJobLauncher

- gobblin-core/src/main/java/gobblin/instrumented/converter/InstrumentedConverterBase.java
- gobblin-metrics/src/main/java/gobblin/metrics/metric/Metrics.java
- gobblin-metrics/src/main/java/gobblin/metrics/metric/filter/MetricFilters.java
- gobblin-metrics/src/main/java/gobblin/metrics/metric/filter/MetricNameRegexFilter.java
- gobblin-metrics/src/main/java/gobblin/metrics/metric/filter/MetricTypeFilter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ContextAwareReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ScheduledReporter.java
- gobblin-metrics/src/test/java/gobblin/metrics/metric/filter/MetricFiltersTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/metric/filter/MetricNameRegexFilterTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/metric/filter/MetricTypeFilterTest.java
* Added a configuration key for specifying custom `MetricFilter`s
* Added `NotificationTimerFilter` to filter out the reporting of `MetricContext.notificationTimer`
* Fixed a dangling `MetricContext` in `InstrumentedConverterBase`
My original approach was to make the creation of the `notificationTimer` configurable but that turned out to be difficult given the current handling of config keys, so I added the `MetricFilter` for now since it will probably be a useful feature in other scenarios too.
> Adding configurable MetricFilter

- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpLightWeightFileSystem.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableFileFilter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/ReadyCopyableFileFilter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/RecursiveCopyableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/converter/DecryptConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/converter/UnGzipConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/DeletingCopyDataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/dataset/DatasetUtils.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/ReadyCopyableFileFilterTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/RecursiveCopyableDatasetTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/util/PathUtilsTest.java
- gobblin-utility/src/main/java/gobblin/util/PathUtils.java
- Adding functionality to optionally apply a filter on CopyableFiles found by the CopyableDataset. One of the use cases is to filter out all files that do not have a .ready file on the source filesystem.
- Fix some typos
- Fix recursive delete in SftpFileSystem
@ibuenros and @liyinan926 can you review?
> Add CopyableFileFilter

- gobblin-distribution/build.gradle
Ensure that a gobblin-dist.tar.gz is created at the end of the build.
> Fix the distribution tarball creation

- README.md
- gobblin-distribution/build.gradle
This will help with the following bug that a few people on the google-groups have hit: https://github.com/linkedin/gobblin/wiki/FAQs#how-do-i-fix-unsupportedfilesystemexception-no-abstractfilesystem-for-scheme-null
Also, created this wiki to document all Gradle build options: https://github.com/linkedin/gobblin/wiki/Gobblin-Build-Options
@chavdar can you review?
> Adding option to exclude hadoop and hive jars from gobblin-dist.tar.gz

- gobblin-distribution/build.gradle
Make the distribution build script detect the `uploadArchives` target so that it can know the correct name for the distribution tarball.
As discovered by @sahilTakiar after #604 was merged, the `install` and `uploadArchives` targets result in differently named tarballs.  Prior to #604, when the `uploadArchives` target was specified the tarball would not be copied to gobblin root.  Post #604, when the `install` target is specified the tarball will not be copied to gobblin root.  This PR makes to work either way.
> Fix distribution creation for both install and upload

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableFile.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/converter/DecryptConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/converter/DistcpConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/converter/UnGzipConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/recovery/RecoveryHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/converter/DecryptConverterTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/recovery/RecoveryHelperTest.java
- gobblin-example/build.gradle
- gobblin-example/src/main/resources/distcp.pull
- gobblin-utility/src/main/java/gobblin/util/guid/Guid.java
- gobblin-utility/src/main/java/gobblin/util/guid/HasGuid.java
- gobblin-utility/src/test/java/gobblin/util/guid/GuidTest.java
This PR adds a feature to Gobblin distcp to persist and recover late-failing work units (e.g. can't set permissions).
Change summary:
* Added a guid to `CopyableFile`.
* `CopySource` adds a work unit guid to each work unit.
* `FileAwareInputStream` catches late failures and persists work units. To do this, it moves copied files to a persistent location, identified by guid and a shortened version of their original path. Furthermore, for each work unit, the writer will search the persistent location for matching files, if one is found, it is recovered instead of doing the copy.
* Created `DistcpConverter` as a superclass for all distcp converters.
> Distcp persists and reuses failed work units.

- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
JDBC connections are not getting closed as per the existing code. So a lot of connections are opened at the source end(RightNow) and the mysql database is down.
So I made a small change in JDBCExtractor to close connections in the finally block. This is the only change. But you may see small alignment differences in the diff.
> Close JDBC connections after executing sqls

- gobblin-api/src/main/java/gobblin/password/PasswordManager.java
- gobblin-distribution/build.gradle
As all the jars needed by the password encryptor cli tool are in the ```gobblin-dist/lib``` directory,
it's not necessary to build ```gobblin-utility.tar.gz``` manually as suggested in the [documentation]
(https://github.com/linkedin/gobblin/wiki/Working-with-Job-Configuration-Files#password-encryption) .
This patch copies the shell script to gobblin-dist/bin. Also added a null check to the password
decryptor to fix the NPE in case of unset passwords.
> Gobblin_password_encryptor should be included in the tarball

- gobblin-oozie/src/test/resources/local/gobblin-oozie-example-system.properties
- gobblin-oozie/src/test/resources/local/gobblin-oozie-example-workflow.properties
- gobblin-oozie/src/test/resources/local/gobblin-oozie-example-workflow.xml
- gobblin-runtime/src/main/java/gobblin/runtime/cli/CliOptions.java
Hackday project: Added example configuration files for running Gobblin on Oozie
* Added a few changes to `CliOptions.java` so that it can read configuration files from hdfs, not just the local filesystem - this is necessary for Oozie, as it reads its configuration files from HDFS
* Added configuration files under `gobblin-oozie/src/test/resources`
* The config files run Gobblin in local mode in a Java process
* `gobblin-oozie-example-system.properties` is an example sysconfig for running Gobblin on Oozie
* `gobblin-oozie-example-workflow.properties` is the job config file that Oozie accepts
* `gobblin-oozie-example-workflow.xml` is the Oozie workflow that launches Gobblin as a Java process
Documentation for these configs and a guide on how to run Gobblin on Oozie is here: …
> Gobblin Oozie config files

- gobblin-data-management/build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/RawDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/RawDatasetRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/RawDatasetProfile.java
- gobblin-utility/src/main/java/gobblin/util/FileListUtils.java
A `RawDataset` is a dataset with a corresponding refined dataset (e.g., raw dataset = tracking hourly, refined dataset = tracking daily). A version of a raw dataset is deletable only if it satisfies certain conditions with the corresponding version of the refined dataset. For example, the modification time of the raw dataset should be earlier than the modification time of the corresponding refined dataset.
A `RawDatasetRetentionPolicy` embeds another `RetentionPolicy`. In `listDeletableVersions(List)` it applies the embedded `RetentionPolicy`'s predicate, as well as `listQualifiedRawDatasetVersions(Collection)`.
> Add RawDataset and RawDatasetRetentionPolicy

- conf/gobblin-standalone.properties
- gobblin-api/src/main/java/gobblin/commit/CommitSequence.java
- gobblin-api/src/main/java/gobblin/commit/CommitSequenceStore.java
- gobblin-api/src/main/java/gobblin/commit/CommitStep.java
- gobblin-api/src/main/java/gobblin/commit/CommitStepBase.java
- gobblin-api/src/main/java/gobblin/commit/DeliverySemantics.java
- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/commit/FsRenameCommitStep.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/CommitSequencePublisher.java
- gobblin-core/src/main/java/gobblin/publisher/TimePartitionedDataPublisher.java
- gobblin-core/src/test/java/gobblin/commit/FsRenameCommitStepTest.java
- gobblin-runtime/build.gradle
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/commit/DatasetStateCommitStep.java
- gobblin-runtime/src/main/java/gobblin/runtime/commit/FsCommitSequenceStore.java
- gobblin-runtime/src/test/java/gobblin/runtime/commit/CommitSequenceTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/commit/FsCommitSequenceStoreTest.java
- gobblin-utility/src/main/java/gobblin/util/filters/HiddenFilter.java
- gobblin-utility/src/main/java/gobblin/util/io/GsonInterfaceAdapter.java
Design: https://github.com/linkedin/gobblin/wiki/Exactly-Once-Support
Summary of changes:
- Exacty once semantics will be used if `delivery.semantics=EXACTLY_ONCE`, and data are published in the job (and not in the tasks).
- Created `CommitStep`, `CommitSequence`, `CommitSequenceStore` and their implementations.
- When exactly-once is used:
- `JobContext.commit()` will first construct a `CommitSequence`, persist the `CommitSequence` into the `CommitSequenceStore`, then execute the `CommitSequence`. If the `CommitSequence` is executed successfully, it will be deleted from the `CommitSequenceStore`.
- `DataPublisher` will not actually publish the data, instead, it will create a `CommitSequence`. This is because the data can only be published after the `CommitSequence` has been fully …
> Exactly-once POC

- gobblin-data-management/src/test/java/gobblin/data/management/retention/sql/SqlBasedRetentionPoc.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/sql/SqlUdfs.java
This is a POC for exploring SQL for retention management.
Dataset structure on HDFS will be loaded into an in-memory database (in the case Derby) by the DatasetFinders. The retention policies will be represented as SQL queries.
The POC has two tables 
- Database snapshots(dataset_path VARCHAR(255), name VARCHAR(255), path VARCHAR(255), ts TIMESTAMP, row_count bigint)
- Kafka daily partitioned data Daily_Partitions (dataset_path VARCHAR(255), path VARCHAR(255), ts TIMESTAMP)
1) Keep the last 2
SELECT * FROM Snapshots ORDER by ts desc LIMIT 2;
2) Keep partitions for last 2 years
SELECT * FROM Daily_Partitions WHERE Timestamp_diff(now, ts, "Days") <= 730 ;
UDFs are defined in SqlUdfs.java
@chavdar can you review?
> POC embedded sql for config-driven retention management

- build.gradle
When Gobblin is built behind a corporate firewall build times might be extremely long since
the gradle javadoc task doesn't pick up the proxy settings by default (see [GRADLE-1228](https://issues.gradle.org/browse/GRADLE-1228)) and timeouts
when fetching external javadocs.
By setting the ```java.net.useSystemProxies``` flag the system-wide proxy settings will be applied which seems to solve this issue.
> Javadoc task should pick up system proxy settings

- bin/gobblin-mapreduce.sh
- gobblin-distribution/build.gradle
Version of Gobblin dependencies are missing from gobblin-mapreduce.sh
During the creation of the Gobblin tarball the current project version is applied to the jars
however, the dependencies in the ```gobblin-mapreduce``` launcher script have no version.
This patch introduces a placeholer ```GOBBLIN_VERSION``` in the script which is substituted with the actual version during ```:gobblin-distribution:build```.
> Version of Gobblin dependencies are missing from gobblin-mapreduce.sh

- gobblin-distribution/build.gradle
ReplaceTokens replaces all occurences of a given token, but this is undesirable
when substituting `@project.version@` as it also replaces the value in the if condition
that checks for this placeholder, thus breaking the script.
> Fix broken Gobblin version resolution ( fixes #662 )

- gobblin-compaction/build.gradle
The `:gobblin-compaction:createCompactionTar` task looks for `gobblin-compaction.jar` instead of the 
versioned jar name.
> Gobblin-compaction tarball doesn't contain gobblin-compaction.jar

- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
> Ensure that parallel runner waits for the underlying tasks to finish

- bin/gobblin-mapreduce.sh
The script was failing with an `Error: java.lang.ClassNotFoundException: com.typesafe.config.ConfigFactory`. Adding the missing dependency to the list of included libraries solved the issue.
> Add missing jar to MR runner script

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableFile.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyDataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/CopyableFileTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/RecursiveCopyableDatasetTest.java
Issue:
Permissions were not being set correctly for newly generated directories in distcp. Root cause:
1. fs.mkdirs(Path, FsPermission) is affected by umask.
2. we were only setting permissions up to the dataset root. However, for patterns like `/foo/*/*`, where the dataset would be /foo/bar/dataset, we should also set permissions for /foo/bar and /foo/bar/dataset if these directories are newly created.
> Fix permissions for directories in distcp.

- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStore.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStoreFactory.java
- gobblin-core/src/main/java/gobblin/instrumented/fork/InstrumentedForkOperatorBase.java
- gobblin-core/src/main/java/gobblin/instrumented/writer/InstrumentedDataWriterBase.java
- gobblin-core/src/main/java/gobblin/source/workunit/MultiWorkUnitWeightedQueue.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CloseableFsCopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyEventSubmitterHelper.java
- gobblin-metrics/src/main/java/gobblin/metrics/Tag.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaAvroReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/metric/filter/MetricFilters.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ScheduledReporter.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/listeners/AbstractCloseableJobListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/listeners/CloseableJobListener.java
- gobblin-utility/src/main/java/gobblin/util/ClusterNameTags.java
- gobblin-utility/src/main/java/gobblin/util/FileListUtils.java
- gobblin-utility/src/main/java/gobblin/util/PathUtils.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemCache.java
- gobblin-utility/src/main/java/gobblin/util/PublisherUtils.java
- gobblin-utility/src/main/java/gobblin/util/io/StreamUtils.java
Remove @link tags from @see javadoc as they are not needed and result in a bunch of warnings like:
```
/home/travis/build/kadaan/gobblin/gobblin-utility/src/main/java/gobblin/util/PathUtils.java:52: warning - Tag @see:illegal character: "123" in "{@link Path}, {@link URI}"
```
> Remove @link tags from @see javadoc tags

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisherWithHiveRegistration.java
- gobblin-core/src/main/java/gobblin/publisher/HiveRegistrationPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/TimePartitionedDataPublisher.java
- gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveRegistrationPolicyBase.java
- gobblin-runtime/build.gradle
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
Added a `BaseDataPublisherWithHiveRegistration` which records the paths that need to be registered as a state property. After `JobContext` commits the data, it will retrieve the paths from the state and register them in Hive.
> Add inline Hive registration to Gobblin job

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanCompactionJobLauncher.java
- gobblin-compaction/src/main/java/gobblin/compaction/CompactorCreationException.java
- gobblin-compaction/src/main/java/gobblin/compaction/CompactorFactory.java
- gobblin-compaction/src/main/java/gobblin/compaction/ReflectionCompactorFactory.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/registration/HiveRegistrationCompactorListener.java
- gobblin-compaction/src/main/java/gobblin/compaction/listeners/CompactorListener.java
- gobblin-compaction/src/main/java/gobblin/compaction/listeners/CompactorListenerCreationException.java
- gobblin-compaction/src/main/java/gobblin/compaction/listeners/CompactorListenerFactory.java
- gobblin-compaction/src/main/java/gobblin/compaction/listeners/ReflectionCompactorListenerFactory.java
- gobblin-compaction/src/main/java/gobblin/compaction/listeners/SerialCompactorListener.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HivePartition.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegister.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegisterUtils.java
- gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveRegistrationPolicyBase.java
* Initial PR to discuss the approach for adding Hive-Reg for datasets produced by `MRCompactor`
* Registration is done in a `AfterCompactionAction` once compaction has completed
* The `AfterCompactionAction`s are configurable and are invoked in `JobRunnerExecutor.afterExecute`
> Reg compacted datasets in Hive

- gobblin-utility/src/main/java/gobblin/util/JobConfigurationUtils.java
Fixing bug reported in https://github.com/linkedin/gobblin/issues/702
* The `JobLauncherUtils.fileToProperties` method takes a path to a props file and reads it using a `FileSystem` object
* The `FileSystem` object is created by invoking `path.getFileSystem(Configuration)`
* It seems that if the `path` has no scheme + authority the default `FileSystem` is used
* The default fs when running locally is the local fs, the default fs when running on a cluster is the HDFS fs
* This can be confusing as the script expects the config file to be in different filesystems depending on where things are run
* Behavior is changed so if no scheme + authority is specified the local fs is used by default, if users expect the files to be on HDFS then they should set the scheme to `hdfs`
** This should be …
> Fixing CliOptions config file fs

- build.gradle
- gobblin-admin/build.gradle
- gobblin-api/build.gradle
- gobblin-azkaban/build.gradle
- gobblin-core/build.gradle
- gobblin-data-management/build.gradle
- gobblin-example/build.gradle
- gobblin-metastore/build.gradle
- gobblin-runtime/build.gradle
- gobblin-salesforce/build.gradle
- gobblin-scheduler/build.gradle
- gobblin-test-harness/build.gradle
- gobblin-utility/build.gradle
- gobblin-yarn/build.gradle
* Fixing option to skip specific test groups
* Currently, `travis/test.sh` skips tests with group `disabledOnTravis`, but this feature is not currently working, this PR should fix that
> Fixing skipTestGroup option

- gobblin-admin/src/main/java/gobblin/admin/AdminWebServer.java
- gobblin-admin/src/main/resources/static/index.html
- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-rest-service/gobblin-rest-server/src/main/java/gobblin/rest/JobExecutionInfoServer.java
- gobblin-scheduler/src/main/java/gobblin/scheduler/SchedulerDaemon.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
1. Allow specifying the host for the AdminWebServer in the configuration file.
1. Allow the JobExecutionInfoServer to advertise a different URI from what it is listening on 
1. Fix one of the cdn dependencies to use the https scheme so that it will work correctly when using SSL/TLS.
_Rational:_ This enables us to put the Admin UI and Rest service behind an nginx proxy
> More flexible Admin configuration

- gobblin-config-management/gobblin-config-client/src/main/java/gobblin/config/client/ConfigClientCache.java
- gobblin-config-management/gobblin-config-client/src/main/java/gobblin/config/client/ConfigStoreFactoryRegister.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStoreFactory.java
- gobblin-data-management/build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/retention/DatasetCleaner.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/DatasetCleanerJob.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/CleanableDatasetBase.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/ConfigurableCleanableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/CombineRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/DeleteNothingRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/NewestKRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/TimeBasedRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ConfigurableGlobDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/GlobCleanableDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ManagedCleanableDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ModificationTimeDatasetProfile.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/MultiCleanableDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/MultiDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/SnapshotDatasetProfile.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/DatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/DateTimeDatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/GlobModTimeDatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/WatermarkDatasetVersionFinder.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/ConfigurableCleanableDatasetTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/TimeBasedRetentionPolicyTest.java
- Add new DatasetCleaner that uses configClient to initialize DatasetFinders using importedBy tag
- Add new constructor to NewestK, Timebased and Combine policies. This constructor takes a typesafe Config and initializes the policy
Tested in simulate mode for a few datasets
@tuGithub and @ibuenros can you review?
> Use configClient to configure retention jobs

- build.gradle
- gobblin-config-management/gobblin-config-client/build.gradle
- gobblin-config-management/gobblin-config-core/build.gradle
- gobblin-metrics/build.gradle
- gobblin-rest-service/gobblin-rest-server/build.gradle
- gobblin-runtime/build.gradle
- gobblin-tunnel/build.gradle
@sahilTakiar Seems like a few projects were missed in your last PR.  Specifically, gobblin-tunnel which was causing travis runs to timeout.  Also saw a number of other excludes and moved them up to the root build as they seemed generic enough.
> Fixing skipTestGroup option (phase 2)

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileDownloader.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/SingleFileDownloader.java
Decouple downloading logic from extractor to allow users to download other filetypes like gzip, zip etc.
@sahilTakiar can you review?
> Allow downloading other filetypes in FileBasedExtractor

- gobblin-compaction/src/main/java/gobblin/compaction/hive/HdfsWriter.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-core/src/main/java/gobblin/commit/FsRenameCommitStep.java
- gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
* Fix for #740 
* Adds a overloaded `copyPath` method that allows writing data first to a temp file, and then committing the data using `renamePath`
* This should fix the problems with `FsStateStore.createAlias`
* Removed all direct usages of `FileUtil.copy` with `HadoopUtils.copyPath`
* Unit tests are coming
> Fix #740 for FsStateStore.createAlias and removing usage of FileUtil.copy

- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ContextAwareReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ScheduledReporter.java
- gobblin-metrics/src/test/java/gobblin/metrics/RootMetricContextTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/reporter/ScheduledReporterTest.java
@sahilTakiar The lombok @synchronized attribute isn't initialized before the super call is done, therefore we needed to replace it with the framework synchronized keyword.
> Fix for NullReferenceException cause by #739

- build.gradle
- gobblin-config-management/gobblin-config-core/build.gradle
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/ClasspathConfigSource.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/ConfigStream.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/Deployable.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/DeployableConfigSource.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/DeploymentConfig.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/FsDeploymentConfig.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/RollbackConfig.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/StoreDeployer.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStore.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStoreFactory.java
- Added `StoreDeployer` which copies config files in classpath to a `ConfigStore`
- Added a new interface called `Deployable` which has a `deploy()` and a `rollback()` method. A `ConfigStore` can implement a `Deployable`. The `StoreDeployer` initializes the right `deployable` `ConfigStore` using the `storeUri`. 
- The actual configs should be in its own package/project and in the classpath. This project will add gobblin-confg-management as a dependency. On calling `StoreDeployer.deploy()`, the configs in classpath are deployed
- Rollback is not yet implemented
If "test-root" is a resource in classpath and all resources (config files) under it needs to be deployed
**Structure in Classpath:**
test-root
&emsp;/data
&emsp;&emsp;/set1
&emsp;&emsp;&emsp;/main.conf
&emsp;/tag
&emsp;&emsp;/tag1 …
> Add HDFS config deployment tool

- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/deploy/FsDeploymentConfig.java
Findbugs reported redundant null check RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
> Fix findbugs warning

- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskExecutor.java
- gobblin-runtime/src/test/java/gobblin/runtime/TaskTest.java
* Fix for #776
* Change is to cancel all `Future`s launched by a `Task`
* A `Task` launches a `Future` for each `Fork` it runs, the PR ensures all the `Future`s are cancelled if any exception is thrown by the `Task`
> Fixing Fork + Task Retry Logic #776

- build.gradle
- gobblin-hive-registration/src/main/java/gobblin/hive/spec/SimpleHiveSpec.java
Since they need to be accessed in subclasses of `SimpleHiveSpec`.
> Make SimpleHiveSpec.Builder fields accessible via @Getter

- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnConfigurationKeys.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnLogSource.java
The new configuration key `gobblin.yarn.log.copier.max.file.size` will allow this to be configured with values such as: 100000, "10M", "512K", etc.  If it is not configured, the log files will not rotate.
Fixes: #814
> Enable the maximum log file size for Gobblin Yarn LogCopier to be configured

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/commit/FsRenameCommitStep.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/CommitSequencePublisher.java
- gobblin-core/src/main/java/gobblin/publisher/TimePartitionedDataPublisher.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
@sahilTakiar This can be enabled for data publishing by adding `data.publisher.overwrite.enabled=true` to the gobblin config.  Fixes #718 & #778
> Adds support to `HadoopUtils` for overwriting files

- build.gradle
@sahilTakiar Can you review this?  Also, it there a way to verify that the resultant javadocs are correct?
> Fix javadoc warnings by only adding linksOffline to projects that the current project depends on.

- .gitignore
- .travis.yml
- build.gradle
- gradle.properties
- gradle/scripts/jacoco-coveralls-support.gradle
- travis/build.sh
- travis/test.sh
* Adding support for running JaCoCo and integration with Coveralls
* JaCoCO can be run using `./gradlew test jacocoTestReport` which will generate JaCoCo reports for each individual Java subproject
* Output will be in `xml` and `html` format and can be found under `build/[subproject]/jacoco`
* Adding the Gradle Plugin `jacoco-full-report`
* Docs: https://github.com/palantir/gradle-jacoco-coverage and https://plugins.gradle.org/plugin/com.palantir.jacoco-coverage
* The default Gradle JaCoCo Plugin does not aggregate all reports into one single report, this is problematic as coveralls expects one aggregated report
* This plugin automatically does the aggregation and is configured in a similar way to the Gradle `jacoco` plugin
* It can be run using `./gradlew test jacocoFullReport`
* The …
> (#798) Adding JaCoCo and Coveralls support for code coverage analysis

- build.gradle
- gobblin-azkaban/build.gradle
- gobblin-compaction/build.gradle
- gobblin-core/build.gradle
- gobblin-distribution/build.gradle
- gobblin-example/build.gradle
- gobblin-hive-registration/build.gradle
- gobblin-runtime/build.gradle
- gobblin-utility/build.gradle
- gobblin-yarn/build.gradle
- gradle/scripts/hadoop-version.gradle
- settings.gradle
* Created a separate `.gradle` file for setting the `useHadoop2` property
* The property is now dynamically set based on the hadoop version specified
* The original behavior of `-PuseHadoop2` is preserved
* The only change is that if `-PhadoopVersion=` a 2.x.x version, then `useHadoop2` does not need to be specified also
* Fixes #825
> (#825) fixing and improving useHadoop2 and hadoopVersion gradle properties

- bin/gobblin-mapreduce.sh
- gobblin-runtime/build.gradle
Also added log4j-extras jar to the distribution, as client side logging uses `RollingFileAppender`.
> Bump dependencies in gobblin-mapreduce

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/CliMRJobLauncher.java
It seems to me that due to a regression of https://github.com/linkedin/gobblin/pull/808 the MRJobLauncher receives a null Configuration object which results in an NPE at `JobConfigurationUtils#putPropertiesIntoConfiguration`.
The instantiation of `MRJobLauncher` was moved from `run()` to the `CliMRJobLauncher`'s constructor, but here `getConf()` is null as `org.apache.hadoop.conf.Configured()` calls to `setConf(null)`. `org.apache.hadoop.util.ToolRunner#run` would set it, but it's too late as MRJobLauncher is instantiated
earlier.
> Null Configuration is passed to MRJobLauncher

- gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveRegistrationPolicyBase.java
* Making the constructor for `HiveRegistrationPolicyBase` public so that it can be initialized in other classes
* Otherwise `HiveRegistrationPolicyBase.getPolicy(state)` throws `NoSuchMethodException: No such accessible constructor on object`
> Making HiveRegistrationPolicyBase constructor public

- gobblin-api/src/main/java/gobblin/dataset/IterableDatasetFinder.java
- gobblin-api/src/main/java/gobblin/dataset/IterableDatasetFinderImpl.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/dataset/DatasetUtils.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/finder/DatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ConfigurableGlobDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ModificationTimeDatasetProfile.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/MultiDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/RawDatasetProfile.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/SnapshotDatasetProfile.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/TrackingDatasetProfile.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/TestCopyableDatasetFinder.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/TestCopyablePartitionableDatasedFinder.java
- gobblin-utility/src/main/java/gobblin/util/executors/IteratorExecutor.java
- gobblin-utility/src/main/java/gobblin/util/iterators/InterruptibleIterator.java
- gobblin-utility/src/test/java/gobblin/util/executors/IteratorExecutorTest.java
This PR enables streaming of datasets to distcp using an iterator. It implements an `IterableDatasetFinder` that returns datasets as an iterator. Distcp only consumes as many datasets at a time as copy listing threads are available.
This allows controlling memory footprint (ie datasets are created on demand when needed, whereas before, all datasets needed to exist in memory at the same time).
> Stream datasets to distcp.

- gobblin-api/src/main/java/gobblin/annotation/Alias.java
- gobblin-api/src/main/java/gobblin/util/ClassAliasResolver.java
- gobblin-api/src/test/java/gobblin/util/ClassAliasResolverTest.java
- gobblin-audit/build.gradle
- gobblin-audit/src/main/java/gobblin/audit/values/auditor/ValueAuditGenerator.java
- gobblin-audit/src/main/java/gobblin/audit/values/auditor/ValueAuditRuntimeMetadata.java
- gobblin-audit/src/main/java/gobblin/audit/values/policy/column/AbstractColumnProjectionPolicy.java
- gobblin-audit/src/main/java/gobblin/audit/values/policy/column/ColumnProjectionPolicy.java
- gobblin-audit/src/main/java/gobblin/audit/values/policy/column/DefaultColumnProjectionPolicyFactory.java
- gobblin-audit/src/main/java/gobblin/audit/values/policy/column/ProjectAllColumnProjectionPolicy.java
- gobblin-audit/src/main/java/gobblin/audit/values/policy/row/AbstractRowSelectionPolicy.java
- gobblin-audit/src/main/java/gobblin/audit/values/policy/row/DefaultRowSelectionPolicyFactory.java
- gobblin-audit/src/main/java/gobblin/audit/values/policy/row/RowSelectionPolicy.java
- gobblin-audit/src/main/java/gobblin/audit/values/policy/row/SelectAllRowSelectionPolicy.java
- gobblin-audit/src/main/java/gobblin/audit/values/sink/AuditSink.java
- gobblin-audit/src/main/java/gobblin/audit/values/sink/DefaultAuditSinkFactory.java
- gobblin-audit/src/main/java/gobblin/audit/values/sink/FsAuditSink.java
- gobblin-audit/src/test/java/gobblin/audit/values/FsAuditSinkTest.java
- gobblin-audit/src/test/java/gobblin/audit/values/MockSink.java
- gobblin-audit/src/test/java/gobblin/audit/values/ValueAuditGeneratorTest.java
- gobblin-audit/src/test/java/gobblin/audit/values/ValueAuditRuntimeMetadataTest.java
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
- settings.gradle
Added base interfaces for value auditing. The pr mainly has interfaces for 
- `RowSelectionPolicy` - An interface to decide if a row needs to be audited
- `ColomnProjectionPolicy` - An interface that projects certain columns/fields of an input {@link GenericRecord} to generate a new {@link GenericRecord} that can be audited.
- `AuditSink` - An interface for persisting value audits
- `ValueAuditGenerator` - The class that implements value based auditing. The class captures the values of certain columns from the rows in the dataset using the {@link ColumnProjectionPolicy}. This is done for every row or for a sample of the rows as defined by the {@link RowSelectionPolicy}
- The module that drives auditing will create an instance of `ValueAuditGenerator` for each avro file being written and …
> Base interfaces for value auditing

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/SerializationUtils.java
This addresses an issue with https://github.com/linkedin/gobblin/pull/910 . If the replication factor > dfs.replication.max , then it won't be changed. This fix attempts to use that property when setting replication.
@ibuenros @ydai1124 Can you review?
> Use dfs.replication.max in job.state replication factor

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
Escaping colons in extract table names to avoid creating invalid HDFS paths (e.g. in gobblin.util.WriterUtils.getDefaultWriterFilePath)
@ibuenros Can you review?
> Escaping colons in extract table names

- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
Refactor JobContext.commit() in preparation for parallelization for the commit logic:
* Refactor the commit logic from the for loop into a separate method processDatasetCommit()
* Refactor the check for support for failed WorkUnit handling into a separte method checkForUnpublishedWUHandling .
* Move commitSequenceBuilder from a instance variable to a local variable in processDatasetCommit().
> Simple refactoring of JobContext.commit()

- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/MultiVersionCleanableDatasetBase.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/SnapshotDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/CombineRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/NewestKRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/util/test/RetentionTestDataGenerator.java
- gobblin-data-management/src/main/java/gobblin/util/test/RetentionTestHelper.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/NewestKRetentionPolicyTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/integration/RetentionIntegrationTest.java
- Fix some generics which cause LiCleanableDataset to fail
- Move some code out of `src/test/java/gobblin/data/management/retention/integration/RetentionIntegrationTest.java
` to `gobblin-data-management/src/main/java/gobblin/util/test/RetentionTestHelper.java`
> use new DatasetVersion in CombinePolicy

- gobblin-data-management/src/main/java/gobblin/data/management/policy/NewestKSelectionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/NonNewestKSelectionPolicy.java
* With this approach, one does not have to cast to `FileSystemDatasetVersion` when using `NewestKSelectionPolicy` - any class that extends `FileSystemDatasetVersion` (such as `TimestampedDatasetVersion`) can be used
> Make NewestKSelectionPolicy use Java Generics instead of FileSystemDatasetVersion

- gobblin-config-management/gobblin-config-client/src/test/java/gobblin/config/client/TestConfigClient.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/ConfigStoreBackedValueInspector.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStore.java
- gobblin-config-management/gobblin-config-core/src/test/java/gobblin/config/TestEnvironment.java
- gobblin-config-management/gobblin-config-core/src/test/java/gobblin/config/common/impl/TestConfigStoreValueInspector.java
- gobblin-config-management/gobblin-config-core/src/test/java/gobblin/config/common/impl/TestInMemoryTopology.java
- gobblin-config-management/gobblin-config-core/src/test/java/gobblin/config/store/hdfs/SimpleHdfsConfigStoreTest.java
- Added support to resolve system and environment variables in config management. Both in `main.conf` and `includes.conf`
- `Typesafe Config` expects the system/env key to be in the format `${?sys.prop.key}`. Note that `?` signifies system/env variables.
- Added support to resolve system/env variables in `includes.conf`. Since `includes.conf` is in plain text with one include per line, it can not be parsed as `TypeSafe Config`. To workaround that we build a `TypeSafe Config` objects with key `includes` and value a list of include paths. This config object is then resolved with fallback on system/env properties.
E.g. If the includes.conf file looks like
<pre>
/path/to/tag1
/path/to/${?sys.key1}
</pre>
It gets loaded in memory as a `TypeSafe Config` object, 
<pre>
includes = [/path/to/tag1, …
> Substitution of system and env variable in config management

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-docs/case-studies/Kafka-HDFS-Ingestion.md
I have been diving into Gobblin and found out there was an additional configuration key that was not documented which enables having topic-specific configuration.
The change includes the documentation already available in [KafkaSource](https://github.com/linkedin/gobblin/blob/master/gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java#L91) 
Closes #936.
> Add documentation for topic specific partitioning configuration

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/NoopDatasetStateStore.java
This PR adds an option to disable state store. (Default is state store is enabled). This is useful when jobs don't use the state store, saving the load of reading / writing it. It also provides a workaround for a memory issue when extracts change name often, as this would cause Gobblin to load previous metadata for many runs, causing OOM.
> Allow disabling state store.

- gobblin-data-management/build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/copy/RecursivePathFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveCopyEntityHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveLocationDescriptor.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/predicates/RegistrationTimeSkipPredicate.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/predicates/RootDirectoryModtimeSkipPredicate.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/predicates/RegistrationTimeSkipPredicateTest.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegistrationUnitComparator.java
- gobblin-hive-registration/src/test/java/gobblin/hive/HiveRegistrationUnitComparatorTest.java
- gobblin-utility/src/main/java/gobblin/util/FileListUtils.java
- gobblin-utility/src/main/java/gobblin/util/filters/AndPathFilter.java
This PR adds metadata to the Hive registration in Distcp:
* `registerer`: specifies the entity that registered this Hive table
* `registrationGenerationTime`: specifies the time in millis at which the registration was performed
The data is used for a fast partition skip filter which skips any partitions for which `registrationGenerationTime` is newer than the modtime of the source location.
Also adds an optional hidden file filter to recursive Hive copying.
> Distcp hive registration metadata

- gobblin-compaction/src/main/java/gobblin/hive/util/HiveJdbcConnector.java
When running Hive compaction from command line the following exception is thrown:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/DistributedFileSystem$12
at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:634)
at gobblin.compaction.hive.HdfsWriter.delete(HdfsWriter.java:50)
at gobblin.compaction.hive.AvroExternalTable.deleteTmpFilesIfNeeded(AvroExternalTable.java:208)
at gobblin.compaction.hive.SerialCompactor.deleteTmpFiles(SerialCompactor.java:340)
at gobblin.compaction.hive.SerialCompactor.compact(SerialCompactor.java:127)
at gobblin.compaction.hive.CompactionRunner.compact(CompactionRunner.java:109)
at gobblin.compaction.hive.CompactionRunner.main(CompactionRunner.java:94)
Caused by: …
```
> Hive compactor: Fix ClassNotFoundException in ShutdownHookManager

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyContext.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveCopyEntityHelper.java
Generating a new `FileSystem` per work unit is very costly (even though Hadoop caches them). This PR stops doing that. 
Also write out cache statistics after creating work units for distcp.
> Copyable file performance

- bin/gobblin-compaction.sh
- conf/log4j-compaction.xml
- gobblin-compaction/build.gradle
- gobblin-compaction/src/main/java/gobblin/compaction/CliOptions.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/CompactionRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactionRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-utility/src/main/java/gobblin/util/JobConfigurationUtils.java
Currently the execution of the Hive and MR-based compactors is not out of the box, needs extra work:
- there's no implementation for MR compaction for CLI execution
- Hive compactor is a standalone package that needs to be built separately
This PR tries to fix these issues. A new shell script **bin/gobblin-compaction.sh** was added with which one can execute both Hive and MR-based compaction jobs from the CLI.
```
Usage: gobblin-compaction.sh [OPTION] --type <compaction type: hive or mr> --conf <compaction configuration file>
Where OPTION can be:
--projectversion <version>    Gobblin version to be used. If set, overrides the distribution build version
--logdir <log dir>            Gobblin's log directory: if not set, taken from ${GOBBLIN_LOG_DIR} if present. 
--help …
```
> Unified way to execute Hive and MR-based compaction jobs

- gobblin-api/src/main/java/gobblin/configuration/ImmutableWorkUnitState.java
- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-api/src/main/java/gobblin/source/workunit/Extract.java
- gobblin-api/src/main/java/gobblin/source/workunit/ImmutableWorkUnit.java
- gobblin-core/src/main/java/gobblin/publisher/HiveRegistrationPublisher.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/AbstractSource.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/FsDatasetStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskStateCollectorService.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/DatasetStateStoreTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/FsDatasetStateStoreTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
- gobblin-runtime/src/test/java/gobblin/runtime/commit/CommitSequenceTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/commit/FsCommitSequenceStoreTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- gobblin-utility/src/main/java/gobblin/util/SerializationUtils.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixTask.java
This is a solution to #881.
Summary:
- Each `WorkUnitState`/`TaskState` now contains a `JobState` reference, rather than a copy of all properties in `JobState`. `WorkUnitState.getProp()` will first look for the property in its own properties, then in its `WorkUnit`, then in its `JobState`.
- `DatasetState` no longer contains properties in `JobState`, and no longer supports `setProp` or `getProp` methods (will throw `UnsupportedOperationException`). A `DatasetState` can only contain a few specific properties such as `dataset.urn`, and they are accessed via specific setter and getter methods (e.g., `setDatasetUrn()` and `getDatasetUrn()`).
- The rationale is the following: a `DatasetState` is created in the driver after the job is done. At this point there shouldn’t be a need to look for, …
> Separate jobstate from taskstate and datasetstate

- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStore.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStoreFactory.java
- gobblin-config-management/gobblin-config-core/src/main/resources/reference.conf
- gobblin-config-management/gobblin-config-core/src/test/java/gobblin/config/store/hdfs/SimpleHdfsConfigureStoreFactoryTest.java
Changes:
- Add a default_store_uri option to specify the default store
- Add validation in the constructor if the default config root exists
- Make changes to support use of any Hadoop FS rather than just HDFS.
- Add some unit tests.
@tuGithub @pcadabam Can you review?
> Make the default store for SimpleHDFSConfigStoreFactory configurable

- build.gradle
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyCombineFileRecordReader.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/entities/CommitStepCopyEntity.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveCopyEntityHelper.java
- gobblin-utility/src/main/java/gobblin/util/io/SeekableFSInputStream.java
- ligradle/findbugs/findbugsExclude.xml
* Related to https://github.com/linkedin/gobblin/pull/968
* Resolving the rest of the FindBugs warnings and setting the build to fail if any new FindBugs warnings are introduced
* Most changes are minor, except for the following list:
* `HiveCopyEntityHelper` had a dead local store warning because `stepPriority++` wasn't doing anything
* `SeekableFSInputStream` doesn't seem to implement `seek` properly; its also possible for `InputStream.skip` isn't guaranteed to skip the specified number of bytes
> Fixing rest of findbugs warnings, and setting findbugs to fail the build on new warnings

- gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java
This is required by the distributed cache: http://stackoverflow.com/questions/23903113/mapreduce-error-usergroupinformation-priviledgedactionexception
> Set explicit 755 permissions to state store

- gobblin-hive-registration/src/main/java/gobblin/hive/HiveMetaStoreClientFactory.java
Relate github issue:  https://github.com/linkedin/gobblin/issues/1033
> Hive metastore initialization should support empty HCat uri ie default to platform defaults

- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSConfigStore.java
- gobblin-config-management/gobblin-config-core/src/test/java/gobblin/config/store/hdfs/SimpleHdfsConfigStoreTest.java
The includes returned are used to build a fallback chain.
With the natural order, if a key found in the first include it is not be overriden by the next include.
By reversing the list, the Typesafe fallbacks are constructed bottom up.
> Fix includes order

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryUtils.java
Updated default orc row index stride to a higher number based on internal experimentations. A bit of description around it: https://streever.atlassian.net/wiki/display/HADOOP/Optimizing+ORC+Files+for+Query+Performance
> Updated default orc row index stride to a higher number

- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
This PR reduces the size of job.state file by not serializing all of the tasks there, as the mappers read their tasks from separate files either way. This reduces required memory for the mappers.
> MR launcher does not write tasks to the jobstate file in HDFS.

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/AvroSchemaManager.java
Enable AvroSchemaManager to read schema from Kafka schema registry if the Uri scheme is http(s) or fall back to HDFS
> Enable AvroSchemaManager to read schema from Kafka schema registry

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryUtils.java
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/arrayWithinRecordWithinArrayWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/optionWithinOptionWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinOptionWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinRecordWithinRecord.dml
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinRecordWithinRecord_nested.ddl
Escape Hive queries column, partition and tables to avoid pitfall against users making use of Hive reserver words for column / partition names
> Escape Hive queries column, partition and tables

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/HiveAvroToOrcConverter.java
Disable flattening for complex types other than nested records and union, since ORC does not support predicate pushdown for complex types, so even if we flatten nested structure within a map or array - it will not help and complicates conversion process.
> Disable flattening for complex types other than nested records and union

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/publisher/DataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyDataPublisher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/SafeDatasetCommit.java
- gobblin-runtime/src/test/java/gobblin/runtime/DummyJobContext.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobContextTest.java
- gobblin-utility/src/main/java/gobblin/util/Either.java
- gobblin-utility/src/main/java/gobblin/util/executors/IteratorExecutor.java
Guide to this PR:
* Created a class `SafeDatasetCommit`. Refactored a lot of the commit logic from `JobContext` to this class.
* `JobContext` creates an `IteratorExecutor` to execute dataset commits in parallel.
* Added a `isThreadSafe` method to `DataPublisher`. If this is false (default), Gobblin will automatically fall back to serial commit even if user choses parallel commit.
* Added a unit test to ensure `JobContext` handles publisher failure semantics correctly.
> Parallelize commit rebased

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/BackfillHiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/util/HiveSourceUtils.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/HiveSourceTest.java
A backfill source will be used to re run avro to orc conversion for all partitions starting from ```lookBackDays```
> Add a backfill hive source that does not check watermarks

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveTargetPathHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/hive/HiveConfigClientUtils.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDatasetTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/hive/HiveDatasetFinderTest.java
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
1. Added ```ConvertibleHiveDataset``` used in conversion jobs
2. Added support for reading dataset configs from gobblin config store if available. If config store is not configured, job configs with a prefix are used as dataset config.  By default the prefix is empty string. But by setting ```hive.dataset.configPrefix``` only configs with this prefix is passed to the ```HiveDataset```'s``` ```datasetConfig```.<br>
**Some Example**<br>
**a. Retention jobs**
<pre>
hive.dataset.configPrefix=hive.dataset.retention
hive.dataset.retention.is.blacklisted=true
hive.dataset.retention.selection.policy=blah
</pre>
```CleanableHiveDataset``` will be initialized with
<pre>
is.blacklisted=true
selection.policy=blah
</pre>
**b. Avro to Orc Conversion jobs**
<pre> …
```
> Add ConvertibleHiveDataset and config store support to HiveDatasetFinder

- conf/gobblin-standalone.properties
- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanGobblinDaemon.java
- gobblin-runtime/src/main/java/gobblin/scheduler/JobScheduler.java
- gobblin-runtime/src/main/java/gobblin/scheduler/SchedulerDaemon.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
- gobblin-utility/src/test/java/gobblin/util/SchedulerUtilsTest.java
- Added new class `AzkabanGobblinDaemon` for deployment on Azkaban .
- Rewrite the original `loadJobConfig` and related method into general form which is compatible for general file system. 
---
- Temporarily remove some parts of SchedulerUtilsTest.java as there's also no counterpart in SchedulerUtils.java(for general file system, most of them are monitor-related), which leads to decrease in the coverage report.
> extension of loading config file from general file system

- build.gradle
- gobblin-core/build.gradle
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/ConfluentKafkaSchemaRegistry.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaDeserializerExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaDeserializerSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaGsonDeserializer.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleJsonExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/SimpleKafkaSchemaRegistry.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/kafka/ConfluentKafkaSchemaRegistryTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/kafka/KafkaDeserializerExtractorTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/kafka/KafkaGsonDeserializerTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/kafka/SimpleKafkaSchemaRegistryTest.java
- gobblin-docs/case-studies/Kafka-HDFS-Ingestion.md
- gobblin-utility/src/main/java/gobblin/util/PropertiesUtils.java
* Adding integration with Confluent's Schema Registry - https://github.com/confluentinc/schema-registry
* `ConfluentKafkaSchemaRegistry.java`
* Created `KafkaDeserializerExtractor` which wraps Kafka's `Deserializer` API
* Kafka's `Deserializer` interface provides a generic way for converting `byte[]` to Java Objects
* The `KafkaDeserializerExtractor` takes in a path to a fully qualified implementation of `Deserializer` and uses it to convert they `byte[]` into a Java Object
* It has built in support for a few known `Deserializer`s including Confluents `KafkaAvroDeserializer` and `KafkaJsonDeserializer`
* Created a `KafkaGsonDeserializer` that converts `byte[]` to `JsonElement`s
* Updated the `gobblin-docs/case-studies/Kafka-HDFS-Ingestion.md` to document all of these new features
* Unit …
> Integration with Confluent Schema Registry, Confluent Deserializers, and Kafka Deserializers

- gobblin-docs/js/extra.js
- mkdocs.yml
Fixes the search bar on the Gobblin documentation page, so that it actually works.
Heavily based on the following commit: https://github.com/nodemcu/nodemcu-firmware/commit/7dd89dd15ef993c9740ba4d4361e6be8edd1284b
Can someone review?
> Fixing search for Gobblin ReadTheDocs

- gobblin-data-management/build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryUtils.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryUtilsTest.java
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/arrayWithinRecordWithinArrayWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/optionWithinOptionWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinOptionWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinRecordWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema.json
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_evolution_disabled.ddl
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_evolution_disabled.dml
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_evolution_enabled.ddl
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_evolution_enabled.dml
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_lineage_missing.ddl
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_lineage_missing.dml
- gobblin-data-management/src/test/resources/hiveConverterTest/recordWithinRecordWithinRecord_flattened.ddl
- gobblin-data-management/src/test/resources/hiveConverterTest/recordWithinRecordWithinRecord_flattened.dml
- gobblin-data-management/src/test/resources/hiveConverterTest/recordWithinRecordWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/hiveConverterTest/recordWithinRecordWithinRecord_nested.dml
Adding support for:
- Schema evolution: Support to evolve destination ORC table for changes in source table schema (Hive / ORC does not support evolution yet, this is being added with hope that Hive / ORC will soon support evolution)
- Staging: Support to first stage converted data in a staging table before publishing / committing it to the final table
- Selective column projection: To counter against schema evolution on source hive table, this feature would help selectively project columns from source that are in destination / ORC table
> Support for schema evolution, staging, selective column projection and compatibility check for Avro to ORC

- README.md
Very minor text formatting fix for README.md (added a space). Self approving
> Minor text formatting fix for README.md

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/flattenedWithRowLimit.dml
Added limit clause to Hive query generation to enable conversion on sample data size for validation purposes
With this addition, to run a job that runs sampled conversion on multiple datasets: 
1. Use BackfillHiveSource
2. Configure rest of Avro to ORC conversion job as you normally would 
(by specifying dataset whitelist, etc)
3. Set rowLimit to a low number (say 1)
4. Run the job
> Added limit clause to Hive query generation to enable conversion validation of sample subset

- gobblin-compaction/src/main/java/gobblin/hive/util/HiveJdbcConnector.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/events/EventConstants.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/provider/UpdateProviderFactory.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveValidationQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/validation/ValidationJobTest.java
Added Azkaban job that can validate conversion results by comparing source and target Hive tables: 
1. Job first discovers all the tables configured for conversion 
2. Then it checks if any conversion was performed on that source table (by checking the update time)
3. If there are any new conversions, the job generates query to compare the two tables or partition (source and destination)
4. The job finishes off by reporting the result of comparison of all datasets converted recently
> Added Azkaban job that can validate conversion result by comparing source and target Hive tables

- gobblin-docs/project/Talks-and-Tech-Blogs.md
Made order of presentations chronological in talks-and-tech-blogs wiki page. Minor change, self approving.
> Made order of presentations chronological in talks-and-tech-blogs wiki page

- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/CleanableHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/FsCleanableHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/MultiVersionCleanableDatasetBase.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/finder/CleanableHiveDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/HiveDatasetVersion.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/TimestampedHiveDatasetVersion.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/finder/AbstractHiveDatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/finder/DatePartitionHiveVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/util/test/RetentionTestHelper.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/LocalHiveMetastoreTestUtils.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/CleanableDatasetBaseTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/FsCleanableHelperTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/integration/HiveRetentionTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/integration/RetentionIntegrationTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/version/finder/DatePartitionedHiveVersionFinderTest.java
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testHiveTimeBasedRetention/hive-retention.job
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testHiveTimeBasedRetention/jobProps.properties
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testHiveTimeBasedRetention/selection.conf
- Added time based retention for hive partitions.
- In the context of hive retention a ```Dataset``` is a ```Table``` and a ```DatasetVersion``` is a ```Partition```
- ```AbstractHiveDatasetVersionFinder``` and its subclasses can be used outside of retention as well.
- Moved some common logic from ```MultiVersionCleanableDatasetBase``` to ```FsCleanableHelper``` as it needs to be used by the ```CleanableHiveDataset``` too.
- Added tests
@ydai1124 and @ibuenros can you review?
> Hive Based Retention

- gobblin-core/src/main/java/gobblin/converter/initializer/AvroToJdbcEntryConverterInitializer.java
- gobblin-core/src/main/java/gobblin/publisher/JdbcPublisher.java
- gobblin-core/src/main/java/gobblin/writer/commands/JdbcWriterCommands.java
- gobblin-core/src/main/java/gobblin/writer/commands/MySqlWriterCommands.java
- gobblin-core/src/main/java/gobblin/writer/initializer/JdbcWriterInitializer.java
- gobblin-core/src/test/java/gobblin/converter/jdbc/AvroToJdbcEntryConverterTest.java
- gobblin-core/src/test/java/gobblin/writer/jdbc/JdbcPublisherTest.java
- gobblin-core/src/test/java/gobblin/writer/jdbc/JdbcWriterCommandsTest.java
- gobblin-core/src/test/java/gobblin/writer/jdbc/JdbcWriterInitializerTest.java
- Bug fix on data type mapping to use java.sql.Timestamp on MySQL's DATETIME data type.
- Bug fix on SQL statements. Added database check in "where" clause on SQL statements. Previously, it was depending on either default database or the connection.
Passed unit test and integration test.
> JDBCWriter. Bug fix on SQL statements. Bug fix on data type mapping.

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
Made Hive table rename backward compatible with Hive v0.13
In Hive v0.13, Hive does not support fully qualified Hive table names such as db.table for table rename. So, changed publish commands to specify 'use dbName' as a precursor to the rename
> Made Hive table rename backward compatible with Hive v0.13

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
Made changes to handle Hive-6129 (inverted exchange partition bug) and corresponding support for backward incompatible changes in Hive: 
- Hive-4095 introduced the partition exchange feature for first time in v0.12
- HIVE-6129 found out that the advertised behavior was inverse (source was being treated as target and vice-versa) and a backward incompatible fix was introduced
So, changed Gobblin code to handle all versions of Hive by taking hint from config about the Hive version and creating the correct corresponding Hive statement 
Also, added a few javadocs
> Made changes to handle Hive-6129 (inverted exchange partition bug) and corresponding support for backward incompatible changes in Hive

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
If a partition is being exchanged into a table but the data directory location for the partition already exists, Hive moves data within a sub-directory of it rather than cleanly overwriting it.
More details here: HIVE-11194
So, adding a pre publish hook to cleanup the existing directory (if any) of an existing partition in destination table before issuing exchange partition from staging to destination.
> Fix for HIVE-11194: exchange partition does not work properly if data directory for destination partitions pre-exists

- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/TeradataExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/TeradataSource.java
Do not required extended access rights  - schema generated from generic JDBC ResultSetMetaData. Works with views and custom queries  (use source.querybased.is.metadata.column.check.enabled=false for derived columns). Tested against Teradata version 13 and 15.
> Teradata JDBC Extractor and Source

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/entities/QueryBasedHivePublishEntity.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveValidationQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveAvroToOrcConverterTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/predicates/RegistrationTimeSkipPredicateTest.java
Change Hive Avro to ORC publish to use Gobblin constructs instead of Hive exchange partition query: 
- Hive exchange partition query was being used to move partitions from staging to final table
- However, this can fail queries in flight because the current model overwrites data location
- To overcome this, we have changed the publish module to use Gobblin constructs 
New publish works as follows: 
- Staging table partition is created in a directory under Gobblin control (dir name prefix is derived from source partition location string; such as if partitionDir.prefixLocationHint is set to 'hourly,daily' and 'hourly' exists as substring in source partition path, then 'hourly' string is prefixed to dir name of the partition) 
- At the time of publish, first the staging partition directory …
> Change Hive Avro to ORC publish to use Gobblin constructs instead of Hive exchange partition query

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
Renamed partitionDir.prefixLocationHint to source.dataPathIdentifier to be more consistent with naming across Hive data conversion and added more docs. 
Minor changes, self approving.
> Renamed partitionDir.prefixLocationHint to source.dataPathIdentifier to be more consistent with naming across Hive data conversion

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/HiveSourceTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java
Changes: 
- Add support for distcp-ng registration time while running isOlderThanLookback check to counter cases where createTime is not set in Partition metadata
- Added tests for Hive type evolution compatibility check
- Minor code refactoring to make naming convention uniform in Avro to ORC converter and code cleanup
Trivial changes / tested. self approving.
> Support for distcp-ng registration time in isOlderThanLookback check and minor refactoring

- build.gradle
- defaultEnvironment.gradle
- gobblin-compaction/src/test/java/gobblin/compaction/mapreduce/MRCompactorJobRunnerFilenameRecordCountProviderTest.java
- gobblin-rest-service/gobblin-rest-server/build.gradle
- gobblin-rest-service/gobblin-rest-server/src/test/resources/gobblin-rest-server-test-log4j.properties
* We've been seeing gobblin-core failures on Travis. It seems related to aws-java-sdk-1.7.4 being needed by hadoop-aws . It seems like the artifact was being pulled from jcenter rather than Maven Central and there might be an issue with the former. I've reordered the repositoriy registration so Maven comes first.
* I think I've finally figured out an issue with intermittently failing :gobblin-compaction:test . MRCompactorJobRunnerFilenameRecordCountProviderTest was creating a directory under source code tree which was confusing gradle. Moved the directory to /tmp/
* Added log4j configuration for gobblin-rest-server tests to write test output to /tmp/gobblin-rest-server-test.log . Hopefully that helps with intermittent failures.
@abti can you review ?
> Make sure maven central repo is first; bug fixes

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/arrayWithinRecordWithinArrayWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/flattenedWithRowLimit.dml
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/optionWithinOptionWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinOptionWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinRecordWithinRecord.dml
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinRecordWithinRecord_flattened.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinRecordWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_evolution_disabled.ddl
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_evolution_disabled.dml
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_evolution_enabled.ddl
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_evolution_enabled.dml
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_lineage_missing.ddl
- gobblin-data-management/src/test/resources/avroToOrcSchemaEvolutionTest/source_schema_lineage_missing.dml
- gobblin-data-management/src/test/resources/hiveConverterTest/recordWithinRecordWithinRecord_flattened.ddl
- gobblin-data-management/src/test/resources/hiveConverterTest/recordWithinRecordWithinRecord_flattened.dml
- gobblin-data-management/src/test/resources/hiveConverterTest/recordWithinRecordWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/hiveConverterTest/recordWithinRecordWithinRecord_nested.dml
Changed Hive validation to make it compatible with old Hive version with auth turned on, and Hive query generation compile with new Hive version:
- Changed Hive conversion validation job to make use of filesystem instead of resultset to make it work with ancient Hive versions that do not play with delegation tokens refer: HIVE-14015
- Tests to check if Hive queries are being generated with backticks at correct places, to compile with new Hive versions
- Changed Hive query generator to apply backticks as restricted by new Hive versions while maintaining backward compatibility
> Changed Hive validation to make it compatible with old Hive version with auth turned on, and Hive query generation compile with new Hive version

- gobblin-runtime/src/main/java/gobblin/runtime/api/GobblinInstanceLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionState.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionStatus.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpec.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance_driver/DefaultGobblinInstanceDriverImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/ImmediateJobSpecScheduler.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/DefaultJobCatalogListenerImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/DefaultJobExecutionStateListenerImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/DefaultJobSpecScheduleImpl.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance_driver/TestDefaultGobblinInstanceDriverImpl.java
- gobblin-runtime/src/test/java/gobblin/runtime/scheduler/TestImmediateJobSpecScheduler.java
Changes:
- A skeleton GobblinInstanceDriver implementation -- DefaultGobblinInstanceDriverImpl
- ImmediateJobSpecScheduler: Simple JobSpecScheduler implementation that puts the tasks immediately in a separate thread.
- Some default listener implementations
- Fix FindBugs in new launcher APIs
- Unit tests
@ibuenros @autumnust Can you review?
> Initial commit for a skeleton GobblinInstanceDriver

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/BackfillHiveSource.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/BackfillHiveSourceTest.java
Simple rename of ```initialize``` method to ```initBackfillHiveSource``` since the name conflicts with method in super class
> Rename init method in BackfillHiveSource

- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/ConfigurableCleanableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/MultiVersionCleanableDatasetBase.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/ConfigurableCleanableDatasetTest.java
```ConfigurableCleanableDataset``` was calling the incorrect super constructor ```super(fs, jobProps, log)``` instead of ```super(fs, jobProps, config, log)```
When retention job is configured through config store, each dataset can be blacklisted by setting ```gobblin.retention.is.blacklisted=true```. Since the wrong constructor was being called, this value was never passed to the super class. Hence the dataset was not blacklisted.
@chavdar can you review?
> Bug fix - Retention does not blacklist dataset

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/ConfluentKafkaSchemaRegistry.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/kafka/ConfluentKafkaSchemaRegistryTest.java
Currently only the name of the Kafka topic is used to retrieve the schema from the registry, however schemas are usually registered under `topicName-value` or `topicName-key`. 
Thus the schema will never be retrieved from the registry and the following exception is thrown:
```
...
Caused by: gobblin.metrics.kafka.SchemaRegistryException:
io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException:
Subject not found.; error code: 40401
...
```
This PR adds a new config parameter `kafka.schema_registry.confluent.schema.name.suffix `which defaults to `-value`. This suffix will be used along with the topic name to query the registry.
> Make topic suffix configurable for lookup in Confluent Schema Registry

- gobblin-example/src/main/resources/wikipedia-console.pull
Console writer doesn't expect to work with a partitioner. Will add this feature in a future PR if needed.
> Fixing console writer example

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaWrapper.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/kafka/KafkaWrapperTest.java
Global configuration for Kafka consumer for Kafka extracts. 
@hibikir This generalizes the proposal in https://github.com/linkedin/gobblin/pull/1059/
While making the changes, I also discovered that the socketTimeout was being set to the same value as the fetchTimeout in the old code. This resulted in intermittent failures in Kafka extraction when the amount of data in the source topic is less than the default fetchBytes. This was also commonly reported on the mailing lists by users trying out Kafka ingest locally. 
@abti, @ibuenros : Please review!
> Making Kafka consumer configurable for Kafka extract

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/GobblinWorkUnitsInputFormat.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
Implements an `InputFormat` for Gobblin that does not require a single file to be read by all mappers.
Fixes the following issue:
Gobblin MR writes a file with extension *.wulist containing a list of *.wu and *.mwu files for mappers to process. Each of these mappers must read this single file, which can cause slowness in HDFS or affect datanodes.
> Refactored MR mode to use GobblinInputFormat.

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/extractor/HiveConvertExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/provider/UpdateNotFoundException.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/watermarker/HiveSourceWatermarker.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/watermarker/HiveSourceWatermarkerFactory.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/watermarker/MultiKeyValueLongWatermark.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/watermarker/PartitionLevelWatermarker.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/watermarker/TableLevelWatermarker.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/HiveSourceTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/watermarker/PartitionLevelWatermarkerTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/watermarker/TableLevelWatermarkerTest.java
For every Table we create a NoOp watermark WorkUnit that stores watermarks for all its Partitions as a ```Map```. This workunit is identified by the property ```IS_WATERMARK_WORKUNIT_KEY``` being set to ```true```.
This workunit is intended to only carry watermark state and does not contain any business logic to execute hive conversion queries.
The watermark is stored as a ```MultiKeyValueLongWatermark``` which is an extension to ```Map``` that implements gobblin's ```Watermark``` interface. The key is a Partition identifier and value is the watermark for this Partition
The maximum number of Partition watermarks for each Table can be adjusted by the property MAX_PARTITIONS_IN_WATERMARK_PER_DATASET_KEY, The default is 50. This means we only track watermarks for 50 most recently modified …
> AvroToorc - Implemented a per partition watermark

- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyDataPublisher.java
- gobblin-docs/data-management/DistcpNgEvents.md
- Added a simple wiki that documents the events sent by the Distcp-ng publisher
- Added code to CopyDataPublisher to use a more readable value if the origin/update timestamps are missing.
@ibuenros @pcadabam @ydai1124 can you review?
> Adding a simple wiki for distcp-ng events

- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopFsHelper.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemWrapper.java
Use FileSystem.newInstance instead of FileSystem.get as it closes shared resource.
Performed integration test.
https://github.com/linkedin/gobblin/issues/1219
> Use FileSystem.newInstance instead of FileSystem.get

- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/TimeBasedRetentionPolicy.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/TimeBasedRetentionPolicyTest.java
1. Some old jobs are still using `gobblin.retention.minutes.retained` property for `TimeBasedRetentionPolicy`. Added backward compatibility 
2. Removed the default retention of 1 day as it is risky to silently set 1 day as retention
@ydai1124 can you review?
> Add backward compatibility in time based retention

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- Manually create ORC data location with the same permissions as Avro data
- Note that hive can also automatically create the non-existing directories, but it does not
seem to create it with the desired permissions.
According to hive docs, permissions for newly created directories/files can be controlled using uMask.
I tried the following but it did not honor the umask
```
hive (default)> SET hive.warehouse.subdir.inherit.perms=false;
hive (default)> SET fs.permissions.umask-mode=022;
hive (default)> CREATE EXTERNAL TABLE IF NOT EXISTS `testtable` (`Id` int, `Urn` string) LOCATION '/user/pcadabam/testtable';
OK
Time taken: 6.031 seconds
```
Directory got created with 750 permissions. Expected is 755
> Use avro permission for orc data

- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecSchedulerListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/DefaultGobblinInstanceDriverImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_exec/JobLauncherExecutionDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/AbstractJobSpecScheduler.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/DefaultJobSpecSchedulerListenerImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/ImmediateJobSpecScheduler.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/JobSpecSchedulerListeners.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/DefaultJobLifecycleListenerImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/FilteredJobLifecycleListener.java
- gobblin-runtime/src/test/java/gobblin/runtime/scheduler/TestImmediateJobSpecScheduler.java
- Change JobSpecSchedulerListener.onJobTriggered(JobSpecSchedule jobSchedule) to onJobTriggered(JobSpec jobSpec)
- Add AbstractJobSpecScheduler to do some of the boiler-plate processing in schedulers
@pcadabam @ibuenros can you review?
> Adding AbstractJobSpecScheduler

- gobblin-metrics/src/main/java/gobblin/metrics/reporter/util/SchemaRegistryVersionWriter.java
- gobblin-utility/src/main/java/gobblin/util/limiter/DefaultLimiterFactory.java
- gobblin-utility/src/test/java/gobblin/util/limiter/DefaultLimiterFactoryTest.java
#1199 removed the constructor `(KafkaAvroSchemaRegistry, String)` and introduced backwards incompatible change. Restored this constructor.
@pcadabam Can you review?
> Add backward compatible constructor

- gobblin-api/src/main/java/gobblin/writer/Destination.java
- gobblin-core/src/main/java/gobblin/writer/JdbcWriter.java
- gobblin-core/src/main/java/gobblin/writer/commands/BaseJdbcBufferedInserter.java
- gobblin-core/src/main/java/gobblin/writer/commands/GenericJdbcBufferedInserter.java
- gobblin-core/src/main/java/gobblin/writer/commands/JdbcBufferedInserter.java
- gobblin-core/src/main/java/gobblin/writer/commands/JdbcWriterCommands.java
- gobblin-core/src/main/java/gobblin/writer/commands/JdbcWriterCommandsFactory.java
- gobblin-core/src/main/java/gobblin/writer/commands/MySqlBufferedInserter.java
- gobblin-core/src/main/java/gobblin/writer/commands/TeradataBufferedInserter.java
- gobblin-core/src/main/java/gobblin/writer/commands/TeradataWriterCommands.java
- gobblin-core/src/test/java/gobblin/writer/jdbc/JdbcBufferedInserterTestBase.java
- gobblin-core/src/test/java/gobblin/writer/jdbc/TeradataBufferedInserterTest.java
With this PR I'd like to add the capability of writing to Teradata.
- Writing is done through batch inserts 
- The final table should be created beforehand which is ideally a _MULTISET_ table
_without a primary index_.
- Writer specific jars (**tdgssconfig** and **terajdbc4**) need to be passed to the job 
Excerpt from a job definition:
> \# Converter
> converter.classes=gobblin.converter.jdbc.AvroToJdbcEntryConverter
> 
> \# Writer
> writer.destination.type=TERADATA
> writer.builder.class=gobblin.writer.JdbcWriterBuilder
> 
> \# Publish
> data.publisher.job.type=gobblin.publisher.JdbcPublisher
> jdbc.publisher.url=jdbc:teradata://host
> jdbc.publisher.driver=com.teradata.jdbc.TeraDriver
Tests:
Export 30M records with and without staging tables to Teradata 15.10
both from HDFS and Kafka …
> TeradataWriter implementation

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- The logging is too verbose when more than 5 datasets are onboarded. Moving most of the DDLs/DMLs to debug as the `HiveJDBCConnector` already logs every statement executed. 
- Set hive log level to `WARN`
> [AvroToOrc] Silence hive logging

- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/ImmutableFSJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/FSJobCatalogHelper.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestStandardGobblinInstanceLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/util/FSJobCatalogHelperTest.java
Mostly simple refactoring of ImmutableFSJobCatalog.
Concentrate the config processing of ImmutableFSJobCatalog in ImmutableFSJobCatalog.ConfigAccessor. Remove some unnecessary conversions between typesafe config and properties.
@ibuenros @autumnust  can you review?
> Standardize the access to the ImmutableFSJobCatalog config

- build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDatasetTest.java
- gobblin-data-management/src/test/resources/convertibleHiveDatasetTest/flattenedAndNestedOrc.conf
- gobblin-data-management/src/test/resources/convertibleHiveDatasetTest/flattenedAndNestedOrc.properties
- gobblin-data-management/src/test/resources/convertibleHiveDatasetTest/flattenedOrc.conf
- gobblin-utility/build.gradle
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
- gobblin-utility/src/test/java/gobblin/util/ConfigUtilsTest.java
Currently `hiveRuntime` properties are set in the config store as 
```
hiveRuntime : {
mapreduce.input.fileinputformat.split.minsize=32000000
mapreduce.input.fileinputformat.split.minsize.per.node=32000000
}
```
Since we use `TypeSafeConfig` to parse, the config  `mapreduce.input.fileinputformat.split.minsize.per.node=32000000` is overwritten by `mapreduce.input.fileinputformat.split.minsize=32000000`
Hence changing the syntax of `hiveRuntime` to a list of key value pairs.
```
hiveRuntime : [
mapreduce.input.fileinputformat.split.minsize,32000000
,mapreduce.input.fileinputformat.split.minsize.per.node,32000000
]
```
> [AvroToOrc] Use comma separated list for hiveRuntime properties

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/job_exec/TestJobLauncherExecutionDriver.java
`MRJobLauncher` deletes the working directory before the lock is checked. See (https://github.com/linkedin/gobblin/blob/3f5939c2521061c633ee082bb954a98ab9027f54/gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java#L149). 
This causes the running job that has the lock to fail when it tries to read files in the working directory. Moving the lock check into `AbstractJobLauncher`'s constructor prevents subclasses from doing destructive operations like this without having the lock.
The diff here is ugly due to whitespace but the change is relatively simple.
See https://github.com/linkedin/gobblin/commit/a0ac0a39af26fe6fd15f05ae632ad4a0055c7812?w=1 to view the diff without whitespace
> Move lock attempt into AbstractJobLauncher's constructor

- gobblin-core/src/main/java/gobblin/writer/test/GobblinTestEventBusWriter.java
- gobblin-core/src/main/java/gobblin/writer/test/TestingEventBusAsserter.java
- gobblin-core/src/main/java/gobblin/writer/test/TestingEventBuses.java
- gobblin-core/src/test/java/gobblin/writer/test/GobblinTestEventBusWriterTest.java
- gobblin-core/src/test/java/gobblin/writer/test/TestingEventBusAsserterTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestStandardGobblinInstanceLauncher.java
- gobblin-runtime/src/test/resources/gobblin/runtime/instance/SimpleHelloWorldJob.jobconf
- gobblin-utility/src/main/java/gobblin/util/test/HelloWorldSource.java
Adding some instrumentation to allow us to test end-to-end gobblin jobs.
The idea is to write output to a Guava EventBus and then have some utilities to assert the output.
Changes:
- TestingEventBuses - maintains a global list of testing event buses. This is to simplify the sharing of buses between the writer(s) and the asserter(s).
- GobblinTestEventBusWriter - a writer implementation to write to an EventBus managed by TestingEventBuses
- TestingEventBusAsserter - helper functions to do asserts on the incoming events from TestingEventBuses.
- Unit tests.
@ibuenros @abti can you review?
> Adding GobblinTestEventBusWriter

- gobblin-data-management/src/test/java/gobblin/data/management/copy/hive/filter/LookbackPartitionFilterGeneratorTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/integration/HiveRetentionTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/trash/TrashTest.java
Some of the tests that alter the current time may not set it back if the test fails.
All test that modify system time belong to the group `SystemTimeTests`. We already have an after group method that resets time if the tests themselves has not done it.
> Fix unit test that may not reset system time

- gobblin-runtime/src/main/java/gobblin/scheduler/SchedulerService.java
- gobblin-utility/src/main/java/gobblin/util/PropertiesUtils.java
- gobblin-utility/src/test/java/gobblin/util/PropertiesUtilsTest.java
Changes to SchedulerService were breaking backward compatibility, because irrespective of whether or not properties at initialization time in SchedulerDaemon had quartz related properties, it was being used to initialize SchedulerFactory; which in turn was making the SchedulerFactory to ignore quartz.properties file in classpath and failing to acquire requisite configs to boot up.
> Make Quartz initialization backward compatible in SchedulerService

- gobblin-data-management/src/main/java/gobblin/data/management/policy/CombineSelectionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/EmbeddedRetentionSelectionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/NewestKSelectionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/SelectAfterTimeBasedPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/SelectAllPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/SelectBeforeTimeBasedPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/SelectBetweenTimeBasedPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/SelectNothingPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/DatasetCleaner.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/action/AccessControlAction.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/action/MultiAccessControlAction.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/action/RetentionAction.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/CleanableHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/ConfigurableCleanableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/MultiVersionCleanableDatasetBase.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/MultiCleanableDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/MultiDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/DateTimeDatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/FileStatusAware.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/FileStatusTimestampedDatasetVersion.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/finder/AbstractDatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/finder/DatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/finder/DateTimeDatasetVersionFinder.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/TimestampedDatasetVersionFinderTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/action/RetentionActionTest.java
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testHiveTimeBasedRetention/hive-retention.job
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testHiveTimeBasedRetention/jobProps.properties
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testMultiVersionRetention/daily-hourly-retention.conf
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testMultiVersionRetention/setup_validate.conf
This PR looks like a lot of changes but it is not. It has several unrelated changes in a single PR
1. Major change is in `AccessControlAction` to not make unecessary `FileSystem` calls. With this change, `AccessControlAction` calls `fs.setPermission` and `fs.setOwner` if the permissions and owner of a path are different from what the user wants. To make this change I had to move around some code because the current `FileSystemDatasetVersion` does not know the `FileStatus` of a `DatasetVersion`. It only knows the `Path`.
2. Currently `DatasetCleanerJob` only supports running retention on datasets that import a tag. The only way to run retention on multiple kinds of datasets  that import different tags is to have different jobs. I have added multi tag support in this pr. The same key …
> Make AccessControlAction to update permissions only when required

- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpFsHelper.java
Fix for #1267. 
Sftp connection is not being closed while getting modification time. So, only 10 files can be pulled from sftp source as sshd supports 10 concurrent channels by default. Fix is added to close the connection once we get modification time.
> Close sftp connection after getting mtime

- conf/gobblin-cli.properties
- gobblin-docker/gobblin-base/ubuntu/Dockerfile
- gobblin-docker/gobblin-distributions/ubuntu-gobblin-0.7.0/Dockerfile
- gobblin-docker/gobblin-distributions/ubuntu-gobblin-0.8.0/Dockerfile
- gobblin-docker/gobblin-standalone/ubuntu-gobblin-0.7.0/Dockerfile
- gobblin-docker/gobblin-standalone/ubuntu-gobblin-0.8.0/Dockerfile
- gobblin-docker/gobblin-standalone/ubuntu-gobblin-latest
- gobblin-docker/gobblin-wikipedia/ubuntu-gobblin-0.7.0/Dockerfile
- gobblin-docker/gobblin-wikipedia/ubuntu-gobblin-0.8.0/Dockerfile
- gobblin-docker/gobblin-wikipedia/ubuntu-gobblin-latest
- gobblin-docs/user-guide/Docker-Integration.md
- mkdocs.yml
* Created a new properties file for launching jobs via the CliJobLauncher
* All Dockerfiles are under the gobblin-docker folder
* The gobblin-base files add libraries necessary for Gobblin to run
* Each entry in gobblin-base is for a different OS
* Only Ubuntu based images have been added so far
* gobblin-distribution contains files for each Gobblin release
* gobblin-standalone contains file for running the Gobblin SchedulerDaemon
* gobblin-wikipedia contains files for running Gobblin Wikipedia
I built all the images locally and uploaded them to Docker Hub, the
following link has all the repositories:
https://hub.docker.com/u/gobblin/dashboard/
Any committer who wants to become an admin of the Docker Hub Gobblin
repositories, just send me your Docker Hub user name.
Each folder under …
> (#1307) Gobblin integration with Docker for Gobblin standalone

- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
- gobblin-utility/src/test/java/gobblin/util/AvroUtilsTest.java
Currently AvroUtils.getFieldHelper() assumes that object passed to it is of type Record. Method recursively calls itself based on the field location passed to it as list. If a record contains map, this method fails with ClassCastException: java.util.HashMap cannot be cast to org.apache.avro.generic.GenericData$Record.
This fix enables support for passing map object to AvroUtils.getFieldHelper(). Also added a test case to test for the same.
> Fix AvroUtils.getFieldHelper() to support map fields. Minor changes to cast hashMap to Map

- gobblin-runtime/src/main/java/gobblin/runtime/api/GobblinInstancePlugin.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/GobblinInstancePluginFactory.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/StandardGobblinInstanceDriver.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestDefaultGobblinInstanceDriverImpl.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestStandardGobblinInstanceDriver.java
Adding the concept of a plugin which a service that gets started/stopped along with the instance driver and can be used to extend it. For example, a plugin can load a keytab and authenticate with Kerberos.
@pcadabam, @ibuenros can you review?
> Adding plugins support to StandardGobblinInstanceDriver

- gobblin-kafka/src/main/java/gobblin/kafka/schemareg/LiKafkaSchemaRegistry.java
Fixed LiKafkaSchemaRegistry to use MD5Digest asString method that provides correct hex digest of data for schema id instead of toString which is not overridden over default impl
> Changed LiKafkaSchemaRegistry to use correct id from MD5Digest

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
The clusterIdentifier tag is missing in the Gobblin events being emitted.
This is happening because the JobContext, and MetricsContext is being initialized before the clusterIdentifier tag is added into the JobState. Once the JobContext is already initialized minus the clusterIdentifier tag, further invocations of Instrumented.getMetricContext are unable to pick up the tag unless extra tags are explicitly added in again using GobblinMetrics.getCustomTagsFromState.
> Ensure clusterIdentifier tag is included in the job metric context

- gobblin-core/src/main/java/gobblin/converter/objectstore/ObjectStoreConverter.java
- gobblin-core/src/main/java/gobblin/converter/objectstore/ObjectStoreDeleteConverter.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreClient.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreDeleteOperation.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreOperation.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreOperationBuilder.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreWriter.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/response/DeleteResponse.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/response/GetObjectResponse.java
- gobblin-core/src/test/java/gobblin/writer/objectstore/ObjectStoreWriterTest.java
Added interfaces for object store writer. 
The main abstractions here are 
- `ObjectStoreClient` which wraps any specific client to an object store.
- `ObjectStoreOperation` and its subclasses encapsulates the data and actions for an object in the store. This is also the gobblin record type of the writer
- `ObjectStoreWriter` executes any operation
- `ObjectStoreConverter` and its subclasses build `ObjectStoreOperation`s
@chavdar and @ibuenros can you review?
> Object store writer interfaces

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/http/DefaultHttpClientConfigurator.java
- gobblin-core/src/main/java/gobblin/http/HttpClientConfigurator.java
- gobblin-core/src/main/java/gobblin/http/HttpClientConfiguratorLoader.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- gobblin-core/src/main/java/gobblin/writer/http/AbstractHttpWriter.java
- gobblin-core/src/main/java/gobblin/writer/http/AbstractHttpWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/http/HttpWriter.java
- gobblin-core/src/test/java/gobblin/http/TestDefaultHttpClientConfiguration.java
- gobblin-core/src/test/java/gobblin/http/TestHttpClientConfiguratorLoader.java
Added instrumentation to allow customization of the instantiation of HttpClient objects:
- Enabled configurability through the job State/Config
- Enabled the adding of decorations to the HttpClient
At the core is the HttpClientConfigurator interface which allows to:
- Extract relevant configuration for the HttpConfig from the job Config/State (configure() methods)
- Create decorations of the HttpClients (getHttpClient())
DefaultHttpClientConfigurator is the standard implementation of HttpClientConfigurator. HttpClientConfiguratorLoader can be used to inject different implementations through job State/Config.
I've refactored RestApiConnector and AbstractHttpWriterBuilder to use the above instrumentation. Next is the Wikipedia extractor.
I've also done some minor code hygiene changes to …
> Configurable http clients

- gobblin-core/src/main/java/gobblin/converter/filter/AvroFieldsPickConverter.java
Updated AvroFieldsPickConverter to maintain the order of fields as user defined.
(AvroFieldsPickConverter was introduced with JDBCWriter where order didn't matter. This fix is for the use case, that needs to keep the order of Avro schema and record as user defined).
Example:
converter.avro.fields=userId,memberId,businessUnit
{
"type" : "record",
"name" : "TUPLE_0",
"fields" : [ {
"name" : "userId",
"type" : [ "null", "string" ],
}, {
"name" : "memberId",
"type" : [ "null", "long" ],
}, {
"name" : "businessUnit",
"type" : [ "null", "string" ],
} ]
}
> AvroFieldsPickConverter to maintain the order of fields as user defined.

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/writer/DataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/commit/SpeculativeAttemptAwareConstruct.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/PartitionedDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/RetryWriter.java
- gobblin-core/src/test/java/gobblin/writer/PartitionedWriterTest.java
- gobblin-core/src/test/java/gobblin/writer/test/TestPartitionAwareWriterBuilder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterBuilder.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
This is the first PR of https://docs.google.com/document/d/1Vf5A7pHbFKwr7-Bbw2X3zBBVZSvT7HXEPE6bsi9qGco/
Main changes:
1. It has the new `GobblinMultiTaskAttempt`, which does not contain any real execution but provides the layout.
Gobblin `Task` has new `commit` method, which is empty in this PR.
1. It has the new interface `SpeculativeAttemptAwareConstruct`. Some most commonly used gobblin writers, and writer wrappers, have implemented this interface.
@chavdar @ibuenros Can you review?
> Initial commit for speculative execution in MR mode

- gobblin-core/src/main/java/gobblin/converter/objectstore/ObjectStoreDeleteConverter.java
- gobblin-core/src/main/java/gobblin/http/DefaultHttpClientConfigurator.java
- gobblin-core/src/main/java/gobblin/http/HttpClientConfigurator.java
- gobblin-example/src/main/java/gobblin/example/wikipedia/WikipediaExtractor.java
Originally, the Wikipedia extract used a plain Java HttpURLConnection. For example, it does not support going through a HTTP proxy.
This is a rather rudimentary solution. I've switched the client to the new configurable HttpClients facility.
@pcadabam  can you review?
> Wikipedia httpclient

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDataset.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDatasetTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java
- gobblin-data-management/src/test/resources/convertibleHiveDatasetTest/flattenedAndNestedOrc.conf
- gobblin-data-management/src/test/resources/convertibleHiveDatasetTest/flattenedAndNestedOrc.properties
This PR adds the following capabilities: 
- Create if not exists Hive view over the converted Hive table / dataset if configured 
- Based on configuration: update view every time Avro to ORC conversion happens OR only when schema evolution happens
> Capability to register and update Hive view over converted Hive datasets

- gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveRegistrationPolicyBase.java
- gobblin-hive-registration/src/test/java/gobblin/hive/policy/HiveRegistrationPolicyBaseTest.java
This PR contains two enhancements: 
- Hive registration config governing database and tables to register has been made more generic.
- Basic template support added for Hive tables to register. 
At the moment, if we have the following config: 
```
hive.database.name=db1 
additional.hive.database.name=db2 
hive.table.name=tbl1 
additional.hive.table.name=tbl2,tbl3
```
Then the following Hive db.table registration will take place: 
```
db1.tbl1 
db1.tbl2
db1.tbl3
db2.tbl1 
db2.tbl2
db2.tbl3
```
Hence, there was no way to control selectively tables that should only be registered to a database, with this PR the following config is possible: 
```
hive.database.name=db1 
additional.hive.database.name=db2 
hive.table.name=tbl1 
additional.hive.table.name=tbl2,tbl3 …
```
> Hive registration config governing database and tables made more generic. 

- bin/gobblin-compaction.sh
- bin/gobblin-mapreduce.sh
Versions in AWS related plugins were not updated as the corresponding S3 directory don't have the new libraries
> Update lib versions for gobblin-{compaction,mapreduce}.sh

- gobblin-tunnel/src/test/java/gobblin/tunnel/TestTunnelWithArbitraryTCPTraffic.java
- gobblin-utility/src/test/java/gobblin/util/HadoopUtilsTest.java
- ETL-5122: HadoopUtilsTest.testSafeRenameRecursively: currently, the test waits for the shutdown of executorService without actually shutting it down.
- ETL-5123: Increase timeouts in TestTunnelWithArbitraryTCPTraffic
@htran1 can you have a look?
> Address unit test flakiness

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanGobblinYarnAppLauncher.java
- gobblin-runtime/src/main/java/gobblin/util/SchedulerUtils.java
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
- gobblin-utility/src/main/java/gobblin/util/PullFileLoader.java
- gobblin-utility/src/test/java/gobblin/util/ConfigUtilsTest.java
- gobblin-utility/src/test/java/gobblin/util/PullFileLoaderTest.java
We have repeated issues with converting Properties to Config because of keys which are prefixes of other keys.
The approach I've taken is to detect Properties collections which have such keys and sanitize the names for such properties.
- ConfigUtils.propertiesToConfig() will detect such keys and append .ROOT_VALUE at the end of the offending property
- ConfigUtils.configToProperties() will detect properties which end in .ROOT_VALUE and remove it transparently.
For legacy jobs, constructs we typically have the flow: Job pull file (Properties) -> Job config (Config) -> State properties. PullFileLoader/SchedulerUtils use the ConfigUtils.propertiesToConfig() to do the first transition and JobLauncherExecutionDriver uses ConfigUtils.configToProperties() to do the second transition, the …
> Add sanitization of job property keys which are prefixes of others

- gobblin-metrics/src/main/java/gobblin/metrics/GobblinMetrics.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/TaskMetrics.java
Revert the change of having a customized `getMetricsFileNameIdentifier` from #1382 since it is not necessary. Change `MRJobLauncher` to use `AttemptId` as file suffix. 
@ibuenros Can you review?
> Changing metrics file suffix to attempt id

- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTaskStateTracker.java
Current `AvroHdfsDataWriter` checks `outputFile` length to get the `bytesWritten`. This is a issue when `TaskPublisher` is enabled, because `outputFile` is moved by `TaskPublisher`, and `bytesWritten` always returns 0 or throws `FileNotFoundException`.
To fix this issue, `FileStatus` is recorded in `FsDataWriter`, and so is `bytesWritten`. Also, `synchronized` in the method `bytesWritten()` is no longer necessary here, which is added in #494.
> Fix bytesWritten in FsDataWriter

- gobblin-aws/src/test/java/gobblin/aws/GobblinAWSClusterLauncherTest.java
- gobblin-cluster/src/test/java/gobblin/cluster/GobblinClusterManagerTest.java
- gobblin-cluster/src/test/java/gobblin/cluster/GobblinHelixJobLauncherTest.java
- gobblin-cluster/src/test/java/gobblin/cluster/GobblinTaskRunnerTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/locks/JobLockFactoryTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/locks/ZookeeperBasedJobLockTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/YarnSecurityManagerTest.java
TestingServer allows using of port -1 which means -- pick a random port. We just have to make sure that job configs are modified dynamically.
@abti Can you verify?
> Get rid of fixed ZK ports in unit tests

- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/main/java/gobblin/util/RateControlledFileSystem.java
- gobblin-utility/src/test/java/gobblin/util/HadoopUtilsTest.java
One race condition is when a directory D1/a/b/c/d is renamed to D2/a/b/c/d after another thread created D2/a/b/c/d.
This resulted in D2/a/b/c/d/d. Handle this by using the Java renameTo() method to avoid the LocalFileSystem fallback of copy.
The copy fallback also results in a race condition when a file is opened for copy in one thread and the parent directory is createed in another thread. A file not found exception is encountered in this case. This case is handled by catching the exception and retrying a few times.
> Handle race conditions involving rename in LocalFileSystem.

- gobblin-compaction/build.gradle
- gobblin-compaction/src/main/java/gobblin/compaction/dataset/DatasetsFinder.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/AvroExternalTable.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/HiveManagedTable.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/HiveTable.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/SerialCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/hivebasedconstructs/CompactionLauncherWriter.java
- gobblin-compaction/src/main/java/gobblin/compaction/hivebasedconstructs/CompactionLauncherWriterBuilder.java
- gobblin-compaction/src/main/java/gobblin/compaction/hivebasedconstructs/HiveMetadataForCompactionExtractor.java
- gobblin-compaction/src/main/java/gobblin/compaction/hivebasedconstructs/HiveMetadataForCompactionExtractorFactory.java
- gobblin-compaction/src/main/java/gobblin/compaction/hivebasedconstructs/MRCompactionEntity.java
- gobblin-data-management/build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/extractor/HiveBaseExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/extractor/HiveBaseExtractorFactory.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/extractor/HiveConvertExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/extractor/HiveConvertExtractorFactory.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/writer/HiveQueryExecutionWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/writer/HiveQueryWriterBuilder.java
- gobblin-utility/src/main/java/gobblin/util/HiveJdbcConnector.java
Writer to launch an `MRCompactor` job from a local gobblin job using info obtained from hive.
A workunit is created for each hive table. The extractor gets primary key field, delta key field, and file location from the hive metastore and passes these to the writer, which adds them to config for compaction. Compaction is then run on the entire folder for the table, since watermark management is not added yet.
Changes:
- Created extractor, writer, writerBuilder, compaction entity
- Modified `HiveSource` to make extractor configurable
- Fix bug with compaction tmp folder being used in two places by adding a subfolder in `DatasetsFinder`
- Move `HiveJdbcConnector` to gobblin-util
Config for use:
Source: `HiveSource`
Extractor: `HiveMetadataForCompactionExtractor`
DataWriterBuilder: …
> Writer to launch compaction job using hive metadata

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanGobblinDaemon.java
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-core/build.gradle
- gobblin-core/src/main/java/gobblin/filesystem/InstrumentedHDFSFileSystem.java
- gobblin-core/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem
- gobblin-core/src/test/java/gobblin/filesystem/InstrumentedHDFSFileSystemTest.java
- gobblin-metrics/src/main/java/gobblin/metrics/RootMetricContext.java
- gobblin-runtime/src/main/java/gobblin/scheduler/JobScheduler.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/ExceptionCatchingPathAlterationListenerDecorator.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/FileStatusEntry.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/PathAlterationObserver.java
Three main changes:
* Fixed a closed `FileSystem` in Gobblin daemon, as well as silent failures of the `JobScheduler`.
* Added injection of tags to `RootMetricContext` when running in Azkaban mode.
* Created an instrumented HDFS file system (used for debugging, in the future we can add metrics to it)
> Updates to Gobblin daemon + other minor features

- gobblin-runtime/src/main/java/gobblin/runtime/instance/StandardGobblinInstanceDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_exec/JobLauncherExecutionDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/plugins/email/EmailNotificationPlugin.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestStandardGobblinInstanceDriver.java
- Added a plugin that attaches an email notification listener to the instance driver. The listener sends emails on job completion
- There is an instance level config to turn off emails. By default this emails are enabled at instance level
- There are job level configs to turn on/off emails
- Fixed `JobLauncherExecutionDriver` to get callbacks when legacy launcher is used
@chavdar and @ibuenros can you review?
> Add email notification plugin

- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/MysqlExtractor.java
… columns
See ETL-5244
There is a bug in the MysqlExtractor where tinyint columns are always treated as ints.
There are MySQL jdbc driver setting (tinyInt1isBit=true and transformedBitIsBoolean=false) that
can cause tinyint(1) columns to be treated as BIT/BOOLEAN columns. The default behavior is to
treat tinyint(1) as BIT.
Currently, {@link MysqlExtractor#getDataTypeMap()} uses the information_schema to check types.
That does not do the above conversion. {@link #parseColumnAsString(ResultSet, ResultSetMetaData, int)}
which does the above type mapping.
On the other hand, SqlServerExtractor treats BIT columns as Booleans. So we can be in a bind
where sometimes BIT has to be converted to an int (for backwards compatibility in MySQL) and
sometimes to a Boolean (for SqlServer).
The fix is to …
> Workaround for inconsistent behavior of MysqlExtractor with tinyint(1)

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/test/java/gobblin/GobblinRuntimeTest.java
- gobblin-runtime/src/test/java/gobblin/TestSkipWorkUnitsPublisher.java
- gobblin-runtime/src/test/java/gobblin/TestSkipWorkUnitsSource.java
- gobblin-runtime/src/test/resources/runtime_test/skip_workunits_test.properties
This fix is to allow a work unit to be skipped gracefully without creating it's corresponding task. The state corresponding to work unit will be saved. 
A new working state "SKIP" is added. 
Note that it is still the publisher's responsibility to handle such a work unit. A publisher can still mark it as failed or committed or simply skip.
Similarly source implementation will decide whether to create a new work unit or not , if a skip working state is found among previous work units.
> Added functionality to gracefully skip a work unit

- gobblin-compaction/src/main/java/gobblin/compaction/hivebasedconstructs/CompactionLauncherWriter.java
- gobblin-compaction/src/main/java/gobblin/compaction/hivebasedconstructs/HiveMetadataForCompactionExtractor.java
- gobblin-core/src/main/java/gobblin/publisher/TimestampDataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
Changes:
In `CompactionLauncherWriter`
- Add table name as a subdir to compaction tmp path to avoid workunits using conflicting tmp paths
- Add table name and timestamp to compaction destination path
In `HiveMetadataForCompactionExtractor`
- Convert db/table name to "db.table" format in the path to match `TimestampDataPublisher` output
In `HiveSource`
- Add config key to allow a partitioned table to have one workunit per table instead of one workunit per partition
> Fix some issues for compaction launched from writer

- gobblin-core/src/main/java/gobblin/writer/RetryWriter.java
- gobblin-core/src/main/java/gobblin/writer/ThrottleWriter.java
- gobblin-core/src/test/java/gobblin/writer/RetryWriterTest.java
- gobblin-core/src/test/java/gobblin/writer/ThrottleWriterTest.java
Writer bytesWritten and recordsWritten metrics are not being propagated through because DataWriters are now wrapped with RetryWriter, and ThrottleWriter depending on the configuration.
The call hierarchy is now RetryWriter -> [ThrottleWriter ->] DataWriter. Since RetryWriter and ThrottleWriter are not implementing the FinalState interface, Fork.getFinalState is skipping the getFinalState invocation to include the Writer Constructs into the state.
This fix implements FinalState in the RetryWriter and ThrottleWriter to address the issue.
> Propagate FinalState from RetryWriter and ThrottleWriter

- gobblin-cluster/src/main/java/gobblin/cluster/GobblinHelixTask.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
* Move enum AbstractJobLauncher.MULTI_TASK_ATTEMPT_COMMIT_POLICY to GobblinMultiTaskAttempt since even the name suggests it pertains to GobblinMultiTaskAttempt; Rename to CommitPolicy to conform to the naming conventions.
* Move static AbstractJobLauncher.runWorkUnits methods to GobblinMultiTaskAttempt since those deal mostly with GobblinMultiTaskAttempt.
@ydai1124 can you review?
> Refactor methods from AbstractJobLauncher to GobblinMultiTaskAttempt

- gobblin-compaction/src/main/java/gobblin/compaction/dataset/Dataset.java
- gobblin-compaction/src/main/java/gobblin/compaction/dataset/DatasetsFinder.java
- gobblin-compaction/src/main/java/gobblin/compaction/dataset/SimpleDatasetsFinder.java
- gobblin-compaction/src/main/java/gobblin/compaction/dataset/TimeBasedSubDirDatasetsFinder.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
Currently gobblin-compaction supports inputs from one base directory. `a/b/hourly/2016/12/10/{00..23}`. Sometimes few hours may need to be used from a different location say `c/d/hourly/2016/12/10/{00..23}`. This PR add support to have multiple input directories for a `Dataset`
@ydai1124 , @yukuai518 can you please review?
> Add support for alternate input paths in gobblin-compaction

- gobblin-core/src/main/java/gobblin/writer/RetryWriter.java
- gobblin-core/src/main/java/gobblin/writer/ThrottleWriter.java
- gobblin-core/src/test/java/gobblin/writer/RetryWriterTest.java
- gobblin-core/src/test/java/gobblin/writer/ThrottleWriterTest.java
Missed including ThrottleTime in the ThrottleWriter FinalState. Correct, and include tests.
Also, correct casing to be aligned with the existing conventions.
> Include ThrottleWriter state in FinalState

- gobblin-core/gobblin-flavor-full.gradle
- gobblin-core/gobblin-flavor-standard.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDataset.java
- gobblin-modules/gobblin-compliance/build.gradle
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/ComplianceRecord.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/ComplianceRecordSchema.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/DatasetDescriptor.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/DatasetDescriptorImpl.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerConfigurationKeys.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerConverter.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerExtractor.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerPublisher.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerQueryExecutor.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerQueryTemplate.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerSource.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerWriter.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerWriterBuilder.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/QueryBaseHivePartitionRecord.java
- gobblin-modules/gobblin-compliance/src/test/java/gobblin/compliance/HivePurgerExtractorTest.java
- gobblin-modules/gobblin-compliance/src/test/java/gobblin/compliance/HivePurgerWriterTest.java
gobblin consumers can use gobblin-compliance module to meet their compliance requisites. Current support is to achieve the compliance requirements for Hive Datasets, irrespective of the data format underneath.
> Adding gobblin-compliance module

- gobblin-core/build.gradle
@shirshanka  Can you confirm that those are no longer needed with the gobblin-kafka refactoring?
> Remove confluent dependencies from gobblin-core

- gobblin-core/src/main/java/gobblin/source/extractor/extract/QueryBasedSource.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/QueryBasedSourceTest.java
- gobblin-salesforce/src/main/java/gobblin/salesforce/SalesforceSource.java
Fixing an issue in QueryBasedSource with handling tables with $ in the name.
Originally, code kept track of two properties: SOURCE_ENTITY (used to access the source table) and EXTRACT_TABLE_NAME_KEY used as the table name in the extract (for writing to the destination). Often those are the same but they may differ if SOURCE_ENTITY has certain characters like $.
Later commit changed the above behavior, always replacing SOURCE_ENTITY with a sanitized version. This broke access to tables whose names contain blacklisted characters like $.
The current commit fixes that by reverting to the original behavior. It also adds SourceEntity class to encapsulate the mapping between SOURCE_ENTITY and EXTRACT_TABLE_NAME_KEY.
The tests also adds a bunch of unit tests as QueryBasedSource sorely lacks …
> Fixing an issue in QueryBasedSource with handling tables with $

- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePurgerConverter.java
- gobblin-modules/gobblin-compliance/src/test/java/gobblin/compliance/HivePurgerConverterTest.java
Changing to ComplianceRecordSchema, else it throws ClassCastException.
java.lang.ClassCastException: gobblin.compliance.ComplianceRecordSchema cannot be cast to java.lang.Class
22-12-2016 03:48:05 PST revy INFO - 	at gobblin.compliance.HivePurgerConverter.convertSchema(HivePurgerConverter.java:24)
22-12-2016 03:48:05 PST revy INFO - 	at gobblin.instrumented.converter.InstrumentedConverterDecorator.convertSchema(InstrumentedConverterDecorator.java:72)
22-12-2016 03:48:05 PST revy INFO - 	at gobblin.runtime.MultiConverter.convertSchema(MultiConverter.java:68)
22-12-2016 03:48:05 PST revy INFO - 	at gobblin.runtime.Task.run(Task.java:160)
22-12-2016 03:48:05 PST revy INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
22-12-2016 03:48:05 PST revy INFO - …
> Specify explicit schema class in HivePurgerConverter

- gobblin-core/gobblin-flavor-custom.gradle
- gobblin-core/gobblin-flavor-full.gradle
- gobblin-core/gobblin-flavor-standard.gradle
- gobblin-distribution/gobblin-flavor-custom.gradle
- gobblin-distribution/gobblin-flavor-full.gradle
- gobblin-distribution/gobblin-flavor-standard.gradle
- gobblin-flavored-build.gradle
Flavored builds were not working correctly as they were checking the wrong directories. There were also circular dependencies.
> Fixing flavored builds

- gobblin-core/gobblin-flavor-custom.gradle
- gobblin-core/gobblin-flavor-full.gradle
- gobblin-core/gobblin-flavor-minimal.gradle
- gobblin-core/gobblin-flavor-standard.gradle
- gobblin-distribution/gobblin-flavor-custom.gradle
- gobblin-distribution/gobblin-flavor-full.gradle
- gobblin-distribution/gobblin-flavor-standard.gradle
This is to avoid circular dependencies in IDEs for gobblin-kafka-08 .
> Move kafka module dependency from gobblin-core to gobblin-distribution

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/locks/FileBasedJobLock.java
- gobblin-runtime/src/main/java/gobblin/runtime/locks/FileBasedJobLockFactory.java
- gobblin-runtime/src/main/java/gobblin/runtime/locks/LegacyJobLockFactoryManager.java
- gobblin-runtime/src/test/java/gobblin/runtime/locks/FileBasedJobLockTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/locks/LegacyJobLockFactoryManagerTest.java
This is part of fixing an issue with using static state in ZookeeperBasedJobLock . This cause hard to find bugs if gobblin runs as continuously running process. This uncovered design issues with job lock instantiation which will be fixed in several commits.
The main issues are:
- Inflexible current implementation of JobLockFactory which has the different implementations hard-coded.
- Lack of per-lock-type factory abstraction. The purpose of such factories will be to keep shared state across locks of the same type. (This is what necessitates ZookeeperBasedJobLock to keep that state as static variables).
The main idea of the new design is to
- Add the above concept of a job lock factory: it can instantiate locks and keep shared state among them
- Add the concept of job lock factory manager. …
> Adding a factory abstraction for file-based job locks

- gobblin-hive-registration/src/main/java/gobblin/hive/HiveMetaStoreClientFactory.java
- gobblin-hive-registration/src/test/java/gobblin/hive/HiveMetaStoreClientFactoryTest.java
Updated the HiveMetaStoreClientFactory implementation to return a RetryingHiveMetaStoreClient instead of a HiveMetaStoreClient. The RetryingHiveMetaStoreClient will automatically retry in case of errors (e.g.: when a metastore is restarted).
Also added a unit test.
> Issue #1506: Gobblin should use RetryingHiveMetaStoreClient instead of HiveMetaStoreClient

- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
This fixes a bug introduced in #1518. The fork aborts when a null record is found (which can happen due to timeout in queue record acquisition). 
Hotfix.
> Fixing logic error in Fork loop

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDataset.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDatasetTest.java
Currently `HiveSource` uses `HivePartition`'s createTime to check if it is within lookback. This can cause reprocessing when old source partitions are dropped and recreated.
This change is to use the logical time represented by partition's name for lookback.
> Use date partition filter in HiveSource

- gobblin-modules/gobblin-couchbase/scripts/install_test_deps.sh
In case mvn is not installed, the build progresses and CouchbaseWriterTest fails with a "Server is not up!" message.
This fix errors out the build in case mvn is not available to build the mock-couchbase package.
> Error out if mvn is unavailable to build mock-couchbase

- gobblin-compaction/src/main/java/gobblin/compaction/dataset/TimeBasedSubDirDatasetsFinder.java
Compaction did not worked for me when I used the following timebased folder pattern:
compaction.timebased.folder.pattern='dt='yyyy-MM-dd/'hr'=HH
I checked the code and the getFolderStructure method and it only replaces a-zA-Z0-9 but not any signs like ', = or - which was in my folder pattern to achieve the following directory pattern: /dt=2017-01-01/hr=12/
I added those characters to the regexp and now it works fine for me.
> Fix for compacting partitioned folders

- gobblin-core/src/main/java/gobblin/source/extractor/partition/AppendMaxLimitType.java
- gobblin-core/src/main/java/gobblin/source/extractor/partition/Partitioner.java
When watermark type is TIMESTAMP, we wanted to extract data up to past few seconds or minutes. But there were only CURRENTDATE and CURRENTHOUR cutoff options. So I added CURRENTMINUTE and CURRENTSECOND to AppendMaxLimitType.
Can someone please review and accept this feature?
> Added CURRENTMINUTE and CURRENTSECOND options for watermark cutoff

- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/reporter/ScheduledReporter.java
Even after setting metrics.report.interval property, reporters were still using the default value of 1 minute. 
ScheduleReporter converts the value of metrics.report.interval from milliseconds to seconds and adds it under the property name reporting.interval. At a later point, all properties relative to metrics are converted to config. This is done by ConfigUtils.propertiesToConfig(), which add all the properties containing the prefix "metrics." to the config and hence reporting.interval is not set in the config which leads it to a default value.
This pull request changes the property name from reporting.interval to metrics.reporting.interval.
> Fixed bug for metrics.report.interval

- .gitignore
- gobblin-example/src/main/resources/SampleStreamingJobConfig.pull
- gobblin-modules/gobblin-kafka-09/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleStreamingExtractor.java
- gobblin-modules/gobblin-kafka-09/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleStreamingSource.java
- gobblin-modules/gobblin-kafka-09/src/test/java/gobblin/kafka/source/extractor/extract/kafka/KafkaSimpleStreamingTest.java
This PR creates a simple streaming Kafka consumer. This uses 09 (and later) Consumer api and conforms to the StreamingExtractor and WatermarkStorage interfaces. One follow on needed is that we need to conform to the gobblin kafka way of specifying topics. This can be fixed after we have implemented the KafkaNewApi in KafkaWrapper.
> Kafka streaming

- build.gradle
- travis/test-build.sh
- travis/test.sh
- Allow the skipping of Java8-dependent modules . Such modules need to have the following in there build.gradle:
exp.requiresJavaVersion=JavaVersion.VERSION_1_8
- Modify the travis build to set the jdkVersion flag
@yukuai518 Can you review?
> Allow building of Java8 modules

- gobblin-compaction/src/main/java/gobblin/compaction/dataset/Dataset.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- Use `Set` of inputPaths instead of `List` because paths are meant to be unique and order of paths does not matter
- Use `CopyOnWriteArraySet` for inputPaths to prevent concurrent modifications
@htran1 can you review?
> Gobblin compaction bug fixes

- gobblin-runtime/src/main/java/gobblin/runtime/fork/AsynchronousFork.java
- gobblin-runtime/src/main/java/gobblin/runtime/fork/Fork.java
This is a short-term fix to ensure that tasks shutdown right away. 
Will do a more thorough refactoring later.
> Making AsynchronousFork honor shutdown record

- gobblin-cluster/src/main/java/gobblin/cluster/GobblinTaskRunner.java
- gobblin-utility/src/main/java/gobblin/util/JvmUtils.java
- gobblin-utility/src/main/java/gobblin/util/PortUtils.java
- gobblin-utility/src/test/java/gobblin/util/PortUtilsTest.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinApplicationMaster.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/YarnService.java
@ibuenros @sahilTakiar Can you review?
This allows the user of gobblin to specify JVM arguments to the app_master and containers and have gobblin automatically pick ports where needed.  This is done by detecting a specific token within the jvm argument string.  This token is in any of the following forms:
1. `${PORT_1234}` : Try to get port 1234 and fail if it is not available
2. `${PORT_1234+}`: Try to get any port from the specified port inclusive to the maximum port (65535) inclusive
3. `${PORT_?}`: Try to get a random port between the minimum port (1025) inclusive and the maximum port (65535) inclusive
Gobblin will attempt to pick the specified port, but if it is not available Gobblin will successively try each high port until an open one is found. The actual JVM argument script will …
> Allow ports in the jvm arguments to be automatically picked.

- gradle/scripts/dependencyDefinitions.gradle
Fixes problem where the build fails because mysql cannot be downloaded as the URL has changed.
> Upgrade to latest wix-embedded-mysql so that build continues to work.

- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubBatch.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubBatchAccumulator.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubDataWriterBuilder.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubAccumulatorTest.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubBatchTest.java
Tolerance is chosen to be 95% so the internal size limit will be (256K * 0.95)
> Ignore single Json record if size is larger than 256KB which is size limit for eventhub

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/password/PasswordManager.java
- gobblin-api/src/test/java/gobblin/password/PasswordManagerTest.java
Added a support on "encrypt.key.val" key will be fetched from state directly. This is to support a case
to relieve burden of placing key file when plain text crypto key in job property can be safely protected.
> PasswordManager to support encrypt.key.val

- gobblin-api/src/main/java/gobblin/crypto/CredentialStore.java
- gobblin-api/src/main/java/gobblin/writer/StreamCodec.java
- gobblin-core-base/src/main/java/gobblin/crypto/EncryptionConfigParser.java
- gobblin-core-base/src/main/java/gobblin/crypto/EncryptionFactory.java
- gobblin-core-base/src/main/java/gobblin/crypto/InsecureShiftCodec.java
- gobblin-core-base/src/main/java/gobblin/crypto/JCEKSKeystoreCredentialStore.java
- gobblin-core-base/src/main/java/gobblin/crypto/RotatingAESCodec.java
- gobblin-core-base/src/test/java/gobblin/crypto/EncryptionConfigParserTest.java
- gobblin-core-base/src/test/java/gobblin/crypto/JCEKSKeystoreCredentialStoreTest.java
- gobblin-core-base/src/test/java/gobblin/crypto/RotatingAESCodecTest.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterTest.java
@ibuenros - simpler version
- Add concept of StreamCodec which can encode/decode streams flowing through them
- InsecureShiftCodec which just increments everything going through it by 1
- RotatingAESCodec with CredentialStore that picks a random AES session key from a CredentialStore and uses it for encryption
- Update FileAwareInputStreamDataWriter to wrap the output stream with a StreamCodec if encryption is specified in config
Stripped out:
- capability concept, encode/decode support for kafka + record-based hdfs writers
> Encryption support for distcp only

- gobblin-core-base/src/main/java/gobblin/crypto/EncryptionConfigParser.java
- gobblin-core-base/src/test/java/gobblin/crypto/EncryptionConfigParserTest.java
@jinhyukchang 
- EncryptionConfigParser parser was picking up config settings it shouldn't care about
- Don't return a half-filled in config if mandatory parameters (like algorithm) aren't present
> Fix over-eager EncryptionConfigParser

- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreUtils.java
- gobblin-hive-registration/src/test/java/gobblin/hive/metastore/HiveMetaStoreUtilsTest.java
When creating a Table from a HiveTable, if `columns` is not set or empty, fetch columns from the Deserializer instead.
Internal JIRA: LIHADOOP-26175
> Populate Table columns from Deserializer if not set in HiveRegistrationUnit columns

- gobblin-core-base/src/jmh/java/gobblin/crypto/EncodingBenchmark.java
- gobblin-core-base/src/main/java/gobblin/crypto/Base64Codec.java
- gobblin-core-base/src/main/java/gobblin/crypto/RotatingAESCodec.java
- gobblin-core-base/src/test/java/gobblin/crypto/RotatingAESCodecTest.java
- Based on benchmarks, add a new Base64Codec class that can delegate to java8's Base64 classes if we are running on a new enough JRE. This provides a 15-20% bump in throughput of the RotatingAESCodec
- Add some benchmarks for RotatingAESCodec
> Base64Codec: perf improvement for RotatingAESCodec

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/password/PasswordManager.java
- gobblin-api/src/test/java/gobblin/password/PasswordManagerTest.java
Reverts linkedin/gobblin#1615
Reverting supporting of "encrypt.key.val" as state can be persisted.
@htran1 , could you take a look? Thanks.
> Revert "PasswordManager to support encrypt.key.val"

- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/gobblin/service/FlowConfigsResource.java
Changed access modifier for constructor of FlowConfigsResource to public for RestLI runtime initialization
> Changed access modifier for constructor of FlowConfigsResource to public for RestLI runtime initialization

- gobblin-core-base/src/main/java/gobblin/converter/SerializedRecordToJsonStringConverter.java
- gobblin-example/src/main/resources/avro-eventhub.job
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubBatch.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubBatchAccumulator.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubDataWriter.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/BufferedAsyncDataWriterTest.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubAccumulatorTest.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubBatchTest.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubDataWriterTest.java
Remove base64 encoding inside EventhubDataWriter because we assume the converter already has the encoded string
> Removed base64 encoding inside EventhubDataWriter

- gobblin-cluster/src/main/java/gobblin/cluster/ScheduledJobConfigurationManager.java
- gobblin-data-management/build.gradle
- gobblin-modules/google-ingestion/build.gradle
Travis build was failing because of two reasons. If something else fails I will add it in this PR
1) Package junit was not found for modules gobblin-data-management and gobblin-ingestion
Fix is to add junit as a dependency.
2) Once above is fixed it starts failing due to findbugs
Bug type NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUS (click for details) 
In class gobblin.cluster.ScheduledJobConfigurationManager
In method gobblin.cluster.ScheduledJobConfigurationManager.fetchJobSpecs()
Called method gobblin.cluster.JobConfigurationManager.postDeleteJobConfigArrival(String, Properties)
At ScheduledJobConfigurationManager.java:[line 138]
Argument 2 is definitely null but must not be null
Definite null passed to dangerous method call target …
> Fix to stop travis build from failing

- gradle/scripts/javadoc.gradle
Link http://docs.guava-libraries.googlecode.com/git-history/v15.0/javadoc/ not longer exists
Replacing with http://google.github.io/guava/releases/15.0/api/docs/
> Fix javadoc warning for guava-libraries

- gobblin-core/src/main/java/gobblin/writer/http/AbstractHttpWriter.java
A Gobblin job that outputs data to http, for instance to a REST endpoint using `gobblin.writer.http.RestJsonWriterBuilder` returns successfully as expected. 
However, after subsequent runs such errors may be seen in the Yarn container logs:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.InternalError: java.io.FileNotFoundException: 
/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/localedata.jar
(Too many open files in system)
```
The `YarnChild` processes are still running for each previous job and they never terminate.
In the thread dumps I see that **DestroyJavaVM** just desperately waits for other threads to complete.
After analyzing the heap dump, it turned out that `singleThreadPool` …
> ThreadPool leak in HttpWriter

- gobblin-core-base/src/main/java/gobblin/compression/CompressionConfigParser.java
- gobblin-core-base/src/main/java/gobblin/compression/CompressionFactory.java
- gobblin-core-base/src/main/java/gobblin/compression/GzipCodec.java
- gobblin-core-base/src/main/java/gobblin/crypto/EncryptionFactory.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriterBuilder.java
- gobblin-core/src/test/java/gobblin/writer/SimpleDataWriterTest.java
The FsDataWriterBuilder changes look a little weird with encoders being created only in the build() method -- however, we can't do it in constructor because the Builder isn't really actually fully initialized until build() is called, and we need to cache the encoder state in the Builder itself because getFileName() exists in the builder and isn't passed down to the writer at construct time.
> Add compression and encryption support to SimpleDataWriter

- gobblin-api/build.gradle
- gobblin-api/src/main/java/gobblin/fork/CopyHelper.java
- gobblin-api/src/main/java/gobblin/writer/DataWriterBuilder.java
- gobblin-api/src/main/java/gobblin/writer/WriterOutputFormat.java
- gobblin-api/src/test/java/gobblin/fork/CopyHelperTest.java
- gobblin-core-base/src/main/java/gobblin/writer/PartitionAwareDataWriterBuilder.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/scheduler/PathAlterationListenerAdaptorForMonitor.java
- gobblin-runtime/src/main/java/gobblin/scheduler/SchedulerDaemon.java
- gobblin-runtime/src/test/java/gobblin/runtime/TaskTest.java
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
- gobblin-utility/src/test/java/gobblin/util/ConfigUtilsTest.java
Currently, record types must implement Copyable to participate in fork-based pipelines. 
This PR relaxes this requirement by adding support for byte[] and immutable types like String etc. 
There are a few notable un-filed issues that were discovered that this PR also fixes. 
a) Fork specific config (typically prefixed by numerical branch ids e.g. writer.staging.dir.0) were being mangled due to transformation from Properties -> TypeSafe Config -> Properties. TypeSafe Config surrounds numeric looking tokens with quotes, leading to these config keys looking like writer.staging.dir."0" in TaskState. This PR works around this by stripping all quotes from keys in the Properties bag when transiting through ConfigUtils::configToProperties
b) #1596 inadvertently introduced a bug in Task.java where …
> Forks: Making primitive types copyable by default, tests and bug fixes

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-modules/gobblin-azkaban/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
1) Changed UpdateNotFoundException to UncheckedExecutionException in ValidationJob
UpdateNotFoundException extends RuntimeException. All the RuntimeExceptions are wrapped as   UncheckedExecutionException by com.google.common.cache.LocalCache. Hence the job fails whenever UpdateNotFoundException is thrown which defeats the purpose of catching it.
2) Replacing LinkedHashMap for storing evolved HiveColumns. This correponds to the issue https://github.com/linkedin/gobblin/issues/1672
3) Adding the property to skip setting group for the destination dataset same as source. This is needed because if the owner is not a part of the group (there are various reasons why such a thing can happen at the first place), then the task will fail.
> Bug fixes for avro2orc

- gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java
@htran1 
I pretty consistently get failures in the yarn unit tests on my Linux machine. I know the problem is some sort of DNS/host resolution issue - the MiniYARNCluster is only listening on 127.0.0.1, but the unit test is trying to connect to my external IP address, but don't know if there's an obvious fix.
That said... this change makes the test fail in 10s instead of the default 15 minute setting (https://hadoop.apache.org/docs/r2.6.2/hadoop-yarn/hadoop-yarn-common/yarn-default.xml) which has made my life easier. :)
> Set a 10s timeout on YARN connection failures for unit tests

- gobblin-api/src/main/java/gobblin/broker/iface/ScopeInstance.java
- gobblin-api/src/main/java/gobblin/broker/iface/SharedResourceFactory.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-core-base/src/main/java/gobblin/instrumented/Instrumented.java
- gobblin-core/src/main/java/gobblin/util/TestUtils.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/broker/MetricContextFactory.java
- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/broker/MetricContextKey.java
- gobblin-metrics-libs/gobblin-metrics-base/src/test/java/gobblin/metrics/broker/MetricContextFactoryTest.java
- gobblin-restli/gobblin-restli-utils/src/main/java/gobblin/restli/SharedRestClientFactory.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/RestliLimiterFactory.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/RestliServiceBasedLimiter.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/test/java/gobblin/restli/throttling/RestliServiceBasedLimiterTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobBrokerInjectionTest.java
- gobblin-utility/src/main/java/gobblin/broker/KeyedScopedConfigViewImpl.java
- gobblin-utility/src/main/java/gobblin/broker/SharedResourcesBrokerImpl.java
- gobblin-utility/src/main/java/gobblin/util/NoopCloseable.java
- gobblin-utility/src/main/java/gobblin/util/limiter/broker/SharedLimiterFactory.java
- gobblin-utility/src/test/java/gobblin/broker/TestFactory.java
Changes:
* Created a `MetricContextFactory` for broker, along with a `MetricContextKey` and a unit test.
* Rest.li Limiter supports emitting metrics. The factory automatically acquires a metric context from the broker.
* In Gobblin runtime, `WorkUnitState` gets a broker builder instead of a pre-built broker so it can inject its own custom configurations (not done currently). Eventually, I would want to replace all `MetricContext`s in gobblin runtime for ones acquired from the broker.
* Added a scope id to the `ScopeInstance` interface.
* Minor changes to generics in broker (fixes compiler/ide warnings)
> Added metrics to rest.li limiter.

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/metadata/MetadataMerger.java
- gobblin-core/src/main/java/gobblin/metadata/types/GlobalMetadata.java
- gobblin-core/src/main/java/gobblin/metadata/types/GlobalMetadataJsonMerger.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/test/java/gobblin/metadata/types/GlobalMetadataTest.java
- gobblin-core/src/test/java/gobblin/publisher/BaseDataPublisherTest.java
- gobblin-core/src/test/java/gobblin/writer/SimpleDataWriterTest.java
- gobblin-utility/src/main/java/gobblin/util/json/JsonUtils.java
- Each writer keeps track of some GlobalMetadata (which for now is only TransferEncoding).
- BaseDataPublisher merges all of these metadata objects together using the GlobalMetadataMerger, and writes the merged data out to disk if the appropriate config is set
- Add a JsonUtil class to hold Jackson objects so we aren't constructing them all over the place. This will also let us hang config settings off there if we figure out there are good defaults to set.
To follow in future PRs:
- Support to set GlobalMetadata from config/an arbitrary retriever
- Allow sources + converters to optionally set global metadata
- Per-record metadata
> Batch level metadata support

- gobblin-data-management/src/main/java/gobblin/data/management/copy/converter/DecryptConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/converter/DistcpConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/converter/UnGzipConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/extractor/FileAwareInputStreamExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/TarArchiveInputStreamDataWriter.java
- gobblin-utility/src/main/java/gobblin/broker/DefaultBrokerCache.java
- gobblin-utility/src/main/java/gobblin/broker/EmptyKey.java
- gobblin-utility/src/main/java/gobblin/broker/NonExtendableBrokerView.java
- gobblin-utility/src/main/java/gobblin/broker/SharedResourcesBrokerImpl.java
- gobblin-utility/src/main/java/gobblin/util/io/BatchedMeterDecorator.java
- gobblin-utility/src/main/java/gobblin/util/io/FilterStreamUnpacker.java
- gobblin-utility/src/main/java/gobblin/util/io/MeteredInputStream.java
- gobblin-utility/src/main/java/gobblin/util/io/MeteredOutputStream.java
- gobblin-utility/src/main/java/gobblin/util/io/MeteredStream.java
- gobblin-utility/src/main/java/gobblin/util/io/StreamCopier.java
- gobblin-utility/src/main/java/gobblin/util/io/StreamThrottler.java
- gobblin-utility/src/main/java/gobblin/util/io/ThrottledInputStream.java
- gobblin-utility/src/main/java/java/io/FilterStreamUnpacker.java
- gobblin-utility/src/test/java/gobblin/broker/DefaultGobblinBrokerTest.java
- gobblin-utility/src/test/java/gobblin/util/io/MeteredInputStreamTest.java
- gobblin-utility/src/test/java/gobblin/util/io/MeteredOutputStreamTest.java
- gobblin-utility/src/test/java/gobblin/util/io/StreamCopierTest.java
- gobblin-utility/src/test/java/gobblin/util/io/ThrottledInputStreamTest.java
The main point of this PR is that we should throttle underlying streams instead of the streams that Gobblin replication sees. For example, if a replication flow does on-the-fly compression / decompression, we want to limit the bytes per second that are actually going through the network, not the output of compression / decompression.
Few changes:
* Introduce metered streams to measure bytes processed in an input/output stream.
* Introduce throttled input stream that is transparently throttled, and a `StreamThrottler` to create the throttled input streams.
* Added the concept of a BrokerView that allows a higher scoped immutable view of a broker. This is necessary for correct functionality of some factories.
* There is no reason replication should use `FSDataInputStream`, so changed to use …
> Throttle underlying input streams.

- gobblin-core/src/main/java/gobblin/source/extractor/extract/QueryBasedExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/QueryBasedSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/partition/Partition.java
- gobblin-core/src/main/java/gobblin/source/extractor/partition/Partitioner.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/QueryBasedExtractorTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/partition/PartitionerTest.java
As between the time when data query was created and that was executed, there might be some new data generated in the source. Removing the upper bounds will help us grab the new data.
> Remove data pull upper bound for the last work unit of query based task

- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDataset.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/ComplianceConfigurationKeys.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/DatasetDescriptor.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePartitionVersionFinder.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HiveProxyQueryExecutor.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/purger/PurgeableHivePartitionDataset.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/CleanableHivePartitionDataset.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/CleanableHivePartitionDatasetFinder.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/ComplianceRetentionJob.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/HivePartitionRetentionVersion.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/HivePartitionVersionRetentionCleaner.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/HivePartitionVersionRetentionCleanerPolicy.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/HivePartitionVersionRetentionReaper.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/HivePartitionVersionRetentionReaperPolicy.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/HivePartitionVersionRetentionRunner.java
Work flow of Retetention:
1) ComplianceRetentionJob.run() is called by by the ComplianceAzkabanJob.
2) ComplianceRetentionJob will find all the HivePartitionDataset(s) for which retention needs to run. Note that here HivePartitionDataset refers to the original hive partitions not the backups/staging partitions.
3) For each HivePartitionDataset, HivePartitionVersionFinder will find associated versions. Here versions refer to a backup/staging partition corresponding to an original partition.
4) A HivePartitionVersionPolicy will be called to shortlist the versions which needs to deleted/moved. All the backups are moved to a backup directory after 2 days so that inflight queries won't get affected.
5) On each shortlisted version, a cleaner/reaper will run. Cleaner for deletion of backups. …
> Added retention to gobblin-compliance

- gobblin-core/src/main/java/gobblin/source/DatePartitionedAvroFileSource.java
- gobblin-core/src/main/java/gobblin/source/DatePartitionedDailyAvroSource.java
- gobblin-core/src/main/java/gobblin/writer/partitioner/DatePartitionType.java
- gobblin-core/src/main/java/gobblin/writer/partitioner/TimeBasedWriterPartitioner.java
- gobblin-core/src/test/java/gobblin/source/extractor/DatePartitionedAvroFileExtractorTest.java
- gobblin-example/src/main/resources/hdfs-monthly-to-hdfs-daily.pull
- gobblin-utility/src/main/java/gobblin/util/DatePartitionType.java
This PR is a continuation of PR https://github.com/linkedin/gobblin/pull/1196 .
Currently the `DatePartitionedDailyAvroSource` can only read daily partitioned data.
This PR extends this functionality by introducing `DatePartitionedAvroFileSource` in which the partitioning is configurable by the properties as follows:
> date.partitioned.source.partition.prefix
> date.partitioned.source.partition.suffix
> date.partitioned.source.partition.pattern
> date.partitioned.source.partition.granularity
This is the _reader equivalent_ of the time-based writer and partitioner, found in `TimeBasedWriterPartitioner` and `TimePartitionedDataPublisher`.
With this add-on new data sets can be read using different temporal granularity, not just as daily partitioned data.
> Replace DatePartitionedDailyAvroSource with configurable partitioning

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/publisher/DataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/source/DatePartitionedAvroFileSource.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/partitioner/WorkUnitStateWriterPartitioner.java
- gobblin-core/src/test/java/gobblin/publisher/BaseDataPublisherTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/DatePartitionedAvroFileExtractorTest.java
@ibuenros @shirshanka 
- Fix an issue in DatePartitionedAvroFileSource where the code would not
resolve paths properly if the prefix config property was empty
- Enhance the AvroFileSource to send along the partition it extracted
in WorkUnitState
- Create a WorkUnitStateWriterPartitioner that will partition an
incoming record solely based on WorkUnitState
- Update writers to set any partition paths they use in an internal
PARTITION_PATH_KEY
- Update BaseDataPublisher to collect partition information and publish
metadata files in each partition directory if the metadata output
directory is not specifically configured somewhere else.
- Update BaseDataPublisher to publish metadata _after_ publishing data.
If this isn't done - and partitions are enabled - then the code that
publishes all of …
> Enable partitioning based on source info + partitioned metadata writes

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/restapi/RestApiExtractor.java
To extend RestApiConnector and RestApiExtractor for other data source, some methods need to be able to override
> Refactor RestApiConnector and RestApiExtractor

- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/event/EventSubmitter.java
- gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/SafeDatasetCommit.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/task/BaseAbstractTask.java
- gobblin-runtime/src/main/java/gobblin/runtime/task/TaskFactory.java
- gobblin-runtime/src/main/java/gobblin/runtime/task/TaskIFace.java
- gobblin-runtime/src/main/java/gobblin/runtime/task/TaskIFaceWrapper.java
- gobblin-runtime/src/main/java/gobblin/runtime/task/TaskUtils.java
- gobblin-runtime/src/main/resources/embedded/embedded.conf
- gobblin-runtime/src/test/java/gobblin/task/CustomTaskTest.java
This PR allows running custom tasks in Gobblin. 
To use custom tasks, implement a `TaskFactory` and use `TaskUtils.setTaskFactoryClass(WorkUnitState, Class<? extends TaskFactory>` in the `Source`. Tasks need to implement `TaskIFace`.
> Can run custom tasks in Gobblin.

- gobblin-runtime/src/main/java/gobblin/runtime/SafeDatasetCommit.java
findBugsMain was failing for gobblin-runtime due to which travis build was failing. Fixed two reasons for failure:
1) Trying to synchronize on an interned string. So instead of using "LOCK" we should use either new String("LOCK") or new Object().
If we use new String("LOCK"), then findBugs will fail stating performance issue and will ask to use "LOCK" instead of new String("LOCK");
2) Casting in equals method. It states that if other is not an instance of this, then return false. Reformatted the code.
> Fixing travis build from failing

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyConfiguration.java
- gobblin-data-management/src/main/java/gobblin/data/management/partition/CopyableDatasetRequestor.java
Currently when there's failure getting dataset in CopyableDatasetRequestor, it logs the error and continue to perform distcp and makes job status success overall. 
This change will have user to choose to make the job fail fast so that failure from CopyableDatasetRequestor will make the job fail immediately.
- Integration test passed.
job property snippet:
gobblin.copy.CopyableDatasetRequestor.failFast=true
> Added fail-fast option to CopyableDatasetRequestor (disabled by default)

- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/main/java/gobblin/service/FlowConfigClient.java
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/main/java/gobblin/service/FlowStatusClient.java
To integrate with dependency framework like Spring, add constructor that can inject RestClient from framework
> Update constructor of FlowConfigClient and FlowStatusClient 

- gobblin-core/src/main/java/gobblin/source/extractor/partition/Partitioner.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/DateWatermark.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/HourWatermark.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/TimestampWatermark.java
Fix the bug that the shared object SimpleDateFormat will cause issues in multi-threads. The scenario is that when all pull jobs start at the same time, the partition calculation for all jobs will be messed up.
> Fix the multithreading bug in TimestampWatermark

- gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/source/extractor/extract/kafka/workunit/packer/KafkaWorkUnitPacker.java
- gobblin-utility/src/main/java/gobblin/util/ImmutableProperties.java
- Accept configured table type and namespace instead of fixed values
- Add configuration key `gobblin.kafka.extract.allowTableTypeAndNamspaceCustomization` to turn on the changes, avoid breaking existing jobs
> Enable KafKaSource to accpet table type and namespace configuration

- gobblin-core/src/main/java/gobblin/publisher/HiveRegistrationPublisher.java
- gobblin-docs/user-guide/Hive-Registration.md
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegProps.java
- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreUtils.java
- gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveRegistrationPolicyBase.java
- gobblin-hive-registration/src/test/java/gobblin/hive/policy/HiveRegistrationPolicyBaseTest.java
Adding upstream data src(specifically "topic.name" for kafka data in this PR, temporarily) info into registered hive table, as one of the table properties.
@ibuenros @htran1  Could you help review ? Thanks.
> Add runtime table properties(e.g. Kafka topic) into Hive Registration

- gobblin-api/src/main/java/gobblin/configuration/State.java
A State can have properties other than commonProperties and specProperties. 
For example WorkUnitState extends State. Hence WorkUnitState does contain commonProperties and specProperties. A WorkUnitState also contains WorkUnit(extends State). Hence a WorkUnitState contains properties other commonProperties and specProperties in the form of Properties belonging to a WorkUnit.
I encountered this error when workUnitState is passed as a parameter to the State constructor leading to loss of few properties.
> Fixing bug in gobblin.configuration.State

- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/TaskMetrics.java
This is a fix to avoid unnecessary memory consumption due to creation of separate Metric objects for every job/task.
I removed branch index, task id and job id form task metric name to avoid creating a new task metrics for every task/branch.
@abti @ibuenros
> Removing fork branch index, task id and job id form task metrics

- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
@ibuenros 
`bin/gobblin run distcp foo bar` was hanging on exit whenever any file was actually copied. The root cause was that `FSAwareInputDataStreamWriter` overrode `close()` without calling the superclass method -- this caused the metric updater thread from `InstrumentedDataWriterBase` to hang around forever because it was never shutdown.
This fix is correct, but I'm not sure if we should also be started the metric writer thread as a daemon thread vs one that can hang the process -- thoughts?
- Remove shadowed closer variable since the superclass defines one already
- Remove overridden close() method - it wasn't calling super.close()
which was causing bugs, and is now irrelevant since the parent close
will close resources properly
> Fix distcp from CLI hang

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
During creation of WorkUnits in HiveSource, failure to create a single WorkUnit shouldn't lead to failure of Job.
Some exceptions in this case (eg. UpdateNotFoundException) are often wrapped as UncheckedExecutionException leading to failure of Job.
> Catching UncheckedExecutionException in HiveSource

- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubAccumulatorTest.java
The intermittent return value of pending batches caused build failure.
> Fix eventhub build issue

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-metastore/src/main/java/gobblin/metastore/nameParser/DatasetUrnStateStoreNameParser.java
- gobblin-metastore/src/main/java/gobblin/metastore/nameParser/GuidDatasetUrnStateStoreNameParser.java
- gobblin-metastore/src/main/java/gobblin/metastore/nameParser/SimpleDatasetUrnStateStoreNameParser.java
- gobblin-metastore/src/main/java/gobblin/metastore/util/StateStoreCleaner.java
- gobblin-metastore/src/test/java/gobblin/metastore/nameParser/GuidDatasetUrnStateStoreNameParserTest.java
- gobblin-modules/gobblin-helix/src/main/java/gobblin/runtime/ZkDatasetStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/FsDatasetStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/MysqlDatasetStateStore.java
Created `DatasetUrnStateStoreNameParser` for providing the mapping between datasetUrn and state store name.
It currently has two implementations. The default: `SimpleDatasetUrnStateStoreNameParser` and SHA1 based guid: `GuidDatasetUrnStateStoreNameParser`.
`FsDatasetStateStore` has this feature enabled. It is backwards compatible.
Other `DatasetStateStore` can also have this feature. 
@htran1 or @ibuenros  can you take a look?
> Support shorten dataset state store name

- gobblin-core-base/src/main/java/gobblin/instrumented/converter/InstrumentedConverterBase.java
- gobblin-core-base/src/main/java/gobblin/instrumented/extractor/InstrumentedExtractorBase.java
- gobblin-core-base/src/main/java/gobblin/instrumented/fork/InstrumentedForkOperatorBase.java
- gobblin-core-base/src/main/java/gobblin/instrumented/qualitychecker/InstrumentedRowLevelPolicyBase.java
- gobblin-core-base/src/main/java/gobblin/instrumented/writer/InstrumentedDataWriterBase.java
- gobblin-core-base/src/main/java/gobblin/writer/AsyncWriterManager.java
- gobblin-core/src/main/java/gobblin/writer/ThrottleWriter.java
- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/filesystem/MetricsFileSystemInstrumentation.java
- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/MetricContext.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/BatchedPermitsRequester.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/RestliLimiterFactory.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-utility/src/main/java/gobblin/broker/SharedResourcesBrokerFactory.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/FileSystemInstrumentation.java
This PR does the following:
* Add an `onClose` trigger for `FileSystemInstrumentations`. Metrics instrumentation writes out a report on this trigger. This required updating the return type of `MetricContext.timer`.
* Fix `BatchedPermitsRequester` to correctly handle multiple batches with the same expiration.
* A few small fixes.
> Fixes to InstrumentedFileSystem on MR jobs and BatchedPermitsContainer.

- gobblin-restli/client.gradle
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/BatchedPermitsRequester.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/RestliLimiterFactory.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/RestliServiceBasedLimiter.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/stressTest/FixedOperationsStressor.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/stressTest/MRStressTest.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/stressTest/RandomDelayStartStressor.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/stressTest/RandomRuntimeStressor.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/stressTest/RateComputingLimiterContainer.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/stressTest/StressTestUtils.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/main/java/gobblin/util/limiter/stressTest/Stressor.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/test/java/gobblin/util/limiter/LocalStressTest.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-client/src/test/java/gobblin/util/limiter/MockRequester.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-server/src/main/java/gobblin/restli/throttling/DynamicTokenBucket.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-server/src/main/java/gobblin/restli/throttling/QPSPolicy.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-server/src/main/java/gobblin/restli/throttling/ThrottlingGuiceServletConfig.java
- gobblin-restli/gobblin-throttling-service/gobblin-throttling-service-server/src/main/java/gobblin/restli/throttling/TokenBucket.java
- gobblin-utility/src/main/java/gobblin/broker/SharedResourcesBrokerFactory.java
There are two main sets of changes in this PR:
Stres Test for Throttling
=================
* There are two stress tests: `MRStressTest` and `LocalStressTest`.
* A `Stressor` is a class that sends requests to a `Limiter`. Different stressors can simulate different usage patterns.
* The `LocalStressTest` uses and embedded throttling server and multiple threads to run a stressor. The requests do not go through the network, but the stress test can add artificial latency representing the network latency. Every 15 seconds, the stress test logs statistics about the throttling.
* The `MRStressTest` uses a real throttling server. It spawns multiple mappers each one running a stressor. The mappers emit their effective permit use rate every 15 seconds, which then gets collected by the reducer to …
> Stress testing classes for throttling service.

- gobblin-hive-registration/src/main/java/gobblin/hive/HiveSerDeWrapper.java
- gobblin-runtime/build.gradle
- gobblin-runtime/src/test/java/gobblin/WriterOutputFormatIntegrationTest.java
- gradle/scripts/dependencyDefinitions.gradle
1) Added TEXTFILE format in HiveSerDeWrapper.
2) Removed "{@link #SERDE_SERIALIZER_FILE_EXTENSION}" from javadocs as they were not declared anywhere.
3) Added "com.esotericsoftware.kryo:kryo:2.22" dependency for supporting TEXTFILE format.
4) Added a test, to convert Avro to TEXTFILE. This test is also a validation that TEXTFILE format is supported and can be used for serializing and deserializing.
Note: In order to support TEXTFILE, following properties should be passed from job/pull file.
serde.deserializer(or serializer).type=TEXTFILE
> Fix for issue 1776

- gobblin-service/src/test/java/gobblin/service/modules/core/IdentityFlowToJobSpecCompilerTest.java
- Added a test to primarily trigger build internally, and as a side-effect increase coverage
- The test added is for compiler when flow does not yield to any job
> Added test for compiler when flow does not yield to any job

- gobblin-yarn/build.gradle
Upgraded johnrengelman shadow plugin to 1.2.4 to fix mavenResolver issue with internal dependencies.
> Upgraded johnrengelman shadow plugin to 1.2.4 to fix mavenResolver issue

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/publisher/DataPublisher.java
- gobblin-modules/gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/SafeDatasetCommit.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/DummyJobContext.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobContextTest.java
- Added SLA in `AzkabanJobLauncher` to have enough time for our own `cancel` logic;
- Previous Job cancellation does not persist state. Added state persistence for job cancellation.
- Added skippable to `DataPublisher`, so that tasks that are finished successfully with skippable `publisher` can have their states persisted. One example would be `HiveRegistrationPublisher`, which does not have any effect to state store, and user can choose to skip it as long as tasks are committed using partial `JobCommitPolicy`.
@htran1 or @ibuenros  can you take a look?
> Support state persistence for partial commit; Add Sla to Azkaban launcher

- bin/gobblin-standalone.sh
We need to clean up the locks directory if gobblin cannot be stopped gracefully, otherwise, it will hold all following schedules for any job in the locks folder from running the next time we restart the gobblin instance locally.
> Locks directory clean up for gobblin standalone

- gobblin-runtime/src/main/java/gobblin/scheduler/JobScheduler.java
Fixed #1792 by moving the handling of the case where `ConfigurationKeys.JOB_CONFIG_FILE_DIR_KEY` exists, but `ConfigurationKeys.JOB_CONFIG_FILE_GENERAL_PATH_KEY` does not to the constructor.  In this case, the `ConfigurationKeys.JOB_CONFIG_FILE_GENERAL_PATH_KEY` is added to the property set with the value `"file://" + this.properties.getProperty(ConfigurationKeys.JOB_CONFIG_FILE_DIR_KEY)`.  Then during startup, if properties contains `ConfigurationKeys.JOB_CONFIG_FILE_DIR_KEY`, the job file monitor is started.
> Fix for #1792

- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreUtils.java
- gobblin-modules/gobblin-couchbase/src/test/java/gobblin/couchbase/CouchbaseTestServer.java
Problem statement:There's a `runtime.props` contained in hive table properties. The value of this props is all the metadata k-v pair that we obtained in runtime, including kafka topic for example. Keeping this value in final metadata is not necessary. This is a minor fix for removal.
@ibuenros Can you help review? Thanks.
> Remove redundant runtime attributes in hive table properties

- gobblin-modules/gobblin-crypto-provider/src/main/java/gobblin/converter/AvroStringFieldEncryptorConverter.java
- gobblin-modules/gobblin-crypto-provider/src/main/java/gobblin/converter/StringFieldEncryptorConverter.java
- gobblin-modules/gobblin-crypto-provider/src/test/java/gobblin/converter/AvroStringFieldEncryptorConverterTest.java
mode right now so that we don't have to manipulate the output schema.
> Field-level string encryptor. String -> string is the only supported

- gobblin-core/src/main/java/gobblin/converter/avro/FlattenNestedKeyConverter.java
- gobblin-core/src/test/java/gobblin/converter/avro/FlattenNestedKeyConverterTest.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
Given configuration:
```
FlattenNestedKeyConverter.fieldsToFlatten="address.city,address.zipcode"
```
A `FlattenNestedKeyConverter` will add top level fields "addressCity" and "addressZipcode" into the outputSchema. Their values will be the same as what the nested keys refer to in the inputRecord.
> Implement FlattenNestedKeyConverter

- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/ImmutableFSJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/scheduler/JobScheduler.java
- gobblin-runtime/src/main/java/gobblin/util/SchedulerUtils.java
- gobblin-runtime/src/test/java/gobblin/runtime/job_catalog/FSJobCatalogHelperTest.java
- gobblin-runtime/src/test/java/gobblin/util/SchedulerUtilsTest.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/PathAlterationObserverScheduler.java
- Rename PathAlterationDetector to PathAlterationObserverScheduler as the current name is confusing. The class does not detect anything.
- Currently, passing an interval <= 0 will throw an exception in start(). Change the logic to not schedule anything instead.
- Trivial simplification in addPathAlterationObserver()
> Changes to PathAlterationDetector/PathAlterationObserverScheduler

- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
changing writer staging and output directories to new job level sub directories, so that two jobs with same ConfigurationKeys.WRITER_STAGING_DIR .WRITER_OUTPUT_DIR in their job conf do not clean up the common staging and output directories.
@ydai1124
> changing writer staging and output directories to job level sub dir

- gobblin-config-management/gobblin-config-client/src/main/java/gobblin/config/client/ConfigClient.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/ConfigStoreBackedTopology.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/ConfigStoreBackedValueInspector.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/ConfigStoreTopologyInspector.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/ConfigStoreValueInspector.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/InMemoryTopology.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/InMemoryValueInspector.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStore.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHadoopFilesystemConfigStore.java
- gobblin-config-management/gobblin-config-core/src/test/java/gobblin/config/store/hdfs/SimpleHdfsConfigStoreTest.java
- gobblin-utility/src/main/java/gobblin/broker/TTLResourceEntry.java
There are many occasions where imports should be resolved at runtime using dynamic tags. Current implementation supports only resolution of environment variables as dynamic tags. This pr aims to generalize resolution of dynamic tags by passing a runtime config(optional).
> Adding dynamic tag resolver using runtime property for config store

- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionCompleteAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionCompleteFileOperationAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionHiveRegistrationAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionMarkDirectoryAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/CompactionAvroJobConfigurator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactionTask.java
- gobblin-compaction/src/main/java/gobblin/compaction/suite/CompactionAvroSuite.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTask.java
This change is to bridge the gap between old renaming logic for databus-etl, and the new compaction logic in MRCompactionTask. 
In old renaming logic, after the compaction is compete, the directory will be renamed to {DIRNAME}_COMPLETE. Replicate the same logic in the MRCompactionTask now. 
The change will only take effect when compaction.rename.source.dir.enabled=true
> Rename directory after compaction is complete

- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/utils/DatasetUtils.java
Int is not sufficient for size of partitions in bytes
> Fixing minor bug in gobblin-compliance:DatasetUtils

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/writer/HiveQueryExecutionWriter.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/CopyPartitionParametersTest.java
1) Passing the necessary source partition info and destination partition info from HiveQueryExecutionWriter.java to HiveConvertPublisher.java via WorkUnit
2) Params which need to be preserved should be passed via configuration property "hive.conversion.preserve.partitionParameters"
3) Adding params into the destination partition inside HiveConvertPublisher.java
> Preserving partition params during avro2orc conversion

- gobblin-config-management/gobblin-config-client/src/main/java/gobblin/config/client/ConfigClient.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/ConfigStoreBackedTopology.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/ConfigStoreTopologyInspector.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/common/impl/InMemoryTopology.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreWithImportedBy.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreWithImportedByRecursively.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreWithResolution.java
This PR is related to #1866
Adding parameter runtimeConfig to ConfigClient. This will enable methods to resolve dynamic tags in config URIs using the runtimeConfig.
> Changing config client to pass runtimeConfig as a parameter to resolve dynamic tags

- gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/provider/DatasetAwareFsMetadataProvider.java
- gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/provider/DatasetAwareMetadataProvider.java
- gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/provider/DatasetAwareMetadataProviderFactory.java
- gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/provider/MetadataAwareFileSystem.java
- gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/provider/PermissionMetadataParser.java
- gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/provider/SimpleConfigMetadataProvider.java
- gobblin-modules/gobblin-metadata/src/main/java/gobblin/metadata/provider/SimpleMetadataProviderFactory.java
- gobblin-modules/gobblin-metadata/src/main/resources/META-INF/services/gobblin.util.filesystem.FileSystemInstrumentationFactory
Main changes:
1. Added `MetadataAwareFileSystem` which instruments permission change related `FileSystem` operations.
2. Created `DatasetAwareMetadataProvider` to provide metadata at dataset level. Reused the existing `GlobalMetadata`.
3. Tested with the `SimpleConfigMetadataProvider` using Gobblin-kafka jobs.
> Add metadata aware filesystem instrumentation

- gobblin-core/src/main/java/gobblin/async/AsyncDataDispatcher.java
- gobblin-core/src/main/java/gobblin/writer/http/AbstractAsyncDataWriter.java
- gobblin-core/src/test/java/gobblin/async/AsyncDataDispatcherTest.java
This fix the following scenario:
consumer: `buffer.size()==0`
consumer: `notifyBufferEmptyOccurrence`
producer: `buffer.put()`
producer: `close: waitForABufferEmptyOccurrence` will return immediately
producer: `close: stopAsync.awaitTermination`
consumer: `isRunning`
consumer: `return` without knowing there is a record in the buffer
> Prevent closing before buffer is empty

- gobblin-docker/gobblin-distributions/ubuntu-gobblin-0.10.0/Dockerfile
- gobblin-docker/gobblin-distributions/ubuntu-gobblin-0.9.0/Dockerfile
- gobblin-docker/gobblin-standalone/ubuntu-gobblin-0.10.0/Dockerfile
- gobblin-docker/gobblin-standalone/ubuntu-gobblin-0.9.0/Dockerfile
- gobblin-docker/gobblin-standalone/ubuntu-gobblin-latest
- gobblin-docker/gobblin-wikipedia/ubuntu-gobblin-0.10.0/Dockerfile
- gobblin-docker/gobblin-wikipedia/ubuntu-gobblin-0.9.0/Dockerfile
- gobblin-docker/gobblin-wikipedia/ubuntu-gobblin-latest
- gobblin-docs/user-guide/Docker-Integration.md
Only had time to test that the `gobblin-wikipedia` files work, haven't had time to test the `gobblin-standalone` files work correctly.
Haven't pushed the image to Docker Hub yet, publishing the Docker files here first for review.
> gobblin-docker files for 0.9.0 and 0.10.0 release

- gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2Client.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/writer/R2RestWriterBuilder.java
- Throw IOException on sending failure, which will be handled by its consumer
> Fix R2Client not closing gracefully
