- gobblin-utility/build.gradle
- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
- gobblin-utility/src/test/java/gobblin/util/SchedulerUtilsTest.java
> Added support for variable substitution in job configuration files

- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
I found this NPE when testing data-purger. This change fixed the exception.
> Add checking for null parameter

- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
- gobblin-utility/src/test/java/gobblin/util/SchedulerUtilsTest.java
> Allow case-insensitive extensions of job configuration files

- gobblin-compaction/src/main/java/gobblin/compaction/CompactionRunner.java
- gobblin-core/src/main/java/gobblin/qualitychecker/row/RowLevelErrFileWriter.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/InputStreamCSVReader.java
- gobblin-example/src/main/java/gobblin/example/simplejson/SimpleJsonExtractor.java
- gobblin-example/src/main/java/gobblin/example/wikipedia/WikipediaExtractor.java
- gobblin-metrics/src/main/java/gobblin/metrics/JobMetrics.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobManager.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobStateToJsonConverter.java
- gobblin-salesforce/src/main/java/gobblin/salesforce/SalesforceExtractor.java
- gobblin-scheduler/src/main/java/gobblin/scheduler/JobScheduler.java
- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
I tried to fix the DM_DEFAULT_ENCODING warnings in most modules. There are still other high priority warnings that need to be addressed.
> Fixed DM_DEFAULT_ENCODING FindBugs warnings

- gobblin-compaction/src/main/java/gobblin/compaction/CompactionRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/HiveJdbcConnector.java
Addressed two remaining findbugs warnings for gobblin-compaction.
> address findbug issues

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-compaction/src/main/java/gobblin/compaction/CompactionRunner.java
- gobblin-core/src/main/java/gobblin/qualitychecker/row/RowLevelErrFileWriter.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/InputStreamCSVReader.java
- gobblin-example/src/main/java/gobblin/example/simplejson/SimpleJsonExtractor.java
- gobblin-example/src/main/java/gobblin/example/wikipedia/WikipediaExtractor.java
- gobblin-metastore/src/test/java/gobblin/metastore/DatabaseJobHistoryStoreTest.java
- gobblin-metrics/src/main/java/gobblin/metrics/JobMetrics.java
- gobblin-rest-service/gobblin-rest-server/src/test/java/gobblin/rest/JobExecutionInfoServerTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobManager.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobStateToJsonConverter.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestBase.java
- gobblin-salesforce/src/main/java/gobblin/salesforce/SalesforceExtractor.java
- gobblin-scheduler/src/main/java/gobblin/scheduler/JobScheduler.java
- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
> Use UTF-8 instead of the default encoding charset encoding

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
- gobblin-utility/src/test/java/gobblin/util/JobLauncherUtilsTest.java
So the method can be used somewhere else. This helps pull request #44.
> Made the code for staging data cleanup a utility method

- gobblin-utility/src/main/java/gobblin/util/HeapDumpForTaskUtils.java
- gobblin-utility/src/test/java/gobblin/util/HeapDumpForTaskUtilsTest.java
Unit test passed. I also tested on data-purger by injecting OOM using small -xmx values to the map tasks.
> Added support to generate script for  dumping task heap when OOM happens

- build.gradle
- gobblin-compaction/build.gradle
- gobblin-compaction/src/main/java/gobblin/hive/util/HiveJdbcConnector.java
> Fixing build and find bugs warnings

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
The solution is not to use Hadoop's MultiThreadedMapper, but instead overwriting the Mapper.run() method to run the WorkUnits in the TaskExecutor. Now the map() method is only responsible for de-serializing and collecting WorkUnits, but not running them.
> Make mappers run WorkUnits (tasks) concurrently

- gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java
Now with Xmx=2g, it can process 5000 files when persisting job state.
> add compression when writing job state to sequence file

- gobblin-core/src/main/java/gobblin/converter/csv/CsvToJsonConverter.java
> Fixed build

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
> Moved Azkaban-specific config to AzkabanJobLauncher

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
> Fixed a method name

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
> Added the missing ids to WorkUnitStates created in getPreviousWorkUnitStates

- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
Currently Gobblin assumes that if a schema or data record is not going into more than one fork branch, then it is not an instance of Copyable. However, it is still possible for the last converter before the ForkOperator to return Copyable schema or data records. If this is the case, Gobblin should still call Copyable.copy() to get a copy of the schema or data record.
> Allow schema or data record to be Copyable even if it is not going to multiple branches

- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareCounter.java
- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareGauge.java
- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareHistogram.java
- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareMeter.java
- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareMetric.java
- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareMetricFactory.java
- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareScheduledReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareTimer.java
- gobblin-metrics/src/main/java/gobblin/metrics/MetricContext.java
- gobblin-metrics/src/main/java/gobblin/metrics/Tag.java
- gobblin-metrics/src/main/java/gobblin/metrics/TagBasedMetricFilter.java
- gobblin-metrics/src/main/java/gobblin/metrics/Taggable.java
- gobblin-metrics/src/main/java/gobblin/metrics/Tagged.java
- gobblin-metrics/src/test/java/gobblin/metrics/ContextAwareMetricFactoryTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/MetricContextTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/TagTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/TaggedTest.java
This commit includes the core APIs and classes of the new metric library and unit tests around them.
> Initial commit of the new metric library

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/writer/DataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/writer/AvroDataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/test/java/gobblin/writer/AvroHdfsDataWriterTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/GobblinOutputCommitter.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-test/resource/job-conf/GobblinTest1.pull
- gobblin-test/resource/job-conf/GobblinTest2.pull
- gobblin-test/resource/job-conf/GobblinTest3.pull
- gobblin-test/resource/mr-job-conf/GobblinMRTest.pull
- gobblin-utility/src/main/java/gobblin/util/ForkOperatorUtils.java
- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
- gobblin-utility/src/main/java/gobblin/util/WriterUtils.java
- gobblin-utility/src/test/java/gobblin/util/ForkOperatorUtilsTest.java
- gobblin-utility/src/test/java/gobblin/util/JobLauncherUtilsTest.java
- gobblin-utility/src/test/java/gobblin/util/WriterUtilsTest.java
Javadocs added, tests pass, adding unit tests for WriterUtils. @liyinan926 can you take a look?
> Bug fix to properly cleanup staging directories

- build.gradle
- gobblin-metrics/build.gradle
- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareScheduledReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/MetricContext.java
- gobblin-metrics/src/main/java/gobblin/metrics/influxdb/InfluxDBReporter.java
- gobblin-metrics/src/test/java/gobblin/metrics/ContextAwareMetricFactoryTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/MetricContextTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/TestConstants.java
- gobblin-metrics/src/test/java/gobblin/metrics/graphite/GraphiteReporterTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/hadoop/HadoopCounterReporterTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/hadoop/NewAPIHadoopCounterReporterTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/influxdb/InfluxDBReporterTest.java
Note that the deleted `commonsHttpClient` is a duplicated entry.
> Added a InfluxDBReporter

- gobblin-metrics/src/test/java/gobblin/metrics/influxdb/InfluxDBReporterTest.java
> Temporarily disabled unit test InfluxDBReporterTest

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-runtime/src/main/java/gobblin/runtime/BoundedBlockingRecordQueue.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
> Lowered the default record queue capacity to 100

- gobblin-metrics/src/main/java/gobblin/metrics/example/GraphiteReporterExample.java
- gobblin-metrics/src/main/java/gobblin/metrics/example/InfluxDBReporterExample.java
- gobblin-metrics/src/main/java/gobblin/metrics/example/ReporterExampleBase.java
> Added some example classes demonstrating usage of the new metric library

- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareScheduledReporter.java
> Javadoc updates to ContextAwareScheduledReporter

- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskContext.java
- gobblin-runtime/src/test/java/gobblin/runtime/TaskContextTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
> Some code refactoring following pull request #124

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
The problem is due to code refactoring as part of #120, an instance of the Hadoop `Job` class is created in the constructor of `MRJobLauncher` before the dependent jars are added to DistributedCache (that updates `conf`). So the `Job` is missing the info on jars added to the DistributedCache. 
> Fixed a bug that caused the NoClassDefFoundError on Hadoop

- .travis.yml
- README.md
> Enabled continuous build with Travis-CI

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/MetricNames.java
> Fixed new high priority FindBugs warnings

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/MetricNames.java
> Refactored some metric names so the naming is more consistent

- build.gradle
- gobblin-api/build.gradle
- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-azkaban/build.gradle
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanCompactionJobLauncher.java
- gobblin-compaction/build.gradle
- gobblin-compaction/src/main/java/gobblin/compaction/hive/AvroExternalTable.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/CompactionRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/HdfsIO.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/HdfsReader.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/HdfsWriter.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/HiveAttribute.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/HiveManagedTable.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/HiveTable.java
- gobblin-compaction/src/main/java/gobblin/compaction/hive/SerialCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyCombineFileRecordReader.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyDedupReducer.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyMapper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyRecursiveCombineFileInputFormat.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyJobRunner.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
Refactored the Camus-sweeper code, improved coding style and readability, also some changes in logic and config parameters.
- Main class is `gobblin.compaction.mapreduce.MRCompactor`
- General MR compaction classes are in `gobblin.compaction.mapreduce`.
- Avro-specific classes are in `gobblin.compaction.mapreduce.avro`.
- Original Hive compaction classes are moved to `gobblin.compaction.hive`.
- Azkaban job class is `gobblin.azkaban.AzkabanCompactionJobLauncher`.
> MapReduce Compaction Implementation

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
Before: if previous offset not found, it always starts at the earliest offset; if previous offset is out of range, either start at earliest offset or skip partition.
Now:
- If previous offset not found, may start at earliest or latest, or skip. Controlled by "bootstrap.with.offset".
- If previous offset out of range, may start at earliest or latest, or skip, or start at the nearest offset (if it's closer to earliest, start at earliest, otherwise start at latest). Controlled by "reset.on.offset.out.of.range".
> Increase flexibility on which offset to start for kafka adapter, when previous offset not found or out of range

- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriterBuilder.java
- gobblin-core/src/test/java/gobblin/writer/SimpleDataWriterTest.java
> Fixed open source license header for some newly added files

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTaskStateTracker.java
> Use a single property to control reporting metrics as Hadoop counters in MR mode

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
> Do not attempt to kill the Hadoop job if it has not been submitted

- build.gradle
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanIntegrationTestLauncher.java
- gobblin-test-harness/src/main/java/gobblin/test/execution/operator/SetupOperator.java
- gobblin-test-harness/src/main/java/gobblin/test/execution/validator/ValidationRule.java
- gobblin-test-harness/src/main/java/gobblin/test/setup/config/ConfigStepsGenerator.java
- gobblin-test-harness/src/main/java/gobblin/test/setup/config/Step.java
- gobblin-test-harness/src/main/java/gobblin/test/setup/config/TestHarnessLauncher.java
Changed Step to have a getStepName which will help in getting the name of the step 
Also added throws exception to LaunchStep
> Copyright changes

- gobblin-runtime/src/main/java/gobblin/runtime/util/JobMetrics.java
- gobblin-runtime/src/test/java/gobblin/runtime/util/JobMetricsTest.java
ibuenros@ can you take a look at this?
The pull request is to be able to tag metrics by hadoop cluster name.
> Add hadoop cluster tag to metrics

- gobblin-utility/build.gradle
> add both gobblin-utility.jar and gobblin-utility-{version}.jar to tar

- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpFsHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/SizeAwareFileBasedHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/SizeAwareFileBasedHelperDecorator.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/AvroFsHelper.java
- gobblin-metrics/src/main/java/gobblin/metrics/Counters.java
Moved  gobblin-metrics/src/main/java/gobblin/metrics/Counters.java  from gobblin-tracking-purger
> Count bytes read from FileBasedExtractor

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/password/PasswordManager.java
- gobblin-api/src/test/java/gobblin/password/PasswordManagerTest.java
- gobblin-utility/src/main/java/gobblin/util/CLIPasswordEncryptor.java
- gobblin-utility/src/main/java/gobblin/util/DatasetFilterUtils.java
Also modified the encryption tool to allow reading master password from file.
> Modify PasswordManager to allow BasicTextEncryptor

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemWrapper.java
Added one option in FsDataWriter for doing file system operations as a proxy user. Tested on spades.
> Implement proxied file system operation

- .gitignore
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/ParallelStateSerDeRunner.java
- gobblin-runtime/src/test/java/gobblin/runtime/util/ParallelStateSerDeRunnerTest.java
1. Parallelized the serialization of `WorkUnit`s in the preparation phase.
2. Parallelized the deserialization of `TaskState`s in the finalization phase.
> Parallelized preparation and finalization in the MR mode

- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
> Fixed a bug that causes false-alarm warning log message when loading job configs

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
There's no need to use a `do-while` loop inside another `do-while` loop. Also, the inner `do-while` loop doesn't check `messageIter.hasNext()` which could potentially be a problem.
> Small refactoring in KafkaExtractor

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
@sahilTakiar @liyinan926 can you review this?
> Add proxy file system support for cleaning staging data

- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
created method `getFsWithProxy` so that it can be used by both `cleanStagingData` methods.
> refactor JobLauncherUtils

- gobblin-api/src/main/java/gobblin/source/workunit/MultiWorkUnit.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
Duplicate of https://github.com/linkedin/gobblin/pull/208
@liyinan926 I addressed your comments.
> Fixing bugs in MultiWorkUnit

- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopFileInputSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/OldApiHadoopFileInputSource.java
> Allow extract type to be an optional property in HadoopFileInputSource

- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
> Fixed a bug in SourceState.createExtract

- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/AvroFsHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/ProxyFsInput.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemWrapper.java
Created ProxyFsInput for getting avro schema when proxy is enabled. 
Tested on Nertz.
@liyinan926 Can you review?
> Add proxyFsInput for AvroFsHelper

- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
Also made some formatting changes to the State class.
@liyinan926 could you review this?
> Fixing NPE when Extractor.getSchema returns null

- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/AvroFsHelper.java
@liyinan926 Can you review this?
> Another change to enable the proxy on AvroFsHelper

- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-api/src/main/java/gobblin/source/workunit/Extract.java
- gobblin-api/src/main/java/gobblin/source/workunit/MultiWorkUnit.java
- gobblin-core/src/test/java/gobblin/source/extractor/hadoop/HadoopFileInputSourceTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/hadoop/OldApiHadoopFileInputSourceTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
> Fixed FindBugs warnings

- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
> Yet another try to fix FindBugs warnings

- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
1. Fixed a bug that caused false-alarm warning log messages.
2. Fixed a bug that will prematurely complete processing of a `WorkUnitstate` if a branch didn't produce any data and it is not the last branch.
> Fixed some bugs in BaseDataPublisher

- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopFileInputSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/OldApiHadoopFileInputSource.java
> Updated HadoopFileInputSource following PR #214

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
Added a `HashSet` in `KafkaSource` that contains the processed partitions. If a partition has a previous offset from the state store, but is not processed, an empty workunit will be created for this partition to avoid losing the checkpoint.
> Create empty workunits for blacklisted topic partitions

- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
> Avoid duplciate keytab login in cleaning staging data

- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-core/src/test/java/gobblin/configuration/WorkUnitStateTest.java
@liyinan926 can you take a look at this?
> Fix WorkUnitState and State equals method

- gobblin-api/src/main/java/gobblin/configuration/ImmutableWorkUnitState.java
- gobblin-api/src/main/java/gobblin/source/workunit/ImmutableExtract.java
- gobblin-api/src/main/java/gobblin/source/workunit/ImmutableWorkUnit.java
These new methods were added in #214
> Modify ImmutableWorkUnit/WorkUnitState/Extract due to new methods added

- gobblin-core/src/main/java/gobblin/writer/AvroHdfsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriter.java
- gobblin-utility/src/main/java/gobblin/util/ExecutorsUtils.java
> Moved code dealing with general file level arrributes to FsDataWriter

- gobblin-core/src/main/java/gobblin/policies/count/RowCountRangePolicy.java
- gobblin-core/src/test/java/gobblin/policies/count/RowCountRangePolicyTest.java
@ibuenros/ @ydailinkedin  can you take a look at this?
> Fix division by long in PolicyChecker

- gobblin-core/src/main/java/gobblin/policies/count/RowCountRangePolicy.java
@ibuenros can you take a look at this.
> Add logs when quality check fails

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
> Added the missing dot

- gobblin-runtime/src/main/java/gobblin/runtime/FsDatasetStateStore.java
> Fixed a bug in FsDatasetStateStore when constructing the state file name

- gobblin-api/src/test/java/gobblin/password/PasswordManagerTest.java
> Don't fail PasswordManagerTest if strong encryption is not support

- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
> Refactored a log message

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
> Fail the job if it failed to process any dataset

- gobblin-data-management/src/main/java/gobblin/data/management/trash/TrashFactory.java
- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemUtils.java
> Fix a bug in ProxiedFileSystemUtils

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobStateTest.java
> Some code cleanup around job/dataset state manipulation

- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/DeleteAllRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/FileStatusDatasetVersion.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/SingleVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/MockTrash.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/TrashFactory.java
Includes minor fixes, and the addition of a FileStatusDatasetVersion.
> File status dataset version.

- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
- gobblin-runtime/src/test/java/gobblin/runtime/local/LocalJobLauncherTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
> Added additional unit tests for multi-dataset cases with partial commit policy

- gobblin-utility/src/main/java/gobblin/util/ProxiedFileSystemUtils.java
SuperUser related configuration keys are duplicated. Even within the single class ProxiedFileSystemUtils, we have two places using two keys which have the same value.
Also, use AUTH_TOKEN_PATH for token path only.
> Make superuser configuration keys consistent, and separate authpath for tokens/keytab

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-core/src/main/java/gobblin/metrics/GobblinMetrics.java
@ibuenros  can you take a look at this?
>  Add azkaban flowId, execId, JobId, ProjectName to metric tags

- gobblin-utility/src/main/java/gobblin/util/PublisherUtils.java
@sahilTakiar can you review this fix?
> Fix splitExtractsByPredicate

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
> Made MAPREDUCE the default job launcher type on Azkaban

- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
@liyinan926 can you review this?
> Replace newlines with pipe

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
> Fixed a bug that cause alert emails on job failures to not be sent

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobManager.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobLauncherTestHelper.java
- gobblin-runtime/src/test/java/gobblin/runtime/JobStateTest.java
> Fixed the way completed task count is computed and some refactoring

- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
Addressing comments for #301 
@pcadabam could you take a look?
> Addressing comments on PR-301

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
> Fixed a bug that prevents alert emails from being sent

- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/ModificationTimeDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ModificationTimeDatasetProfile.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/DateTimeDatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/ModDateTimeDatasetVersionFinder.java
> Enable retention based on folder mod time

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-azkaban/build.gradle
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/TimeRangeChecker.java
- gobblin-utility/src/test/java/gobblin/util/TimeRangeCheckerTest.java
@pcadabam and @liyinan926 can you take a look?
> Adding extra scheduling features to AzkabanJobLauncher

- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java
- gobblin-utility/src/test/java/gobblin/util/HadoopUtilsTest.java
- gobblin-utility/src/test/java/gobblin/util/TimeRangeCheckerTest.java
@ibuenros and @pcadabam could you both take a look?
> Adding FsPermission serialize / de-serialize methods

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
@chavdar  and @ydailinkedin can you take a look at this?
> Fix group in FsWriter

- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/ModificationTimeDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/CombineRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/UnixTimestampVersionFinder.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/CombineRetentionPolicyTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/UnixTimestampVersionFinderTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/test/ContainsARetentionPolicy.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/test/ContainsBRetentionPolicy.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/test/ContainsCRetentionPolicy.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/test/ContainsStringRetentionPolicy.java
Used to combine different simple retention policies with UNION or INTERSECT operations.
> Implemented combine retention policy.

- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/DatasetBase.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/FileLevelTimestampVersionFinder.java
@ibuenros Can you review? Thanks!
> Fix NPE when finding dataset versions

- gobblin-data-management/src/main/java/gobblin/data/management/retention/DatasetCleaner.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/AsyncTrash.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/GobblinProxiedTrash.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/GobblinTrash.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/ProxiedTrash.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/TestTrash.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/Trash.java
- gobblin-data-management/src/test/java/gobblin/data/management/trash/AsyncTrashTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/trash/TestTrashTest.java
- gobblin-utility/src/main/java/gobblin/util/executors/ForceQueuePolicy.java
- gobblin-utility/src/main/java/gobblin/util/executors/ScalingQueue.java
- gobblin-utility/src/main/java/gobblin/util/executors/ScalingThreadPoolExecutor.java
Implementation of async trash for parallel deletions.
> Implementation of async trash for parallel deletions.

- bin/gobblin-standalone.sh
Changes to `gobblin-standalone.sh`:
- Allows values to be set via environment variables that can be
overridden by passing in the values as args
- Explicit setting of `FWDIR`, while still defaulting to the original value for
legacy reasons
- Explicit exits on status check
> Add env support to gobblin-standalone.sh

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-utility/src/main/java/gobblin/util/JobLauncherUtils.java
> Enable cleaning entire job's staging/output data at once

- gobblin-api/src/main/java/gobblin/publisher/DataPublisher.java
- gobblin-api/src/main/java/gobblin/publisher/SingleTaskDataPublisher.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/test/java/gobblin/test/TestDataPublisher.java
> Add SingleTaskDataPublisher and restore DataPublisher to the original API

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobMetrics.java
- gobblin-utility/src/main/java/gobblin/util/ClustersNames.java
> Move clusterIdentifier logic from JobMetrics to ClusterNames

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-metrics/src/main/java/gobblin/metrics/Tag.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobMetrics.java
- gobblin-runtime/src/test/java/gobblin/runtime/util/JobMetricsTest.java
- gobblin-utility/src/main/java/gobblin/util/TagUtils.java
@ibuenros @liyinan926 can you review?
> Move commonly used tags to utils

- bin/gobblin-standalone.sh
- gobblin-scheduler/src/main/java/gobblin/scheduler/SchedulerDaemon.java
- Adds support for setting any additional JVM flags
- Can specify a custom configuration properties file for supplementing the default configuration shipped with Gobblin
- Backwards compatible
> Standalone configuration improvements

- gobblin-core/src/main/java/gobblin/source/extractor/utils/InputStreamCSVReader.java
- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriter.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/JobStateToJsonConverter.java
> Fixed a bunch of FindBugs warning

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
> Turn on mapreduce output compression by default

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaAvroExtractor.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
> Check schema equals in AvroUtils.convertRecordSchema()

- gobblin-core/src/main/java/gobblin/converter/filter/AvroSchemaFieldRemover.java
> fix bug in AvroSchemaFieldRemover

- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/DateTimeDatasetVersionFinder.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/TimestampedDatasetVersionFinderTest.java
> Fix a bug in DateTimeDatasetVersionFinder

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/MRCompactorAvroKeyDedupJobRunner.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/InputStreamCSVReader.java
- gobblin-metrics/src/main/java/gobblin/metrics/example/ReporterExampleBase.java
> Fixing various find bugs warnings

- gobblin-core/src/main/java/gobblin/writer/AvroHdfsTimePartitionedWriter.java
Records older than max allowed time ago will be dropped.
Currently there's no limit, and we had situations where some Kafka partitions contain records in thousands of hours, which caused the mapper to OOM.
There is a similar property in Camus.
> Add option to set max time ago for AvroHdfsTimePartitionedWriter

- gobblin-data-management/src/test/java/gobblin/data/management/partition/PartitionTest.java
> Fix incorrect import

- bin/gobblin-yarn.sh
> Some enhacements to gobblin-yarn.sh

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/restapi/RestApiExtractor.java
Added a exclusive column list , which can be used for salesforce configuration with huge list of columns.
> Added a exclusive column list , which can be used for salesforce configuration with huge list of columns. 

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/qualitychecker/row/RowLevelPolicy.java
- gobblin-core/src/main/java/gobblin/policies/avro/AvroRecordTimestampLowerBoundPolicy.java
- gobblin-core/src/main/java/gobblin/policies/time/RecordTimestampLowerBoundPolicy.java
- gobblin-core/src/main/java/gobblin/writer/partitioner/TimeBasedAvroWriterPartitioner.java
- gobblin-core/src/main/java/gobblin/writer/partitioner/TimeBasedWriterPartitioner.java
> Add RecordTimestampLowerBoundPolicy

- gobblin-core/src/main/java/gobblin/qualitychecker/row/RowLevelErrFileWriter.java
- gobblin-core/src/main/java/gobblin/qualitychecker/row/RowLevelPolicyChecker.java
> Change RowLevelPolicyChecker.executePolicies to return false if type=OPTIONAL and record failed

- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/PartitionedDataWriter.java
Which makes it easier for multiple writers to pass states to the same state object.
> Make writerId unique among writers of the same task

- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpFsHelper.java
@liyinan926 can you review this?
> Make known hosts optional for sftp connection

- build.gradle
- gobblin-compaction/build.gradle
- gobblin-core/build.gradle
- gobblin-data-management/build.gradle
- gobblin-distribution/build.gradle
- gobblin-runtime/build.gradle
- gobblin-scheduler/build.gradle
- gobblin-test-harness/build.gradle
Based on #386 
Some of the artifacts have to be obtained from Conjar repo.
> Update Hive version to 1.2.1

- gobblin-core/src/main/java/gobblin/metrics/ConsoleEventReporterFactory.java
- gobblin-core/src/main/java/gobblin/metrics/ConsoleReporterFactory.java
- gobblin-core/src/main/java/gobblin/writer/PartitionedDataWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyDataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyEventSubmitterHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/TarArchiveInputStreamDataWriter.java
- gobblin-utility/src/main/java/gobblin/util/io/StreamUtils.java
@ibuenros can you review this?
> Submit events from distcp-ng

- gobblin-azkaban/build.gradle
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanGobblinYarnAppLauncher.java
- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanJobLauncher.java
> Added a Azkaban launcher for Gobblin on Yarn

- build.gradle
- maven-install.sh
Simply allows to install artifatcts to a local repo.
> Add support for maven install

- gobblin-runtime/src/main/java/gobblin/runtime/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
> Add writer.bytes.written to task state

- gobblin-core/src/main/java/gobblin/metrics/ConsoleEventReporterFactory.java
- gobblin-yarn/src/test/java/gobblin/yarn/YarnHelixUtilsTest.java
> Deleted the parent directory in YarnHelixUtilsTest

- gobblin-utility/src/main/java/gobblin/util/logs/LogCopier.java
> Limit the number of minutes and bytes per log file in LogCopier

- gobblin-api/src/main/java/gobblin/util/RecordCountProvider.java
- gobblin-compaction/src/main/java/gobblin/compaction/Dataset.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorTimeBasedJobPropCreator.java
- gobblin-utility/src/main/java/gobblin/util/recordcount/LateFileRecordCountProvider.java
@zliu41 Can you review?
Has not tested yet. Want to first make sure this is the appropriate way to trigger recompaction.
> ETL-3802: Trigger compaction if late data exceeds threshold

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
> Fix findbug warning

- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionRecordCountEvent.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
> ETL-3765: Report record count after compaction is done

- bin/gobblin-yarn.sh
Changed it from .../yarn/conf to .../conf/yarn
> Fixed the yarn conf path

- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionRecordCountEvent.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
CompactionRecordCountEvent now reports whether re-compaction is needed/completed. 
@zliu41 Can you review?
> Add recompact information to compactionRecordCountEvent

- conf/yarn/reference.conf
- gobblin-yarn/build.gradle
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/test/resources/reference.conf
> Added an option to include the job execution history server in GobblinYarnAppLauncher

- build.gradle
- maven-install.sh
This allows publishing artifacts to other locations such as artifactory.  See issue: #508
> Added ability to disable artifact signing and specify the artifact repository

- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStore.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreCreationException.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreFactory.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreWithBatchFetches.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreWithImportedBy.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreWithImportedByRecursively.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreWithResolution.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/ConfigStoreWithStableVersion.java
- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/api/VersionDoesNotExistException.java
This is the clean one commit ( duplicated with https://github.com/linkedin/gobblin/pull/401  )
@chavdar 
Please review
> commit for config management api

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-scheduler/src/main/java/gobblin/scheduler/JobScheduler.java
> Made it an option for the job scheduler to wait for running jobs to complete

- gobblin-runtime/src/test/java/gobblin/runtime/BoundedBlockingRecordQueueTest.java
There seems to be an intermittent failure on Travis for this test.
@liyinan926 could you review?
> Increase timeout in BoundedBlockingRecordQueueTest

- gobblin-api/src/main/java/gobblin/annotation/Alpha.java
- gobblin-api/src/main/java/gobblin/annotation/Beta.java
- gobblin-api/src/main/java/gobblin/annotation/Stable.java
@ibuenros @sahilTakiar Can you review?
> Marker apis

- gobblin-metastore/src/main/java/gobblin/metastore/JobHistoryDataSourceProvider.java
> Add password encryption to JobHistoryDataSourceProvider

- gobblin-metrics/src/main/java/gobblin/metrics/reporter/OutputStreamReporter.java
* Deleting a bunch of duplicate code from `OutputStreamReporter.Builder` that also exists in `MetricReportReporter.Builder`
> Fixing FindBugs warnings from PR #549

- build.gradle
- gobblin-yarn/build.gradle
Fun project: printout the project dependencies in the dot graph format
> Dot project dependencies

- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/DeletingCopyDataPublisher.java
@liyinan926 can you review this?
> Delete .ready files after publish

- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyEventSubmitterHelper.java
> Add file size to distcp sla event

- gobblin-yarn/src/main/java/gobblin/yarn/YarnService.java
> A small code fix to add a missing type parameter

- build.gradle
- defaultEnvironment.gradle
- gobblin-azkaban/build.gradle
- gobblin-compaction/build.gradle
- gobblin-core/build.gradle
- gobblin-data-management/build.gradle
- gobblin-distribution/build.gradle
- gobblin-example/build.gradle
- gobblin-metastore/build.gradle
- gobblin-metrics/build.gradle
- gobblin-runtime/build.gradle
- gobblin-salesforce/build.gradle
- gobblin-scheduler/build.gradle
- gobblin-test-harness/build.gradle
- gobblin-yarn/build.gradle
* Added `conjars` repository to `defaultEnvironment.gradle` file and deleted the `repository` blocks in all the sub-projects
* Formatting fixes for `build.gradle` (no logic changes to this file, only formatting changes)
> Adding conjars repositories block for all subprojects

- gobblin-rest-service/gobblin-rest-api/build.gradle
> Fixed rest-api maven publishing

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableFile.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyDataPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/publisher/CopyEventSubmitterHelper.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/CopyableFileTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/CopyableFileUtils.java
distcp should emit origin and upstream timestamp for dataset and file publish events
> distcp should emit origin and upstream timestamp for dataset and file publish events

- gobblin-distribution/build.gradle
@ydai can you review?
* Fixes the tarball build
* Added the version to the name of the tarball
> Fixing tarball build

- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
- gobblin-core/src/main/java/gobblin/writer/FsDataWriter.java
NOTE: duplicates were being added to the list due to task retries
> Ensure that the output file list does not contain duplicates

- gobblin-data-management/src/test/java/gobblin/data/management/retention/sql/SqlUdfs.java
> Fix import

- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
We rely on fs.mkdirs to create the parent directories of a CopyableFile if not exists. If the directories exist (created by other mappers), fs.mkdirs will return a false which we ignore.
> Fix parent directory creation in distcp-ng

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyConfiguration.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopyableFile.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/CopyableFileTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/RecursiveCopyableDatasetTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/extractor/InputStreamExtractorTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/publisher/CopyDataPublisherTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/recovery/RecoveryHelperTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterTest.java
> Add option to set group for distcp-ng

- gobblin-admin/src/main/java/gobblin/cli/CliTablePrinter.java
- gobblin-admin/src/main/java/gobblin/cli/JobCommand.java
@eogren Can you review these minor changes?
> Fixed findbugs issues with gobblin-admin.

- gobblin-metastore/src/main/java/gobblin/metastore/util/StateStoreCleaner.java
> Fix hanging StateStoreCleaner

- gobblin-utility/src/main/java/gobblin/util/ParallelRunner.java
- gobblin-utility/src/test/java/gobblin/util/ParallelRunnerTest.java
> Change ParallelRunner.close to wait for all futures to finish

- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
Fix for https://github.com/linkedin/gobblin/issues/561
* This should ensure that for a given `WorkUnitState` its data has been committed before the `WorkUnitState.WorkingState` is set to `COMMITTED`.
* The solution is a bit of hack because the code will now commit data for all `WorkUnitState`s first and then it will set the `WorkingState` of each `WorkUnitState` to `COMMITTED`
* This is better than the previous behavior as it may cause duplicate data, but it will never drop data
* If users need exactly-once guarantees they should use the `CommitSequencePublisher` from the exactly-once POC
> Issue #561 - fix for BaseDataPublisher to mark WorkingState correctly

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
I am trying to use the MRCompactor. I have added a launcher class similar to ```AzkabanCompactionJobLauncher``` (not included in this PR). While testing it I ran into a ```ConcurrentModificationException``` in MRCompactor. Looking at the code, this seems to happen because we are mutating a ```HashSet``` in ```createJobPropsForDataset``` while iterating on it in ```createJobPropsForDatasets```. This PR attempts to fix this.
> Fix a ConcurrentModificationException in MRCompactor

- build.gradle
Will address users who are hitting the error in https://github.com/linkedin/gobblin/issues/615
> Removing compile dependency on JCE

- gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/FsDatasetStateStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskStateCollectorService.java
> Fix race condition in FsStateStore

- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegProps.java
> Fixing findbugs warnings in HiveRegProps

- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
> Don't send an email on shutdown when email notifications are disabled.

- gobblin-core/src/main/java/gobblin/publisher/BaseDataPublisher.java
> Fix for #719

- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobScheduler.java
> Fix for #725

- gobblin-data-management/src/test/java/gobblin/data/management/copy/ConcurrentBoundedWorkUnitListTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriterTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/DatasetVersionFinderTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/retention/TimeBasedRetentionPolicyTest.java
- gobblin-metrics/src/test/java/gobblin/metrics/callback/NotificationStore.java
@ibuenros  Please review. Thanks.
> Fix import dependency

- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/CleanableDatasetBase.java
With dataset management we allow per dataset blacklist as opposed to comma separated list of blacklists in the job props file. The pr sets dataset backlist using Config
@ibuenros or @ydai1124 can you review?
> Per dataset retention blacklist

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/gobblin/password/PasswordManager.java
> Add ability to configure the encryption_key_loc filesystem

- gobblin-metrics/build.gradle
- gobblin-metrics/src/main/java/gobblin/metrics/context/filter/ContextFilterFactory.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/sla/SlaEventSubmitter.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaSchemaRegistry.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ContextAwareReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/ScheduledReporter.java
> Fix for #739

- bin/gobblin-mapreduce.sh
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaRecord.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleJsonExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleJsonSource.java
A json kafka source extending from KafkaSimpleSource to output kafka messages as json with offset, key and payload.
> Add kafka simple json source

- gobblin-utility/src/main/java/gobblin/util/AvroFlattener.java
- gobblin-utility/src/test/java/gobblin/util/AvroFlattenerTest.java
- gobblin-utility/src/test/resources/flattenAvro/arrayWithinRecordWithinArrayWithinRecord_flattened.json
- gobblin-utility/src/test/resources/flattenAvro/arrayWithinRecordWithinArrayWithinRecord_original.json
- gobblin-utility/src/test/resources/flattenAvro/optionWithinOptionWithinRecord_flattened.json
- gobblin-utility/src/test/resources/flattenAvro/optionWithinOptionWithinRecord_original.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinArrayWithinArray_flattened.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinArrayWithinArray_original.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinMapWithinMap_flattened.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinMapWithinMap_original.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinOptionWithinRecord_flattened.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinOptionWithinRecord_original.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinRecordWithinRecord_flattened.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinRecordWithinRecord_original.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinRecord_flattened.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinRecord_original.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinUnionWithinRecord_flattened.json
- gobblin-utility/src/test/resources/flattenAvro/recordWithinUnionWithinRecord_original.json
> Flatten Avro Schema to make it optimal for ORC

- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
- gobblin-tunnel/build.gradle
- gobblin-tunnel/src/main/java/gobblin/tunnel/ProxySetupHandler.java
- gobblin-tunnel/src/main/java/gobblin/tunnel/ReadWriteHandler.java
Hey @kunalkandekar there were a few FindBugs warnings introduced in #541, mostly around specifying Charset encodings, and adding defaults in switch case statements. Could you take a quick look and make sure everything looks ok?
> Fixing FindBugs warnings for gobblin-tunnel from #541

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
> Parallize late data copy

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanTags.java
- gobblin-yarn/build.gradle
- gobblin-yarn/src/main/java/gobblin/yarn/token/TokenUtils.java
> Add TokenUtils

- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegistrationUnit.java
- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreUtils.java
- gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveRegistrationPolicyBase.java
- gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveSnapshotRegistrationPolicy.java
> Add snapshot Hive registration policy

- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSStoreMetadata.java
> Fix findbugs warning

- gobblin-config-management/gobblin-config-core/src/main/java/gobblin/config/store/hdfs/SimpleHDFSStoreMetadata.java
@sahilTakiar can you review this small change?
> Fix permission of store metadata file to allow read access to all users

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
> Ensure that jobs cleanup correctly

- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcProvider.java
@sahilTakiar Can you take a look?
> fix for issue #529

- gobblin-utility/build.gradle
- gobblin-utility/src/main/java/gobblin/util/concurrent/CancellableTask.java
- gobblin-utility/src/main/java/gobblin/util/concurrent/HashedWheelTimerTaskScheduler.java
- gobblin-utility/src/main/java/gobblin/util/concurrent/ScheduledExecutorServiceTaskScheduler.java
- gobblin-utility/src/main/java/gobblin/util/concurrent/ScheduledTask.java
- gobblin-utility/src/main/java/gobblin/util/concurrent/TaskScheduler.java
- gobblin-utility/src/main/java/gobblin/util/concurrent/TaskSchedulerFactory.java
- gobblin-utility/src/main/java/gobblin/util/concurrent/TaskSchedulerType.java
- gobblin-utility/src/main/java/gobblin/util/logs/LogCopier.java
- gobblin-utility/src/test/java/gobblin/util/concurrent/AutoResetEvent.java
- gobblin-utility/src/test/java/gobblin/util/concurrent/HashedWheelTimerTaskSchedulerTest.java
- gobblin-utility/src/test/java/gobblin/util/concurrent/ScheduledExecutorServiceTaskSchedulerTest.java
- gobblin-utility/src/test/java/gobblin/util/concurrent/TaskSchedulerFactoryTest.java
- gobblin-utility/src/test/java/gobblin/util/concurrent/TaskSchedulerTest.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinApplicationMaster.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinWorkUnitRunner.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnConfigurationKeys.java
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnLogSource.java
@sahilTakiar @ibuenros Can you please review this fix for #729. Also, add anyone else on your side who has had experience with this.
> Switch LogCopier from ScheduledExecutorService to HashedWheelTimer

- gobblin-compaction/build.gradle
> (#830) excluding hive-exec from gobblin-compaction

- _nav_pages/documentation.md
- _posts/2016-03-11-docs-update.md
* Update GitHub pages to point to new documentation system
* Adding post about new documentation system
> Updating documentation page, adding post about new doc system

- README.md
* Removing IRC batch and we discussed its no longer going to be supported
* Updating `README.md` file so that it points to new documentation on ReadTheDocs
@pcadabam can you review?
> Updating README.md to reference ReadTheDocs documentation

- gobblin-azkaban/src/main/java/gobblin/azkaban/AzkabanTags.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/DatasetCleaner.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/RetentionEvents.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/ConfigurableCleanableDataset.java
- gobblin-utility/src/main/java/gobblin/util/AzkabanTags.java
- gobblin-utility/src/main/java/gobblin/util/reflection/GobblinConstructorUtils.java
- gobblin-utility/src/test/java/gobblin/util/reflection/GobblinConstructorUtilsTest.java
@ibuenros or @ydai1124 can you review?
> Add failure events when dataset.clean() throws exception

- gobblin-api/src/main/java/gobblin/testing/AssertWithBackoff.java
- gobblin-runtime/src/test/java/gobblin/scheduler/JobConfigFileMonitorTest.java
- gobblin-utility/src/test/java/gobblin/util/SchedulerUtilsTest.java
@sahilTakiar @zliu41 This should hopefully fix one of the issues I have see with the Travis builds: 
```
Formatting ./build/gobblin-scheduler/test-results/TEST-gobblin.scheduler.JobConfigFileMonitorTest.xml
=====================================================
Testsuite: gobblin.scheduler.JobConfigFileMonitorTest
Tests run: 3, Failures: 1, Errors: 0, Time elapsed: 7.66 sec
--------- ----------- ---------
Testcase: testAddNewJobConfigFile took 7.656 FAILURE
java.util.concurrent.TimeoutException: Timeout waiting for condition '4 scheduled jobs'. java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException: Timeout waiting for condition '4 scheduled jobs'.
at gobblin.testing.AssertWithBackoff.assertTrue(AssertWithBackoff.java:185)
at …
```
> Changed a couple of tests which write to files so that they will always have a fresh directory

- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ConfigurableGlobDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/MultiCleanableDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/MultiDatasetFinder.java
Bugs fixed -
1. Support deprecated key gobblin.retention.dataset.profile.class
2. Add null check to array of FileStatus returned by fs.globStatus
@tuGithub can you review?
> gobblin retention bug fixes

- build.gradle
Looks like there are quite a few bug fixes / improvements in 1.8.0. https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310911&version=12323299
Release note mentioned some backward incompatible changes. Tested on Kafka ingestion and compaction and no issue popped up.
> Update Avro version to 1.8.0

- build.gradle
1.8.0 not currently supported in internal multiproduct build.
> Revert "Update Avro version to 1.8.0"

- gobblin-runtime/src/main/java/gobblin/runtime/BoundedBlockingRecordQueue.java
@sahilTakiar This change is to improve performance:
```
Benchmark                        Mode  Cnt      Score     Error   Units
Benchmarks.arrayBlockingQueue   thrpt   20  30779.313 ± 677.491  ops/ms
Benchmarks.linkedBlockingQueue  thrpt   20  19899.541 ± 769.676  ops/ms
```
> Change BoundedBlockingRecordQueue to be backed by ArrayBlockingQueue

- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java
The purpose is to resolve conflict between two Hive registration jobs running simultaneously.
The original logic may cause create table/add partition failure (`MySQLIntegrityConstraintViolationException` - primary key already exists in the metastore table) even if `client.tableExists` returns false.
The new logic first tries to create table/add partition, if unsuccessful, will try to alter table if needed, and throws `IOException` if unsuccessful again.
> Minor revision to create table/add partition logic in HiveMetaStoreBasedRegister

- gobblin-data-management/src/test/java/gobblin/data/management/util/PathUtilsTest.java
- gobblin-utility/src/main/java/gobblin/util/PathUtils.java
@ibuenros can you review this?
> Fix Path Ancestor check

- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/CleanableDatasetBase.java
- Log when empty directories are deleted/failed
- Fix for not deleting dataset root directory
> Log empty directory deletes

- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/DateTimeDatasetVersionFinder.java
> Fix NPE in DateTimeDatasetVersionFinder

- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/GlobModTimeDatasetVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/UnixTimestampVersionFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/version/finder/WatermarkDatasetVersionFinder.java
> Fix NPE in datasetversion finder

- gobblin-runtime/src/main/java/gobblin/runtime/JobContext.java
Previously if `data.publisher.job.type` is empty it would fail.
> Make it possible to specify empty job data publisher

- build.gradle
- gobblin-docs/developer-guide/CodingStyle.md
- gobblin-docs/developer-guide/IDE-setup.md
- gobblin-docs/developer-guide/files/codestyle-intellij-gobblin.xml
Fixed out of the box integration with idea. 
./gradlew -PuseHadoop2 idea 
and File > Open in idea works without errors (earlier broke on java 7 language level)
Language level set to java 7, docs updated, codestyle checked in (with import order fixed based on coding style).
> IDEA integration improvement

- gobblin-data-management/src/main/java/gobblin/data/management/policy/CombineSelectionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/NewestKSelectionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/policy/VersionSelectionPolicy.java
>  Make VersionSelectionPolicy to work with any DatasetVersion

- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveCopyEntityHelper.java
Allows not deleting files when deregistering a Hive partition in distcp.
> Add delete methods when deregistering Hive partitions in distcp.

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveCopyEntityHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDataset.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/EventSubmitter.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/MultiTimingEvent.java
Adds timers to Hive distcp work unit generation.
Also adds a `MultiTimingEvent` class that emits a single event for timings of different stages in a process.
> Added instrumentation to Hive copy.

- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnitBinPacker.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnitWeighter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-utility/src/main/java/gobblin/util/binpacking/FieldWeighter.java
- gobblin-utility/src/main/java/gobblin/util/binpacking/WorstFitDecreasingBinPacking.java
- gobblin-utility/src/test/java/gobblin/util/binpacking/WorstFitDecreasingBinPackingTest.java
Implemented bin packing for distcp-ng. Made it generic enough to be usable by other Gobblin flows.
> Bin pack distcp-ng work units.

- gobblin-yarn/src/main/java/gobblin/yarn/GobblinHelixJobLauncher.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinHelixJobLauncherTest.java
> Cleanup the helix job when closing the GobblinHelixJobLauncher

- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaRecord.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/restapi/RestApiExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/ConcurrentBoundedWorkUnitList.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/RetentionEvents.java
- gobblin-data-management/src/main/java/gobblin/util/commit/DeleteFileCommitStep.java
- gobblin-data-management/src/main/java/gobblin/util/test/RetentionTestDataGenerator.java
- gobblin-hadoop2/src/main/java/gobblin/hadoop/token/TokenUtils.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegistrationUnit.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveTable.java
- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreUtils.java
- gobblin-metastore/src/main/java/gobblin/metastore/DatabaseJobHistoryStore.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/JobEvent.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/MultiTimingEvent.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/TaskEvent.java
- gobblin-metrics/src/main/java/gobblin/metrics/graphite/GraphiteEventReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/influxdb/InfluxDBEventReporter.java
- gobblin-metrics/src/main/java/gobblin/metrics/reporter/util/AvroSerializer.java
- gobblin-runtime/src/main/java/gobblin/runtime/locks/ZookeeperBasedJobLock.java
- gobblin-salesforce/src/main/java/gobblin/salesforce/SalesforceExtractor.java
- gobblin-utility/src/main/java/gobblin/util/io/GsonInterfaceAdapter.java
- ligradle/findbugs/findbugsExclude.xml
* Fixing about 60 FindBugs warnings
* Excluding FindBugs on `gobblin.audit.values.auditor`
> Fixing findbugs errors

- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveCopyEntityHelper.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/hive/HiveCopyEntityHelperTest.java
also set the owner of the hive table as the flow executor
> Distcp ng handle directory structure copy 

- gobblin-data-management/build.gradle
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HdfsBasedSchemaProvider.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HdfsBasedUpdateProvider.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HdfsBasedUpdateProviderFactory.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveAvroSchemaProvider.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveConvertExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveQueryExecutionWriter.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveQueryWriterBuilder.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveSourceWatermarker.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveUnitUpdateProvider.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/HiveUnitUpdateProviderFactory.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/LongWatermark.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/QueryBasedHiveConversionEntity.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/TableLevelWatermarker.java
- gobblin-data-management/src/main/java/gobblin/data/management/convertion/umls.ucls
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveLocationDescriptor.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveUtils.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/HiveSourceTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/mock/MockUpdateProvider.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/mock/MockUpdateProviderFactory.java
- gobblin-example/src/main/resources/hive-avro-to-orc.pull
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveMetastoreClientPool.java
- gobblin-utility/src/main/java/gobblin/util/PathUtils.java
- gobblin-utility/src/main/java/gobblin/util/reflection/GobblinConstructorUtils.java
Detailed design for this change can be found at https://docs.google.com/document/d/1PjvhDzvPxIjsb-gaRk1iiM7R8LyJHU3620DXmfoOeBs/edit?ts=57283d21#heading=h.z2tj4tr1he0q
This change implements everything discussed in the above design.
@abti  and @zliu41 can you review?
> Avro2orc Source/Converter/Extractor/Publisher

- gobblin-yarn/src/test/java/gobblin/yarn/GobblinApplicationMasterTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinHelixJobLauncherTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinWorkUnitRunnerTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/JobConfigurationManagerTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/YarnSecurityManagerTest.java
- gobblin-yarn/src/test/resources/GobblinApplicationMasterTest.conf
- gobblin-yarn/src/test/resources/GobblinHelixJobLauncherTest.conf
- gobblin-yarn/src/test/resources/GobblinWorkUnitRunnerTest.conf
- gobblin-yarn/src/test/resources/GobblinYarnAppLauncherTest.conf
- gobblin-yarn/src/test/resources/YarnSecurityManagerTest.conf
> Using new zk port numbers for unit tests

- gobblin-data-management/src/main/java/gobblin/data/management/convertion/hive/LongWatermark.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveUtils.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/WhitelistBlacklist.java
- ligradle/findbugs/findbugsExclude.xml
- travis/build.sh
* Minor change related to https://github.com/linkedin/gobblin/pull/970
* Setting the Travis Build to fail if new FindBugs warnings are introduced
* Fixing a few FindBugs warnings that were introduced since https://github.com/linkedin/gobblin/pull/970 was merged
> Fixing new FindBugs warnings, and setting Travis build to fail if new FindBugs warnings are added

- gobblin-api/src/main/java/gobblin/writer/FluentDataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/config/ConfigBuilder.java
- gobblin-core/src/main/java/gobblin/writer/http/AbstractHttpWriter.java
- gobblin-core/src/main/java/gobblin/writer/http/AbstractHttpWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/http/DelegatingHttpClientConnectionManager.java
- gobblin-core/src/main/java/gobblin/writer/http/HttpWriterDecoration.java
- gobblin-core/src/main/java/gobblin/writer/http/HttpWriterDecorator.java
- gobblin-core/src/main/java/gobblin/writer/http/UnexpectedResponseException.java
@jinhyukchang can you have a look ?
> Initial commit for HTTP Writer APIs

- gobblin-runtime/src/main/java/gobblin/runtime/app/ServiceBasedAppLauncher.java
@sahilTakiar Additional services that are configured via the config file should be able to be passed properties so they can configure themselves.
> Enable creating services which accept `Properties` for configuration

- gobblin-core/src/main/java/gobblin/source/extractor/extract/kafka/KafkaWrapper.java
@zliu41 can you review ?
It seems like the brokers can sometimes return partial partition metadata that can throw NPEs . This should cause those topics to be ignored.
Please see ETL-4495 for more info.
> Making kafka metadata read more resillient to issues with the brokers

- gobblin-docs/user-guide/Hive-Registration.md
- mkdocs.yml
@chavdar @sahilTakiar can you review?
> Add Hive registration doc

- gobblin-core/src/main/java/gobblin/source/extractor/partition/Partitioner.java
The previous PR mess up,sorry for that,open a new one.
> Fixing SOURCE_QUERYBASED_LOW_WATERMARK_BACKUP_SECS no default value

- gobblin-docs/user-guide/Compaction.md
The unified way of compaction job execution ([PR#952](https://github.com/linkedin/gobblin/pull/952)) should be documented.
> Document changes in PR#952

- gobblin-data-management/src/main/java/gobblin/data/management/copy/TimestampBasedCopyableDataset.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/TimestampBasedCopyableDatasetTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/policy/TimeBasedSelectionPolicyTest.java
Moved RB655435 to github. @chavdar Can you take a look?
> Create TimestampBasedCopyableDataset and version selection policy

- .travis.yml
- build.gradle
- travis/test-build.sh
- travis/test-coverage.sh
- travis/test-default.sh
- travis/test-group1.sh
- travis/test-groups.inc
These changes should create a matrix of Travis VMs so we can run test in parallel and afford more logging.
> Adding parallel test Travis VMs

- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java
> Make some tests single-threaded to avoid race conditions

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/events/EventConstants.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/util/HiveSourceUtils.java
> Add sla events for avro to orc conversion

- gobblin-api/src/main/java/gobblin/source/extractor/ComparableWatermark.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/SubsetFilesCopyableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/SubsetFilesCopyableDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/WatermarkBasedCopyableFileFilter.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/watermark/CopyableFileWatermarkGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/watermark/CopyableFileWatermarkHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/watermark/FullPathCopyableFileWatermarkGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/watermark/StringWatermark.java
- gobblin-data-management/src/main/java/gobblin/data/management/dataset/DatasetUtils.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ConfigurableGlobDatasetFinder.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/CopySourceTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/WatermarkBasedCopyableFileFilterTest.java
- gobblin-utility/src/main/java/gobblin/util/filters/RegexPathFilter.java
- gobblin-utility/src/main/java/gobblin/util/io/AdditionalCloseableInputStream.java
- gobblin-utility/src/main/java/gobblin/util/io/CloseableHttpConn.java
- gobblin-utility/src/test/java/gobblin/util/filters/RegexPathFilterTest.java
- gobblin-utility/src/test/java/gobblin/util/reflection/GobblinConstructorUtilsTest.java
https://docs.google.com/document/d/1EmjQLmpvbFcBcFdCQSC46MkQ_EiowGDG8WLt729Zwdg/
> ETL-4470: Implementation of http filer puler using Distcp-ng

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/HiveAvroToOrcConverter.java
Made HiveAvroToOrcConverter compatible with Hive v0.13 version
> Made HiveAvroToOrcConverter compatible with Hive v0.13 version

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/entities/SchemaAwareHiveTable.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryUtils.java
Fixed findbug issues with data management
> Fixed findbug issues with data management

- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/arrayWithinRecordWithinArrayWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/optionWithinOptionWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinOptionWithinRecord_nested.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinRecordWithinRecord_flattened.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/recordWithinRecordWithinRecord_nested.ddl
Minor fix to reflect updated DDL statements
> Fixed test resources for fixing test cases

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/provider/UpdateProviderFactory.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/HiveSourceTest.java
> AvroToOrc bug fix to not find update time for partitions older than lookback

- gobblin-cluster/src/main/java/gobblin/cluster/GobblinClusterManager.java
- gobblin-cluster/src/main/java/gobblin/cluster/GobblinTaskRunner.java
Fix findbugs with gobblin-cluster
> Fix findbugs with gobblin-cluster

- gobblin-salesforce/src/main/java/gobblin/salesforce/SalesforceExtractor.java
Adding a security token for access from non-whitelisted IPs
> Adding security token to Salesforce bulk API login

- gobblin-salesforce/src/main/java/gobblin/salesforce/SalesforceExtractor.java
> Fixing a findbugs warning in SalesforceExtractor

- gobblin-data-management/build.gradle
- gobblin-example/src/main/resources/wikipedia-kafka.pull
- gobblin-kafka/build.gradle
- gobblin-runtime/build.gradle
@abti, @sahilTakiar :  this should be a quick one.
> Confluent schema registry example for kafka writer

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/AvroSchemaManager.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java
> Refactored to rename HiveAvroORCQueryUtils to HiveAvroORCQueryGenerator

- build.gradle
@abti @shirshanka  can you review?
> Change findbugs report to html from xml

- README.md
- gobblin-docs/Powered-By.md
- mkdocs.yml
Added powered by section in wiki for companies using Gobblin.
> Added powered by section in wiki for companies using Gobblin

- gobblin-docs/project/Talks-and-Tech-Blogs.md
Added Gobblin meetup June 2016 presentations on Talks and Tech Blogs wiki
> Added Gobblin meetup June 2016 presentations on Talks and Tech Blogs wiki

- gobblin-compaction/src/main/java/gobblin/hive/util/HiveJdbcConnector.java
Added simulate mode in Hive JDBC Connector to simulate query execution
> Added simulate mode in Hive JDBC Connector to simulate query execution

- gobblin-docs/project/Talks-and-Tech-Blogs.md
Added videos from June 2016 meetup to talks-and-tech-blogs wiki page. Minor change, self approving.
> Added videos from June 2016 meetup to talks-and-tech-blogs wiki page

- gobblin-docs/developer-guide/Contributing.md
> Updating the code contributions documentation

- gobblin-docs/project/Talks-and-Tech-Blogs.md
Update Gobblin on AWS video presentation link with right start time in playback. Minor change, self approving
> Update Gobblin on AWS video presentation link with right start time in playback

- gobblin-docs/Powered-By.md
Added Paypal to powered by wiki page. Minor addition to wiki, self approving.
> Added Paypal to powered by wiki page

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
Added Hive query generation to optionally support explicit database names
> Added Hive query generation to optionally support explicit database names

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
Added comments to indicate if DDL and DML generation are being done using source or destination schemas in Hive Avro to ORC
> Added comments to indicate if DDL and DML generation are being done using source or destination schemas in Hive Avro to ORC

- gobblin-runtime/src/main/java/gobblin/runtime/api/Configurable.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/GobblinInstanceDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/GobblinInstanceLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobCatalogListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecution.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpec.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecMonitor.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecScheduler.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/MutableJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/StandardRunControls.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/package-info.java
@ibuenros @pcadabam @tuGithub @ydai1124 @abti @vasanthrajamani @autumnust Can you review ?
> Initial commit for new gobblin launch interfaces

- gobblin-runtime/build.gradle
> Add missing dependency

- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpec.java
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
It incorrectly converts strings to numbers. @pcadabam can you review ?
> Revert changes to ConfigUtils

- gobblin-utility/src/test/java/gobblin/util/HadoopUtilsTest.java
> Capture exceptions correctly in HadoopUtilsTest.testSafeRenameRecursively

- gobblin-compaction/src/main/java/gobblin/hive/util/HiveJdbcConnector.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveValidationQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
Fixed bugs with Hive conversion Validation job, did code cleanup in Hive JDBC connector, removed an unusable buggy query implementation
> Fixed bugs with Hive conversion Validation job, did code cleanup in Hive JDBC connector, removed an unusable buggy query implementation

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
Changed Hive conversion validation job to use HIVE_DATASET_CONFIG_PREFIX consistent with HiveAvroToOrcSource
> Changed Hive conversion validation job to use HIVE_DATASET_CONFIG_PREFIX consistent with HiveAvroToOrcSource

- build.gradle
For CI integration
@pcadabam Can you review?
> Add gradle property withFindBugsXmlReport to enable XML FindBugs reports

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveSchemaEvolutionTest.java
Made Hive schema evolution commands compatible with older Hive versions
> Made Hive schema evolution commands compatible with older Hive versions

- .travis.yml
- build.gradle
- gobblin-runtime/src/test/java/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- travis/test-group1.sh
Checking if some of the intermittent mysql failures are addressed
> Upgrade wix-embedded-mysql 

- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionState.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionStateListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionStatus.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecMonitorFactory.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecSchedule.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecScheduler.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/package-info.java
- gobblin-runtime/src/test/java/gobblin/runtime/std/JobExecutionUpdatable.java
@ibuenros @autumnust can you review?
> JobLauncher interface update

- gobblin-data-management/src/main/java/gobblin/data/management/copy/SubsetFilesCopyableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/SubsetFilesCopyableDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/WatermarkBasedCopyableFileFilter.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/WatermarkBasedCopyableFileFilterTest.java
@ibuenros Small one. Can you review?
> Adding options in watermarkCopyableFileFilter and some refactoring

- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
> Not fail the task if metricsReport failed to be stopped.

- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
@chavdar very quick one, can you review? Thanks!
> Schema files (schema.avsc) will be written with 774 permission.

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/events/EventConstants.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
> Parallalize Avro to Orc validation job

- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/MultiDatasetFinder.java
> Throw exception when retention dataset finder fails to initialize

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/provider/HdfsBasedUpdateProvider.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/hive/HiveConfigClientUtils.java
> [AvroToOrc] cache data modTime to reduce too many HDFS calls

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-utility/src/main/resources/templates/wikiSample.template
- gobblin-utility/src/test/java/gobblin/util/TemplateTest.java
- gobblin-utility/src/test/resources/templates/distcp-ng-hive.template
- gobblin-utility/src/test/resources/templates/distcp-ng.template
- gobblin-utility/src/test/resources/templates/test.template
change the key name of required.attributes to  gobblin.template.required_attributes
> change the key name of required.attributes

- conf/gobblin-standalone.properties
- gobblin-runtime/src/main/java/gobblin/scheduler/PathAlterationListenerAdaptorForMonitor.java
- gobblin-utility/src/main/resources/templates/gobblin-kafka.template
- simple kafka template 
- file detector running period (30s) added into gobblin/conf/gobblin-standalone.properties
> Kafka-template

- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/AvroFsHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopFsHelper.java
- gobblin-core/src/test/java/gobblin/source/extractor/hadoop/HadoopFsHelperTest.java
Moving avro-agnostic methods from AvroFsHelper to HadoopFsHelper
> Refactor methods between HadoopFsHelper and AvroFsHelper

- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobCatalogListenersContainer.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionState.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionStateListenerContainer.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobLifecycleListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobLifecycleListenersContainer.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecScheduler.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecSchedulerListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpecSchedulerListenersContainer.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/MutableJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/DefaultGobblinInstanceDriverImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/CachingJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/InMemoryJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/JobCatalogListenersList.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_exec/JobLauncherExecutionDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/DefaultJobSpecSchedulerListenerImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/ImmediateJobSpecScheduler.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/JobSpecSchedulerListeners.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/DefaultJobLifecycleListenerImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/FilteredJobLifecycleListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/JobExecutionStateListeners.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/JobLifecycleListenersList.java
- gobblin-runtime/src/main/java/gobblin/runtime/std/JobSpecFilter.java
- gobblin-runtime/src/test/java/gobblin/runtime/api/TestJobExecutionState.java
- gobblin-runtime/src/test/java/gobblin/runtime/job_catalog/TestJobCatalogListenersList.java
- gobblin-runtime/src/test/java/gobblin/runtime/std/TestFilteredJobLifecycleListener.java
- gobblin-runtime/src/test/java/gobblin/runtime/std/TestJobSpecFilter.java
- gobblin-utility/src/main/java/gobblin/util/callbacks/CallbacksDispatcher.java
A lot of files touched with mostly mechanical changes.
Summary of changes:
- Adding weak listeners which will get automatically GCed
- Adding JobSpecSchedulerListener and related classes to listen to scheduling events
- Extending the JobLifecycleListener with JobSpecSchedulerListener and onJobLaunch(JobExecutionDriver jobDriver)
- Adding JobSpecFilter and FilteredJobLifecycleListener 
@ibuenros @autumnust  Can you review?
> New std driver2

- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDatasetFinder.java
> Add config store uri builder for hive datasets

- gobblin-runtime/build.gradle
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobCatalogListener.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpec.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/MutableJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/FSJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/FSPathAlterationListenerAdaptor.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/ImmutableFSJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/InMemoryJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/JobCatalogListenersList.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/FSJobCatalogHelper.java
- gobblin-runtime/src/main/java/gobblin/scheduler/JobScheduler.java
- gobblin-runtime/src/test/java/gobblin/runtime/api/TestJobSpec.java
- gobblin-runtime/src/test/java/gobblin/runtime/job_catalog/TestFSJobCatalog.java
- gobblin-runtime/src/test/java/gobblin/runtime/job_catalog/TestInMemoryJobCatalog.java
- gobblin-runtime/src/test/java/gobblin/runtime/util/FSJobCatalogHelperTest.java
- gobblin-runtime/src/test/java/gobblin/scheduler/JobConfigFileMonitorTest.java
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
- gobblin-utility/src/main/java/gobblin/util/PathUtils.java
- gobblin-utility/src/main/java/gobblin/util/PullFileLoader.java
- gobblin-utility/src/main/java/gobblin/util/SchedulerUtils.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/FileStatusEntry.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/PathAlterationDetector.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/PathAlterationObserver.java
- gobblin-utility/src/test/java/gobblin/util/SchedulerUtilsTest.java
Verison 2 of FSjobcatalog based on refactored SchedulerUtils.(Moving some of the functions into FSjobCatalogLoadingHelper )
Close the original PR. 
This one is cleaner to review. Please take a look at @ibuenros , Thanks.
> Refactor: FSJobCatalog V1 & V2

- gobblin-docs/user-guide/Gobblin-genericLoad
- gobblin-docs/user-guide/Gobblin-template.md
- mkdocs.yml
@ibuenros @chavdar can you review ? Thanks !
> template wiki doc added

- gobblin-core/src/main/java/gobblin/writer/ConsoleWriter.java
- gobblin-core/src/main/java/gobblin/writer/ConsoleWriterBuilder.java
- gobblin-core/src/test/java/gobblin/writer/ConsoleWriterTest.java
- gobblin-example/src/main/resources/wikipedia-console.pull
> Adding a simple console writer to gobblin

- gobblin-docs/case-studies/Hive-Distcp.md
- mkdocs.yml
> Add hive distcp doc

- gobblin-docs/adaptors/Hive-Avro-To-ORC-Converter.md
> Add avro to orc docs

- mkdocs.yml
> Add a tab for avro-to-orc doc

- gobblin-docs/adaptors/Hive-Avro-To-ORC-Converter.md
> Fix avro to orc docs

- gobblin-docs/data-management/Gobblin-Retention.md
> Add hive retention docs

- mkdocs.yml
Self-approving trivial change.
> Updating mkdocs

- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionResult.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionState.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/DefaultGobblinInstanceDriverImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/StandardGobblinInstanceDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_exec/JobLauncherExecutionDriver.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestStandardGobblinInstanceLauncher.java
- gobblin-runtime/src/test/resources/gobblin/runtime/instance/SimpleHelloWorldJob.jobconf
- gobblin-utility/src/main/java/gobblin/util/callbacks/CallbacksDispatcher.java
- gobblin-utility/src/main/java/gobblin/util/test/HelloWorldSource.java
- gobblin-utility/src/main/java/gobblin/util/test/StdoutWriter.java
- gobblin-utility/src/test/java/gobblin/util/test/TestHelloWorldSource.java
Changes:
- Small fixes to new job launcher implementation
- Adding a simple source (HelloWorldSource) for testing purposes and as a potentially very simple introduction to Gobblin.
- Adding a small end-to-end test for instance driver
> Adding a simple end-to-end test for the new Job launcher API

- CHANGELOG.md
This is the initial commit of releasing 0.8.0. It is not completed yet, missing several documentations regarding new features from the team and another PR (kafka writer test) from @shirshanka . @chavdar Can you review the brief structure of the new CHANGELOG?
> Initial commit for releasing 0.8.0

- CHANGELOG.md
> Revert "Initial commit for releasing 0.8.0"

- gobblin-runtime/src/main/java/gobblin/runtime/api/GobblinInstanceDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/GobblinInstanceEnvironment.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/GobblinInstanceLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobExecutionLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/DefaultGobblinInstanceDriverImpl.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/StandardGobblinInstanceDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/StandardGobblinInstanceLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/FSJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/ImmutableFSJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_catalog/InMemoryJobCatalog.java
- gobblin-runtime/src/main/java/gobblin/runtime/job_exec/JobLauncherExecutionDriver.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestDefaultGobblinInstanceDriverImpl.java
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestStandardGobblinInstanceLauncher.java
- gobblin-runtime/src/test/java/gobblin/runtime/job_exec/TestJobLauncherExecutionDriver.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/PathAlterationDetector.java
- gobblin-utility/src/main/java/gobblin/util/filesystem/PathAlterationObserver.java
Add the concept of GobblinInstanceEnvironment to simplify configuration of components
> Add the concept of GobblinInstanceEnvironment 

- gobblin-runtime/src/main/java/gobblin/runtime/instance/StandardGobblinInstanceDriver.java
- gobblin-runtime/src/main/java/gobblin/runtime/instance/StandardGobblinInstanceLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/scheduler/QuartzJobSpecScheduler.java
- gobblin-runtime/src/main/resources/templates/hello-world.template
- gobblin-runtime/src/test/java/gobblin/runtime/instance/TestStandardGobblinInstanceLauncher.java
* Add methods to StandardGobblinInstanceDriver build for standard JobSpecScheduler implementations
* Add hello-world template
> Small new launcher api related fixes

- gobblin-data-management/src/main/java/gobblin/data/management/version/finder/DatePartitionHiveVersionFinder.java
> Use prefix for hive date partition version finder

- gobblin-metrics/src/main/java/gobblin/metrics/ContextAwareMeter.java
Trivial change to make ContextAwareMeter public.
> Making ContextAwareMeter public

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
The list of destination formats is not provided from the job props. It is available from the config store.
> [AvroToOrc] Fix valiation job

- gobblin-core/src/main/java/gobblin/publisher/TimestampDataPublisher.java
> Create publisher to split output by timestamp

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/avro/AvroSchemaManager.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/avro/SchemaNotFoundException.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/extractor/HiveConvertExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
> [AvroToOrc] Handle schema not found exception

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
> [AvroToOrc] Close JDBC connecter

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
> [AvroToOrc] Fix SLA event

- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/TimeBasedRetentionPolicy.java
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
@pcadabam Fix issue ETL-4958. Can you review?
> Add blacklist to filter out typesafe incompatible keys

- gobblin-data-management/src/main/java/gobblin/data/management/version/FileStatusTimestampedDatasetVersion.java
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testMultiVersionAccessControl/daily-retention-with-accessControl.conf
- gobblin-data-management/src/test/resources/retentionIntegrationTest/testMultiVersionAccessControl/setup_validate.conf
> Fix findbugs failures

- gobblin-core/src/main/java/gobblin/converter/EnvelopeSchemaConverter.java
- gobblin-core/src/test/java/gobblin/converter/EnvelopeSchemaConverterTest.java
- gobblin-core/src/test/java/gobblin/converter/KafkaAvroSchemaRegistryForTest.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaAvroSchemaRegistryFactory.java
- gobblin-metrics/src/main/java/gobblin/metrics/kafka/KafkaSchemaRegistryFactory.java
> Create converter for opening GoldenGate envelope schema

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/writer/HiveQueryExecutionWriter.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/testMultiPartition.ddl
- gobblin-data-management/src/test/resources/avroToOrcQueryUtilsTest/testMultiPartition.dml
Fix in partition spec parsing, DDL and DML generation for multi-partition spec support
> Multi-partition spec support fix in Avro to ORC

- gobblin-docs/data-management/Gobblin-Retention.md
> Fix access control docs

- gobblin-core/src/main/java/gobblin/source/extractor/extract/QueryBasedExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/MysqlExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/SqlServerExtractor.java
As https://github.com/linkedin/gobblin/pull/1085 became idle, I've forked the branch and addressed PR comments. This PR is to address the issue addressed in https://github.com/linkedin/gobblin/issues/1065.  
Integration tested with MysqlSource.
> Use workUnitState.getProp on JdbcExtractors

- gobblin-core/src/main/java/gobblin/writer/EnvelopeDataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/SchemaBasedPartitionedDataWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/partitioner/SchemaBasedWriterPartitioner.java
- gobblin-core/src/test/java/gobblin/writer/partitioner/SchemaBasedWriterPartitionerTest.java
@ydai1124 / @chavdar please review
> Add partitioner and data writer builder for envelope schema

- build.gradle
- gobblin-core/build.gradle
- gobblin-core/src/main/java/gobblin/converter/csv/CsvToJsonConverterV2.java
- gobblin-core/src/main/java/gobblin/retry/RetryerFactory.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/google/GoogleAnalyticsUnsampledExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/google/GoogleAnalyticsUnsampledSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/google/GoogleCommon.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/google/GoogleCommonKeys.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/google/GoogleDriveExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/google/GoogleDriveFileSystem.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/google/GoogleDriveFsHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/google/GoogleDriveSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/CsvFileDownloader.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/FileBasedSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/SizeAwareFileBasedHelperDecorator.java
- gobblin-core/src/main/java/gobblin/source/extractor/hadoop/HadoopFsHelper.java
- gobblin-core/src/test/java/gobblin/converter/csv/CsvToJsonConverterV2Test.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/google/GoogleAnalyticsUnsampledExtractorTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/google/GoogleDriveFileSystemTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/google/GoogleDriveFsHelperTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/filebased/GoogleDriveSourceTest.java
- gobblin-core/src/test/resources/converter/csv/10_fields.json
- gobblin-core/src/test/resources/converter/csv/11_fields_with_null.json
- gobblin-core/src/test/resources/converter/csv/schema_with_10_fields.json
- gobblin-core/src/test/resources/converter/csv/schema_with_11_fields.json
- gobblin-example/src/main/resources/google-analytics-unsampledreport-to-avro.pull
- gobblin-utility/src/main/java/gobblin/util/ConfigUtils.java
- gobblin-utility/src/main/java/gobblin/util/io/SeekableFSInputStream.java
Gobblin Google Analysis Source with Google Drive Source
- Supports Google Analysis unsampled report.
- Unit test passed
- Integration passed
- New CSVFileDownloader that conforms RFC 4180 via leveraging OpenCSV
- New CsvToJsonConverterV2 that supports customization.
> Gobblin Google Analysis Source / Google Drive Source

- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpFsHelper.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/sftp/SftpLightWeightFileSystem.java
Fix for issue https://github.com/linkedin/gobblin/issues/1319
> Disconnect SFTP channel when inputstream is closed

- gobblin-core/src/main/java/gobblin/publisher/TimestampDataPublisherWithHiveRegistration.java
> Add publisher for hive registration of timestamp paths

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/watermarker/PartitionLevelWatermarker.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/watermarker/TableLevelWatermarker.java
> Change verbose logs to debug

- build.gradle
- gobblin-admin/build.gradle
- gobblin-rest-service/gobblin-rest-api/build.gradle
- gobblin-rest-service/gobblin-rest-client/src/main/java/gobblin/rest/JobExecutionInfoClient.java
- gobblin-rest-service/gobblin-rest-server/build.gradle
- gobblin-runtime/build.gradle
- gobblin-tunnel/build.gradle
- gradle/wrapper/gradle-wrapper.properties
I needed to update pegasus dependency too.
> Move gobblin to Gradle 2.13

- gobblin-core/src/main/java/gobblin/converter/objectstore/ObjectStoreConverter.java
- gobblin-core/src/main/java/gobblin/converter/objectstore/ObjectStoreDeleteConverter.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreClient.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreDeleteOperation.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreOperation.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreOperationBuilder.java
- gobblin-core/src/main/java/gobblin/writer/objectstore/ObjectStoreWriter.java
- gobblin-core/src/test/java/gobblin/converter/objectstore/ObjectStoreDeleteConverterTest.java
- gobblin-core/src/test/java/gobblin/writer/objectstore/ObjectStoreWriterTest.java
Some bug fixes to object store writer.
@ibuenros can you review
> Objectstore bug fixes

- gobblin-compaction/build.gradle
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroDeltaFieldNameProvider.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/AvroKeyDedupReducer.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/ConfBasedDeltaFieldProvider.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/avro/FieldAttributeBasedDeltaFieldsProvider.java
- gobblin-compaction/src/test/java/gobblin/compaction/mapreduce/avro/AvroKeyDedupReducerTest.java
- gobblin-compaction/src/test/java/gobblin/compaction/mapreduce/avro/ConfBasedDeltaFieldProviderTest.java
- gobblin-compaction/src/test/java/gobblin/compaction/mapreduce/avro/FieldAttributeBasedDeltaFieldsProviderTest.java
Provide two ways of getting delta field in reducer. One is conf based, and another is from the record schema.
> ETL-5076: Delta support in gobblin compaction

- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionRecordCountEvent.java
- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionSlaEventHelper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
> Add more metadata to compaction events

- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
> Make workUnitsMap synchronoized

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-cluster/src/main/java/gobblin/cluster/GobblinHelixTask.java
- gobblin-cluster/src/main/java/gobblin/cluster/GobblinHelixTaskStateTracker.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CloseableFsCopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/extractor/CloseableFsFileAwareInputStreamExtractor.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/extractor/FileAwareInputStreamExtractor.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/ForkException.java
- gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskStateTracker.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/local/LocalTaskStateTracker.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/GobblinOutputCommitter.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTaskStateTracker.java
- gobblin-runtime/src/test/java/gobblin/runtime/TaskTest.java
Design doc: https://docs.google.com/document/d/1Vf5A7pHbFKwr7-Bbw2X3zBBVZSvT7HXEPE6bsi9qGco/edit#
What this PR contains:
1. Modified `Task` to contain the real `run` and `commit` method.
2. Modified `AbstractJobLauncher` to create `GobblinMultiTaskAttempt`, and use the `run` and `commit` steps in `GobblinMultiTaskAttempt`.
3. Modified `MRJobLauncher` to accommodate the situation with speculative execution enabled.
4. Modified `TaskStateTracker` to have two callback functions: `onTaskRunCompletion` and`onTaskCommitCompletion`.
> Second commit of speculative execution in MR mode

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/verify/DataCompletenessVerifier.java
> Completeness verification events

- gobblin-utility/src/test/java/gobblin/util/executors/IteratorExecutorTest.java
Previously, endOneCallable could signal multiple times before endCall could be processed.
> Fix a race condition in IteratorExecutorTest

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-metrics/src/main/java/gobblin/metrics/GobblinMetrics.java
- gobblin-metrics/src/main/java/gobblin/metrics/event/TaskEvent.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/TaskMetrics.java
- gobblin-runtime/src/test/java/gobblin/runtime/TaskTest.java
> Add final tag for committed mr task attempt

- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDatasetFinder.java
The current datasetUrn key is `event.sla.datasetUrn` which is an internal key. Submitting the event though builder which uses the correct `datasetUrn` key
@ibuenros / @abti  can you review?
> Fix datasetUrn key in HiveDatasetFinder

- gobblin-api/src/test/java/gobblin/password/PasswordManagerTest.java
- gobblin-data-management/build.gradle
- gobblin-data-management/src/test/java/gobblin/data/management/copy/converter/DecryptConverterTest.java
- travis/test.sh
- Changed some memory gradle configs
- Disabled DecryptConverterTest and PasswordManagerTest on Travis since they fail consistently there; we need further investigation
- Minor refactoring in DecryptCoverterTest for code hygiene reasons
> Gradle mem config

- gobblin-runtime/src/test/java/gobblin/scheduler/JobConfigFileMonitorTest.java
Test could proceed before the change was detected because the number of jobs does not change.
> Fix a race condition in JobConfigFileMonitorTest.testChangeJobConfigFile

- gobblin-hive-registration/src/main/java/gobblin/hive/HivePartition.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegistrationUnit.java
- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java
> Add verbose logging in hive registration

- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java
> More verbose logs for hive-registration

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/BackfillHiveSource.java
> Ignore lookback in avro to orc backfill source

- gobblin-core/src/main/java/gobblin/publisher/TimestampDataPublisher.java
Modify TimestampDataPublisher so that the output path is in the correct format.
Before:
`outputDir/timestamp/dbname_tablename_xxxxx`
After:
`outputDir/dbname.tablename/timestamp`
> Update timestamp publisher output path

- gobblin-yarn/build.gradle
- gobblin-yarn/src/main/java/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/test/java/gobblin/yarn/GobblinYarnAppLauncherTest.java
- gobblin-yarn/src/test/resources/application.conf
- gobblin-yarn/src/test/resources/log4j-yarn.properties
- gobblin-yarn/src/test/resources/reference.conf
Pass dynamic configuration such as ZK and RM ports through a new configuration file.
Package required libraries into a fat jar for distribution to the app master and workers.
Add verification and waits for state changes and handle race conditions causing intermittent failures.
> YARN app launcher test fixes.

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/dataset/ConvertibleHiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/CleanableHiveDataset.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java
Avro to ORC conversion changes for updating storage format, run publish queries once and other bug fixes
> Avro to ORC conversion changes for updating storage format, run publish queries once and other bug fixes

- gobblin-docs/developer-guide/GobblinModules.md
@shirshanka @abti Can you review?
> Adding gobblin-modules documentation

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-core/src/main/java/gobblin/converter/string/StringSplitterToListConverter.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/TokenBasedFileInputStreamExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/filebased/TokenizedFileDownloader.java
- gobblin-core/src/test/java/gobblin/converter/string/StringSplitterToListConverterTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/filebased/TokenizedFileDownloaderTest.java
Added a simple token based extractor, and a simple converter. @ibuenros Can you take a look?
> Add token based extractor

- gobblin-compaction/src/main/java/gobblin/compaction/dataset/TimeBasedSubDirDatasetsFinder.java
- gobblin-compaction/src/main/java/gobblin/compaction/listeners/CompactorCompletionListenerFactory.java
- gobblin-compaction/src/main/java/gobblin/compaction/listeners/SimpleCompactorCompletionListener.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
1. Made method signature change and constructor change for compaction completion listener
2. Made attributes public in TimeBasedSubDirDatasetsFinder
> Add compaction complete listerner for entire work flow

- gobblin-example/src/main/resources/wikipedia-console.pull
- gobblin-example/src/main/resources/wikipedia-kafka.pull
- gobblin-example/src/main/resources/wikipedia-orc.pull
Copy changes from wikipedia.pull
> fix URI parsing issue

- gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java
Move one flavor of AbstractJobLauncher.runWorkUnits to GobblinMultiTaskAttempt since the latter is the only invoker. Convert the method to an instance method.
@ydai1124 Can you review ?
> Move one flavor of AbstractJobLauncher.runWorkUnits

- gobblin-runtime/src/test/java/gobblin/GobblinRuntimeTest.java
Modified GobblinRuntimeTest and removed .keep files which were added in the first place to add empty directories in the git repo
> Removing .keep files

- gobblin-compaction/src/main/java/gobblin/compaction/dataset/Dataset.java
- gobblin-compaction/src/main/java/gobblin/compaction/dataset/TimeBasedSubDirDatasetsFinder.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
> Make input paths immutable

- .travis.yml
- build.gradle
- gobblin-metastore/build.gradle
- gobblin-metastore/src/test/java/gobblin/metastore/DatabaseJobHistoryStoreTest.java
- gobblin-metastore/src/test/java/gobblin/metastore/testing/TestMetastoreDatabaseFactory.java
- gobblin-metastore/src/test/java/gobblin/metastore/testing/TestMetastoreDatabaseServer.java
- gobblin-rest-service/gobblin-rest-server/build.gradle
- gobblin-runtime/build.gradle
- travis/test-coverage.sh
- travis/test-default.sh
- travis/test-group1.sh
- travis/test.sh
> gobblin-metastore tests on travis use container mysql

- query_github_issues.py
Use the REST API to find issues created within the last 10 days.
@vasanthrajamani can you review?
> Simple script to query github issues

- README.md
> Updated Readme to include Gitter link

- gobblin-api/src/main/java/gobblin/broker/SimpleScopeType.java
- gobblin-api/src/main/java/gobblin/broker/iface/SharedResourceFactory.java
- gobblin-utility/src/main/java/gobblin/util/limiter/CountBasedLimiter.java
- gobblin-utility/src/main/java/gobblin/util/limiter/LimiterFactory.java
- gobblin-utility/src/main/java/gobblin/util/limiter/MultiLimiter.java
- gobblin-utility/src/main/java/gobblin/util/limiter/NoopLimiter.java
- gobblin-utility/src/main/java/gobblin/util/limiter/PoolBasedLimiter.java
- gobblin-utility/src/main/java/gobblin/util/limiter/RateBasedLimiter.java
- gobblin-utility/src/main/java/gobblin/util/limiter/TimeBasedLimiter.java
- gobblin-utility/src/main/java/gobblin/util/limiter/broker/SharedLimiterFactory.java
- gobblin-utility/src/main/java/gobblin/util/limiter/broker/SharedLimiterKey.java
- gobblin-utility/src/test/java/gobblin/util/limiter/MultiLimiterTest.java
- gobblin-utility/src/test/java/gobblin/util/limiter/broker/SharedLimiterFactoryTest.java
Main changes:
* Created `LimiterFactory` for building Limiters.
* Created `SharedLimiterFactory` and `SharedLimiterKey` for use with broker.
* Created `MultiLimiter` (combine multiple limiters), and `NoopLimiter`.
> Implemented shared limiter factory.

- bin/gobblin-aws.sh
Adding Gobblin AWS cluster launcher script which was left out due to git ignore previously. Minor commit, self approving.
> Added Gobblin AWS cluster launcher script

- gobblin-core-base/src/test/java/gobblin/writer/AsyncWriterManagerTest.java
- gobblin-modules/gobblin-couchbase/src/main/java/gobblin/couchbase/writer/CouchbaseWriter.java
- gobblin-modules/gobblin-couchbase/src/main/java/gobblin/couchbase/writer/CouchbaseWriterConfigurationKeys.java
- gobblin-modules/gobblin-couchbase/src/test/java/gobblin/couchbase/writer/CouchbaseWriterTest.java
Will let people know when this is ready for review.
> Fix flaky tests described in #1538

- gobblin-docs/sources/KafkaSource.md
- mkdocs.yml
> Fixing documentation build breakages

- gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java
@pcadabam can you take a look?
> Fix NPE in MultiTaskAttempt

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/events/EventWorkunitUtils.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/publisher/HiveConvertPublisher.java
- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/event/sla/SlaEventKeys.java
- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/event/sla/SlaEventSubmitter.java
Add isFirstPublish metadata in successful data publish event for tracking
> Add isFirstPublish metadata in successful data publish event for tracking

- gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java
- gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
> Close kafkaCounsumer in KafkaSource and KafkaExtractor

- build.gradle
- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-runtime/build.gradle
- gobblin-runtime/src/jmh/java/gobblin/runtime/fork/AsynchronousForkBenchmark.java
- gobblin-runtime/src/jmh/java/gobblin/runtime/fork/MockTaskContext.java
- gobblin-runtime/src/jmh/java/gobblin/runtime/fork/SynchronousForkBenchmark.java
- gobblin-runtime/src/main/java/gobblin/runtime/AbstractTaskStateTracker.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskExecutor.java
- gobblin-runtime/src/main/java/gobblin/runtime/fork/AsynchronousFork.java
- gobblin-runtime/src/main/java/gobblin/runtime/fork/Fork.java
- gobblin-runtime/src/main/java/gobblin/runtime/fork/SynchronousFork.java
- gobblin-runtime/src/main/java/gobblin/runtime/util/RuntimeConstructs.java
- gobblin-utility/src/main/java/gobblin/util/concurrent/AutoResetEvent.java
@sahilTakiar Can you get this to the right person for review?
> Optimize tasks with only one branch by removing the need for an intermediary queue.

- gobblin-example/src/main/resources/avro-to-mysql.pull
Added pull file example on JDBC writer
> Added pull file example on JDBC writer

- build.gradle
- gobblin-core-base/src/main/java/gobblin/test/SequentialJsonTestSource.java
- gobblin-core-base/src/main/java/gobblin/writer/Batch.java
- gobblin-core-base/src/main/java/gobblin/writer/BatchAccumulator.java
- gobblin-core-base/src/main/java/gobblin/writer/BatchAsyncDataWriter.java
- gobblin-core-base/src/main/java/gobblin/writer/BufferedAsyncDataWriter.java
- gobblin-core-base/src/main/java/gobblin/writer/RecordFuture.java
- gobblin-core-base/src/main/java/gobblin/writer/RecordMetadata.java
- gobblin-example/build.gradle
- gobblin-modules/gobblin-eventhub/build.gradle
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubBatch.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubBatchAccumulator.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubDataWriter.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubDataWriterBuilder.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubRequest.java
- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubWriterConfigurationKeys.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/BufferedAsyncDataWriterTest.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubAccumulatorTest.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubBatchTest.java
- gobblin-modules/gobblin-eventhub/src/test/java/gobblin/eventhub/writer/EventhubDataWriterTest.java
- gradle/scripts/dependencyDefinitions.gradle
- gradle/scripts/javaVersionCheck.gradle
- gradle/scripts/restli.gradle
This is the initial version of data writer which can send single record or a batch of records to Eventhub via HttpClient synchronous send model.
> EventhubSyncDataWriter

- gobblin-runtime/src/main/java/gobblin/runtime/util/TaskMetrics.java
@ibuenros can you take a look?
> Add dataseturn tag to TaskMetrics

- gradle/scripts/computeVersions.gradle
> Fix minor and major version computation

- gobblin-config-management/gobblin-config-client/src/main/resources/META-INF/services/gobblin.config.store.api.ConfigStoreFactory
> Add LocalHDFSConfigStoreFactory to service loader

- gobblin-modules/gobblin-eventhub/src/main/java/gobblin/eventhub/writer/EventhubDataWriter.java
1.Add password encryption for eventhub datawriter
2. Throw an exception if request failed
> Add password encryption for eventhub datawriter

- gobblin-core-base/src/main/java/gobblin/converter/AnyToRecordWithMetadataConverter.java
- gobblin-core-base/src/main/java/gobblin/converter/EncryptedRecordWithMetadataConverter.java
- gobblin-core-base/src/main/java/gobblin/type/RecordWithMetadata.java
- gobblin-core-base/src/main/java/gobblin/type/SerializedRecordWithMetadata.java
- gobblin-core-base/src/test/java/gobblin/converter/AnyToRecordWithMetadataConverterTest.java
> Adding record with metadata

- gobblin-core-base/src/main/java/gobblin/converter/SamplingConverter.java
- gobblin-core-base/src/test/java/gobblin/converter/SamplingConverterTest.java
- gobblin-example/src/main/resources/streaming-kafka-kafka.pull
> Add a sampling converter

- gobblin-core/src/main/java/gobblin/writer/SimpleDataWriter.java
> Fix speculative run for SimpleDataWriter

- gobblin-modules/gobblin-kafka-09/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleStreamingExtractor.java
- gobblin-modules/gobblin-kafka-09/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleStreamingSource.java
The real `state` class in the source is actually `JobState`, which does not support `getProp`. Change it to Typesafe config.
> Make KafkaSimpleStreamingSource to use Config

- gobblin-data-management/src/test/java/gobblin/data/management/copy/hive/WhitelistBlacklistTest.java
- gobblin-modules/gobblin-kafka-08/src/test/java/gobblin/kafka/writer/Kafka08DataWriterIntegrationTest.java
- gobblin-runtime/src/test/java/gobblin/runtime/job_catalog/TestFSJobCatalog.java
Migrating from Junit to TestNG Assert in few test classes
> Migrating from Junit to TestNG Assert in few test classes

- gobblin-modules/gobblin-kafka-08/build.gradle
- gradle/scripts/defaultBuildProperties.gradle
- gradle/scripts/dependencyDefinitions.gradle
Update hadoop version to 2.6.0 since that is required by the hive 1.1.0 version.
> Add junit dependency that is required for kafka-08 tests.

- gobblin-docs/developer-guide/Gobblin-Compliance-Design.md
- gobblin-docs/project/Team.md
- gobblin-docs/user-guide/Gobblin-Compliance.md
- mkdocs.yml
First cut of the Gobblin Compliance docs, to help with https://github.com/linkedin/gobblin/pull/1630
> Add Gobblin Compliance docs

- gradle/scripts/mavenPublishing.gradle
@ibuenros Can you review this?
> Stop using deprecated dynamic property for ossrh* properties

- gobblin-service/src/main/java/gobblin/service/ServiceConfigKeys.java
- gobblin-service/src/main/java/gobblin/service/modules/core/GobblinServiceManager.java
Made GobblinServiceManager optional based via config
> Made GobblinServiceManager optional based via config

- gobblin-distribution/build.gradle
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/test/java/gobblin/service/FlowConfigTest.java
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/gobblin/service/FlowConfigsResource.java
- gobblin-service/src/main/java/gobblin/service/modules/core/GobblinServiceManager.java
Made FlowCatalog named injectable in FlowConfigResources, and added hooks for RestLI bootstrap
> Made FlowCatalog named injectable in FlowConfigResources, and added hooks for RestLI bootstrap

- gobblin-core-base/src/main/java/gobblin/crypto/JCEKSKeystoreCredentialStore.java
- gobblin-runtime/src/main/java/gobblin/runtime/crypto/JCEKSKeystoreCredentialStoreCli.java
CLI utilities to generate a JCEKSKeystore file and count how many keys are inside of it (and implicitly check the password of the store)
> Add some CLI options for keystore generation

- gobblin-core-base/src/main/java/gobblin/crypto/Base64Codec.java
- gobblin-core-base/src/main/java/gobblin/crypto/RotatingAESCodec.java
- gobblin-core-base/src/test/java/gobblin/crypto/RotatingAESCodecTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/crypto/DecryptCli.java
- gobblin-runtime/src/main/java/gobblin/runtime/crypto/JCEKSKeystoreCredentialStoreCli.java
@ibuenros or @shirshanka , can you please take a look?
> Add decryption support and a CLI command to use it

- gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java
@ibuenros can you take a look?
> Improve exception handling when creating table using Hive metastore

- gobblin-core-base/src/main/java/gobblin/source/extractor/limiter/LimiterConfigurationKeys.java
- gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java
- gobblin-runtime/src/main/java/gobblin/runtime/LimitingExtractorDecorator.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskContext.java
- gobblin-runtime/src/test/java/gobblin/runtime/LimiterStopEventTest.java
Add a reporter interface to submit events if Limiter.acquirePermit gets null record.
> Add events submission if extraction reaches to certain limit

- gobblin-core/src/main/java/gobblin/source/extractor/extract/restapi/RestApiCommand.java
Extend RestApiCommandType by adding a POST type
> Extend RestApiCommandType

- gobblin-api/src/main/java/gobblin/runtime/api/SpecExecutorInstanceConsumer.java
- gobblin-cluster/src/main/java/gobblin/cluster/JobConfigurationManager.java
- gobblin-cluster/src/main/java/gobblin/cluster/ScheduledJobConfigurationManager.java
- gobblin-cluster/src/main/java/gobblin/cluster/event/DeleteJobConfigArrivalEvent.java
- gobblin-modules/gobblin-kafka-08/src/main/java/gobblin/service/SimpleKafkaSpecExecutorInstance.java
- gobblin-modules/gobblin-kafka-08/src/main/java/gobblin/service/SimpleKafkaSpecExecutorInstanceConsumer.java
- gobblin-modules/gobblin-kafka-08/src/main/java/gobblin/service/SimpleKafkaSpecExecutorInstanceProducer.java
- gobblin-modules/gobblin-kafka-08/src/test/java/gobblin/service/SimpleKafkaSpecExecutorInstanceTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/api/JobSpec.java
- gobblin-runtime/src/test/java/gobblin/runtime/api/TestJobSpec.java
- gobblin-service/src/main/java/gobblin/service/modules/flow/IdentityFlowToJobSpecCompiler.java
- gobblin-service/src/main/java/gobblin/service/modules/orchestration/Orchestrator.java
Bug fixes for Spec Producer and Consumer in Service and Cluster as well as a few SerDe changes (that are placeholders for now, and will be deleted with Avro based SerDe)
> Bug fixes for Spec Producer and Consumer in Service and Cluster

- gobblin-service/src/main/java/gobblin/service/modules/monitoring/FlowStatus.java
- gobblin-service/src/main/java/gobblin/service/modules/monitoring/FlowStatusGenerator.java
- gobblin-service/src/main/java/gobblin/service/modules/monitoring/JobStatus.java
- gobblin-service/src/main/java/gobblin/service/modules/monitoring/JobStatusRetriever.java
- gobblin-service/src/main/java/gobblin/service/modules/monitoring/LatestFlowExecutionIdTracker.java
This is based on what we discussed. @abti or @htran1 can you take a look?
> Initial commit for flowstatus monitoring

- gobblin-runtime/src/main/java/gobblin/service/monitoring/FlowStatus.java
- gobblin-runtime/src/main/java/gobblin/service/monitoring/FlowStatusGenerator.java
- gobblin-runtime/src/main/java/gobblin/service/monitoring/JobStatus.java
- gobblin-runtime/src/main/java/gobblin/service/monitoring/JobStatusRetriever.java
- gobblin-runtime/src/main/java/gobblin/service/monitoring/LatestFlowExecutionIdTracker.java
> Change service monitoring to runtime

- gobblin-core/src/main/java/gobblin/source/extractor/extract/jdbc/JdbcExtractor.java
> Fix the tunneling close issue ETL-5178 when JdbcExtractor is closed

- gobblin-docs/sources/QueryBasedSource.md
- gobblin-docs/sources/RestApiSource.md
@htran1 @ibuenros Please review. Thanks.
> Fix image display issue on Query based and Rest Api documentation

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveAvroORCQueryGenerator.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/util/HiveAvroORCQueryGeneratorTest.java
- gobblin-modules/gobblin-azkaban/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
1) Set Partition location and partition file format in the same query in Avro2Orc conversion
2) Added file format validation job
> Validation job in Avro2Orc and bug fix

- gobblin-core-base/src/main/java/gobblin/converter/filter/GobblinTrackingEventFlattenFilterConverter.java
- gobblin-core-base/src/test/java/gobblin/converter/filter/GobblinTrackingEventFlattenFilterConverterTest.java
> Add field Rename to GobblinTrackingEvents converter

- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/restore/AdhocRestorePolicy.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/restore/ComplianceRestoreJob.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/restore/HivePartitionRestorePolicy.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/restore/LKGRestorePolicy.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/restore/RestorableDataset.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/restore/RestorableHivePartitionDataset.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/restore/RestorableHivePartitionDatasetFinder.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/restore/RestorePolicy.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/retention/HivePartitionRetentionVersion.java
Added restore with two restore policies.
Added skeleton for compliance validation.
> Added restore to gobblin-compliance

- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/ComplianceConfigurationKeys.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/ComplianceEvents.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/DatasetUtils.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/HivePartitionDataset.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/purger/HivePurgerPublisher.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/purger/HivePurgerQueryTemplate.java
- gobblin-modules/gobblin-compliance/src/main/java/gobblin/compliance/purger/HivePurgerSource.java
Added metrics to gobblin-compliance:purger
Following metrics/events are added:
recordsWritten
recordsRead
bytesWritten
bytesRead
executionsInCurrentCycle
CycleCompletionEvent
WorkUnitGeneratedEvent
WorkUnitCommittedEvent
WorkUnitFailedEvent
> Added metrics to gobblin-compliance.purger

- bin/gobblin-mapreduce.sh
Added:
- goblin-core-base
- goblin-metrics-base
- gobblin-codecs
- gobblin-crypto
- gobblin-crypto-provider
- goblin-data-management
- gobblin-metadata
- guava-retrying
- javassist
- reflections
Also alphabetized the listing to make it a little easier to visually scan through.
> Update gobblin-mapreduce.sh to reflect various module updates:

- gobblin-core/src/main/java/gobblin/source/extractor/extract/QueryBasedExtractor.java
- gobblin-core/src/main/java/gobblin/source/extractor/extract/QueryBasedSource.java
- gobblin-core/src/main/java/gobblin/source/extractor/partition/Partition.java
- gobblin-core/src/main/java/gobblin/source/extractor/partition/Partitioner.java
- gobblin-core/src/main/java/gobblin/source/extractor/utils/Utils.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/DateWatermark.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/HourWatermark.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/SimpleWatermark.java
- gobblin-core/src/main/java/gobblin/source/extractor/watermark/TimestampWatermark.java
- gobblin-core/src/test/java/gobblin/source/extractor/extract/QueryBasedExtractorTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/partition/PartitionerTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/watermark/DateWatermarkTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/watermark/HourWatermarkTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/watermark/SimpleWatermarkTest.java
- gobblin-core/src/test/java/gobblin/source/extractor/watermark/TimestampWatermarkTest.java
- All but last partition is set as [lowWatermark, highWatermark) , last partition will be [lowWatermark, highWatermark]
- Fixing tests is in progress
> Fix partition gaps in Partitioner

- gobblin-api/src/main/java/gobblin/configuration/State.java
@htran1  or @aditya1105  can you take a look?
> Fix an issue in State

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/query/HiveValidationQueryGenerator.java
- gobblin-modules/gobblin-azkaban/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
Small bug fixes.
Removal of dataValidation since it was written for flattened avro2orc conversion. For nested avro2orc there will a lot of difference. Also for nested join query on struct shouldn't be executed as struct may contain map inside it.
> Bug fixes in validation job for avro2orc

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/converter/AbstractAvroToOrcConverter.java
- gobblin-data-management/src/test/java/gobblin/data/management/conversion/hive/converter/HiveAvroToOrcConverterTest.java
Added Whitelist Blacklist support for Hive view registration in Avro to ORC pipeline. This is important to allow for a subset of dataset's Hive view registration if config store is not enabled.
> Added Whitelist Blacklist support for Hive view registration in Avro to ORC pipeline

- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobPropCreator.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactorJobRunner.java
> Check the late directory again if prevoius compaction is failed

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-service/src/main/java/gobblin/service/modules/flow/IdentityFlowToJobSpecCompiler.java
- gobblin-service/src/test/java/gobblin/service/modules/core/IdentityFlowToJobSpecCompilerTest.java
Added flow execution id to the jobSpecs compiled for a flowSpec and related test.
> Added flow execution id to the jobSpecs compiled for a flowSpec

- gobblin-core-base/src/main/java/gobblin/converter/filter/GobblinTrackingEventFlattenFilterConverter.java
> Add default value when flattening GobblinTrackingEvent

- conf/standalone/log4j-cluster.properties
- gobblin-cluster/src/main/java/gobblin/cluster/GobblinHelixJobLauncher.java
- gobblin-cluster/src/main/java/gobblin/cluster/GobblinHelixTask.java
- gobblin-cluster/src/main/java/org/apache/helix/task/GobblinJobRebalancer.java
- gobblin-runtime/src/main/java/gobblin/runtime/Task.java
This PR adds a custom rebalancer that can move long-running tasks.
Tested locally.
> Adding a custom rebalancer GobblinJobRebalancer for long-running tasks

- gobblin-modules/gobblin-kafka-09/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleStreamingExtractor.java
- gobblin-modules/gobblin-kafka-09/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSimpleStreamingSource.java
- gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/converter/LiKafkaByteArrayMsgToAvroConverter.java
- gobblin-utility/src/main/java/gobblin/util/EmptyIterable.java
@htran1 address issues for gaas monitoring. can you take a look?
> Small fixes for steaming kafka extractor and converter

- gobblin-service/src/main/java/gobblin/service/modules/core/GobblinServiceManager.java
Added getter for Config in GobblinServiceManager
> Added getter for Config in GobblinServiceManager

- gobblin-runtime/src/main/java/gobblin/runtime/api/SpecCompiler.java
- gobblin-service/src/main/java/gobblin/service/ServiceMetricNames.java
- gobblin-service/src/main/java/gobblin/service/modules/flow/IdentityFlowToJobSpecCompiler.java
- gobblin-service/src/main/java/gobblin/service/modules/orchestration/Orchestrator.java
Added basic Instrumentation to the following Gobblin Service modules: 
- Compiler 
- Orchestrator
> Added Instrumentation to Gobblin Service

- gobblin-modules/gobblin-azkaban/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
1) Adding hive settings to validation job. This is needed if we want to set hive parameters for the current connection(eg: mapreduce.map.memory.mb=1024). Hence hive.settings will take semicolon seperated hive queries which will be executed at the start of the hive connection
2) Changing IOException to Exception when trying to close hive connection.
> Adding hive settings to validation job for avro2orc

- gobblin-runtime/src/main/java/gobblin/runtime/embedded/EmbeddedGobblin.java
- gobblin-runtime/src/main/resources/embedded/embedded.conf
> Fix a bug in copy writer.

- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionCompleteFileOperationAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/verify/CompactionThresholdVerifier.java
- gobblin-compaction/src/main/java/gobblin/compaction/verify/InputRecordCountHelper.java
> Fix record count by using input file name

- gobblin-core-base/src/main/java/gobblin/instrumented/writer/InstrumentedDataWriterBase.java
- gobblin-core/src/main/java/gobblin/async/AsyncDataDispatcher.java
- gobblin-core/src/main/java/gobblin/writer/http/AbstractAsyncDataWriter.java
- gobblin-core/src/main/java/gobblin/writer/http/AsyncHttpWriter.java
- gobblin-core/src/main/java/gobblin/writer/http/AsyncHttpWriterBuilder.java
- gobblin-core/src/main/java/gobblin/writer/http/AsyncWriteRequestBuilder.java
- gobblin-core/src/test/java/gobblin/writer/http/AsyncHttpWriterTest.java
- gobblin-example/build.gradle
- gobblin-modules/gobblin-http/build.gradle
- gobblin-modules/gobblin-http/src/main/avro/HttpOperation.avsc
- gobblin-modules/gobblin-http/src/main/java/gobblin/http/ApacheHttpClient.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/http/HttpRequestBuilder.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/http/HttpResponseHandler.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2Client.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2RestRequestBuilder.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2RestResponseHandler.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/restli/R2RestWriterBuilder.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/utils/HttpConstants.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/utils/HttpUtils.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/writer/AvroHttpWriterBuilder.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/writer/R2RestWriterBuilder.java
- gobblin-modules/gobblin-http/src/test/java/gobblin/HttpTestUtils.java
- gobblin-modules/gobblin-http/src/test/java/gobblin/MockGenericRecord.java
- gobblin-modules/gobblin-http/src/test/java/gobblin/http/HttpRequestBuilderTest.java
- gobblin-modules/gobblin-http/src/test/java/gobblin/restli/R2RestRequestBuilderTest.java
- gobblin-utility/src/main/java/gobblin/util/AvroUtils.java
- Rename `RestliR2Client` to `R2Client`, `buildRequest` to `buildWriteRequest`
- `HttpRequestBuilder` builds a `HttpUriRequest` from a http operation `GenericRecord`
-  `R2RestRequestBuilder` builds a `RestRequest` from a http operation `GenericRecord`
> Default http and r2 rest request builders/response handlers

- gobblin-modules/gobblin-azkaban/src/main/java/gobblin/data/management/conversion/hive/validation/ValidationJob.java
Adding config store whitelisting for file format validation
> Enabling config store for validation

- gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/source/extractor/extract/kafka/ConfigStoreUtils.java
Defaults to return all kafka topics if blacklist and whitelist tags are not provided.
> Relaxing config store requirements for getting blacklisted/whitelisted topics

- gobblin-core/src/main/java/gobblin/converter/avro/AvroToBytesConverter.java
- gobblin-core/src/test/java/gobblin/converter/avro/AvroToBytesConverterTest.java
@htran1 - one more for you please?
> Add AvroToBytesConverter; inverse of BytesToAvro.

- gobblin-core/src/main/java/gobblin/security/ssl/SSLContextFactory.java
- gobblin-core/src/test/java/gobblin/security/ssl/SSLContextFactoryTest.java
- gobblin-modules/gobblin-http/build.gradle
- gobblin-modules/gobblin-http/src/main/java/gobblin/r2/D2ClientProxy.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/r2/R2ClientFactory.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/r2/R2HttpClientProxy.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/writer/R2RestWriterBuilder.java
- gobblin-modules/gobblin-http/src/test/java/gobblin/r2/R2ClientFactoryTest.java
- Provide http based or d2 integrated clients, supported with https
- Generate ssl context used by https
> Provide default implementation for R2 clients

- gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AvroApacheHttpJoinConverter.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AvroR2JoinConverter.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/converter/HttpJoinConverter.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/utils/HttpConstants.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/writer/R2RestWriterBuilder.java
> Add createHttpClient implementation to AvroR2JoinConverter.java

- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/ConfigBasedDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/ConfigBasedMultiDatasets.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/CopyRouteGeneratorOptimizedNetworkBandwidth.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/CopyRouteGeneratorOptimizedNetworkBandwidthForTest.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/CopyRouteGeneratorOptimizer.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/EndPoint.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/HadoopFsEndPoint.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/SourceHadoopFsEndPoint.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- gobblin-data-management/src/test/java/gobblin/data/management/copy/replication/CopyRouteGeneratorTest.java
Also Add dataset existance checking for `HadoopFsEndPoint.java` 
This PR is part of migration to use Config-store-based DistcpNG job.
> Minor fix for /data/management/copy/replication

- gobblin-api/src/main/java/gobblin/configuration/ConfigurationKeys.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/ConfigBasedCopyableDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/ConfigBasedDatasetsFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/replication/ConfigBasedMultiDatasets.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/dataset/ConfigurableCleanableDataset.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/policy/CombineRetentionPolicy.java
- gobblin-data-management/src/main/java/gobblin/data/management/retention/profile/ConfigBasedCleanabledDatasetFinder.java
- gobblin-data-management/src/main/java/gobblin/data/management/trash/Trash.java
- gobblin-data-management/src/main/java/gobblin/data/management/version/finder/DateTimeDatasetVersionFinder.java
- gobblin-data-management/src/test/java/gobblin/data/management/trash/TrashTest.java
- Fix race condition for trash folder accessing
- Add new conf. DATASET_PATH to maintain the generality of ConfigBasedCleanabledDatasetFinder
> Implementation of tag-based retention

- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/HiveCopyEntityHelper.java
- gobblin-data-management/src/main/java/gobblin/data/management/copy/hive/avro/HiveAvroCopyEntityHelper.java
changing avro.schema.url in source partitions to reflect new destination path
@ibuenros Please review.
> changing avro.schema.url for hive partitions before distcp

- gobblin-aws/src/main/java/gobblin/aws/AWSClusterSecurityManager.java
- gobblin-aws/src/main/java/gobblin/aws/AWSSdkClient.java
- gobblin-aws/src/main/java/gobblin/aws/GobblinAWSClusterLauncher.java
> Change AWS security to credentials providers.

- gobblin-modules/gobblin-http/src/main/java/gobblin/converter/AvroR2JoinConverter.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/r2/R2Client.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/utils/HttpUtils.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/writer/R2RestWriterBuilder.java
@ibuenros Can you help review?
> Add throttling limiter key for R2 client

- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionCompleteAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionCompleteFileOperationAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionHiveRegistrationAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/action/CompactionMarkDirectoryAction.java
- gobblin-compaction/src/main/java/gobblin/compaction/event/CompactionSlaEventHelper.java
- gobblin-compaction/src/main/java/gobblin/compaction/mapreduce/MRCompactionTask.java
- gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/MRTask.java
> Add compaction complete event

- gobblin-modules/gobblin-http/src/main/java/gobblin/r2/R2RestResponseHandler.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/utils/HttpConstants.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/writer/AsyncHttpWriterBuilder.java
- gobblin-modules/gobblin-http/src/main/java/gobblin/writer/R2RestWriterBuilder.java
> submitting event in case of failed R2 request

- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveSource.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveWorkUnit.java
- Added partition and table information on HiveWorkUnit
- Added a capability of taking filesystem uri from job property for HiveSource
Passed unit test and integration test via MR mode.
> Added partition and table information on HiveWorkUnit

- CHANGELOG.md
Fix a grammar issue in CHANGELOG.
> Cosmetic fix

- gobblin-modules/gobblin-crypto-provider/src/main/java/gobblin/converter/StringFieldEncryptorConverter.java
Also, some of our encryptors throw IllegalArgumentException; explicitly catch those as well as IOExceptions
> Ensure that the field name is present in the exception text if an error is thrown from the encryptor

- gobblin-docs/user-guide/Gobblin-Schedulers.md
- gobblin-oozie/src/test/resources/mapreduce/gobblin-oozie-mr-example-sysconfig.properties
- gobblin-oozie/src/test/resources/mapreduce/gobblin-oozie-mr-example-workflow.properties
- gobblin-oozie/src/test/resources/mapreduce/gobblin-oozie-mr-example-workflow.xml
see https://issues.apache.org/jira/browse/GOBBLIN-54
> add documentation for launching gobblin in oozie MR mode

- dev/sign.sh
- https://issues.apache.org/jira/browse/GOBBLIN-167
Add dev tooling for signing releases. This will reduce multi-step process to a few for Apache releases.
Release process is yet to be finalized, this script is to curate all required tooling.
> [GOBBLIN-167] Add dev tooling for signing releases

- build.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-169
Ability to curate licenses of all Gobblin dependencies transitively so that we can ensure that we are pulling in only Apache compatible license dependencies. 
Tested locally, and report was reviewed. 
> [GOBBLIN-169] Ability to curate licenses of all Gobblin dependencies

- gobblin-modules/gobblin-sql/src/main/java/gobblin/source/jdbc/SqlServerExtractor.java
updating connection url for sqlserver with database name
@htran1  Kindly review.
> updating connection url for sqlserver with database name

- gobblin-api/src/main/java/gobblin/configuration/ImmutableWorkUnitState.java
- gobblin-api/src/main/java/gobblin/configuration/SourceState.java
- gobblin-api/src/main/java/gobblin/configuration/State.java
- gobblin-api/src/main/java/gobblin/configuration/WorkUnitState.java
- gobblin-api/src/main/java/gobblin/source/extractor/CheckpointableWatermark.java
- gobblin-api/src/main/java/gobblin/source/extractor/Watermark.java
- gobblin-api/src/main/java/gobblin/source/extractor/WatermarkInterval.java
- gobblin-api/src/main/java/gobblin/source/workunit/Extract.java
- gobblin-api/src/main/java/gobblin/source/workunit/ImmutableExtract.java
- gobblin-api/src/main/java/gobblin/source/workunit/ImmutableWorkUnit.java
- gobblin-api/src/main/java/gobblin/source/workunit/MultiWorkUnit.java
- gobblin-api/src/main/java/gobblin/source/workunit/WorkUnit.java
- gobblin-core/src/main/java/gobblin/state/ConstructState.java
- gobblin-data-management/src/main/java/gobblin/data/management/conversion/hive/source/HiveWorkUnit.java
- gobblin-hive-registration/src/main/java/gobblin/hive/HiveRegProps.java
- gobblin-metastore/src/test/java/org/apache/gobblin/metastore/FsStateStoreTest.java
- gobblin-runtime/src/main/java/gobblin/runtime/CheckpointableWatermarkState.java
- gobblin-runtime/src/main/java/gobblin/runtime/JobState.java
- gobblin-runtime/src/main/java/gobblin/runtime/TaskState.java
- gobblin-runtime/src/test/java/org/apache/gobblin/runtime/util/JobStateToJsonConverterTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-179 
Add shim layer for Gobblin state
Existing test that were disabled during package migration work. 
> [GOBBLIN-179] Add shim layer for Gobblin state

- gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceExtractor.java
- https://issues.apache.org/jira/browse/GOBBLIN-274
Have to test with a real Salesforce system.
> [GOBBLIN-274] Fix wait for salesforce batch completion

- gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
- https://issues.apache.org/jira/browse/GOBBLIN-1442
After recent change, we see the default value of offsetRange in GMCE change to empty map, so add one more check to make sure the map is not empty so that we won't hit the exception
> [GOBBLIN-1442]Fix the bug of NoSuchElement Exception in HiveWriter

- gobblin-docs/user-guide/Docker-Integration.md
Fix reference to docker repository, remove Todo.
> Update Docker recipe

- .github/workflows/build_and_test.yaml
Add check for github actions to verify transitive dependencies in gradle, so that errors will surface sooner.
> [GOBBLIN-1467] Add check to verify transitive gradle dependencies

- .github/workflows/build_and_test.yaml
- gradle/scripts/jacoco-coveralls-support.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-1477
Fixed bug where static tests and code coverage were not being run
Followed some apache recommendations with github actions to add better security measures and use less resources https://cwiki.apache.org/confluence/display/BUILDS/GitHub+Actions+status
> [GOBBLIN-1477] Add code coverage, security checks and fix bug with static tests for Github Actions

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
- https://issues.apache.org/jira/browse/GOBBLIN-1473
Prevously, `ConcurrentModificationException` could happen when switching from active to inactive in the scheduler, because specs were removed from `scheduledFlowSpecs` while iterating through it. This fixes it in this scenario by not removing during iteration and just clearing the map at the end (since every entry should get removed anyway).
> [GOBBLIN-1473] Fix ConcurrentModificationException when handling leadership change

- gobblin-example/src/main/resources/csvToAvro.conf
New users have troubles figuring out what should be replaced in the example configs:
https://stackoverflow.com/questions/61890043/gobblin-json-to-avro-convert-failed-with-not-a-json-array-error
> [GOBBLIN-1156] Clarify quickstart example

- gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
- https://issues.apache.org/jira/browse/GOBBLIN-1489
define AZKABAN_SERVER_NAME in ConfigurationKeys.java which are otherwise defined in various places. 
add NON_TRANSIENT_ERROR_MESSAGES which can be used to separate retry-able exceptions from fatal ones
> [GOBBLIN-1489] Add Azkaban Server Name and non transient error config keys

- gobblin-docs/adaptors/Hive-Avro-To-ORC-Converter.md
- https://issues.apache.org/jira/projects/GOBBLIN/issues/GOBBLIN-931?filter=allopenissues
The following typos are amended:
registred  -> registered
converison  -> conversion
Just a typo fix
> Update Hive-Avro-To-ORC-Converter.md for typos

- gobblin-docs/developer-guide/GobblinModules.md
- https://issues.apache.org/jira/browse/GOBBLIN-1364
Fixed obsolete descriptions and updated the table in the "Gobblin Modules" document
No additional test since it's just a documentation fix. Instead I ran `mkdocs` locally and ensured that the generated document was fixed as expected.
> [GOBBLIN-1364] Update the "Gobblin Modules" document

- gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
- gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/MetadataWriter.java
- gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/GobblinMCEProducer.java
- gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
- gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
https://issues.apache.org/jira/browse/GOBBLIN-1486
Fixing javadoc and some typo while reading the code about metadata ingestion pipeline. This PR covers mostly the part of `HiveMetadataWriter` and `GobblinMCEWriter`, there will be a follow up on `IcebergMetadataWriter`. 
> [GOBBLIN-1486] Documentation improvement for Gobblin Metadata Ingestion pipeline

- gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
> [hotFix] Fix typo in HiveMetadataWriter

- gobblin-data-management/src/test/java/org/apache/gobblin/data/management/conversion/hive/HiveSourceTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1494
HiveSourceTest returns 2 watermarks for testGetWorkunitsAfterWatermark instead of 1.
This is due to System.getCurrentTime.millis() returning a different value when comparing against the filesystem last updated filetime. To guard against this, change the test to incorporate the workunit within the watermark by assigning it an earlier creation time, thus implying that the file was modified so it needs to be ingested again. …
> [GOBBLIN-1494] Fixes flaky test on HiveSource

- gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
- gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/CopySource.java
- gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/CopySourceTest.java
- gobblin-data-management/src/test/java/org/apache/gobblin/data/management/copy/TestCopyableDataset.java
- gobblin-metrics-libs/gobblin-metrics-base/src/main/java/org/apache/gobblin/metrics/event/TimingEvent.java
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/pegasus/org/apache/gobblin/service/JobStatistics.pdl
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/snapshot/org.apache.gobblin.service.flowexecutions.snapshot.json
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-api/src/main/snapshot/org.apache.gobblin.service.flowstatuses.snapshot.json
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowExecutionResourceLocalHandler.java
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/test/java/org/apache/gobblin/service/FlowExecutionResourceLocalHandlerTest.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/TaskStateCollectorService.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatus.java
- gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatusRetriever.java
- gobblin-runtime/src/test/java/org/apache/gobblin/runtime/TaskStateCollectorServiceTest.java
- gobblin-runtime/src/test/java/org/apache/gobblin/runtime/util/CalculateTotalWorkUnitSizeTest.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaAvroJobStatusMonitor.java
- https://issues.apache.org/jira/browse/GOBBLIN-1493
Progress reporting for a data copy will provide users with quantitative feedback on the progress of a data copy job as a percentage as well as an estimate of the time remaining for completion. This will update the existing job status endpoint to include the progress percentage and estimate of time left. 
This PR decorates each work unit with its size in bytes and uses that information to determine the progress of a copy while individual tasks are completed. It emits GobblinTrackingEvents containing the progress as a percentage intermittently and calculates the remaining time for the copy, storing both …
> [GOBBLIN-1493] Report data copy's progress

- gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
- gobblin-modules/gobblin-service-kafka/src/main/java/org/apache/gobblin/service/SimpleKafkaSpecProducer.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
@Will-Lo @umustafi please review
- https://issues.apache.org/jira/browse/GOBBLIN-1498
This PR will add meter metrics for a) running scheduled, b) nonscheduled flows, c) flows execution is skipped, d) add/update/delete/cancel flow specs sent by SimpleKafkaSpecProducer
> [GOBBLIN-1498] add a few metrics in GaaS to help debug point of failure

- gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanGobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
- https://issues.apache.org/jira/browse/GOBBLIN-1500
Previously we always check with one default yarn client, but if the cluster is enabled with Robin and can connect to different RM, it will ends up we cannot find existing application and submit duplicate tasks. So now we need to check against different potential yarn cluster, and also make sure when submitting yarn application, we only have one RM token.
Options
Test start a new application can work, test reconnect can work  …
> [GOBBLIN-1500]Support gobblin on yarn to be able to run on clusters with federated Yarn cluster enabled 

- gobblin-metastore/src/main/java/org/apache/gobblin/metastore/MysqlStateStore.java
- https://issues.apache.org/jira/browse/GOBBLIN-1503
If mysql db enters read-only mode due to a failover, the connections need to be reset before writes will work. Currently the validation query is "select 1", so it will not evict connections in read-only mode. This new query is taken from https://stackoverflow.com/questions/39552146/evicting-connections-to-a-read-only-node-in-a-cluster-from-the-connection-pool, and should fail the validation if the db is read-only, so connections will be retried.
Tested that query succeeded on a non-read only mysql db.
3. Subject …
> [GOBBLIN-1503] Modify mysql validation query to fail if db is in read-only mode

- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncherListener.java
- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncherMetrics.java
- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixPlanningJobLauncherMetrics.java
- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/HelixRetriggeringJobCallable.java
- gobblin-modules/gobblin-service-kafka/src/main/java/org/apache/gobblin/service/StreamingKafkaSpecConsumer.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/JobExecutionLauncher.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/job_exec/JobLauncherExecutionDriver.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/job_monitor/KafkaAvroJobMonitor.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/job_monitor/KafkaJobMonitor.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/metrics/RuntimeMetrics.java
add some new metrics
@jack-moseley  @Will-Lo  please review
- https://issues.apache.org/jira/browse/GOBBLIN-1508
add a few metrics in gobblin cluster and update some from counter to meter, because meter can give both count and rate of an entity
> [GOBBLIN-1508] update some cluster side metrics from guage to meter

- gobblin-utility/src/main/java/org/apache/gobblin/util/HadoopUtils.java
- https://issues.apache.org/jira/browse/GOBBLIN-1517
Currently if an error is thrown during recursive renaming, the error message does not contain the from and to path so it's hard to tell exactly which rename of the recursive rename failed. Usually the hadoop IOException contains these paths, but in some cases they do not, so it's better make sure it is printed.
trivial message change
> [GOBBLIN-1517] Improve error message during recursive renaming

- gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/orc/HiveOrcSerDeManager.java
- https://issues.apache.org/jira/browse/GOBBLIN-1531
bug fix
> [GOBBLIN-1531] ad-hoc fix for NPE in hive registration

- gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- https://issues.apache.org/jira/browse/GOBBLIN-1538
Log json response for connector request failure. This is to prepare a future improvement to throw as a different exception for non-actionable failures, such as "requested resource does not exist", or "REST API is not enabled for the organization"
Just one line log change
> [GOBBLIN-1538] Log json response for connector request failure

- gobblin-aws/src/main/java/org/apache/gobblin/aws/GobblinAWSClusterManager.java
- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterManager.java
- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixMultiManager.java
- gobblin-cluster/src/test/java/org/apache/gobblin/cluster/TestShutdownMessageHandlerFactory.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/ControllerUserDefinedMessageHandlerFactory.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinApplicationMaster.java
- https://issues.apache.org/jira/browse/GOBBLIN-1572
1) use new classes in place of the deprecated ones
2) accept some intellij suggested changes for codestyle
> [GOBBLIN-1572] remove use of deprecated helix class

- .github/workflows/build_and_test.yaml
> bump version of code cov plugin

- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- https://issues.apache.org/jira/browse/GOBBLIN-1591
FileContext objects are not cached and you get a new object every time you call FileContext.get()
Currently Gobblin creates a DataWriter for every Task. These DataWriters are not destroyed till all the Tasks complete committing. In FileAwareInputStreamDataWriter , we hold a reference to FileContext which is quite expensive.
We should not keep this reference and use it when it is really required during the commit phase, so it can be GC'ed when required
tested the objects reduction by taking heap dumps
3. Subject …
> [GOBBLIN-1591] Lazily initialize FileContext and do not hold a reference to it

- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/ClusterEventMetadataGenerator.java
- https://issues.apache.org/jira/browse/GOBBLIN-1590
emit low high watermark info in gobblin cluster so that job status monitor can parse the information and publish to user
local build
> [GOBBLIN-1590] Add low/high watermark information in event emitted by Gobblin cluster

- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/RecursivePathFinder.java
- https://issues.apache.org/jira/browse/GOBBLIN-1592
add new feature to make hive copy also respect config "gobblin.copy.applyFilterToDirectories" to determine whether apply filter to directories.
local build
> [GOBBLIN-1592] Make hive copy be able to apply filter on directory

- gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1583
Use a GaaS-wide configuration to set the Job Start SLA time, so that each flow does not need to manually set their SLAs.
> [GOBBLIN-1583] Add System level job start SLA

- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobLauncher.java
- gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-modules/gobblin-service-kafka/src/main/java/org/apache/gobblin/service/StreamingKafkaSpecConsumer.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
We have several bugs in the dag manager:
1. the number of job enqueue does not match the number of job dequeue from jobSprcConsumer
2. CurrentAttempts and generation are not passed to the job config correctly
mint build and unit test. Also test locally and see currentAttempts get populated correctly 
> [GOBBLIN-1593] Fix bugs in dag manager about metric reporting and job status monitor

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1594
Currently, a poorly formed SLA time (e.g. String instead of Long) will cause the DagManagerThread to completely stall and not make any progress. This is a short term fix to at least move the DagManager forward if the SLA is not properly defined, future fix will be to verify before flow creation
DagManagerTest
> [GOBBLIN-1594] Add guard in DagManager for improperly formed SLA

- .github/workflows/build_and_test.yaml
- https://issues.apache.org/jira/browse/GOBBLIN-1605
For Github Actions when verifying MySQL connection, the following error shows up before running tests:
```
Err:1 http://security.ubuntu.com/ubuntu focal-updates/main amd64 mysql-client-core-8.0 amd64 8.0.27-0ubuntu0.20.04.1
404  Not Found [IP: 52.147.219.192 80]
Err:3 http://security.ubuntu.com/ubuntu focal-updates/main amd64 mysql-client-8.0 amd64 8.0.27-0ubuntu0.20.04.1
404  Not Found [IP: 52.147.219.192 80]
Err:4 http://security.ubuntu.com/ubuntu focal-updates/main amd64 mysql-client all 8.0.27-0ubuntu0.20.04.1
404  Not Found [IP: 52.147.219.192 80]
Fetched 7496 B in 0s (21.5 kB/s)
E: Failed to …
```
> [GOBBLIN-1605] Fix mysql ubuntu download 404 not found for Github Actions CI/CD

- gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanJobLauncher.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/AbstractJobLauncher.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/TaskExecutor.java
- gobblin-utility/src/main/java/org/apache/gobblin/util/logs/Log4jConfigurationHelper.java
- https://issues.apache.org/jira/browse/GOBBLIN-1615
It adds a config in AzkabanJobLauncher and in TaxkExecutor to set log level of any class. It will be helpful in debugging.
> [GOBBLIN-1615] add config to set log level for any class

- .github/workflows/build_and_test.yaml
- https://issues.apache.org/jira/browse/GOBBLIN-1622
CI/CD with Github Actions downloads MySQL packages using ubuntu apt-get.
There can be conflicts that arise if the packages are not cleaned and cause an issue in the cache. i.e.
```
Get:29 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [14.0 kB]
Reading package lists...
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease (expected focal but got testing)
E: Repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease' changed its 'Origin' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod …
```
> [GOBBLIN-1622] Clear bad mysql packages from cache in CI/CD machines

- gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceConnector.java
- gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceSource.java
- https://issues.apache.org/jira/browse/GOBBLIN-1616
We just notice that in salesForceSource, we also create extractor and http connection, this is PR to add logic to close them properly
local build
> [GOBBLIN-1616] Add close connection logic in salseforceSource

- gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1631
Heartbeat corresponds to one cycle of DAG manager thread (when it reaches cleanup phase). We want one metric per thread so we can tell which thread is dead/alive. Use thread id in metric name.
> [GOBBLIN-1631]Emit heartbeat for dagManagerThread

- gobblin-data-management/src/main/java/org/apache/gobblin/runtime/retention/DatasetCleanerTask.java
- https://issues.apache.org/jira/browse/GOBBLIN-1626
This PR will make FileSystem object in DatasetCleanerTask use the use supplied configs
> [GOBBLIN-1626] use user supplied props to create FileSystem in DatasetCleanerTask

- gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1641
Currently the dag manager does not have metrics around how many flows are being exceeded per executor, so we should track this.
> [GOBBLIN-1641] Add meter for sla exceeded flows

- gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/HiveMetadataWriter.java
- gobblin-hive-registration/src/main/java/org/apache/gobblin/hive/writer/MetadataWriterKeys.java
- gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/GobblinMCEWriter.java
- gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriter.java
- gobblin-iceberg/src/test/java/org/apache/gobblin/iceberg/writer/IcebergMetadataWriterTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1647
Add new GTE which is sent on successful commit or drop of a partition from hive metadata writer
Tested and checked sample events in test pipeline
> [GOBBLIN-1647] Add hive commit GTE to HiveMetadataWriter

- bin/gobblin.sh
- gobblin-docs/user-guide/Gobblin-CLI.md
- https://issues.apache.org/jira/browse/GOBBLIN-931
* Correct typo "gobblon" to "gobblin"
* Fix some documentation wording
Only print statement update/comments update, no code changes
> [Gobblin-931] Fix typo in gobblin CLI usage

- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-client/src/main/java/org/apache/gobblin/service/FlowConfigV2Client.java
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigResourceLocalHandler.java
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigsResourceHandler.java
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigsV2Resource.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/FlowSpecSearchObject.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/InstrumentedSpecStore.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/SpecStore.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_catalog/FlowCatalog.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_store/FSSpecStore.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_store/MysqlBaseSpecStore.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_store/MysqlSpecStore.java
- gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_store/MysqlSpecStoreTest.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowConfigResourceHandler.java
- gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
- gradle/scripts/dependencyDefinitions.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-1675
- Add pagination feature to query from the specStore using start (first index of the specStore spec to return) and count (total number of specStore specs to return) for both getting all flows, and for getting filtered flows.
- Returns specs in specStore between the indices of start and start + count - 1, inclusive.
- Adds unit tests for filtered flows with pagination
- Adds unit tests for all flows with pagination
- E2E testing in GobblinServiceManager tests …
> [GOBBLIN-1675] Add pagination for GaaS on server side

- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/TimeAwareRecursiveCopyableDataset.java
- https://issues.apache.org/jira/browse/GOBBLIN-1681
> [GOBBLIN-1681] Guard against exists fs call as well

- build.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-1700
> [GOBBLIN-1700] Remove unused coveralls-gradle-plugin dependency

- gobblin-modules/gobblin-elasticsearch-deps/build.gradle
- gobblin-modules/gobblin-metrics-graphite/build.gradle
- gobblin-modules/gobblin-metrics-hadoop/build.gradle
- gobblin-modules/gobblin-metrics-influxdb/build.gradle
- gobblin-modules/gobblin-orc-dep/build.gradle
- gobblin-restli/client.gradle
- gradle/scripts/repositories.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-1701
[Failing CI due to jcenter outage](https://github.com/apache/gobblin/runs/8257965152?check_suite_focus=true)
JCenter is deprecated in favor of maven central. We should still keep Jcenter as a backup because this is an old repo with some ancient dependencies that may not be on maven central (common issue descirbed here https://jeroenmols.com/blog/2021/03/24/migrate-artifacts-mavencentral/)
https://docs.gradle.org/current/userguide/declaring_repositories.html
> The order of declaration determines how Gradle will check for dependencies at runtime. If Gradle finds a module descriptor in a particular …
> [GOBBLIN-1701] Replace jcenter with either maven central or gradle plugin portal

- gobblin-compaction/src/main/java/org/apache/gobblin/compaction/mapreduce/orc/OrcKeyDedupReducer.java
- https://issues.apache.org/jira/browse/GOBBLIN-1699
> [GOBBLIN-1699] Log progress of reducer task for visibility with slow compaction jobs

- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/messaging/DynamicWorkUnitConsumer.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/messaging/DynamicWorkUnitProducer.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/messaging/MessageBuffer.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/messaging/data/DynamicWorkUnitDeserializationException.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/messaging/data/DynamicWorkUnitMessage.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/messaging/data/DynamicWorkUnitSerde.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/messaging/data/SplitWorkUnitMessage.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/messaging/handler/SplitMessageHandler.java
- gobblin-runtime/src/test/java/org/apache/gobblin/runtime/messaging/data/DynamicWorkUnitSerdeTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1683
- https://issues.apache.org/jira/browse/GOBBLIN-1673
The Dynamic work unit project is to enable gobblin streaming to modify the workunits from a source after the pipeline has started. 
In order to do this, the task runner must communicate its current state back to the application master. This PR describes the data schema for communication and provides the skeleton code for the AM and gobblin task runner to communicate. 
Unit tests added for serialization. No UT's added for interfaces because they are interfaces. No UT added for the background thread method since that is not an easy to test method.
1. …
> [GOBBLIN-1673][GOBBLIN-1683] Skeleton code for handling messages between task runner / application master for Dynamic work unit allocation

- .github/workflows/build_and_test.yaml
- https://issues.apache.org/jira/browse/GOBBLIN-1710
Tested in this feature branch https://github.com/apache/gobblin/commit/ed460f021aeb0f86ecbc652e14a60c0b98326efb
https://github.com/homatthew/gobblin/actions/runs/3055275438
- Example of successful run
https://github.com/homatthew/gobblin/actions/runs/3055275438
> [GOBBLIN-1710] Make Codecov optional in CI and not fail

- gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigResourceLocalHandler.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/InstrumentedSpecStore.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/SpecStore.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_catalog/FlowCatalog.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_store/MysqlBaseSpecStore.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_store/MysqlSpecStoreWithUpdate.java
- gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_store/MysqlSpecStoreWithUpdateTest.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowConfigResourceHandler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowConfigV2ResourceHandlerWithWarmStandby.java
- https://issues.apache.org/jira/browse/GOBBLIN-1697
1. Have a separate resource handler to handle all flow config request regardless it's leader or not
2. Have a new mysql spec store that support update with version
Unit test
3. Subject is limited to 50 characters
4. Subject does not end with a period
5. Subject uses the imperative mood ("add", not "adding")
6. Body wraps at 72 characters
7. Body explains "what" and "why", not "how"
> [GOBBLIN-1697]Have a separate resource handler to rely on CDC stream to do message forwarding

- gobblin-metastore/src/main/java/org/apache/gobblin/metastore/JobHistoryDataSourceProvider.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/spec_store/MysqlBaseSpecStore.java
- gobblin-utility/src/main/java/org/apache/gobblin/util/jdbc/DataSourceProvider.java
- https://issues.apache.org/jira/browse/GOBBLIN-1713
Adding check to a code path to detect once a MySQL connection becomes read-only.  Enforce verification when this happens, so we know to create new, replacement connections (to a read-write host). Add additional logs to warn us when this query isn't set or if an exception occurs because of a connection issue. 
This calls the parent class non-default constructor to utilize this check. It will overwrite the driverClassName, url, username, and password values set by the constructor. However it will keep the other properties. 
```
if (!Boolean.parseBoolean(properties.getProperty(SKIP_VALIDATION_QUERY, …
```
> [GOBBLIN-1713] Add missing sql source validation

- gobblin-metastore/src/main/java/org/apache/gobblin/runtime/StateStoreBasedWatermarkStorage.java
- gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaStreamingExtractor.java
- https://issues.apache.org/jira/browse/GOBBLIN-1722
Add log lines when committing/retrieving watermarks to help debug issues where watermarks are not advancing as expected. These are probably useful to see in general anyway.
Tested log line in test pipeline
> [GOBBLIN-1722] Add log line for committing/retrieving watermarks in streaming

- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/CountUpAndDownLatch.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/GobblinMultiTaskAttempt.java
- https://issues.apache.org/jira/browse/GOBBLIN-1735
> [GOBBLIN-1735] Correct a log line and GTE with correct number of total task count

- gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
> [HOTFIX] Fix checkstyleMain

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/IcebergDatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/datanodes/hive/HiveDataNode.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/datanodes/hive/HiveMetastoreUriDataNode.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/datanodes/iceberg/IcebergDataNode.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/datanodes/iceberg/IcebergOnHiveDataNode.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/dataset/IcebergDatasetDescriptorTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/flowgraph/datanodes/iceberg/IcebergDataNodeTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1739
- created iceberg datanode on top of hive datanode which specifies having a metastore uri
- created dataset descriptor extending the sql descriptor
- Added unit tests for the iceberg datanode and dataset descriptor
> [GOBBLIN-1739]Define Datanodes and Dataset Descriptor for Iceberg

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanDagFactory.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/spec/JobExecutionPlanDagFactoryTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1748 
Seeing race condition of a sort where sometimes a multi-hop DAG is cleaned up after a first step is completed but the other hops are pending or in progress. 
> [GOBBLIN-1748] Add logs to debug multi-hop flows creation, progression, and cleanup

- gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
- gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/BaseFlowToJobSpecCompiler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompiler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
- https://issues.apache.org/jira/browse/GOBBLIN-1756
Remove the behavior that we change properties after dag is calculated. Also current mysql quota manager can detect duplicates, so remove this flag as we don't need this. 
Unit test to validate this is the rc
> [GOBBLIN-1756] Fix the issue that we skipping flows for multihop jobs

- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/dag_action_store/MysqlDagActionStore.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/kafka/HighLevelConsumer.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/restli/GobblinServiceFlowExecutionResourceHandlerWithWarmStandby.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitorFactory.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitorFactory.java
- https://issues.apache.org/jira/browse/GOBBLIN-1754 
Includes small fixes and logging added to change monitors, their initialization, and any related parts of code that the API and execution layer interact with. 
Did manual integration test by deploying with other components to verify this is working. 
> [GOBBLIN-1754] Fixes for mysql store change monitors

- gradle/scripts/defaultBuildProperties.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-1762
> [GOBBLIN-1762] Upgrade Gobblin OSS Hadoop version to 2.10.0

- README.md
- https://issues.apache.org/jira/browse/GOBBLIN-1612
This PR restores the description about downloading gradle wrapper which was removed #3159 so that users can build Gobblin from the source distribution without getting flustered.
No additional tests, since it's just a documentation fix.
> [GOBBLIN-1612] Add description about downloading gradle wrapper

- gobblin-restli/gobblin-flow-config-service/gobblin-flow-config-service-server/src/main/java/org/apache/gobblin/service/FlowConfigV2ResourceLocalHandler.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/FlowSpec.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/BaseDatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/DatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/DatasetDescriptorUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/EncryptionConfig.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/FSDatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/FSDatasetPartitionConfig.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/FSVolumeDatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/FormatConfig.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/HiveDatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/HttpDatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/IcebergDatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/dataset/SqlDatasetDescriptor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/DatasetDescriptorConfigKeys.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/DatasetDescriptorErrorStrings.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/DatasetDescriptorErrorUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/pathfinder/AbstractPathFinder.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/pathfinder/BFSPathFinder.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/template/FlowTemplate.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/template/StaticFlowTemplate.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/dataset/FSDatasetDescriptorTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/dataset/HttpDatasetDescriptorTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/dataset/IcebergDatasetDescriptorTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/dataset/SqlDatasetDescriptorTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/flow/MultiHopFlowCompilerTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1759
Adds more detailed logging when attempting to resolve flow configuration
Logs errors for both variable substitution as well as flow template mismatches/errors
Changes tests to test for number of errors returned or checks that no errors were reported instead of just true or false during flow compilation process
> [GOBBLIN-1759] Add error reporting when attempting to resolve flow configs

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
- https://issues.apache.org/jira/browse/GOBBLIN-1799 
The total add spec time and number of scheduled flows are being incremented even when we decided to skip flows far out into the future, overestimating these values by a large amount. 
> [GOBBLIN-1799] Fix add spec and actual number flows scheduled metrics

- gobblin-modules/gobblin-azkaban/src/main/java/org/apache/gobblin/azkaban/AzkabanGobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
- https://issues.apache.org/jira/browse/GOBBLIN-1815
did some minor refactoring so that child classes can override a part of the logic
> [GOBBLIN-1815] Refactor yarn app launchers to support extending these classes

- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDataset.java
- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergDatasetFinder.java
- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergRegisterStep.java
- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/iceberg/IcebergTable.java
- https://issues.apache.org/jira/browse/GOBBLIN-1811
As part of this PR, below are the changes that are made:
- Make IcebergRegisterStep serializable by updating the class attributes
- fix unit tests failing due to usage of mockito-inline
- revert dependency to use mockito-core
- support flexible and open-ended way to provide catalog properties
- Unit tests run successfully and also performed a sample iceberg distcp operation
6. Body explains …
> [GOBBLIN-1811]Fix Iceberg Registration Serialization

- gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncher.java
- gobblin-runtime/src/test/java/org/apache/gobblin/runtime/mapreduce/MRJobLauncherTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1785
add a month partitioned jars dir for mr jobs and set up a simple retention policy over it.
more details in https://docs.google.com/document/d/16cHbeHeCpAP79AqE4odxiXs6tLw7wJpCZhgMBSpL3eg/edit
> [GOBBLIN-1785] add MR_JARS_BASE_DIR and logic to delete old mr jar dirs

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
- https://issues.apache.org/jira/browse/GOBBLIN-1849 
Flow information missing in logs used to track schedule triggers and needed to identify the particular flow being triggered
N/A not needed for logging 
> [GOBBLIN-1849] Add Flow Group & Name to Job Config for Job Scheduler

- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowTriggerHandler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
Logs were incorrectly formatted with `%` instead of `{}` so flow information is not being logged out
> [GOBBLIN-1858] Fix logs relating to multi-active lease arbiter

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
- https://issues.apache.org/jira/browse/GOBBLIN-1878
The format of timestamps were inconsistently using milliseconds versus a Date format making it hard to compare and process these logs. Change to milliseconds for consistency. 
> change nextTriggerTime from date to millis

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobSchedulerTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-1880
We want to handle invalid cron schedules to capture corner edge cases
updated unit tests
> [GOBBLIN-1880] handle invalid cron schedules

- gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FSDagStateStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlDagStateStore.java
- https://issues.apache.org/jira/browse/GOBBLIN-1889
-  I want to add metric for total dag count in the dag state store that will help track and monitor if too many dags are being added by the gobblin service
> [GOBBLIN-1889] add total dag count metric for dag state store

- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
- https://issues.apache.org/jira/browse/GOBBLIN-1916
Including `flow execution id` as a part of multi-active lease arbitration for `LAUNCH` events is frequently causing the same trigger on multiple hosts to be perceived as unique flow executions since the `flow execution id` reflects the system clock of the participant. For a single flow trigger, there may be up to N flow execution ids where N is the number of active participants. The same flow action is perceived as unique from the other ones and excess flows are launched concurrently (upon which the additional ones are cancelled). Remove all use of the flow execution id for the `LAUNCH` case right now. …
> [GOBBLIN-1916] Remove flowExecutionId from Multi-Active Lease Arbitration

- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinHelixJobTask.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/SafeDatasetCommit.java
- gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/BulkResultIterator.java
- gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceExtractor.java
- gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceHistogramService.java
- gobblin-salesforce/src/main/java/org/apache/gobblin/salesforce/SalesforceSource.java
- https://issues.apache.org/jira/browse/GOBBLIN-1917
- Updating the log messages in the Salesforce related classes.
- In some cases, the exception was not included in the log. Adding it to make debugging issues easier.
- For some cases, added more details in the logs to print the current progress of the tasks.
- Minor coding style updates as well to improve code readability.
- There are no functional changes in this PR
- No changes around tests, as no functional changes as part of this PR
4. Subject uses the imperative mood …
> [GOBBLIN-1917] Logging updates for Salesforce classes

- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/api/MysqlMultiActiveLeaseArbiter.java
- https://issues.apache.org/jira/browse/GOBBLIN-1925
Bug fix for distinct events that attempt a lease when a valid one already exists in the database. We want to remember the distinct event time, not the current database time because the current database time may be within epsilon of the existing trigger, so when we revisit the event it may be considered not unique and the trigger is lost. 
Change debug statements to info temporarily to debug reminder events being set with a trigger timestamp that is sometimes _newer_ than `dbEventTimestamp` running into this constraint [violation](https://github.com/apache/gobblin/blob/809ccd62b3a92c1d484636e6ec67d78de40 …
> Change debug statements to info temporarily to debug

- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/mapreduce/GobblinWorkUnitsInputFormat.java
- https://issues.apache.org/jira/browse/GOBBLIN-1986
Naively logging every input holds the potential to go WAY overboard.  w/ 50k+ work units, I found it to actually cripple the UI of my executor.  for reference, I downloaded the executor logs:
```
$ egrep 'input files at' ~/executor-logs_88066352.log | wc
1  578167 49237326
$ cat ~/executor-logs_88066352.log | wc
42240  988632 56428831
```
see: just that one line has 49M of the 56M chars of my (otherwise voluminous!) output. 
existing unit tests
4. Subject uses the imperative …
> [GOBBLIN-1986] Log `FileStatus` for only the first N inputs in `GobblinWorkUnitsInputFormat`

- gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/JobStatusRetriever.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/flowgraph/Dag.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/TimingEventUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/spec/JobExecutionPlan.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetriever.java
- https://issues.apache.org/jira/browse/GOBBLIN-1910
This PR does some refactoring which will help the other major refactoring (https://github.com/apache/gobblin/pull/3825) and reduce it's size.
updated existing tests
> [GOBBLIN-1910] part one of the changes that dag refactoring will require

- gobblin-all/build.gradle
gobblin-all does not include gobblin-temporal, making it inacccessible for many downstream consumers
> [GOBBLIN-1998] Add Gobblin-temporal to gobblin-all

- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/UnixTimestampRecursiveCopyableDataset.java
UnixTimestampRecursiveCopyableDataset is not searching destination files correctly; it is finding relative paths relative to datasetRoot() , but it should actually calculate destination side relative paths relative to `targetPath`
- https://issues.apache.org/jira/browse/GOBBLIN-2005
trivial changes + tests in UnixTimestampRecursiveCopyableDatasetTest are disabled! 
> [GOBBLIN-2005] use correct root path when finding relative paths on destination side

- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/copy/writer/FileAwareInputStreamDataWriter.java
- https://issues.apache.org/jira/browse/GOBBLIN-2009
From my observation, setting an ACL may change the file permission if it is not the same as permission. But changing permission does not change the ACLs; it may update the mask value which changes the effective permission of the ACL entry though.
Thus in order to achieve same ACL and same permission in destination as source, we should first apply ACLs and then apply permissions.
```
hdfs dfs -ls /tmp/x3
-rw-rwxr--   3 griddata users          0 2024-02-29 20:15 /tmp/x3
```
```
hdfs dfs -getfacl hdfs://ltx1-holdemnn01/tmp/x3
user::rw-
user:abora:r-x
group::rwx
mask::rwx
other::r--
```
`hdfs dfs -setfacl …
> [GOBBLIN-2009] set perm and acl correctly

- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/ProcessWorkUnitImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/launcher/ExecuteGobblinJobLauncher.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/launcher/ProcessWorkUnitsJobLauncher.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/util/JobStateUtils.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/PriorJobStateWUProcessingSpec.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WUProcessingSpec.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WUProcessingSpecForBorrowingPriorState.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/worker/WorkFulfillmentWorker.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/ExecuteGobblinWorkflow.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/NestingExecOfProcessWorkUnitWorkflowImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ProcessWorkUnitsWorkflowImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/metrics/SubmitGTEActivityImpl.java
- https://issues.apache.org/jira/browse/GOBBLIN-2010
Provide the ability to execute a full Gobblin job using Temporal.io, rather than MR.  Handle an arbitrary `JobState` config that specifies the intended `Source`, `Writer`, Publisher`, `Converter`, etc. and carry out whatever Data Movement is desired from Gobblin-on-Temporal.
manual execution of Iceberg-Distcp (unit tests forthcoming)
> [GOBBLIN-2010] Implement Distributed Data Movement (DDM) Gobblin-on-Temporal end-to-end workflow for arbitrary job config

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementStateStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerMetrics.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcFactory.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngine.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagerTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2015
Adding details to LaunchDagProc, which is the dag proc that handles new request for launching a Dag.
LaunchDagProc will compile the the flow config that is provided through DagAction and create a Dag.
All the start nodes of this Dag are run in this LaunchDagProc.
What happens after these dag nodes finishes will be handled by a separate DagProc which will be added in future PR.
added a unit test in LaunchDagProcTest
5. …
> [GOBBLIN-2015] implement LaunchDagProc to handle new dag launches

- gobblin-cluster/src/main/java/org/apache/gobblin/cluster/GobblinClusterConfigurationKeys.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/AbstractAppSecurityManager.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/AbstractTokenRefresher.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/AbstractYarnAppSecurityManager.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinApplicationMaster.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnAppLauncher.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/GobblinYarnConfigurationKeys.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnAppSecurityManagerWithKeytabs.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/YarnService.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/helix/HelixClusterLifecycleManager.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/helix/HelixInstancePurgerWithMetrics.java
- gobblin-yarn/src/main/java/org/apache/gobblin/yarn/helix/HelixMessageSubTypes.java
- gobblin-yarn/src/test/java/org/apache/gobblin/yarn/GobblinYarnAppLauncherTest.java
- gobblin-yarn/src/test/java/org/apache/gobblin/yarn/YarnSecurityManagerTest.java
- gobblin-yarn/src/test/java/org/apache/gobblin/yarn/helix/HelixInstancePurgerWithMetricsTest.java
The purpose of this PR is to provide a way for Yarn apps to run without the need for Helix. Doing so, currently provides limited support for long running apps due to a lack of token refresh notifications.
In the future, it might make sense to implement this if long running apps are needed in Gobblin-on-temporal on yarn
> [GOBBLIN-2004] Helix-free yarn app launcher

- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/CommitActivityImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/assistance/Help.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java
- https://issues.apache.org/jira/browse/GOBBLIN-2020
There are a few bugs in Gobblin-Temporal execution mode:
1. If the publishing step fails, the activity does not report a failure due to missing a step post commit to check the dataset states
2. No GTEs are emitted upon job failure, which makes tracking difficult
3. Some metadata propagation for flow execution ID with workflows is incorrect due to a bug reading worker configs instead of job props
4. The GenerateWus activity does not return the right number of workunits created due to counting top level multiworkunits
This PR addresses the above 4 issues and resolves them
Confirmed that flows can …
> [GOBBLIN-2020] Fix number of failure scenarios and bugs in temporal workflows

- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/metrics/EventSubmitterContext.java
> [GOBBLIN-2031] Fix empty message in event submitter in Temporal

- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/ProcessWorkUnitImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/launcher/ExecuteGobblinJobLauncher.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/EagerFsDirBackedWorkUnitClaimCheckWorkload.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WorkUnitClaimCheck.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ProcessWorkUnitsWorkflowImpl.java
> [GOBBLIN-2030] Integrate AutoTroubleshooter with Temporal

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
- https://issues.apache.org/jira/browse/GOBBLIN-2035
Guice initialization failing when trying to initialize named SchedulerLeaseArbiter because optional binding does not have name associated with it. 
> [GOBBLIN-2035] Explicitly bind SchedulerLeaseArbiter

- gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/DagActionStoreChangeEvent.avsc
- gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementStateStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcFactory.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagTaskVisitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/DagTask.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/ReevaluateDagTask.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaAvroJobStatusMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitorFactory.java
- gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStoreTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiterTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlUserQuotaManagerTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/JobStatusRetrieverTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/MysqlJobStatusRetrieverTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2022
Adding a ReEvaluateDagProc, that takes action when a job in the dag completes.
Possible actions can be a) launching a new job if the previous job succeeded, b) retrying the job if the previous job failed and is marked for a `retry`, c) do nothing if the previous job passed, but no new job is runnable because some prerequisite jobs are still running, d) cleaning the dag if all jobs are finished. …
> [GOBBLIN-2022] add re-evaluate dag proc

- gobblin-runtime/src/test/java/org/apache/gobblin/runtime/spec_executorInstance/MockedSpecExecutor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcFactory.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/KillDagTask.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitor.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProcTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2023
Added a KillDagProc that kills all the dag nodes of the dag provided through KillDagAction. If the KillDagAction has job.name field set, then it kills only that particular job (aka dag node)
added KillDagProcTest
> [GOBBLIN-2023] add kill dag proc

- gradle/scripts/repositories.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-2008
- issue relates to use of insecure http endpoints to access jars in the Gobblin build
CI build fix
> [GOBBLIN-2008] use https in repositories.gradle

- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitor.java
- https://issues.apache.org/jira/browse/GOBBLIN-2038
Fixing another startup initialization bug, the previous PR https://github.com/apache/gobblin/pull/3916 has a bug where it is never set as active. We need to fix that in order to process dags and spec store changes.
Runs locally
> [GOBBLIN-2038] Fix bug where monitor startup is never occurring

- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/kafka/HighLevelConsumer.java
- https://issues.apache.org/jira/browse/GOBBLIN-2044
Exceptions encountered while processing kafka messages in the `HighLevelConsumer` are silently thrown and the thread is killed. This PR updates the code to catch and log the exception and record causing it. 
> [GOBBLIN-2044] Catch and log exceptions in HighLevelConsumer queue consumption

- gobblin-runtime/src/main/java/org/apache/gobblin/scheduler/JobScheduler.java
- gobblin-runtime/src/test/java/org/apache/gobblin/scheduler/JobSchedulerTest.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/LeaseAttemptStatus.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MultiActiveLeaseArbiter.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlDagActionStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiter.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiterTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2051
Rework portions of `FlowLaunchHandler`, `DagActionStore`, and related classes for clarity, including:
- add: `DagActionStore::addDagAction(DagAction)`
- name explicitly: `LeaseAttemptStatus::getConsensusDagAction()`
- migrate to `java.util.Optional`
updated existing unit tests
> [GOBBLIN-2051] Rework `FlowLaunchHandler`, `DagActionStore`, and related classes for clarity

- gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/dataset/DatasetUtils.java
- gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/OpenTelemetryMetrics.java
- gobblin-metrics-libs/gobblin-metrics/src/test/java/org/apache/gobblin/metrics/OpenTelemetryMetricsTest.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSObservabilityEventProducer.java
- gobblin-service/src/test/java/org/apache/gobblin/service/monitoring/GaaSObservabilityProducerTest.java
- gobblin-utility/src/main/java/org/apache/gobblin/util/PropertiesUtils.java
- gobblin-utility/src/test/java/org/apache/gobblin/util/PropertiesUtilsTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2053
Add support for headers in opentelemetry metric emitter.
Also fix prefix parsing where it is intended to remove the prefix after parsing it.
Add logging to indicate amount of metrics emitted by the gauge
Unit tests
> [GOBBLIN-2053] Add header and fix prefix configs opentelemetry

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderScheduler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngine.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/utils/FlowCompilationValidationHelper.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2061
Initialize DagProcessingEngine with right parameters 
Add DagProcessingEngine to GobblinServiceManager
Add logging to DagProcessingEngine instantiation and Threads
Fix instantiation of QuartzScheduler for DagActionReminderScheduler
Fix DagAction type retrieval from Quartz reminder job detail map
> [GOBBLIN-2061] Fix initialization for DagProcessingEngine

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcFactory.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/ResumeDagTask.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitor.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProcTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2057
Implemented a ResumeDagProc to process RESUME dag action
> [GOBBLIN-2057]add resume dag proc

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceGuiceModule.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlDagActionStore.java
- gobblin-service/src/test/java/org/apache/gobblin/service/GobblinServiceManagerTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2067
1) do not try to get dags before during MostlyMySqlDagManagementStateStore initialization because this implementation does not need to update quota usage when the service restarts or when its leadership status changes because quota usage are persisted in mysql table.
Also, calling getDags during startUp may fail, because the topologies that are required to deserialize dags may not have been added to the topology catalog yet.
2) provide an option to set GOBBLIN_SERVICE_GUICE_MODULE which is needed when GobblinServiceManager is created through Guice.
3) do not start dag manager threads when dag proc …
> [GOBBLIN-2067] do not try to get dags during MostlyMySqlDagManagementStateStore initialization

- gobblin-core/src/main/java/org/apache/gobblin/source/extractor/extract/restapi/RestApiConnector.java
- gobblin-iceberg/src/main/java/org/apache/gobblin/iceberg/publisher/GobblinMCEPublisher.java
- gobblin-modules/gobblin-kafka-common/src/main/java/org/apache/gobblin/source/extractor/extract/kafka/KafkaUtils.java
Make offset range in Gobblin Metadata pipeline configurable, as in some case, offset range might not be supported
- https://issues.apache.org/jira/browse/GOBBLIN-2068
1. add a null check in GobblinMCEPublisher
2. Add null check in KafkaUtils where kafka leader might not be needed/ required
existing unit test
3. Subject is limited to 50 characters
4. Subject does not end with a period
5. Subject uses the imperative mood ("add", not "adding")
6. Body wraps at 72 characters
7. Body explains "what" and "why", not "how"
> [GOBBLIN-2068]Make offset range in Gobblin Metadata pipeline configurable

- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
- https://issues.apache.org/jira/browse/GOBBLIN-2081
do not run dag proc related code when dag proc engine is not enabled 
- [] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
> [GOBBLIN-2081] do not run dag proc related code when dag proc engine is not enabled

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/core/GobblinServiceManager.java
- https://issues.apache.org/jira/browse/GOBBLIN-2091
It was trying to unregister dag manager when it was not registered at the first place.
```
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is DagManager [RUNNING] registered?
at com.google.common.eventbus.SubscriberRegistry.unregister(SubscriberRegistry.java:111) ~[com.google.guava.guava-21.0.jar:?]
at com.google.common.eventbus.EventBus.unregister(EventBus.java:201) ~[com.google.guava.guava-21.0.jar:?]
at org.apache.gobblin.service.modules.core.GobblinServiceManager.handleLeadershipChange(GobblinServiceManager.java:372) …
```
> [GOBBLIN-2091] disable dag manager code when dag proc engine is enabled

- .github/workflows/build_and_test.yaml
- gobblin-metastore/build.gradle
- gobblin-metastore/src/test/java/org/apache/gobblin/metastore/DatabaseJobHistoryStoreTest.java
- gobblin-metastore/src/test/java/org/apache/gobblin/metastore/testing/TestMetastoreDatabaseServer.java
- gobblin-rest-service/gobblin-rest-server/src/test/java/org/apache/gobblin/rest/JobExecutionInfoServerTest.java
- gradle/scripts/dependencyDefinitions.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-2098
Updating the test Mysql version, and getting rid of com.wix:wix-embeded-mysql(deprected) in favour of org.testcontainers
> [GOBBLIN-2098]Update the test Mysql version, and getting rid of com.wix:wix-embeded-mysql(deprecated) in favour of org.testcontainers

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderScheduler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagement.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/InstrumentedLeaseArbiter.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/LeaseAttemptStatus.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MultiActiveLeaseArbiter.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiter.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderSchedulerTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandlerTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiterTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2100
This PR adds javadocs to the following crucial public classes & objects: `DagActionLeaseParams, DagAction, DagActionStore`. It does minor refactoring and renames `DagActionLeaseOject` to `DagActionLeaseParams`.
N/A
> [GOBBLIN-2100] Add javadocs to DagAction related classes

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderScheduler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagement.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImpl.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MostlyMySqlDagManagementStateStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MysqlMultiActiveLeaseArbiter.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagManagementDagActionStoreChangeMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagActionReminderSchedulerTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/MysqlDagActionStoreTest.java
i) call sendEnforceJobStartDeadlineDagAction after starting the job, not before that
ii) merge addDagAction and addReminderDagAction into one method
iii) cache DagManagement in DagActionReminderScheduler
iv) add some logs
> add some logs and cache DagManagement in DagActionReminderScheduler

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DeadlineEnforcementDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/DagTask.java
- https://issues.apache.org/jira/browse/GOBBLIN-2120
Mark `dagActionsConclude` as failed if the delete failed
N/A
> [GOBBLIN-2120] Mark dagActionsConclude correctly

- gobblin-modules/gobblin-kafka-09/src/test/java/org/apache/gobblin/runtime/KafkaAvroJobStatusMonitorTest.java
- gobblin-runtime/src/main/java/org/apache/gobblin/service/monitoring/FlowStatusGenerator.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java
…ProcEngine is enabled.
- https://issues.apache.org/jira/browse/GOBBLIN-2123
- add PENDING_RETRY to FINISHED_STATUSES list, so that a reevaluate dag action is created for it that will submit another execution for this job
added tests in ReevaluateDagProcTest
> [GOBBLIN-2123] create reevaluate dag action for jobs in state PENDING_RETRY

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagActionStore.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/FlowLaunchHandler.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/Orchestrator.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DeadlineEnforcementDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/DagProcessingEngineMetrics.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/scheduler/GobblinServiceJobScheduler.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2121
create dag actions for kill rest requests, so they are processed by dag proc engine not dag manager
> [GOBBLIN-2121] redirect kill requests to dag proc engine

- gobblin-api/src/main/java/org/apache/gobblin/service/ServiceConfigKeys.java
- gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/ServiceMetricNames.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/Task.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/fork/Fork.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerMetrics.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcFactory.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngine.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DeadlineEnforcementDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/EnforceFlowFinishDeadlineDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/EnforceJobStartDeadlineDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/DagProcessingEngineMetrics.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/DagTask.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaAvroJobStatusMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitorFactory.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagManagementTaskStreamImplTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/DagProcessingEngineTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/OrchestratorTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/EnforceDeadlineDagProcsTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProcTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProcTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProcTest.java
- gobblin-service/src/test/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProcTest.java
- gobblin-utility/src/main/java/org/apache/gobblin/util/ExceptionUtils.java
- gobblin-utility/src/test/java/org/apache/gobblin/util/ExceptionUtilsTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2124
provides a way to not retry non-retryable exceptions
add tests in dagprocenginetest
> [GOBBLIN-2124] only retry transient exceptions

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
avoid race condition b/w add dag node and delete dag. race condition can happen when deadlinedagproc update the dag node after cancelling it and reevaluate dag proc that was generated by the same cancelling tries to delete dag (/dag node)
difficult to add tests, this change is only changing the order of execution
> [GOBBLIN-2130] avoid race condition b/w add dag node and delete dag

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/DagManagerUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/TimingEventUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/DagProcUtils.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/KillDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/LaunchDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ReevaluateDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/ResumeDagProc.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/SpecStoreChangeMonitor.java
- https://issues.apache.org/jira/browse/GOBBLIN-2132
set flow event field in dag and also emit FLOW_RUNNING GTE when job is submitted. if this is not done, flow will not transition from COMPILED to RUNNING.
add some logs for debugging
> [GOBBLIN-2132] set flow event field in dag and also emit GTE when flow is submitted

- gobblin-api/src/main/java/org/apache/gobblin/configuration/ConfigurationKeys.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/DagActionStoreChangeMonitor.java
- https://issues.apache.org/jira/browse/GOBBLIN-2131
process all dag actions parallely during initialization
Already has the test  testStartupSequenceHandlesFailures which covers startup 
> [GOBBLIN-2131] process all dag actions during startup parallely

- gobblin-compaction/src/main/java/org/apache/gobblin/compaction/mapreduce/MRCompactor.java
- gobblin-data-management/src/main/java/org/apache/gobblin/data/management/retention/DatasetCleaner.java
- gobblin-modules/gobblin-compliance/src/main/java/org/apache/gobblin/compliance/restore/ComplianceRestoreJob.java
- gobblin-modules/gobblin-compliance/src/main/java/org/apache/gobblin/compliance/retention/ComplianceRetentionJob.java
- gobblin-modules/gobblin-compliance/src/main/java/org/apache/gobblin/compliance/validation/ComplianceValidationJob.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/app/ServiceBasedAppLauncher.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/embedded/EmbeddedGobblin.java
- https://issues.apache.org/jira/browse/GOBBLIN-2139
update use of guava api, because the old api is removed in the higher versions
trivial change
> [GOBBLIN-2139] use a newer api in guava

- gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/OpenTelemetryMetricsBase.java
- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/GaaSJobObservabilityEventProducer.java
- https://issues.apache.org/jira/browse/GOBBLIN-2149
Add logs to debug opentelemetry metric emission
Added log statements only
> [GOBBLIN-2149] Add logs in OpenTelemetry for debugging

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/MultiActiveLeaseArbiterFactory.java
- https://issues.apache.org/jira/browse/GOBBLIN-2136
MultiActiveLeaseArbiter is not getting required configs to decrypt the encrypted password to connect to the MySQL tables. For some reason, it was able to connect to the db before https://github.com/apache/gobblin/pull/4031 PR
In this PR, I am providing it with the additional configs
> [GOBBLIN-2136] fixing an issue of not able to connect to db

- gobblin-modules/gobblin-troubleshooter/src/main/java/org/apache/gobblin/troubleshooter/AutoTroubleshooterLogAppender.java
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/troubleshooter/Issue.java
- gobblin-temporal/build.gradle
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/GenerateWorkUnits.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/util/JobStateUtils.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/EagerFsDirBackedWorkUnitClaimCheckWorkload.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/PriorJobStateWUProcessingSpec.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WorkUnitClaimCheck.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/work/WorkUnitsSizeSummary.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ExecuteGobblinWorkflowImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/ddm/workflow/impl/ProcessWorkUnitsWorkflowImpl.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/dynamic/ScalingDirectiveSource.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/dynamic/WorkforcePlan.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/metrics/TemporalEventTimer.java
- gobblin-temporal/src/test/java/org/apache/gobblin/temporal/ddm/activity/impl/GenerateWorkUnitsImplTest.java
- gobblin-temporal/src/test/java/org/apache/gobblin/temporal/ddm/work/EagerFsDirBackedWorkUnitClaimCheckWorkloadTest.java
- gobblin-utility/build.gradle
- gobblin-utility/src/main/java/org/apache/gobblin/util/JobLauncherUtils.java
- gobblin-utility/src/main/java/org/apache/gobblin/util/WorkUnitSizeInfo.java
- gobblin-utility/src/test/java/org/apache/gobblin/util/JobLauncherUtilsTest.java
- gobblin-utility/src/test/java/org/apache/gobblin/util/WorkUnitSizeInfoTest.java
- gradle/scripts/dependencyDefinitions.gradle
- https://issues.apache.org/jira/browse/GOBBLIN-2179
Enhance GoT observability with `WorkUnitsSizeSummary` and `WorkUnitSizeInfo`:
a. `GenerateWorkUnits`' result type, `GenerateWorkUnitsResult`, now contains `WorkUnitsSizeSummary`, capturing the total number of `MultiWorkUnit`s and constituent sub-`WorkUnit`s, the total size in bytes, as well as the size distribution across all WUs.
b. `WorkUnitClaimCheck`, which is the argument to `ProcessWorkUnit` now contains `WorkUnitSizeInfo`, capturing the total size of the possibly `MultiWorkUnit` as well as an abbreviated characterization of the size of any constituent `WorkUnit`s.
Together these now provide …
> [GOBBLIN-2179] Enhance GoT observability with `WorkUnitsSizeSummary` and `WorkUnitSizeInfo`

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/task/DagTask.java
- https://issues.apache.org/jira/browse/GOBBLIN-2201
Fix the failing checkstyle
> failing checkstyle fix

- gobblin-metrics-libs/gobblin-metrics/src/main/java/org/apache/gobblin/metrics/OpenTelemetryMetrics.java
- gobblin-temporal/src/main/java/org/apache/gobblin/temporal/workflows/metrics/TemporalMetricsHelper.java
- https://issues.apache.org/jira/browse/GOBBLIN-2202
Changed Aggregation Temporality to DELTA instead of CUMULATIVE for Open Telemetry Metrics
NA
> [GOBBLIN-2202] Change aggregation temporality to DELTA instead of CUMULATIVE for Open Telemetry Metrics

- gobblin-core/src/main/java/org/apache/gobblin/qualitychecker/task/TaskLevelPolicyChecker.java
- gobblin-metrics-libs/gobblin-metrics-base/src/main/avro/GaaSJobObservabilityEvent.avsc
- gobblin-runtime/src/main/java/org/apache/gobblin/runtime/DatasetTaskSummary.java
- https://issues.apache.org/jira/browse/GOBBLIN-2205
> Add data quality field in GaaSJobObservabilityEventSchema

- gobblin-data-management/src/main/java/org/apache/gobblin/util/commit/CreateDirectoryWithPermissionsCommitStep.java
- gobblin-utility/src/main/java/org/apache/gobblin/util/HadoopUtils.java
- gobblin-utility/src/test/java/org/apache/gobblin/util/HadoopUtilsTest.java
- https://issues.apache.org/jira/browse/GOBBLIN-2208
During manifest based copy due to default ACL inheritence in the destination, after manifest based copy source and destination end up having different ACL's for source and destination
As a solution fix for it, after creating directory(once the ACL inheritance will take place), we will call removeAcl to remove any existing ACL from the destination, and then copy the source directory ACL's
6. …
> [GOBBLIN-2208]Acl preservation fix

- gobblin-service/src/main/java/org/apache/gobblin/service/modules/orchestration/proc/EnforceFlowFinishDeadlineDagProc.java
- https://issues.apache.org/jira/browse/GOBBLIN-2215
> [GOBBLIN-2215] Send flow event if flow deadline is crossed

- gobblin-service/src/main/java/org/apache/gobblin/service/monitoring/KafkaJobStatusMonitor.java
- https://issues.apache.org/jira/browse/GOBBLIN-2216
> [GOBBLIN-2216] Update job status before adding REEVALUATE dag action

- gobblin-api/src/main/java/org/apache/gobblin/compat/hadoop/TextSerializer.java
- gobblin-api/src/test/java/org/apache/gobblin/compat/TextSerializerTest.java
> Revert "[GOBBLIN-2223] Optimise writing of serialised Work Unit to File system"
